common/config/rush/shrinkwrap.yaml
extensions/ql-vscode/package.json
lib/semmle-vscode-utils/package.json
tools/build-tasks/package.json

Because [this](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining)

Update to TypeScript 3.7.2

---

extensions/ql-vscode/src/view/result-tables.tsx
extensions/ql-vscode/src/view/resultsView.css

Fixes https://github.com/github/pe-security-codeql/issues/170.

Show number of results in results view

---

extensions/ql-vscode/CHANGELOG.md

Proactively add recent changes to the changelog, thanks @shati-patel for the suggestion.

Update changelog with recent changes

---

.github/workflows/main.yml
.github/workflows/release.yml
extensions/ql-vscode/src/queries.ts

Fixes https://github.com/github/codeql-coreql-team/issues/252.

Truncate long database upgrade messages in native dialog box

---

extensions/ql-vscode/src/query-history.ts

This PR displays the failure icon that we use for invalid databases next to any query history items that didn't finish successfully.

Display a failed icon next to failed query history items

---

.github/pull_request_template.md
extensions/ql-vscode/CHANGELOG.md

Add a changelog entry for #224 (thanks @shati-patel for 🦅👀) and add a PR template to remind us to update the changelog when there are user-visible changes.

Add pull request template

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/new-extension-release.md

Add issue templates for creating a release checklist and also standardish templates for bug and feature reports.

Add issue templates

---

README.md

Add VS Marketplace badge

---

.github/workflows/main.yml

This reverts commit c95ac8e6eacc5ab6565c5a287bd930ef6e1c2da8.

Revert "Exclude documentation from CI workflow"

---

.github/pull_request_template.md

Add steps to the checklist in the PR template to ensure that appropriate process is followed so that the documentation team are kept up to date.  The reviewer of each PR should ensure that these steps have been completed when reviewing the PR.

Add steps to the pull request checklist to inform the documentation team

---

extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/package.json
extensions/ql-vscode/src/extension.ts
extensions/ql-vscode/src/logging.ts
extensions/ql-vscode/src/queryserver-client.ts
extensions/ql-vscode/test/pure-tests/query-test.ts

Fix version bump PR creation during release workflow

---

extensions/ql-vscode/src/messages.ts

So we can refer to their types if necessary.

Convert namespaces to enums in messages.ts

---

.editorconfig
.vscode/launch.json
CONTRIBUTING.md
extensions/ql-vscode/test/pure-tests/location.test.ts
tsfmt.json

Adds section in CONTRIBUTING.md to document how to run tests. Also,
fixes some markdown linting warnings.
And fixes the launch config for running unit tests.

Update contributing documentation and launch config

---

extensions/ql-vscode/src/test-adapter.ts

Only create nonempty test suites

---

extensions/ql-vscode/src/bqrs-cli-types.ts
extensions/ql-vscode/src/cli.ts
extensions/ql-vscode/src/messages.ts
extensions/ql-vscode/src/run-queries.ts

These are not-yet-user facing changes required by https://github.com/github/codeql-coreql-team/issues/28

Add bqrs types and ability to run template queries.

---

build/package-lock.json

I think this file is not needed. It's causing a security warning. Let's get rid of it.

chore: Remove unnecessary package lock

---

extensions/ql-vscode/src/archive-filesystem-provider.ts
extensions/ql-vscode/src/cli.ts
extensions/ql-vscode/src/databases-ui.ts
extensions/ql-vscode/src/databases.ts
extensions/ql-vscode/src/helpers.ts
extensions/ql-vscode/src/interface-types.ts
extensions/ql-vscode/src/interface.ts
extensions/ql-vscode/src/messages.ts
extensions/ql-vscode/src/qlpack-discovery.ts
extensions/ql-vscode/src/result-keys.ts
extensions/ql-vscode/src/sarif-utils.ts
extensions/ql-vscode/src/test-adapter.ts
extensions/ql-vscode/src/view/alert-table.tsx
extensions/ql-vscode/src/view/event-handler-list.ts
extensions/ql-vscode/src/view/results.tsx
extensions/ql-vscode/src/vscode-tests/no-workspace/archive-filesystem-provider.test.ts
extensions/ql-vscode/src/vscode-tests/no-workspace/helpers.test.ts
extensions/ql-vscode/src/vscode-tests/run-integration-tests.ts

Just some code cleanup. Nothing big here.

lint: Ran the auto-fix command for the linter

---

extensions/ql-vscode/src/query-history.ts

fix: Use a proper 'file' schema for uris

---

extensions/ql-vscode/src/distribution.ts
extensions/ql-vscode/src/vscode-tests/no-workspace/distribution.test.ts

Allow extension to remain on the deprecated launcher.
There's no point in issuing a warning for using a deprecated launcher if the correct launcher doesn't exist.
Also, adds a bunch of unit tests around here.

fix: Avoid warning user if no new launcher exists

---

extensions/ql-vscode/package.json
extensions/ql-vscode/src/config.ts
extensions/ql-vscode/src/run-queries.ts

Fixes #323.
cc: @github/product-docs-dsp in case this needs docs.

Add 'Always Save' to running unsaved query dialog

---

.vscode/settings.json
extensions/ql-vscode/gulpfile.js/webpack.config.ts
extensions/ql-vscode/test/pure-tests/location.test.ts
lib/semmle-bqrs/src/bqrs-results.ts

Fixes #348.
This PR also includes 2 small, non-related changes for better editing experience.

Add source locations for string results

---

common/config/rush/pnpm-lock.yaml
extensions/ql-vscode/package.json
tsfmt.json

This PR adds husky to the project. This will force linting and formatting to run on each commit.

Add format and lint on commit

---

extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/package.json
extensions/ql-vscode/src/databaseFetcher.ts
extensions/ql-vscode/src/databases-ui.ts
extensions/ql-vscode/src/databases.ts
extensions/ql-vscode/src/distribution.ts
extensions/ql-vscode/src/extension.ts
extensions/ql-vscode/src/helpers.ts
extensions/ql-vscode/src/logging.ts
extensions/ql-vscode/src/test-adapter.ts
extensions/ql-vscode/test/pure-tests/logging.test.ts

New command that requests a URL and allows a user to install a
database from that url.
Closes #357

Add command to download, unzip, and open databases

---

extensions/ql-vscode/src/databaseFetcher.ts
extensions/ql-vscode/src/databases-ui.ts

Fix paths on windows when opening archive databases

---

extensions/ql-vscode/src/archive-filesystem-provider.ts

This would have been helpful to debug https://github.com/github/securitylab/discussions/88

Log more details when source archive entries aren't found

---

extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/src/databaseFetcher.ts
extensions/ql-vscode/src/databases-ui.ts
extensions/ql-vscode/src/vscode-tests/no-workspace/databases-ui.test.ts
extensions/ql-vscode/test/data/library.qll

Closes #383.
See the heuristics in the issue.

Allow users more flexibility when opening a DB

---

.github/workflows/codeql.yml

Adds a new workflow to run codescanning on every commit.

Introduce codeql code scanning action

---

extensions/ql-vscode/CHANGELOG.md

Small correction to match the [specification](https://help.semmle.com/QL/ql-handbook/qldoc.html) :-)

Update capitalization of "QLDoc" in CHANGELOG.md 

---

extensions/ql-vscode/README.md

Makes it easier for new users to search for projects.

Update link to lgtm to go to the explore section

---

extensions/ql-vscode/CHANGELOG.md

Adds some missing changelog items.

Update changelog in preparation for v1.2.2 release

---

extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/src/databases-ui.ts

Catch and report error when selecting invalid database

---

extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/src/databaseFetcher.ts

Add descriptive message for archive import failure

---

extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/src/databases-ui.ts

These commands now work on multiple databases:
* remove databases
* open external folder
* upgrade databases## Checklist
Fixes #455.

Add multi-select support for db view

---

extensions/ql-vscode/src/query-history.ts

Also, fix type error.
Fixes https://github.com/github/semmle-docs/issues/160#issuecomment-647525682

Add better error message when comparing queries

---

extensions/ql-vscode/package.json

Change command name

---

README.md
extensions/ql-vscode/CHANGELOG.md

A few very minor fixes spotted in the README and changelog :octocat:

Small editorials tweaks 

---

common/config/rush/pnpm-lock.yaml
extensions/ql-vscode/package.json
extensions/ql-vscode/src/definitions.ts

Small refactoring to avoid a synchronous call.

Avoid using a synchronous file system command

---

extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/src/query-history.ts

Fixes https://github.com/github/vscode-codeql/issues/487.

Fix display of quick-query query text

---

extensions/ql-vscode/src/interface-utils.ts
extensions/ql-vscode/src/vscode-tests/no-workspace/interface-utils.test.ts
extensions/ql-vscode/src/vscode-tests/run-integration-tests.ts

This works around but does not fundamentally address https://github.com/github/vscode-codeql/issues/493.

Remove failing integration test

---

extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/src/cli.ts

Fixes #499
- [N/A] `@github/product-docs-dsp` has been cc'd in all issues for UI or other user-facing changes made by this pull request.

Use proper check for existence of search path

---

extensions/ql-vscode/src/compare/view/Compare.tsx
extensions/ql-vscode/src/view/results.tsx

Fixes codescanning warnings:
- https://github.com/github/vscode-codeql/security/code-scanning/1
- https://github.com/github/vscode-codeql/security/code-scanning/2

Check window event origins

---

.github/workflows/codeql.yml

We should also disable the LGTM check, e.g., https://github.com/github/vscode-codeql/pull/511/checks?check_run_id=901294820

Run CodeQL Action on PRs

---

extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/src/databaseFetcher.ts

Fixes https://github.com/github/vscode-codeql/issues/510

Suppress database downloaded message when action canceled

---

.github/workflows/label-issue.yml

Adds the label `VSCode` to all newly created issues, for consistent project tracking.
- [N/A] `@github/product-docs-dsp` has been cc'd in all issues for UI or other user-facing changes made by this pull request.

Actions: Autolabel issues when opened

---

extensions/ql-vscode/CHANGELOG.md

Update Chnagelog for v1.3.2

---

.github/workflows/release.yml

Add a simple perl script that will augment the CHANGELOG with an [UNRELEASED] section when creating the PR after a release.

Update changelog after release

---

tsconfig.json

The reason to add this is that I am getting misleadings errors in
vscode that this file is missing. By adding this file, I no longer
see these errors.

Add a top-level tsconfig.json

---

extensions/ql-vscode/package-lock.json

Update npm dependencies fix security vulns

---

extensions/ql-vscode/package-lock.json
extensions/ql-vscode/package.json

Update mocha version

---

extensions/ql-vscode/package-lock.json
extensions/ql-vscode/package.json
extensions/ql-vscode/src/vscode-tests/index-template.ts

PR #591 broke the build.
- [ n/a  ] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.

Fix mocha test running

---

extensions/ql-vscode/src/contextual/queryResolver.ts

Update error message when there is a missing contextual query

---

extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/package.json

Allow setting number of threads to 0

---

extensions/ql-vscode/src/astViewer.ts
extensions/ql-vscode/src/databases-ui.ts
extensions/ql-vscode/src/extension.ts
extensions/ql-vscode/src/query-history.ts
extensions/ql-vscode/src/vscode-tests/no-workspace/astViewer.test.ts

Use DiposableObject more consistently and ensure all commands are
added as a disposable to the ExtensionContext.

Refactor extension context subscriptions

---

.github/workflows/main.yml

Avoid running workflows on push events

---

extensions/ql-vscode/src/vscode-tests/no-workspace/databaseFetcher.test.ts

These tests make API calls and may need extra time to complete.

Fix flaky tests

---

.vscode/launch.json
extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/src/cli.ts
extensions/ql-vscode/src/config.ts
extensions/ql-vscode/src/distribution.ts
extensions/ql-vscode/src/extension.ts
extensions/ql-vscode/src/query-history.ts
extensions/ql-vscode/src/queryserver-client.ts
extensions/ql-vscode/src/vscode-tests/minimal-workspace/activation.test.ts
extensions/ql-vscode/src/vscode-tests/minimal-workspace/config.test.ts
extensions/ql-vscode/src/vscode-tests/no-workspace/query-results.test.ts
extensions/ql-vscode/test/pure-tests/query-test.ts

This setting has existed for a while, but it was not used for some
reason.
Resolves #625.

Use the codeQL.runningTests.numberOfThreads

---

.github/workflows/release.yml

New version will avoid deprecation warnings for add-path
and set-var.

Bump version of create-pull-request action

---

extensions/ql-vscode/src/cli.ts
extensions/ql-vscode/src/distribution.ts
extensions/ql-vscode/src/vscode-tests/no-workspace/query-test.ts

And also only add the `--kind=DIL` to `generateDil` if version is
`>= 2.3.0`.
Integration tests will come next.

Add version info to cli

---

CONTRIBUTING.md

Update the contributing docs

---

.github/workflows/release.yml

This will allow us to create easily accessible artifacts for any branch.

Add workflow_dispatch to release workflow

---

extensions/ql-vscode/src/contextual/locationFinder.ts
extensions/ql-vscode/src/contextual/queryResolver.ts
extensions/ql-vscode/src/contextual/templateProvider.ts
extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/queryResolver.test.ts

Without this line I get errors like `Could not find qlpack file for dbscheme ...` when using 'View AST'.

Add missing call to `getPrimaryDbscheme` in `qlpackOfDatabase`

---

extensions/ql-vscode/src/test-adapter.ts
extensions/ql-vscode/src/vscode-tests/no-workspace/distribution.test.ts

Fix Code Scanning warnings

---

extensions/ql-vscode/package.json

Replace "Code QL database" with "CodeQL database" for consistency with [documentation](https://codeql.github.com/docs/codeql-cli/creating-codeql-databases/).

Fix minor typo in welcome content

---

.github/workflows/main.yml

Update cli version in integration test

---

extensions/ql-vscode/package.json

Rephrase in terms of query results rather than queries.  Thanks @aschackmull for the spot!

Update page size setting description

---

.vscode/extensions.json
CONTRIBUTING.md
extensions/ql-vscode/README.md
extensions/ql-vscode/gulpfile.ts/tsconfig.json
extensions/ql-vscode/src/vscode-tests/no-workspace/databaseFetcher.test.ts
extensions/ql-vscode/tsconfig.json

- Updates Semmle links to the new GitHub redirect destinations.
- Use HTTPS for links.

Update Semmle links in extension README

---

.github/workflows/main.yml

- [N/A] `@github/docs-content-codeql` has been cc'd in all issues for UI or other user-facing changes made by this pull request.

Actions: Test against CodeQL CLI 2.5.0

---

extensions/ql-vscode/gulpfile.ts/webpack.config.ts
extensions/ql-vscode/gulpfile.ts/webpack.ts
extensions/ql-vscode/package-lock.json
extensions/ql-vscode/package.json

This commit updates to webpack 5 in order to fix some dependabot errors.
Because webpack 5 introduces some breaking changes, this commit also
makes some minor changes to the build code.

Fix dependabot warnings

---

extensions/ql-vscode/src/cli.ts
extensions/ql-vscode/src/databases.ts
extensions/ql-vscode/src/extension.ts
extensions/ql-vscode/src/helpers.ts
extensions/ql-vscode/src/queryserver-client.ts
extensions/ql-vscode/src/vscode-tests/cli-integration/query.test.ts
extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases.test.ts

A simple refactoring that simplifies and unifies how we check if a
feature is supported by a specific cli version.
This is an internal change and not visible to end users.

Refactor version constraints

---

.github/workflows/codeql.yml

Run only on pushes and PRs against `main`.
- [N/A] `@github/docs-content-codeql` has been cc'd in all issues for UI or other user-facing changes made by this pull request.

Actions: Simplify code scanning workflow

---

extensions/ql-vscode/src/interface.ts

(Introduced by https://github.com/github/vscode-codeql/pull/831)

Remove commented out code

---

.github/workflows/main.yml

Add v2.5.1 to cli versions in integration test

---

.github/workflows/main.yml

We need to be testing against the latest codeql cli version. This PR updates the integration
tests to include the latest version.

Update integration test cli versions

---

extensions/ql-vscode/package-lock.json
extensions/ql-vscode/src/compare/view/Compare.tsx
extensions/ql-vscode/src/view/result-tables.tsx
extensions/ql-vscode/src/view/results.tsx

* Log injection errors
* Also, ran `npm audit fix`

Fix code scanning errors and dependabot issues

---

.github/workflows/main.yml

Update cli integration tests with new cli version

---

.github/workflows/main.yml

CodeQL CLI v2.5.6 was released yesterday 🎉

Update CLI integration tests with latest version of CLI

---

extensions/ql-vscode/src/run-remote-query.ts

Depends on internal PR, which has now been merged 😄 
@robertbrignull added a new endpoint for triggering remote query runs, so we no longer use workflow dispatch.
N/A - internal only (no user-facing changes)
- ~[CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.~
- ~Issues have been created for any UI or other user-facing changes made by this pull request.~
- ~`@github/docs-content-codeql` has been cc'd in all issues for UI or other user-facing changes made by this pull request.~

Use new endpoint for running remote queries

---

.github/workflows/main.yml

Add v2.6.0 to list of versions we use for integration testing

---

extensions/ql-vscode/CHANGELOG.md

Update changelog for v2.5.4 release

---

extensions/ql-vscode/src/run-remote-query.ts

Now that the queries endpoint returns the id we can link straight
there. We'll make more changes to the progress tracking, but I think
it's worth making this minimal change now.

Start linking to the exact workflow run

---

.github/workflows/main.yml
extensions/ql-vscode/src/vscode-tests/ensureCli.ts

[Version 2.7.2 is here!](https://github.com/github/codeql-cli-binaries/releases/tag/v2.7.2) 🎉

Update CLI version in tests

---

extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx

Some further tidy up to make working in the remote queries view a bit easier
N/A

Break remote queries view into more components

---

.github/workflows/main.yml
extensions/ql-vscode/src/vscode-tests/ensureCli.ts

- [n/a] If this pull request makes user-facing changes that require documentation changes, the `ready-for-doc-review` label has been added to this pull request or the corresponding issue.

Bump CLI version to run integration tests against

---

.github/workflows/main.yml
extensions/ql-vscode/src/vscode-tests/ensureCli.ts

CodeQL CLI [v2.7.6](https://github.com/github/codeql-cli-binaries/releases) is here! 🎉 
n/a

Bump CLI version for integration tests

---

extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts

Use streaming SARIF parser

---

extensions/ql-vscode/package-lock.json
extensions/ql-vscode/package.json
extensions/ql-vscode/src/remote-queries/view/CollapsibleItem.tsx
extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
extensions/ql-vscode/src/remote-queries/view/remoteQueries.css

Created a re-usable CollapsibleItem component and used that to show the results of analyses.
N/A

Show collapsible analyses results

---

extensions/ql-vscode/src/remote-queries/run-remote-query.ts

This was our first temporary attempt at configuration of a remote
query run. I don't think that we're using it anymore, so it simplifies
the code to remove it.

Remove .repositories configuration approach

---

extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/src/compare/compare-interface.ts
extensions/ql-vscode/src/config.ts
extensions/ql-vscode/src/databaseFetcher.ts
extensions/ql-vscode/src/extension.ts
extensions/ql-vscode/src/helpers.ts
extensions/ql-vscode/src/interface.ts
extensions/ql-vscode/src/pure/helpers-pure.ts
extensions/ql-vscode/src/query-history.ts
extensions/ql-vscode/src/query-results.ts
extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts
extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts
extensions/ql-vscode/src/remote-queries/run-remote-query.ts
extensions/ql-vscode/src/run-queries.ts
extensions/ql-vscode/src/upgrades.ts
extensions/ql-vscode/src/vscode-tests/cli-integration/queries.test.ts
extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts
extensions/ql-vscode/src/vscode-tests/no-workspace/query-results.test.ts

There is no new behaviour added in this commit. Just some cleanup:
- Move some shared constants to the `helpers` module
- Add comments to some of the query related modules
- Some general formatting and tidying
- [n/a] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the …

General refactoring and adding comments

---

.github/workflows/main.yml
extensions/ql-vscode/src/vscode-tests/ensureCli.ts

CodeQL CLI [v2.8.1](https://github.com/github/codeql-cli-binaries/releases/tag/v2.8.1) has been released 🎉 
n/a

Update CLI version in integration tests

---

extensions/ql-vscode/src/remote-queries/run-remote-query.ts
extensions/ql-vscode/src/vscode-tests/no-workspace/run-remote-query.test.ts

We no longer check for DB uploads in the API, so we can get rid of this code 🧹 See internal linked PR. 
cc @robertbrignull, since you did the API side! 
N/A 😈

Remove unused code about validating DB uploads

---

extensions/ql-vscode/src/extension.ts

We want them to be deleted when the application exits. We don't want
them to be stored with user queries.
No changelog needed since this is an addition to a feature not yet released.
Contextual queries are queries that are run in the background to perform IDE activities, like find definitions and results, and also view AST. We don't want these queries to be stored with the other query history since they aren't interesting to users and will never appear in the query history view.
- [n/a] _[Maintainers …

Store query results for contextual queries elsewhere

---

extensions/ql-vscode/src/remote-queries/view/DownloadButton.tsx
extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
extensions/ql-vscode/src/remote-queries/view/remoteQueries.css
extensions/ql-vscode/src/view/octicons.tsx

Updated Remote Queries components to use octicons from the primer package.
N/A:

Use Primer octicons where possible

---

extensions/ql-vscode/src/remote-queries/view/CollapsibleItem.tsx

A couple of fixes for the CollapsibleItem component:
- Fix the colouring of the chevron icon
- Made the whole container clickable rather than just the icon and updated mouse pointer to reflect that
N/A:

Some UI fixes for collapsible items

---

extensions/ql-vscode/package.json
extensions/ql-vscode/scripts/forbid-mocha-only

Add pre-push hook check to block leftover .only()s

---

extensions/ql-vscode/src/extension.ts
extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts
extensions/ql-vscode/src/remote-queries/bqrs-processing.ts
extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts
extensions/ql-vscode/src/remote-queries/shared/analysis-result.ts
extensions/ql-vscode/src/remote-queries/shared/result-limits.ts
extensions/ql-vscode/src/remote-queries/view/RawResultsTable.tsx
extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
extensions/ql-vscode/src/remote-queries/view/TextButton.tsx
extensions/ql-vscode/src/vscode-tests/no-workspace/remote-query-history.test.ts

Added logic and components to deal with processing and rendering raw results (.bqrs files) in remote queries.
N/A:

Add support for remote queries raw results

---

extensions/ql-vscode/src/remote-queries/view/RawResultsTable.tsx

Break up a line if it's too long.
N/A:

Minor styling fix for raw results

---

extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx

These will now be shown as part of the next extension release!
N/A:

Enable viewing of analyses results

---

extensions/ql-vscode/src/pure/interface-types.ts
extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts
extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
extensions/ql-vscode/src/remote-queries/view/remoteQueries.css

This is no longer required since we'll be showing the results in the web view.
The code changes are basically a revert of https://github.com/github/vscode-codeql/pull/1125
N/A:

Remove SARIF viewer support

---

extensions/ql-vscode/src/remote-queries/view/FileCodeSnippet.tsx

Fix highlighting issues

---

extensions/ql-vscode/src/remote-queries/view/FileCodeSnippet.tsx
extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
extensions/ql-vscode/src/remote-queries/view/RepositoriesSearch.tsx
extensions/ql-vscode/src/remote-queries/view/remoteQueries.css

A simple, webview-only search box for filtering repositories from the remote queries results view.
Do we want any animations for showing/hiding repos?

Add repositories search box

---

.github/dependabot.yml

Run dependabot updates weekly

---

extensions/ql-vscode/src/cli.ts
extensions/ql-vscode/src/config.ts
extensions/ql-vscode/src/extension.ts
extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts
extensions/ql-vscode/src/remote-queries/run-remote-query.ts

Rename remote queries -> variant analysis

---

extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts
extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts

Instead of fully failing when a workflow run is cancelled, we check whether there is a result index available. If so, we display the available results! See internal issue for more info 😎 
Note: There's no indication of a "partially cancelled" query in the query history, but we do still display a popup in both cases saying that the variant analysis was cancelled. See screenshots below. I'm very open to alternative UX suggestions 😄 
- Cancelled with no artifacts to download: 
- Cancelled, but there are artifacts to download:
N/A - still internal 🌱

MRVA: Display available results, even if some jobs are cancelled

---

extensions/ql-vscode/src/remote-queries/run-remote-query.ts
extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/run-remote-query.test.ts

Adds more information about onboarding new repos.

Update the warning message after running variant analysis

---

extensions/ql-vscode/src/remote-queries/run-remote-query.ts
extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/run-remote-query.test.ts

Further massage the message after running remote queries

---

extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts

This should avoid an error hit by @jf205.

Handle missing nwos returned from graphql query

---

.github/workflows/main.yml
extensions/ql-vscode/src/vscode-tests/ensureCli.ts

Bumping our tests and workflows to [latest CLI release](https://github.com/github/codeql-cli-binaries/releases/tag/v2.9.3) 😸

Update tests to CLI v2.9.3

---

.github/workflows/main.yml
extensions/ql-vscode/src/vscode-tests/ensureCli.ts

CLI v2.10.2 is [released](https://github.com/github/codeql-cli-binaries/releases/tag/v2.10.2) 😸 
- [N/A] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the `ready-for-doc-review` label there.

Bump CLI version to 2.10.2 for integration tests

---

.github/workflows/main.yml
extensions/ql-vscode/src/vscode-tests/ensureCli.ts

CLI v2.10.3 is [released](https://github.com/github/codeql-cli-binaries/releases/tag/v2.10.3) 💝

Bump CLI version to 2.10.3 for integration tests

---

extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/package.json
extensions/ql-vscode/src/extension.ts

Reverts github/vscode-codeql#1466

Revert "Remove canary requirement for GitHub database download"

---

CODEOWNERS

This will set the correct CODEOWNERS for the MRVA webviews.

Add correct CODEOWNERS for MRVA webviews

---

extensions/ql-vscode/src/remote-queries/shared/repository.ts
extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts

Define some initial models that represent the variant analysis domain. These will be used in the various extension flows and new view/components.

Define variant analysis domain models

---

CONTRIBUTING.md

Clarifies a step of the release process so it's less likely someone will approve a potentially dangerous step of the workflow before running the rest of the release process checks.

Clarify step of the release process

---

extensions/ql-vscode/src/remote-queries/gh-api/variant-analysis.ts

The structure returned from the API has changed so this PR updates the relevant models. See internal linked issue for details.
N/A: Code not in use yet.

Update skipped repo groups structure for variant analysis

---

extensions/ql-vscode/src/view/compare/Compare.tsx
extensions/ql-vscode/src/view/remote-queries/RemoteQueries.tsx

This will implement https://github.com/github/vscode-codeql/commit/ebba9949a8150a771bf726fb3af5d9b74ef0a0bf and https://github.com/github/vscode-codeql/commit/d18e3dd40e57fdb233382cc40058848bd0347753 for the `Compare` and `RemoteQueries` views. These should not be impacted in the same way as the `VariantAnalysis` view, but this will make them consistent and more resilient to future changes.

Fix missing dependencies and cleanup of addEventListener

---

extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisHeader.tsx

Only show file name (not full path) in query details

---

CONTRIBUTING.md

And also clean up the explanation on how to run each type of test.

Clarify the roles of different types of tests

---

extensions/ql-vscode/src/legacy-query-server/run-queries.ts
extensions/ql-vscode/src/run-queries-shared.ts

@alexet These are minor cleanups to your PR #1623.

A couple of small changes around the new query server

---

extensions/ql-vscode/src/mocks/gh-api-request.ts

This will allow us to simulate failed requests.
N/A - internal only

Update mock GitHub API request models to support failures

---

extensions/ql-vscode/src/query-history.ts

This will ensure that we are awaiting all calls by using `Promise.all`.

Fix dangling promises in `forEach` calls

---

.github/workflows/main.yml
extensions/ql-vscode/CHANGELOG.md

Release prep. Bumps some node versions to v16.14.2 to match VSCode's node version.
- [N/A] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the `ready-for-doc-review` label there.

Release prep for v1.7.3

---

extensions/ql-vscode/package-lock.json
extensions/ql-vscode/package.json
extensions/ql-vscode/src/databases/db-config-store.ts
extensions/ql-vscode/test/pure-tests/databases/db-config-store.test.ts

Uses [chokidar](https://www.npmjs.com/package/chokidar) to watch for changes to the `dbconfig.json` file. 
Note: This watcher currently isn't used anywhere, except in tests.
(paired with @norascheuch and @charisk)
N/A - internal only 🐸

Set up a watcher that checks for changes to the new db config

---

extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysis.stories.tsx
extensions/ql-vscode/src/view/variant-analysis/RepositoriesSearchSortRow.tsx

Add missing margin to repositories sort/filter row

---

extensions/ql-vscode/src/common/value-result.ts
extensions/ql-vscode/src/databases/db-config-store.ts
extensions/ql-vscode/src/databases/db-manager.ts
extensions/ql-vscode/src/databases/ui/db-tree-data-provider.ts
extensions/ql-vscode/src/databases/ui/db-tree-view-item.ts
extensions/ql-vscode/test/pure-tests/databases/db-config-store.test.ts

Adds logic to capture and surface any errors when loading and reading the database configuration file. At the moment we're not surfacing the actual error messages in the panel - the exact UX is TBD.

Surface db config errors

---

extensions/ql-vscode/src/databases/ui/db-tree-view-item.ts
extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts

We don't store a path, but simply the ThemeIcon.
N/A:

Rename iconPath to icon

---

extensions/ql-vscode/src/databases/db-config-store.ts
extensions/ql-vscode/src/databases/db-config.ts
extensions/ql-vscode/src/databases/db-tree-creator.ts
extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts
extensions/ql-vscode/test/pure-tests/databases/data/without-selected/workspace-databases.json
extensions/ql-vscode/test/pure-tests/databases/data/workspace-databases.json
extensions/ql-vscode/test/pure-tests/databases/db-config-store.test.ts
extensions/ql-vscode/test/pure-tests/databases/db-config-validator.test.ts
extensions/ql-vscode/test/pure-tests/databases/db-tree-creator.test.ts
extensions/ql-vscode/workspace-databases-schema.json

To display selected Databases in the panel we first have to add the attribute to the workspace-databases.json file.

Add selected to config

---

extensions/ql-vscode/package-lock.json
extensions/ql-vscode/package.json

This is the first part of migrating our tests to to Jest.
The change is intentionally against `main` to avoid nasty merge conflicts.
N/A:

Install VS Code jest runner

---

.vscode/launch.json

Make it a bit easier to run a single test.
N/A:

Add launch configuration to run single unit test

---

extensions/ql-vscode/src/remote-queries/variant-analysis-monitor.ts

This will add error handling to the retrieval of variant analyses in the monitor by catching the error. It will show a warning to the user and log it. Then, it will simply sleep for 5 seconds and try again.
I'm not sure if we want to show all of these errors to the user since this can result in many warnings popping up if many variant analyses are being monitored, but this is probably something that the user should be made aware of.
https://user-images.githubusercontent.com/1112623/205052460-e9897c83-82ff-4431-b808-d5f47ae80e35.mov

Handle errors when retrieving variant analyses in the monitor

---

extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-monitor.test.ts

This integration test will check that the monitor will actually make multiple requests to the API and that it will trigger a download extension command for each repo that has finished scanning.

Add integration test for variant analysis monitor

---

.github/workflows/main.yml
extensions/ql-vscode/src/vscode-tests/ensureCli.ts

CLI v 2.11.5 is now [released](https://github.com/github/codeql-cli-binaries/releases/tag/v2.11.5) 🎈

Bump CLI version to 2.11.5 for integration tests

---

extensions/ql-vscode/src/common/app.ts
extensions/ql-vscode/src/common/vscode/vscode-app.ts
extensions/ql-vscode/test/__mocks__/appMock.ts

See internal issue for details.
N/A:

Add executeCommand to app container

---

extensions/ql-vscode/src/databases/ui/db-panel.ts

Fixed hooking to collapse/expand events from the tree view and made sure we dispose of subscriptions to events.
N/A:

Properly track collapsed/expanded events

---

extensions/ql-vscode/src/databases/db-module.ts
extensions/ql-vscode/src/extension.ts

Tidy up db module initialisation so that all code related to db module initialisation happens within `DbModule`. We use `undefined` to communicate that the module may not be available.
N/A:

Db module init tidy up

---

extensions/ql-vscode/test/factories/db-config-factories.ts
extensions/ql-vscode/test/pure-tests/databases/db-tree-creator.test.ts

Unfortunately we can't use this in integration tests because those are in `/src`.
N/A:

Add db config factory function and use it in tests

---

extensions/ql-vscode/src/config.ts

A PR which makes live results enabled for all users. This is the final change that'll be made before releasing. We can build extensions off of this branch for pre-release testing.
IMPORTANT NOTE:  this should NOT be merged until we're ready to do the final release.

Make live results enabled for everyone

---

extensions/ql-vscode/CHANGELOG.md

v1.7.7 release

---

extensions/ql-vscode/src/common/vscode/vscode-app.ts

Fix executeCommand to pass arguments correctly

---

extensions/ql-vscode/src/common/app.ts
extensions/ql-vscode/src/common/vscode/vscode-app.ts
extensions/ql-vscode/test/__mocks__/appMock.ts
extensions/ql-vscode/test/__mocks__/loggerMock.ts

This will allow easy mocking of the logger and will help with avoiding dependency to the VS Code API.
N/A:

Add logger to the app container

---

extensions/ql-vscode/src/databases/ui/db-panel.ts
extensions/ql-vscode/src/vscode-tests/cli-integration/databases/db-panel.test.ts

Add basic integration test for 'add db' functionality

---

extensions/ql-vscode/test/unit-tests/pure/date.test.ts

Simple fix for now to unblock other PRs. We will look at what the correct thing to be doing here is separately.
N/A:

Fix broken unit test that relies on date

---

extensions/ql-vscode/package.json
extensions/ql-vscode/src/databases/config/db-config-store.ts
extensions/ql-vscode/src/databases/db-item-selection.ts
extensions/ql-vscode/src/databases/db-manager.ts
extensions/ql-vscode/src/databases/ui/db-panel.ts
extensions/ql-vscode/test/unit-tests/databases/config/db-config-store.test.ts

Adds a remove context menu action.

Add remove context menu action

---

extensions/ql-vscode/src/databases/config/db-config-store.ts
extensions/ql-vscode/test/unit-tests/databases/config/db-config-store.test.ts
extensions/ql-vscode/test/unit-tests/databases/db-manager.test.ts
extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel.test.ts

See internal linked issue for more context!

Fix flaky test: avoid file watcher in db manager tests

---

extensions/ql-vscode/test/unit-tests/databases/config/db-config-store.test.ts

Improve tests coverage in db-config-store

---

CONTRIBUTING.md

Explain what the different test suites are meant to be used for.
N/A:

Improve docs around different test suites

---

extensions/ql-vscode/src/databases/config/db-config-store.ts
extensions/ql-vscode/src/databases/config/db-config.ts
extensions/ql-vscode/src/databases/ui/db-panel.ts
extensions/ql-vscode/test/unit-tests/databases/config/db-config-store.test.ts
extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel.test.ts

Renaming everything remote to variant analysis.

Polish user facing messages

---

extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel.test.ts
extensions/ql-vscode/test/vscode-tests/no-workspace/databases/db-panel-selection.test.ts

Tests are moved into the `no-workspace` folder

Extract db panel selection tests to new file 

---

extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel.test.ts
extensions/ql-vscode/test/vscode-tests/no-workspace/databases/db-panel-add-items.test.ts

Tests are moved into the `no-workspace` folder

Extract db panel add items tests to new file

---

extensions/ql-vscode/package.json

To make the `select` action more prominent and give the menu more vividness we want to order and group the actions.

Sort and group context menu actions

---

extensions/ql-vscode/package.json

Update text when no query history item exists.

Query history polish: update empty state

---

extensions/ql-vscode/src/databases/ui/db-tree-view-item.ts
extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel-rendering.test.ts

DB panel: use cloud icon for variant analysis repositories

---

extensions/ql-vscode/package.json
extensions/ql-vscode/src/query-history/query-history-manager.ts

Updates the copy and introduces groups to the context menu for the query history.

Query History: context menu copy and groups

---

extensions/ql-vscode/package.json

Query History Item: remove on hover

---

extensions/ql-vscode/src/databases/ui/db-panel.ts

Fix placeholder copy

---

extensions/ql-vscode/package.json

Renamed `Remove` -> `Delete` in the variant analysis repos panel so that it matches the term we use in the query history.
N/A:

Update the copy for the codeQLVariantAnalysisRepositories.removeItemContextMenu command

---

extensions/ql-vscode/databases-schema.json
extensions/ql-vscode/src/databases/config/db-config-store.ts
extensions/ql-vscode/src/databases/config/db-config.ts
extensions/ql-vscode/test/factories/db-config-factories.ts
extensions/ql-vscode/test/unit-tests/databases/config/data/databases.json
extensions/ql-vscode/test/unit-tests/databases/config/data/without-selected/databases.json
extensions/ql-vscode/test/unit-tests/databases/config/db-config-validator.test.ts
extensions/ql-vscode/test/unit-tests/databases/db-manager.test.ts

The version isn't used yet but will be used in the future.
N/A:

Added version to db config

---

extensions/ql-vscode/.eslintrc.js
extensions/ql-vscode/src/abstract-webview.ts
extensions/ql-vscode/src/cli.ts
extensions/ql-vscode/src/config.ts
extensions/ql-vscode/src/contextual/locationFinder.ts
extensions/ql-vscode/src/databases.ts
extensions/ql-vscode/src/distribution.ts
extensions/ql-vscode/src/interface.ts
extensions/ql-vscode/src/legacy-query-server/run-queries.ts
extensions/ql-vscode/src/log-insights/join-order.ts
extensions/ql-vscode/src/pure/result-keys.ts
extensions/ql-vscode/src/pure/sarif-utils.ts
extensions/ql-vscode/src/query-history/query-history-manager.ts
extensions/ql-vscode/src/quick-query.ts
extensions/ql-vscode/src/remote-queries/sarif-processing.ts
extensions/ql-vscode/src/run-queries-shared.ts
extensions/ql-vscode/src/test-adapter.ts
extensions/ql-vscode/src/view/common/FileCodeSnippet/CodeSnippetLine.tsx
extensions/ql-vscode/src/view/results/alert-table.tsx
extensions/ql-vscode/src/view/results/graph.tsx
extensions/ql-vscode/src/view/results/result-tables.tsx
extensions/ql-vscode/src/view/results/results.tsx
extensions/ql-vscode/src/view/variant-analysis/RepoRow.tsx
extensions/ql-vscode/test/vscode-tests/no-workspace/query-serialization.test.ts

Enforce use of === and !== and update places where we're not. See https://eslint.org/docs/latest/rules/eqeqeq for details.
Please shout if there are reasons we should not do this.
N/A:

Enable eqeqeq ESLint rule and fix violations

---

extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisStatusStats.tsx

Add link to Actions workflow when running MRVA

---

extensions/ql-vscode/package.json

Remove random capital letters to match the other tooltips.
N/A:

Remove random capital letters

---

extensions/ql-vscode/package.json

Note that I've not updated the CHANGELOG since it doesn't seem a significant change. Let me know if that doesn't seem right.
N/A:

Update copy for local db select button

---

extensions/ql-vscode/src/databases/config/db-config-store.ts
extensions/ql-vscode/test/unit-tests/databases/config/db-config-store.test.ts

Removes 1 extra click for users.
N/A:

Pre-select top-10 list in variant analysis repos panel

---

extensions/ql-vscode/docs/test-plan.md
extensions/ql-vscode/package.json
extensions/ql-vscode/src/config.ts
extensions/ql-vscode/test/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts
extensions/ql-vscode/test/vscode-tests/cli-integration/remote-queries/variant-analysis-submission-integration.test.ts
extensions/ql-vscode/test/vscode-tests/no-workspace/remote-queries/repository-selection.test.ts

This enables the new panel, and adds some test cases to the test plan.
N/A:

Unveil new variant analysis repositories panel

---

extensions/ql-vscode/src/databases/config/db-config-validator.ts

Pre-compile the jSON schema used for validating the db config and cache the validation function.
N/A:

Cache schema validator for db config

---

extensions/ql-vscode/src/cli.ts

In some of the methods of the `CodeQLCliServer` class there we had multiple optional arguments, including default values. This made it quite hard to read and required specifying the default values for an argument if you only needed to change a later argument. This will switch them to have options objects which are easier to read and don't require repeating default values.

Use options objects instead of multiple optional arguments in CLI methods

---

extensions/ql-vscode/docs/test-plan.md

Just a couple of things I noticed last time I was going through the test plan.
N/A:

Minor changes to the test plan

---

extensions/ql-vscode/package.json

Removes new UI commands from command palette

Remove new commands from command palette

---

extensions/ql-vscode/package.json

Add controller repo 'learn more' link

---

README.md
extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/docs/test-plan.md
extensions/ql-vscode/package.json
extensions/ql-vscode/src/databases/db-module.ts
extensions/ql-vscode/src/extension.ts
extensions/ql-vscode/src/variant-analysis/repository-selection.ts
extensions/ql-vscode/src/variant-analysis/run-remote-query.ts
extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-submission-integration.test.ts

Reverts github/vscode-codeql#2121

Revert "Move MRVA out of canary"

---

extensions/ql-vscode/src/config.ts
extensions/ql-vscode/src/telemetry.ts
extensions/ql-vscode/test/vscode-tests/no-workspace/telemetry.test.ts

Follows on from https://github.com/github/vscode-codeql/pull/2114 and cleans up the config and places where we checked if the new telemetry collection was enabled.

Cleanup config to enabling new telemetry

---

extensions/ql-vscode/src/commandRunner.ts

The `commandRunnerWithProgress` implementation isn't actually any different from `commandRunner`, except for the call to `withProgress` and support for an `outputLogger` argument. Therefore, this will simply make `commandRunnerWithProgress` a wrapper around `commandRunner`, removing quite some duplication in the process.

Unify `commandRunner` implementations

---

CONTRIBUTING.md
extensions/ql-vscode/package-lock.json
extensions/ql-vscode/package.json

These are no longer in use.
N/A:

Remove primer packages and make styled-components a top-level dependency

---

extensions/ql-vscode/src/commandRunner.ts

The `commandRunnerWithProgress` is unused because all commands have been converted to using `commandRunner` in combination with `withProgress`.

Remove `commandRunnerWithProgress`

---

extensions/ql-vscode/test/vscode-tests/cli-integration/data/codeql-pack.lock.yml

These changes get made automatically when you run the CLI integration tests. I'm just committing the changes to the repo.

Commit autogenerated changes to codeql-pack.lock.yml

---

extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts

These tests seem to be consistently timing out, so we're increasing the timeout to allow them to finish.

Raise timeout of queries tests

---

extensions/ql-vscode/package-lock.json
extensions/ql-vscode/package.json

This reverts commit 8e40d7d61ddfb20fbdb51672088e37a1378a3c7b (#2320) because of mismatched package versions in Storybook which cause it to fail to start.

Revert "Bump @storybook/builder-webpack5 (#2320)"

---

extensions/ql-vscode/src/data-extensions-editor/bqrs.ts
extensions/ql-vscode/test/unit-tests/data-extensions-editor/bqrs.test.ts

This puts the unsupported methods first in the extension view.

Sort on supported status.

---

extensions/ql-vscode/src/ast-cfg-commands.ts
extensions/ql-vscode/src/debugger/debug-configuration.ts
extensions/ql-vscode/src/debugger/debugger-factory.ts
extensions/ql-vscode/src/debugger/debugger-ui.ts
extensions/ql-vscode/src/extension.ts
extensions/ql-vscode/src/local-queries/index.ts
extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts

Introduce index.ts for local-queries module
N/A:

Introduce index.ts for local-queries module

---

extensions/ql-vscode/src/extension.ts
extensions/ql-vscode/src/local-queries/index.ts
extensions/ql-vscode/src/local-queries/local-queries.ts
extensions/ql-vscode/src/local-queries/quick-eval-code-lens-provider.ts
extensions/ql-vscode/src/local-queries/quick-query.ts
extensions/ql-vscode/src/run-queries-shared.ts

This PR is part of an endeavour to order files in the codebase according to the domain model. Here files related to the local queries are moved to one folder.
Nothing unexpected came up during the work.

Move local query files

---

extensions/ql-vscode/src/data-extensions-editor/auto-model.ts

Ensure that even methods without classification are marked as neutral. See internal linked issue for details.

Allow unclassified methods to be marked as neutral

---

extensions/ql-vscode/src/data-extensions-editor/auto-model-api.ts
extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts

Deal with no predictions gracefully

---

extensions/ql-vscode/src/databases/ui/db-panel.ts

Linking to the correct search api documentation

Code search: Use correct link and text

---

extensions/ql-vscode/CHANGELOG.md
extensions/ql-vscode/package.json

Removes the feature flag and updates the Changelog.

Remove code search feature flag

---

extensions/ql-vscode/src/data-extensions-editor/queries/csharp.ts
extensions/ql-vscode/src/data-extensions-editor/queries/java.ts

This updates the `ExternalApi.qll` dependencies for Java and C# to their latest versions in the `github/codeql` repository (as of [`7efbd88`](https://github.com/github/codeql/commit/7efbd8828bb919491217e1aa5ae2f92ffdb7a454)).

Update ExternalApi.qll dependencies

---

extensions/ql-vscode/package.json

Adds the correct icon to run queries from the new panel.

Fix merge conflict error: Re-add icon

---

extensions/ql-vscode/package.json

Release run query from file tab icon

---

extensions/ql-vscode/src/view/results/graph.tsx
extensions/ql-vscode/src/view/results/result-tables.tsx

Converts the `Graph`  from a class component to a function component.

Convert Graph to a functional component

---

extensions/ql-vscode/CHANGELOG.md

We're about to release v1.8.8! This PR updates the changelog (including some small tweaks to the previous entry).
N/A

Release prep for v1.8.8

---

extensions/ql-vscode/CHANGELOG.md

Or at least I assume this is a typo.

Fix typo in CHANGELOG.md

---

extensions/ql-vscode/CHANGELOG.md

No changes needed other than the new version.

Release prep for v1.8.9

---

extensions/ql-vscode/package.json
extensions/ql-vscode/src/common/commands.ts
extensions/ql-vscode/src/config.ts
extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts

- create a new feature flag: `config.codeQL.dataExtensions.modelDetailsView`
- focus panel tab if 'view'-button is clicked in Data Extensions Editor

Set up model details view

---

extensions/ql-vscode/src/variant-analysis/gh-api/mocks/gh-api-request.ts
extensions/ql-vscode/src/variant-analysis/gh-api/mocks/request-handlers.ts
extensions/ql-vscode/src/variant-analysis/gh-api/mocks/scenarios/auto-model-success/0-autoModel.json
extensions/ql-vscode/src/variant-analysis/gh-api/mocks/scenarios/auto-model-success/1-autoModel.json
extensions/ql-vscode/src/variant-analysis/gh-api/mocks/scenarios/auto-model-success/README.md

Adds the scenario and fixes the request replay logic.
N/A:

Add auto-model mock API scenario

---

extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx

This is to avoid rendering everything right away.
N/A:

Start with collapsed items in data extensions editor

---

extensions/ql-vscode/package.json
extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts
extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx
extensions/ql-vscode/src/stories/data-extensions-editor/MethodRow.stories.tsx

This updates the visible strings to the new name.

Update editor name in visible strings.

---

extensions/ql-vscode/src/data-extensions-editor/auto-model-codeml-queries.ts
extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-queries.ts
extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/auto-model-codeml-queries.test.ts

This allows the model editor to use the automodel queries from the pack.

Use auto-model pack to run auto-model queries.

---

extensions/ql-vscode/package.json

Add beta label to model editor

---

extensions/ql-vscode/src/model-editor/extension-pack-picker.ts

Fix for https://github.com/github/vscode-codeql/pull/2766#pullrequestreview-1604777623

Fix a comment that should be renamed.

---

extensions/ql-vscode/src/model-editor/shared/sorting.ts

This will sort methods in the model editor alphabetically as a tie-breaker when the number of usages is equal, rather than by the initial sort order (which I believe is unspecified).

Sort methods alphabetically

---

extensions/ql-vscode/src/model-editor/shared/in-progress-methods.ts
extensions/ql-vscode/src/stories/model-editor/LibraryRow.stories.tsx
extensions/ql-vscode/src/view/common/Dropdown.tsx
extensions/ql-vscode/src/view/model-editor/KindInput.tsx
extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx
extensions/ql-vscode/src/view/model-editor/MethodRow.tsx
extensions/ql-vscode/src/view/model-editor/ModeledMethodDataGrid.tsx
extensions/ql-vscode/src/view/model-editor/ModeledMethodsList.tsx
extensions/ql-vscode/src/view/model-editor/__tests__/LibraryRow.spec.tsx
extensions/ql-vscode/src/view/model-editor/__tests__/MethodRow.spec.tsx
extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodDataGrid.spec.tsx
extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodsList.spec.tsx
extensions/ql-vscode/test/factories/data-extension/method-factories.ts
extensions/ql-vscode/test/factories/model-editor/extension-pack.ts

This adds tests for these 4 components:
- `LibraryRow` (also adds a story)
- `ModeledMethodsList`
- `ModeledMethodDataGrid`
- `MethodRow`

Add tests for model editor row and grid components

---

extensions/ql-vscode/src/stories/method-modeling/MethodModeling.stories.tsx
extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx
extensions/ql-vscode/src/view/method-modeling/__tests__/MethodModeling.spec.tsx

Some minor changes to the top part of the method modeling panel to get closer to the designs now that they have been updated. This is not the final product as we're still discussing exact UI and colours with Design, but I thought we could iterate over it.
N/A:

Minor redesign of method modeling title

---

extensions/ql-vscode/src/stories/method-modeling/MethodModeling.stories.tsx

I merged two PRs touching the same code around the same time and the merge on main broke
* https://github.com/github/vscode-codeql/pull/2832
* https://github.com/github/vscode-codeql/pull/2834
N/A:

Update import to fix build

---

extensions/ql-vscode/src/view/model-editor/ModelTypeDropdown.tsx

Discussed in https://github.com/github/vscode-codeql/pull/2833#discussion_r1331235378
I didn't spread at all in the end because it's not necessary.
N/A:

Remove unnecessary spread of modeled method

---

extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx

Add unsaved tag on method modeling panel

---

extensions/ql-vscode/src/model-editor/bqrs.ts
extensions/ql-vscode/src/model-editor/external-api-usage-queries.ts
extensions/ql-vscode/src/model-editor/queries/csharp.ts
extensions/ql-vscode/src/model-editor/queries/java.ts
extensions/ql-vscode/src/model-editor/queries/query.ts
extensions/ql-vscode/test/unit-tests/model-editor/bqrs.test.ts
extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/external-api-usage-query.test.ts
extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/model-editor-queries.test.ts

This updates the model editor queries to the version that will be merged into the CodeQL repository. There are some slight changes to the output format, so we slightly need to change the BQRS decoding of those queries.
The queries themselves were copied from the two PRs (https://github.com/github/codeql/pull/14200 and https://github.com/github/codeql/pull/14199) with some minor additions at the end since these were changes in core CodeQL library files.

Update model editor queries

---

extensions/ql-vscode/CHANGELOG.md

I believe these PRs are interesting to mention in the CHANGELOG, all other PRs are related to unreleased/canary functionality.

Release v1.9.1

---

extensions/ql-vscode/src/common/vscode/abstract-webview.ts
extensions/ql-vscode/src/local-queries/results-view.ts

This will change the `AbstractWebview` to dispose its tracked objects (using `this.push`) when the panel is disposed rather than when the view is disposed. This makes `this.push` actually useful in a view. Before, the objects would only get disposed when the extension itself was disposed.

Dispose tracked objects when panel is disposed

---

docs/test-plan.md

Add missing feature flag to test plan

---

extensions/ql-vscode/package.json

Move method modeling panel back to CodeQL view container
N/A:

Move method modeling panel out of explorer

---

extensions/ql-vscode/src/packages/commands/CommandManager.ts

I don't think these TODOs are adding any values so I've removed them.

Remove unnecessary TODOs

---

extensions/ql-vscode/package.json

Make method modeling panel available to canary users

---

extensions/ql-vscode/CHANGELOG.md

Release v1.9.2

---

extensions/ql-vscode/src/stories/model-editor/MethodRow.stories.tsx
extensions/ql-vscode/src/view/common/ScreenReaderOnly.tsx
extensions/ql-vscode/src/view/model-editor/MethodRow.tsx
extensions/ql-vscode/src/view/model-editor/ModeledMethodDataGrid.tsx

Adds icons for adding/deleting multiple models to the model editor.
Currently this is just static UI and these aren't linked up to anything. The things still to do are:
- Enable/disable the buttons at the right times.
- Implement `onClick` handlers.
I'll do these things in separate PRs to keep things small.

Add add/remove buttons for models

---

extensions/ql-vscode/.storybook/main.ts
extensions/ql-vscode/package-lock.json
extensions/ql-vscode/package.json

This adds the `@storybook/addon-a11y` package and adds it as a Storybook add-on. This makes it possible to view axe violations in Storybook.

Add @storybook/addon-a11y package

---

extensions/ql-vscode/src/databases/code-search-api.ts
extensions/ql-vscode/src/databases/ui/db-panel.ts

Instead of returning an empty array we're not cancelling the command execution.

Improve code search cancelling

---

extensions/ql-vscode/src/config.ts
extensions/ql-vscode/src/model-editor/auto-modeler.ts
extensions/ql-vscode/src/model-editor/model-editor-view.ts

See reasoning in internal linked issue.
N/A:

Make automodel batch size configurable

---

extensions/ql-vscode/src/databases/code-search-api.ts
extensions/ql-vscode/src/databases/ui/db-panel.ts

Code Search: use withProgress to indicate api request progress

---

docs/test-plan.md

A couple of things I noticed when running through the test plan last week
N/A:

Minor test plan fixes

---

docs/test-plan.md

This should make it easier to test the "Model with AI" functionality.
N/A:

Add note in Model with AI test case in test plan

---

extensions/ql-vscode/src/model-editor/queries/ruby.ts

This updates the bundled model editor Ruby queries to match the ones in [github/codeql#14679](https://redirect.github.com/github/codeql/pull/14679). There are no changes to the queries, but I had to add the `queries/modeling/internal/Util.qll` dependency since it's in the `codeql/ruby-queries` pack rather than in `codeql/ruby-all`.

Update model editor Ruby queries

---

extensions/ql-vscode/src/log-insights/join-order.ts

This PR ports the changes from the DCA join order badness RA parser to the VS Code extension to [add support for unnamed RA nodes](https://github.com/github/codeql-dca/pull/1758) and [UNION nodes](https://github.com/github/codeql-dca/pull/1751).

Port DCA join-order badness RA parser changes

---

extensions/ql-vscode/CHANGELOG.md

Add CHANGELOG entry for `yauzl` migration

---

extensions/ql-vscode/src/config.ts

Currently unused, but this will make it easier to add support for more complex access paths to the model editor, gated behind `"codeQL.model.enableAccessPathSuggestions": true`.
See internal linked issue (+ hackathon project) for more details!
N/A - no visible changes

Add new feature flag for "access path suggestions"

---

extensions/ql-vscode/src/view/common/SuggestBox/__tests__/SuggestBox.test.tsx

I'm not able to reproduce these tests failing, so let's skip them for now.

Skip suggest box tests using Tab

---

extensions/ql-vscode/src/view/model-editor/AccessPathSuggestBox.tsx
extensions/ql-vscode/src/view/model-editor/ModelInputSuggestBox.tsx
extensions/ql-vscode/src/view/model-editor/ModelOutputSuggestBox.tsx
extensions/ql-vscode/src/view/model-editor/ModelTypePathSuggestBox.tsx

This extracts all common functionality from the various model editor suggest box components into a single component that can be shared by the model editor suggest box components to make improvements easier.

Extract `AccessPathSuggestBox` component

---

extensions/ql-vscode/src/model-editor/model-evaluator.ts

Change the model evaluation notification so that it doesn't have a cancel action and also update the text.
N/A:

Update model evaluation notification

---

docs/node-version.md

Update the docs for the VS Code Node.js version to mention that an automated workflow exists and it should not be necessary to do anything manually. We will keep the information around for how to check and update the Node.js version manually just in case.

Mention that an automated workflow exists for updating the node version

---

extensions/ql-vscode/src/common/interface-types.ts
extensions/ql-vscode/src/model-editor/model-alerts/model-alerts-view.ts
extensions/ql-vscode/src/model-editor/model-editor-view.ts
extensions/ql-vscode/src/model-editor/model-evaluator.ts
extensions/ql-vscode/src/model-editor/shared/view-state.ts
extensions/ql-vscode/src/stories/model-alerts/ModelAlerts.stories.tsx
extensions/ql-vscode/src/view/model-alerts/ModelAlerts.tsx
extensions/ql-vscode/src/view/model-alerts/ModelAlertsHeader.tsx
extensions/ql-vscode/test/vscode-tests/activated-extension/model-editor/model-evaluator.test.ts

Adds a title to the model alerts view:
N/A—feature-flagged for internal use/testing

Add title to model alerts view

---

extensions/ql-vscode/CHANGELOG.md

Minor: Replaces a broken link in the changelog

Remove rogue semmle link

---

.github/dependabot.yml

Exclude major version updates for the octokit group in dependabot

---

extensions/ql-vscode/CHANGELOG.md

Add Ruby model editor support to CHANGELOG

---

extensions/ql-vscode/src/common/authentication.ts
extensions/ql-vscode/src/common/github-url-identifier-helper.ts
extensions/ql-vscode/src/common/vscode/authentication.ts
extensions/ql-vscode/src/common/vscode/octokit.ts
extensions/ql-vscode/src/config.ts
extensions/ql-vscode/src/databases/code-search-api.ts
extensions/ql-vscode/src/databases/database-fetcher.ts
extensions/ql-vscode/src/databases/github-databases/api.ts
extensions/ql-vscode/src/databases/ui/db-panel.ts
extensions/ql-vscode/src/databases/ui/db-tree-view-item-action.ts
extensions/ql-vscode/src/extension.ts
extensions/ql-vscode/src/query-history/query-history-info.ts
extensions/ql-vscode/src/variant-analysis/custom-errors.ts
extensions/ql-vscode/src/variant-analysis/shared/variant-analysis.ts
extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
extensions/ql-vscode/src/variant-analysis/variant-analysis-results-manager.ts
extensions/ql-vscode/test/factories/authentication.ts
extensions/ql-vscode/test/factories/config.ts
extensions/ql-vscode/test/unit-tests/common/github-url-identifier-helper.test.ts
extensions/ql-vscode/test/unit-tests/databases/ui/db-tree-view-item-action.test.ts
extensions/ql-vscode/test/unit-tests/variant-analysis.test.ts
extensions/ql-vscode/test/unit-tests/variant-analysis/custom-errors.test.ts
extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-manager.test.ts
extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-results-manager.test.ts
extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts

This adds GHEC-DR support for running variant analyses and downloading databases. It's easiest to review this commit-by-commit.

Add GHEC-DR support

---

extensions/ql-vscode/src/query-server/query-server-client.ts

Previously, we were using the [`close` event handler](https://nodejs.org/api/child_process.html#event-close) for the query server child process(es). This did not always properly handle the case where the child query server process crashed, because `close` is only emitted after all stdio streams of the child process are closed (see back-linked issue).
This PR handles the `exit` and `error` processes instead: `exit` is emitted even if child process stdio streams are still open. Note that the documentation indicates that `exit` may still fire after `error`, so this change includes some simple logic to make sure that we only restart the query server once if both fire.

Handle exit and error events for query server child processes

---

extensions/ql-vscode/README.md

I went through every link and found these two that are outdated.

Update outdated links in VS Code extension README

---

extensions/ql-vscode/CHANGELOG.md

Release 1.16.1
Remember to update the [changelog](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) if there have been user-facing changes!

Release v1.16.1

---

extensions/ql-vscode/src/view/compare-performance/ComparePerformance.tsx

Compare-perf: Allow word wrap to break anywhere

---

README.md

See docs https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/adding-a-workflow-status-badge.

Use correct CI badge URL

---

extensions/ql-vscode/CHANGELOG.md

Release v1.17.2

---

extensions/ql-vscode/package-lock.json

This resolves https://github.com/github/vscode-codeql/security/dependabot/93.

Upgrade brace-expansion to v2.0.2
