common/config/rush/shrinkwrap.yaml, extensions/ql-vscode/package.json, extensions/ql-vscode/src/distribution.ts
Previously a cast was necessary as the type for `unzipper.Open.file.extract` was incorrect.  My PR to fix the typedef (DefinitelyTyped/DefinitelyTyped#40240) has now been merged, so this PR removes the cast.
=> Remove cast now unzipper typedef fix is merged

extensions/ql-vscode/package.json, extensions/ql-vscode/src/query-history.ts
One of the things https://github.com/github/pe-security-codeql/issues/59 asked for.
=> Allow removing items from query history

extensions/ql-vscode/README.md
The anchor `#importing-a-database-from-lgtmcom` doesn't work in the [marketplace](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-codeql) overview and `#importing-a-database-from-lgtm.com` doesn't work in the GitHub preview 🤦‍♀ 
This works on both.
=> Readme: Fix anchor link

extensions/ql-vscode/package.json, tools/build-tasks/src/deploy.ts
- Bumps the version of the extension to 1.0.1. We should bump the version immediately after every official release, so that any builds that happen after the release are treated as prerelease versions of the next release.
- Separates the components of the timestamp in the version number for non-release builds. This just makes it easier to read. I also left off the milliseconds, which were kind of overkill, and switched to using UTC time to avoid time-zone ambiguity.
- Updates the version number in the copy of the extension's `package.json` that winds up in the actual .vsix, so VS Code actually sees the version as being the proper prelease version.
=> A few versioning fixes

extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/queries.ts
This was a simple case of passing entirely the wrong data as an
argument to the `upgradeDatabase` call in `queries.ts`. We were
passing the list of search paths for upgrades, when we should have
been passing the list of directories directly containing upgrade
scripts to be applied.
Fixes #168.
=> Fix auto-upgrade script path

extensions/ql-vscode/src/view/alert-table.tsx, extensions/ql-vscode/src/view/raw-results-table.tsx, extensions/ql-vscode/src/view/result-table-utils.tsx, extensions/ql-vscode/src/view/result-tables.tsx, extensions/ql-vscode/src/view/resultsView.css
We don't need to render all tables and use css to hide the ones we
don't currently want to see. Instead have `render` return the dom that
should be visible given the current state.
=> Simplify selected results table handling

extensions/ql-vscode/src/interface.ts
When following a link from the result viewer, we highlighted the target range simply by selecting it. 
When this range is an identifier, it triggers vscode's occurrence-match highlighting, which makes it hard to see at a glance what was highlighted. This PR introduces decorators to highlight it a bit more, using the same colors as in search/replace.
The decoration is cleared on any selection change event in that editor.
Before
-
After
-
=> Add decoration to focused item

extensions/ql-vscode/package.json
Now that we've released 1.0.1, all subsequent builds should be prerelease versions of 1.0.2
=> Bump version to 1.0.2

extensions/ql-vscode/src/distribution.ts, extensions/ql-vscode/src/extension.ts
- Add a specific error message when the user has been rate limited which specifies when the rate limiting resets.
- If an error occurs while updating the CLI during an automatic update check, this will be displayed as a warning rather than an error as it is non-critical.
- Remove the link to edit the settings when we encounter a GitHub API error, since we no longer have any settings that could be related to these errors.
- Error messages take into account the specific task.
Am very much open to better names for `ReportingConfig`
=> Improve error handling for CLI installation and updates

extensions/ql-vscode/src/queries.ts
This way they don't clash when switching between sorted queries. As the filename wasn't assigned in the constructor, it was using the value for the next run query rather than the id for the current query.
=> Store the current counter value and use it for the sorted results path.

extensions/ql-vscode/src/interface.ts
This gives better results for query names that start with for example a multiple letter acronym.
=> Use quoted query name in view results message

extensions/ql-vscode/package.json, extensions/ql-vscode/src/interface-types.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/result-keys.ts, extensions/ql-vscode/src/view/alert-table.tsx, extensions/ql-vscode/src/view/event-handler-list.ts, extensions/ql-vscode/src/view/result-table-utils.tsx, extensions/ql-vscode/src/view/results.tsx, extensions/ql-vscode/src/view/resultsView.css
This adds the command `CodeQL: Show Next Step on Path` and `CodeQL: Show Previous Step on Path` for navigating the steps on the currently shown path.
The idea is that you can add keybindings for these commands to navigate the path without the mouse. Doing this with the mouse required quite a bit of zig-zag eye tracking between the code view and result view.
You still have to click one of the steps on a path to "choose" that path. There are currently no commands for switching between results or paths. It would be nice to have a fully keyboard-controllable result view, but I think I'll leave that for a future PR.
It's a bit of a hassle to make the result view remember which path node was previously clicked. For this we need a way to reference a specific part of the result set, that is, a …
=> Add commands for navigating the steps on a path

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history.ts
- there's now a command in the context menu for setting the label to some custom text
- the default format string can be configured in settings
Fixes https://github.com/github/pe-security-codeql/issues/198
=> Improvements to Query History Labels

extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/queries.ts
This is a key cause of not being able to produce interpreted results, so logging this case when it occurs helps us debug a lack of interpreted results.
Also make the database metadata check async.
=> Log if a database metadata file could not be found

configs/typescript-config/common.tsconfig.json, extensions/ql-vscode/src/archive-filesystem-provider.ts, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/distribution.test.ts, extensions/ql-vscode/test/pure-tests/query-test.ts, lib/semmle-bqrs/src/bqrs-custom.ts, lib/semmle-io/src/digester.ts, tools/build-tasks/src/textmate.ts, tools/build-tasks/src/typescript.ts
Specifically the `noUnusedLocals` and `noUnusedParameters` options.  This will mean that we catch these types of warning at compile-time rather than on the PR.
To fix unused locals, I've removed some `private` annotations on constructor parameters where the property was unused.  For unused parameters, I've removed the parameter from internal functions and prefixed an underscore.
=> Enable unused value compiler checks

extensions/ql-vscode/src/query-history.ts
Do this by lazily updating the selection of the query history view, since the only API for changing a TreeView selection reveals the TreeView.
Fixes #197
=> Fix sidebar focus change when showing results

extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/webview-uri.test.ts
This fixes sorting for result sets with a "#" in their name.  Add an integration test to verify this behaviour.
=> Fix double-encoding of "#" in webview URI conversion

.github/workflows/main.yml, extensions/ql-vscode/test/pure-tests/query-test.ts
This pull installs CodeQL on the test Actions job so that we can run the unit tests on Actions that require the CodeQL CLI.  It also adds additional checkpoints to the query server tests to resolve some race conditions.
=> Add support for running unit tests requiring CodeQL on Actions

extensions/ql-vscode/src/distribution.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/helpers.test.ts
Implement a rate limiter for function invocations and use it to limit non-user-triggered CLI update checks to once per 24 hours.  This helps to avoid hitting the GitHub API limits of 60 requests per hour for unauthenticated IPs.
=> Reduce update check frequency

extensions/ql-vscode/test/pure-tests/query-test.ts
This pull increases the timeout for the query unit tests to avoid transient test failures like https://github.com/github/vscode-codeql/commit/e966c339d35766550b91a85eda1a93d8cb822112/checks?check_suite_id=383124497 resulting from the query server not starting up in time.
=> Increase timeout for query unit tests

extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/helpers.test.ts
Mock Date in InvocationRateLimiter integration tests so tests don't need to use `setTimeout`.
=> Mock Date in InvocationRateLimiter integration tests

extensions/ql-vscode/package.json, extensions/ql-vscode/src/distribution.ts
We just merged a change so that the main CodeQL executable on Windows is called `codeql.exe`. For now, `codeql.cmd` still exists as a wrapper, so we have some leeway in making this change.
=> Use codeql.exe instead of codeql.cmd on Windows

extensions/ql-vscode/package.json, extensions/ql-vscode/src/distribution.ts
Reverts github/vscode-codeql#211
We need to (1) make a new CLI release and (2) update the extension's CLI version constraint before launching CodeQL via `codeql.exe`.
=> Revert "Use codeql.exe instead of codeql.cmd on Windows"

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json
Addresses at least one point of https://github.com/github/vscode-codeql/issues/216.
=> Default to disabling word based auto-complete when editing QL.

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/interface-types.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/queries.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/quick-query.ts, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/sarif-utils.ts, extensions/ql-vscode/src/upgrades.ts, extensions/ql-vscode/src/view/alert-table.tsx, extensions/ql-vscode/src/view/result-table-utils.tsx, extensions/ql-vscode/src/view/result-tables.tsx, extensions/ql-vscode/src/view/results.tsx, extensions/ql-vscode/src/vscode-tests/no-workspace/sarifMessageParsingTest.test.ts
This is just a rebased version of https://github.com/github/vscode-codeql/pull/184 and https://github.com/github/vscode-codeql/pull/185
=> Create diagnostics messages using sarif.

.github/workflows/main.yml
Actions appears to be computing the diff with respect to the pull request base, so that a commit will trigger the workflow if the pull request as a whole contains any changes that modify non-markdown files, which is slightly unfortunate, but still an improvement for tiny documentation PRs.
=> Exclude documentation from CI workflow (WIP don't merge)

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/interface-types.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/view/alert-table.tsx, extensions/ql-vscode/src/view/raw-results-table.tsx, extensions/ql-vscode/src/view/result-table-utils.tsx, extensions/ql-vscode/src/view/result-tables.tsx, extensions/ql-vscode/src/view/results.tsx, extensions/ql-vscode/src/view/resultsView.css, extensions/ql-vscode/src/vscode-tests/minimal-workspace/activation.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/archive-filesystem-provider.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/distribution.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/webview-uri.test.ts
Adds a drop-down to the interpreted results display which allows sorting by alert message, in addition to the current default of the order that the sarif file arrives in, which colocates results that occur in the same source file in the order that they appear in the source file.
Fixes https://github.com/github/vscode-codeql/issues/196.
=> Support sorting for interpreted alerts 

.github/workflows/release.yml
This was tested by pushing a dummy tag `v9.8.7` and seeing that the correct artifact name was produced.
=> Trim prefix from git ref name during release

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/logging.ts, extensions/ql-vscode/src/queryserver-client.ts, extensions/ql-vscode/test/pure-tests/query-test.ts
Include a convenience button to show the query server log in case the
reason the user wants to restart the server is that it's acting
unexpectedly and they want to investigate why.
Fixes https://github.com/github/vscode-codeql/issues/243.
`@github/product-docs-dsp`: this adds a command `CodeQL: Restart Query Server` to the command palette.
=> Add command for restarting the query server.

extensions/ql-vscode/src/distribution.ts
No changes to UI.
Fixes https://github.com/github/vscode-codeql/issues/253.
=> Relax CLI version constraint to allow minor version increases

syntaxes/README.md, syntaxes/ql.tmLanguage.json, syntaxes/updateSyntax
Linguist needs a texmate grammar in a repository. The grammar is just a slightly modified version of the vscode one (the markdown grammar is different and doesn't have the same subrules). It seems easier to put it here where in future we can make it track the vscode grammar changes.
I plan to add a case to the action to fail if running the script changes the file but we want to get linguist support done soon.
=> Add compiled grammar to top level for use in linguist

extensions/ql-vscode/src/vscode-tests/run-integration-tests.ts
Integration tests have been flaky. I tracked down the problem to the vscode electron binary sometimes segfaulting *after* all tests have been successfully run. The information the test runner gets from `vscode-test` unfortunately does not distinguish this segfault from test failure. See comments for what we could do about this.
I tried bisecting which integration test, if any, was causing the problem, without much success --- locally I get a segfault rate of about 0.5%-5% depending on which tests are present. It seems like the fewer tests are included in the suite, the fewer segfaults, but artificially duplicating tests doesn't make the segfaults tractably common. A minimal commandline to (possibly) trigger the segfault, after `npm run integration` has been run at least once, is
``` …
```
=> Retry integration tests when they fail

extensions/ql-vscode/src/messages.ts
The queryserver protocol only commits to the error being a number, so that a new error type can be added to the CodeQL CLI without a major version bump.  Therefore these values should be namespaces not enums to reflect the fact they are not exhaustive.
Reverts github/vscode-codeql#270
=> Revert "Convert namespaces to enums in messages.ts"

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts
This change ensures that "Show log" is available on all messages
from the extension. It's important to note that the only place that
was specifying an "item" before was doing it incorrectly. That's
been fixed.
Closes #287
=> Add "Show log" button for all messages

extensions/ql-vscode/src/quick-query.ts
Starting from a single-root workspace, Quick Query tries to add a workspace folder which points into workspace state, which then causes an extension host restart, and a different workspace state, leading to two Quick Query workspace folders.
The restart upon switching from single-root to multi-root appears to be unavoidable, and interrupts extension code execution, see https://github.com/microsoft/vscode/issues/69335#issuecomment-521105295 for details.
=> Fix weird behavior of Quick Query in non-multi-root workspaces

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/run-queries.ts
Display an understandable error message when trying to Run Query on
a qll file. Closes https://github.com/github/codeql-coreql-team/issues/201
=> fix: Readable error message for invalid file

common/config/rush/pnpm-lock.yaml, extensions/ql-vscode/package.json
There is a security warning for minimist. The extension only depends
on it transitively. Not all of its direct dependencies have updated it
yet. I don't like having to add a dependency like this, but if it
avoids github screaming at us, then I think we should.
=> chore: Fix security warning in minimist

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/distribution.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts
On startup, if a new binary is available, request user acceptance
before starting the update.
Fixes #283
=> fix: Avoid auto-updating the codeql binaries

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/query-history.ts
If the user tries to open a log file that is too large for vscode's
extension mechanism to handle, reveal the file in the finder/explorer
and let the user open in an external program.
Fixes #301
=> feat: Allow large log files to be opened externally

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/distribution.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/distribution.test.ts, extensions/ql-vscode/test/pure-tests/logging.test.ts
The old launcher has been deprecated and codeql.exe is
recommended.
Fixes #287.
=> feat: Display warning when codeql.cmd is used

extensions/ql-vscode/src/query-history.ts
Spotted a small typo ("exterally") and updated the error message.
=> Fix typo in error message

extensions/ql-vscode/package.json
Provides basic XML syntax highlighting for qhelp files as described in issue #325.
I noticed the need for qhelp file features after annoying @aschackmull with bad XML in my qhelp file 😉
This change tells vscode to interpret qhelp files as XML as seen in this screenshot:
* It is not clear to me if name is qhelp or Qhelp? As both variants are used in the [Query help style guide](https://github.com/Semmle/ql/blob/master/docs/query-help-style-guide.md)
* I was not sure whether I (as an external contributor) should add this small feature to the CHANGELOG and cc product-docs-dsp?
=> feat: XML syntax highlighting for qhelp files

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/syntaxes/ql.tmLanguage.yml
Fixes #329 
`unique` is really a context-sensitive keyword, but that's even more of a hassle in a TextMate grammars than it is in the compiler itself. We'll just highlight it as a real keyword. The worst that will happen is that existing variables and predicates named "unique" will be highlighted like keywords, which will hopefully just encourage QL developers to rename those anyway.
=> Highlight `unique` as a keyword

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/run-queries.ts
Include the text of the query file when hovering. For quick eval, only 
show the selected text.
Long files are truncated in the hover. It looks like vscode limits tooltips to only a few hundred chars.
Not sure if showing the text for all queries makes sense. The other option is to only show expanded tooltips for quick eval.
=> feat: Include query text in history hover

extensions/ql-vscode/CHANGELOG.md
The latest changelog entry (for 1.1.2) didn't include the date. Is it possible to include this retroactively?
=> Changelog: Add release date

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/view/alert-table.tsx, extensions/ql-vscode/src/view/result-table-utils.tsx, extensions/ql-vscode/src/view/result-tables.tsx
The message includes a clickable link that takes you directly to the raw results view. Fixes https://github.com/github/codeql-coreql-team/issues/383.
`@github/product-docs-dsp` not sure if this needs docs.
=> Add suggestive message to alerts view when 0 alerts, >0 raw results.

extensions/ql-vscode/src/definitions.ts
An earlier refactoring erroneously always used `KeyType.ReferenceQuery` even when the requested operation was jump-to-definition. For def-use pairs that were within a single file, this had no effect, but when traversing from one file to another, it led to the extension mistakenly reporting the definition could not be found.
=> Jump-to-definition: Fix mistakenly always using the references query

extensions/ql-vscode/package.json
Fixes https://github.com/github/vscode-codeql/issues/339.
=> Remove 'qhelp' as global alias for 'xml' filetype

.vscode/launch.json
The behavior without this line is to use whichever workspace was
opened last when testing. I find this more convenient, since I have
several (non-vscode-codeql-starter-workspace) local workspaces I use
for manual testing, and it's nice to have them persist from one run to
the next.
=> internal: Revert specifying workspace in launch config

extensions/ql-vscode/.eslintrc.js, extensions/ql-vscode/package.json
Run lint on prepush. Also, remove indentation checking from eslint, handled by tsfmt instead.
=> Fixes to how we lint automatically

extensions/ql-vscode/package.json, extensions/ql-vscode/src/databaseFetcher.ts
Fixes a bug where it's possible to fail on importing a database because the parent folder doesn't exist.
=> Ensure extension dir

extensions/ql-vscode/.eslintrc.js, extensions/ql-vscode/src/adapt.ts, extensions/ql-vscode/src/cli-version.ts, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/definitions.ts, extensions/ql-vscode/src/distribution.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/queryserver-client.ts, extensions/ql-vscode/src/quick-query.ts, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/sarif-utils.ts, extensions/ql-vscode/src/upgrades.ts, extensions/ql-vscode/src/view/alert-table.tsx, extensions/ql-vscode/src/view/raw-results-table.tsx, extensions/ql-vscode/src/view/result-table-utils.tsx, extensions/ql-vscode/src/view/result-tables.tsx, extensions/ql-vscode/src/view/results.tsx, extensions/ql-vscode/src/vscode-tests/no-workspace/sarifMessageParsingTest.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/webview-uri.test.ts, extensions/ql-vscode/test/pure-tests/query-test.ts
Enforces semi-colons for all statements.
=> Add semi-colon linting

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/view/resultsView.css
These are two independent changes.
- The monospace font used in links made the text larger so that less text could fit on the screen. It also suggested that all link text was an code snippet, which it isn't. The advantage of a fixed-width font, vertical alignment, was not put to any use.
- Underlining of links made it almost impossible to distinguish a space from an underscore.
Before:
After:
Notice how it's practically impossible to tell underscores from spaces in the underlined link for `unpack_index_entry output argument [cache_nr]` (row 11).
=> Make links variable-width without underline

extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/extension.ts
Now, importing an archive includes a progress monitor and will also display a message when complete. Error handling is also more uniform.
=> Refactor how we import database archives

extensions/ql-vscode/README.md
The 1.1.5 release (specifically https://github.com/github/vscode-codeql/pull/366) removed the "**+**" icon for adding databases. I've updated the README to point people to a new command.
**Note**: Though there are multiple ways to add databases, I think it makes sense to keep the "Quick start" guide in the README as simple as possible. We'll go into more detail in the documentation.
cc @aeisenberg or @jcreedcmu for review, thanks!
_N/A: We have an internal docs issue to track changes to the database commands_
=> Update README with new command for adding database

extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/test-ui.ts
Mainly intentded to make it easier to debug the cause of
command-palette commands being undefined.
=> Logging: More chatty logging during extension initialization.

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/extension.ts
=> Remove feature flag guard around source archive jump-to-definition

extensions/ql-vscode/src/definitions.ts
Turns out we were already raising an exception, but the `DefinitionProvider`/`ReferencesProvider` helpfully silently swallows raised exceptions. (well, they get logged to console, but that's as good as silent from the average user's perspective). I don't see any way to suppress the 'zero definitions/references found' popup, but at least we can clarify *why* zero were found with this message.
I included the specific tag that's being looked for by the extension, since I think it might potentially help advanced users debug what's going on in the event that the issue is *not* merely upgrading, but the queries being missing or improperly located or something because of some future refactoring. 
Fixes #387.
=> Add error message when there are no definitions/references queries available.

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/language-configuration.json, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/languageSupport.ts
This change provides proper indent/outdent for block comments. Through
onEnterRules. Because onEnterRules are not exactly API, I had to use
a back door to implement them.
Also, it tweaks the language-configuration.json by adding more support
for things like word boundaries and auto-closing pairs.
Since QL has similar syntactical items as JavaScriot, I started with
the JS lang config and removed single quotes and back ticks.
Fixes #171
=> Add onEnterRules for language config

common/config/rush/pnpm-lock.yaml, extensions/ql-vscode/package.json, extensions/ql-vscode/src/vscode-tests/run-integration-tests.ts
Whenever https://github.com/microsoft/vscode-test releases 1.4.0, which includes 
https://github.com/microsoft/vscode-test/pull/56, we can merge this PR.
Fixes https://github.com/github/vscode-codeql/issues/263.
=> Retry integration tests only on segfault

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/run-queries.ts
Addresses the SARIF part of https://github.com/github/vscode-codeql/issues/342. Could still use CSV export.
`@github/product-docs-dsp` any need for docs for this?
=> Allow viewing SARIF from query history view

extensions/ql-vscode/README.md
Updates the readme to take into account #405.
=> Update the download from LGTM section in the readme

rush.json
Small PR to help local development on new versions of node. You'll still get a warning, but at least it will work.
=> Add node v14 to allowed node versions

extensions/ql-vscode/src/distribution.ts
There are now multiple release assets available. Make sure we don't
throw an error when looking for the codeql distribution.
Fixes https://github.com/github/vscode-codeql/issues/419.
=> Only look for codeql.zip assets

extensions/ql-vscode/src/vscode-tests/run-integration-tests.ts
There are some flaky CI test failures that manifest only as a message
like
[main 2020-06-01T16:09:47.671Z] [VS Code]: render process crashed!
(and only afaict on windows) which I am not sure how to detect at the
moment. If that message is occurring in the exception caught at this
stage, we can check for it.
=> Chore: Retry tests more aggressively on windows

common/config/rush/pnpm-lock.yaml, extensions/ql-vscode/package.json, extensions/ql-vscode/src/cli-version.ts, extensions/ql-vscode/src/distribution.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/cli-version.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/distribution.test.ts
Reverts github/vscode-codeql#425 — this was merged before it was ready
=> Revert "Use semver package for semantic version comparison and precedence checking"

extensions/ql-vscode/src/distribution.ts
Choose platform-specific release asset based on platform, falling back
to `codeql.zip` if platform is unknown, or platform-specific release
asset is unavailable.
=> Download platform-specific releases if they are available.

extensions/ql-vscode/src/adapt.ts, extensions/ql-vscode/src/interface-types.ts, extensions/ql-vscode/src/interface-utils.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/view/alert-table.tsx, extensions/ql-vscode/src/view/raw-results-table.tsx, extensions/ql-vscode/src/view/result-table-utils.tsx, extensions/ql-vscode/src/view/result-tables.tsx, extensions/ql-vscode/src/view/results.tsx
Make pagination work for raw tables, leaving alert tables alone for now.
This is worth reviewing, although I'm aware of a couple of improvements I want to make imminently. There is some code duplication between the first render and subsequent page fetches that I want to refactor, and the visual appearance of the pagination widget is definitely worth cleaning up a bit.
This should be a no-op if the experimental flag is off, but that deserves either some unit tests or slightly more strenous manual testing.
=> Implement pagination for BQRS results.

extensions/ql-vscode/src/query-history.ts
This should cause less confusion and annoyance from users.
=> Clarify log message

extensions/ql-vscode/src/cli-version.ts, extensions/ql-vscode/src/distribution.ts
The assumption is that the cli is old or corrupted. In either case we want to upgrade.
=> Force undefined version if version command fails

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/qltest-discovery.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/run-queries.ts
When the `env.language` value is not passed as the locale, OS-default
locale is used. This change ensures that we use the workspace locale
where we want and explicitly calls out where we should continue to use
the OS-default.
Fixes #440.
=> Explicitly use the workspace-configured locale

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-hstory.test.ts
Use the same mechanism that we are using for log files to open
large sarif files. This is because the extension is not
capable of opening large (>50MB) files due to vscode restrictions.
Fixes #418.
=> Ask user to open sarif file externally when too large

extensions/ql-vscode/src/run-queries.ts
`fs-extra` already has an async overload for `readdir`.
=> Remove unnecessary promisify.

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databaseFetcher.ts
This allows opening zip files whose local headers are not correct.
Fixes #468.
=> Use `Open` instead of `Extract` to open zip files

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts
A user typically expects that the first selection would be
the query that they are comparing _from_ and the second query
is being compared _to_.
This commit ensures that something like this expectation will
always hold.
So, when there are two queries selected, the first one selected
will always be _from_ and appear on the left side of the compare
view. The one selected later will be _to_ and appear on the right.
There is a corner case when there are 3 or more selected queries
and a user *unselects* a query. We do not track the selection
order of the remaining two queries.
Fixes #470.
=> Ensure query compare order matches expectation

extensions/ql-vscode/src/databases.ts
`resolveRawDataset` can never be called.
Had a discussion with @jcreedcmu and it seems like we don't need to use `resolveRawDataset`.
=> Remove unused code path

common/config/rush/pnpm-lock.yaml, extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/definitions.ts
Zips source folders of databases when they are added. Only if the databases are fully controlled by VS Code.
Fixes #479
Also, avoids the error specified in https://github.com/github/codeql-coreql-team/issues/452
=> Ensure source folders are zipped

extensions/ql-vscode/src/adapt.ts, extensions/ql-vscode/src/interface-types.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/view/result-tables.tsx, extensions/ql-vscode/src/view/results.tsx
Enable pagination for interpreted as well as raw results.
This is still under feature flag, so no user-facing changes quite yet, but the flag can possibly be enabled for everyone once this lands. There will be a number of code cleanups available at that point.
=> Allow pagination for interpreted results

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databases-ui.test.ts
=> Fix nested problem adding database starting with db-*

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/view/result-tables.tsx, extensions/ql-vscode/src/view/resultsView.css
Some small changes that add consistency and modernizes the layout of the pagination section.
Should be based off of `jcreed:jcreed/interpreted-pagination` #481. This is light theme: 
And this is dark:
I'm sure we could do better if we had an actual designer look at this, but this is probably good for now.
This is a follow-up review for #481.
=> Augments the pagination styling

extensions/ql-vscode/src/adapt.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/view/raw-results-table.tsx, extensions/ql-vscode/src/view/result-tables.tsx, extensions/ql-vscode/src/view/results.tsx
This PR enables pagination for everyone and begins cleaning up the transitional machinery that was necessary to flag it.
=> Remove pagination feature flag

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/view/result-tables.tsx, extensions/ql-vscode/src/view/resultsView.css
When there are no results, always ensure that max pages is 1.
This commit also changes the way pagination buttons are removing their border.
Fixes #504.
=> Fixes pagination when there are no results

.vscode/launch.json
We need to provide the `--extensionDevelopmentPath` flag in these
launch configurations.
It appears to be unnecessary to include
`${workspaceRoot}/extensions/ql-vscode/out/vscode-tests/**/*.js`
in addition to the strictly more general pattern
${workspaceRoot}/extensions/ql-vscode/out/**/*.js
An unfortunate UI fact appears to be that the log of the gulp build is
focused whenever these tasks are run, even though the log you actually
care about seeing is in the `Debug Console` section. Not sure how to
fix that.
=> Fix broken launch config

.vscode/tasks.json
Users should not need to install npx in order to launch the extension. This also simplifies the launch script to use `npm` everywhere.
=> Remove reference to npx in luanch config

extensions/ql-vscode/src/contextual/astBuilder.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/astBuilder.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/data/astBuilder.json
Small bug I noticed when viewing AST of Go queries.
=> Fix AST viewer bug where nodes with id=0 did not have children

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/discovery.ts, extensions/ql-vscode/src/qlpack-discovery.ts, extensions/ql-vscode/src/qltest-discovery.ts, extensions/ql-vscode/src/test-adapter.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/qltest-discovery.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/queryResolver.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/qltest-discovery.test.ts
qlpack tests that are not contained within the current workspace folder
will be filtered from the test runner view.
This also fixes a test that should have been failing but wasn't.
Fixes #517.
=> Filters qltest-discovery

.vscode/launch.json, extensions/ql-vscode/src/ide-server.ts
With this flag on, it is possible to remote-debug the language server in a java debugger.
=> Add a debug flag to allow remote debugging

extensions/ql-vscode/CHANGELOG.md
@github/docs-content-dsp we are going to be doing a release later today. I am adding a line in the changelog about the experimental AST Viewer mostly because I've already gotten a bunch of questions about it and how to enable. Until the feature flag is removed, I don't think we need official documentation for it. Are you all fine with that?
=> Update changelog to include line about experimental AST Viewer

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/run-queries.ts
Fixes #538
Adds a new menu item to cancel a query run when the query is unsaved.
Also, ensures that no warning message is sent to the console.
The dialog now looks like this:
The new menu item is highlighted in red. This change is minor enough that I don't think it needs a changelog entry.
=> Avoid running query when a user cancels when there are unsaved changes

extensions/ql-vscode/syntaxes/ql.tmLanguage.yml
Fixes #543
```ql
newtype TA = TB()
private predicate foo() { any() }
```
Our TextMate grammar didn't realize that the newtype declaration ended after the closing paren of the branch's parameter list, so the `private` modifier was highlighted incorrectly.
It's surprisingly tricky to get TextMate to handle this correctly, so I wound up just treating the IPA declaration head (`newtype TA`), the branch head (`= TB`), the branch parameter list, and the branch body as directly children of the module body. This is kind of hacky, but it does fix the bug without introducing any new cases where we have incorrect highlighting of valid code.
=> Fix highlighting after disembodied IPA branch

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/bqrs-utils.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/interface-utils.test.ts
A common situation when a file is not relevant for a particular result
is to return an empty file path location.
Currently, we are displaying this situation as a hyperlink in the
results, but when clicking on the link, there is an error.
To mirror the behaviour of Eclipse, we should avoid showing a link here.
This commit changes that behaviour.
Fixes #545 
Not notifying `@github/docs-content-dsp` because this is a small change that external users will unlikely to come across.
=> Avoid showing a link when the underlying path is empty

.github/workflows/main.yml, .github/workflows/release.yml
Improve security practices by pinning to a numbered version of the `upload-artifact` action.
- [N/A] `@github/docs-content-dsp` has been cc'd in all issues for UI or other user-facing changes made by this pull request.
=> Actions: Pin version of upload-artifact action

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/extension.ts
Max number of simultaneous queries launchable by runQueries command is
now configurable by codeQL.runningQueries.maxQueries.
Resolves #463.
=> Allow max queries to be configurable

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-results.test.ts
Fix Query sort issues
With this change, we use the stored sort order if it exists
after reloading a query results page.
When retrieving paginated results, need to make sure we are getting
page offsets from the correct results file.
Previously, we were incorrectly extracting page offsets from the default
(unsorted) file. With this change, we ensure that we get offsets from
the proper results file when there is a request for a page of results.
Resolves #586
Resolves #587
=> Fix Query sort issues

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts
=> Fix "View SARIF" context menu race.

extensions/ql-vscode/src/view/result-table-utils.tsx
Never show an empty string in the results view. This fixes #535 (again).
Thanks @shati-patel for noticing this. It was indeed a regression with #574.
=> Ensure all fields have labels

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/interface-types.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/view/result-tables.tsx, extensions/ql-vscode/src/view/results.tsx, extensions/ql-vscode/src/vscode-tests/no-workspace/databases.test.ts
This commit fixes the problem whereby a database is removed and the
problems associated with queries run from that database stick around
in the problems view.
Also, once problems are cleared, we need to make sure that we uncheck
the checkbox in the results view.
This commit has several limitations:
1. There is duplicated code for message handling in both results.tsx and
result-tables.tsx.
2. Problems are cleared whenever there is *any* change to any database.
Ideally we should only clear problems when a database is removed and
only problems associated with that database. I'll fix part of this in
a future commit.
Resolves #525
=> Clear problems view when a database is removed

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/astViewer.ts, extensions/ql-vscode/src/contextual/locationFinder.ts, extensions/ql-vscode/src/contextual/templateProvider.ts, extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/interface-utils.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/quick-query.ts, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/upgrades.ts, extensions/ql-vscode/src/vscode-utils/ui-service.ts
The commandRunner wraps all vscode command registrations. It provides
uniform error handling and an optional progress monitor.
In general, progress monitors should only be created by the
commandRunner and passed through to the locations that use it.
Resolves #464.
Resolves #534.
=> Add the commandRunner

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/run-queries.test.ts
Simple command that generates the DIL for a query if it doesn't exist and then opens it in an editor.
Fixes #395.
=> Add command to view the DIL of a query

.vscode/launch.json, CONTRIBUTING.md
And update contributing with new instructions.
This will make it easier for core developers to quickly launch and relaunch tasks, though it will make it harder for new and occasional devs to keep their environment up to date. Thoughts?
=> Remove build before launch in launch.json

extensions/ql-vscode/src/bqrs-utils.ts, extensions/ql-vscode/src/contextual/fileRangeFromURI.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/fileRangeFromURI.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databases.test.ts
Also, refactor resolveSourceFile to make it easier to read.
And add unit tests for resolveSourceFile.
This fixes a bug where clicking on an item in the AST viewer when the location is invalid threw an exception.
This PR also fixes a bug in resolveSourceFile where the `pathWithinSourceArchive` was being removed and appended to the `sourceArchiveZipPath`. In normal situations, we don't hit this bug because most database source archive uris have an empty path for the `pathWithinSourceArchive`.
- [ n/a …
=> Return undefined for finding file ranges on empty URI

extensions/ql-vscode/src/archive-filesystem-provider.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/archive-filesystem-provider.test.ts
This commit fixes a bug uncovered by
c66fe07b06eee4843775a1bb2516fae53840e422.
The findSourceArchive function in databases.ts creates a
codeql-zip-archive uri with an empty authority component. This will
fail to decode. Until recently, this situation never happened. But in
the commit linked above, we start decoding some of these incorrectly
encoded uris.
This commit fixes that issue.
- [n/a] `@github/docs-content-dsp` has been cc'd in all issues for UI or other user-facing changes made by this pull …
=> Fix archive encoding when there is an empty uri authority

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts
Resolves #476. This is the final PR in this extension for the AST Viewer. It simply removes the feature flag. This PR should not be merged until https://github.com/github/codeql/issues/3956 is closed and the documentation is released.
=> Remove feature flag for the AST Viewer

extensions/ql-vscode/src/archive-filesystem-provider.ts, extensions/ql-vscode/src/contextual/locationFinder.ts, extensions/ql-vscode/src/contextual/templateProvider.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/archive-filesystem-provider.test.ts
Also, create a convenience function for generating a codeql-zip-archive
at the root of the archive.
=> Fix other locations where we create an invalid codeql-zip-archive uri

extensions/ql-vscode/src/cli.ts
This option is not recognized. I had added this option earlier and not sufficiently tested it.
=> Remove the --kind dil options from decompile command

extensions/ql-vscode/src/archive-filesystem-provider.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/archive-filesystem-provider.test.ts
Empty paths should be replaced as '/'. This is a fix for a bug
introduced in 899f988df871c4923af01508b7efd06169888b90.
Resolves #647.
=> Ensure decoded archive fs paths are never empty

extensions/ql-vscode/CHANGELOG.md
Adds a missing entry to the changelog.
=> Prepare for release v1.3.5

extensions/ql-vscode/src/view/RawTableValue.tsx
React nodes containing booleans aren't rendered. We want a node with a string. 
I don't why this has only just stopped working but this seems to fix the problem.
=> Results View: Fix display of booleans

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/archive-filesystem-provider.ts, extensions/ql-vscode/src/contextual/fileRangeFromURI.ts, extensions/ql-vscode/src/contextual/locationFinder.ts, extensions/ql-vscode/src/contextual/templateProvider.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/pure/bqrs-cli-types.ts, extensions/ql-vscode/src/pure/sarif-utils.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/fileRangeFromURI.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databases.test.ts, extensions/ql-vscode/test/pure-tests/sarif-utils.test.ts
Fixes #562
This fixes a bug where if there are special characters in a database
path, it is not possible to navigate to that file from the results view.
Note that the results from our BQRS returned properly encoded URIs, but
our paths coming from sarif were unencoded. Our path parsing handled
the latter correctly (even though these are not correct URIs) and the
former incorrectly.
The fix here is to first ensure all uris are properly encoded. We do
this by running `encodeURI` in sarif-utils (can't run encodeURIComponent
or else the path separators `/` will also be encoded).
Then, we ensure that when we resolve locations, we decode all file
paths.
This works in all cases I have tried. I still have an issue with running
View AST on some of these databases, but that I believe is a separate …
=> Ensure uris are using encoded strings

extensions/ql-vscode/package.json, extensions/ql-vscode/test/pure-tests/command-lint.test.ts
These commands are not applicable from the global context. They require
an argument to be passed in. So, they should be hidden in the command
palette.
Fixes #658.
=> Disable codeql test commands from the command palette

extensions/ql-vscode/src/astViewer.ts
This will prevent selections jumping around when an ast entry is
selected and its child has the same source location as the current
selection.
Fixes #656.
=> Avoid recursive selection changes in ast viewer

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/interface-utils.ts
~~Adds a new config option to control this behavior. If this behavior is
generally desirable, we will remove the option and avoid using preview
editors for all users.~~
Not going with a config setting as I don't feel like we should be cluttering up the settings page.
This change partially mitigates the limitations with how vscode handles editors backed by custom uri providers.
See https://github.com/github/vscode-codeql/issues/500#issuecomment-712301680 for an explanation of what this does and why we should do it.
=> Open editor containing query location in non-preview mode

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/test-ui.ts
If the expected file does not already exists. This helps with test
creation and allows users to create tests more quickly.
Fixes #338.
=> Creates an empty `.expected` file when running test output compare

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/test-adapter.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databases.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/test-adapter.test.ts
The diff and the errors were always available, but they were not being sent to the output.
Additionally, make sure to send output to both the test explorer log and the codeql test log.
Resolves #582.
=> Add more structured output for tests

extensions/ql-vscode/src/contextual/astBuilder.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/data/astBuilder.json
=> Use the value not the label for the print ast node

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/helpers-pure.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databases-ui.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databases.test.ts, extensions/ql-vscode/test/pure-tests/helpers-pure.test.ts, extensions/ql-vscode/tsconfig.json
Cleans orphan databases on startup. This commit also bumps the fs-extra
dependency to get readdir with dirent objects.
Adds the `asyncFilter` to filter arrays asynchronously.
Implemented as a command so a saavy user could assign a keyboard shortcut to it, but it is not accessible through the command palette.
Fixes #674.
=> Clean databases folder on startup

.vscode/launch.json, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/ide-server.ts, extensions/ql-vscode/src/queryserver-client.ts
And separate flag for IDE server. Setting these flags to `true` will
start the respective Java processes in debug mode so that they can
be attached to a debugger.
=> Add debug flag for query server

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databases.test.ts
=> Re-sort databases list after db rename

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/view/result-tables.tsx, extensions/ql-vscode/src/view/results.tsx
Also, set a max and min value on the input control of the page. This
prevents going to a negative page, or a page after the last one.
Fixes #525
=> Add a setting to control page size

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/contextual/astBuilder.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/astBuilder.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/data/astBuilder.json
The C PrintAST library now includes the edge name in the AST Viewer
tree.
Resolves #687
=> Use the ast edge label when building the ast node label

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/pure/messages.ts, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/run-queries.test.ts, extensions/ql-vscode/test/data/compute-default-strings.ql, extensions/ql-vscode/test/pure-tests/files.test.ts
=> Pass computeDefaultStrings to query server when compiling queries

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/messages.ts, extensions/ql-vscode/src/queryserver-client.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases.test.ts
Sends commands to the query server to add and remove databases from the allow list. This feature will enable proper unlocking of databases when they are removed from vscode.
Fixes #572 
Fixes #333 
Fixes #249
=> Add support for (de-)registering databases with the query server

extensions/ql-vscode/src/vscode-tests/no-workspace/query.test.ts
Accidentally committed `.only`.
=> Ensure all tests run

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/contextual/queryResolver.ts, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/pure/helpers-pure.ts, extensions/ql-vscode/src/quick-query.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/queryResolver.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/helpers.test.ts
This change will only work on databases created by cli >= 2.4.1. In that
version, a new `primaryLanguage` field in the `codeql-database.yml`
file. We use this property as the language.
This change also includes a refactoring of the logic around extracting
database information heuristically based on file location. As much
as possible, it is extracted to the `helpers` module. Also, the
initial quick query text is generated based on the language (if known)
otherwise it falls back to the old style of generation.
Fixes #321
=> Add a language label next to databases in the UI

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/run-queries.ts
1. Clicking on query history menu items when nothing is selected. Error
message is clearer. It would be better to disable when nothing is
selected, but waiting on
https://github.com/microsoft/vscode/issues/99767 to be released.
2. Trying to run query with a missing or invalid qlpack has better
message.
3. Better hover text for "Open query".
=> Make error messages clearer for some common problems

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/distribution.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/helpers.test.ts
This fixes two classes of DBs that can't be installed directly from
downloading:
1. DBs whose central directories do not align with their file headers.
We need to download and save the entire archive  before we can read
the central directory and use that to guide the unzipping.
2. Large DBs require too much memory so can't be downloaded and unzipped
in a single stream.
We also add proper progress notifications to the download progress
monitor so users are aware of how many more MBs are left to download.
It's not yet possible to do the same for unzipping using the current
unzipper library, since unzipping using the central directory does not
expose a stream.
Fixes #621
Fixes #622
Integration tests are passing and added two more for progress monitoring.
Manually tested on the linux database …
=> Save downloaded DB archives to disk before unzipping

.github/workflows/main.yml, .vscode/launch.json, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/queryserver-client.ts, extensions/ql-vscode/src/upgrades.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/data/qlpack.yml, extensions/ql-vscode/src/vscode-tests/cli-integration/databases.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/global.helper.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/query.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/run-cli.test.ts, extensions/ql-vscode/src/vscode-tests/ensureCli.ts, extensions/ql-vscode/src/vscode-tests/run-integration-tests.ts
* Requires that QL_PATH environment variable is set and points to a
checkout of github/codeql
* Adds the `quiet` flag to the cli. When set, this flag will prevent
some modal dialogs from disrupting the flow. Currently, we only ensure
that the upgrades dialog is avoided.
* Update the main.yml workflow to checkout the codeql repo
Added a second commit, which does the following:
Move query.test.ts to the cli integration tests
* Now query.test.ts runs on multiple cli versions
* Removed most `dispose` calls in cli tests because each test shares the
same instance of the extension and all of its properties. So, we
shouldn't be disposing until the last test completes. It's likely that
we will need to be more careful about cleaning up state between test
runs, but we haven't hit that yet and this …
=> Re-enable the queries cli test

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/discovery.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/qltest-discovery.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/qltest-discovery.test.ts
This change avoids popping up error messages in two cases:
1. When doing test discovery, do not run discovery on non-existant
directories. Also, if there is an error, print to the log, and do not
pop up an error window. The reason is that test discovery is a
background operation and these should not normally cause pop-ups.
2. When looking for orphaned databases, don't pop up an error if the
storagePath can't be found. This is normal when working in a new,
single root workspace.
Fixes #695
=> Avoid uninteresting user facing errors

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/view/result-table-utils.tsx, extensions/ql-vscode/src/view/result-tables.tsx, extensions/ql-vscode/src/view/results.tsx, extensions/ql-vscode/src/view/resultsView.css
The descriptive text is the same as the label in the query history view.  The link opens the file that ran the query.
Here is a screenshot of a wide window:
And here is a narrow window:
Fixes #634.
=> Add descriptive text and a link at top of query results

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts
This removes the cached treeItem that is a property of the
completedQuery. We should not be caching them since they are cached by
the vscode api itself. Instead, we should recreate whenever requested.
Also, this change fixes #598 in a new way. Instead of adding the
context to the cached treeItem, we simply refresh only the item that has
changed. This is a fast operation.
Fixes #709.
=> Fix set label command on history items

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json
Also, hide the `CodeQL: Run Queries` command inside of zip folders
since we do not allow queries to be in archives. I wish we could be more
specific about when to show that command, eg- only *.ql files and
directories, but I couldn't find a way to restrict a command to only
appear on directories.
Fixes #707
=> Add View AST Command to text editor where appropriate

extensions/ql-vscode/src/pure/messages.ts, extensions/ql-vscode/src/upgrades.ts
Where possible use the new single file form of upgrades. Older versions of `codeql` simply ignore the `singleFileUpgrades` property and give multifile upgrades. Hence we can just set the new flag and see which sort of upgrade we get pack. If a version of codeql returns a multi file upgrade then it certainly supports running them so there are no issues there.
=> Use single file upgrades where possible.

.vscode/launch.json, extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/commandRunner.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/run-cli.test.ts, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
Ensure we only show the truncated error message in the popup. This will help with debugging.
=> Include the full stack in error log messages

extensions/ql-vscode/src/upgrades.ts
Tiny fix to ensure we display an error message if database upgrades can't be compiled.
=> Fix missing call to showAndLogErrorMessage

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-results.test.ts
Add a `canary` config setting to enable users to opt into unreleased features of the extension.  When canary features are turned on, forward the `@scored` tag if it's present in the query metadata to enable experimental features for internal users.
=> Forward scored metadata for canary users

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/messages.ts, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/upgrades.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databases-ui.test.ts
This depends on a rebased copy of #639 and also on some unreleased cli features and shouldn't be merged until we know which version they will be released in.
This PR makes us use silent non-destructive upgrades. It also refactors the current upgrade mechanism in places so we have slightly fewer code paths.
There are a few identation changes so you may want to add `?w=1` to the url when reviewing to ignore those changes.
=> Non destructive upgrades in vscode

.github/workflows/main.yml, extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/messages.ts, extensions/ql-vscode/src/queryserver-client.ts, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/upgrades.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/query.test.ts, extensions/ql-vscode/src/vscode-tests/ensureCli.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases.test.ts
This commit fixes #733. It does it by ensuring that the query server
emits an event when it restarts the query server. The database manager
listens for this even and properly re-registers its databases.
A few caveats though:
1. Convert query restarts to using a command that includes progress.
This will ensure that errors on restart are logged properly.
2. Because we want to log errors, we cannot use the vscode standard
EventEmitters. They run in the next tick and therefore any errors
will not be associated with this command execution.
3. Update the default cli version to run integration tests against to
2.4.2.
4. Add a new integration test that fails if databases are not
re-registered.
- [n/a] `@github/docs-content-dsp` has been cc'd in all issues for UI or other user-facing changes made …
=> Ensure databases are re-registered when query server restarts

.github/workflows/main.yml, .github/workflows/release.yml, extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/README.md, extensions/ql-vscode/TELEMETRY.md, extensions/ql-vscode/gulpfile.ts/appInsights.ts, extensions/ql-vscode/gulpfile.ts/index.ts, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/commandRunner.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/distribution.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/telemetry.ts, extensions/ql-vscode/src/upgrades.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databaseFetcher.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/distribution.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/telemetry.test.ts
This commit adds telemetry capturing for command execution. The data captured is only the command id.
We also capture errors thrown by any command execution.
This adds telemetry to an Azure application insights instance. Talk to me if you want access to it.
We still need a way to notify users that telemetry is being collected and a way to disable it.
Also:
* Extract commandRunner to its own file
* Add an option to log all telemetry commands to the console
* Add a popup (text to be determined) that requires users to accept
telemetry before using.
* Convert telemetry to opt-in instead of opt-out
* Add a "canary" setting that users can use to opt-in to unreleased
features.
=> Add telemetry for commands

CONTRIBUTING.md, extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/telemetry.ts
Modal dialogs do not allow for markdown text. Also, make CodeQL more
prominent in the dialog.
=> Change text of modal dialog

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/upgrades.ts
Non-destructive upgrades only exist in versions >= 2.4.2
=> Fix version constraint

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/telemetry.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/helpers.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/telemetry.test.ts
This commit moves the URL in the text of the telemetry pop up to a
separate button. Clicking on the button will automatically open the
link in the browser.
Also, adds unit tests for the open dialog helper functions.
=> Add a 'More Information' option in telemetry popup

.github/workflows/main.yml, extensions/ql-vscode/src/astViewer.ts, extensions/ql-vscode/src/compare/compare-interface.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/discovery.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/logging.ts, extensions/ql-vscode/src/pure/disposable-object.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/queryserver-client.ts, extensions/ql-vscode/src/status-bar.ts, extensions/ql-vscode/src/test-adapter.ts, extensions/ql-vscode/src/test-ui.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/databases.test.ts, extensions/ql-vscode/src/vscode-tests/index-template.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/astViewer.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/astBuilder.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databases-ui.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/helpers.test.ts, extensions/ql-vscode/src/vscode-tests/run-integration-tests.ts, extensions/ql-vscode/src/vscode-tests/test-dispose-handler.ts, extensions/ql-vscode/src/vscode-utils/multi-file-system-watcher.ts, extensions/ql-vscode/src/vscode-utils/ui-service.ts, extensions/ql-vscode/test/pure-tests/disposable-object.test.ts
These functions assist with object disposal. They add custom behaviour
during disposal. The primary usage of disposalHandlers is during testing
where some objects should not be disposed in order to avoid testing
errors.
Additionally, move DisposableObject to the pure folder and create unit
tests for it.
This is an internal change and does not require a changelog entry.
When dispose handlers are used, the error log during tests is significantly quieter.
- [n/a] `@github/docs-content-dsp` has been cc'd …
=> Add disposeHandlers

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases-ui.ts
Problem was misplaced parens. We were not waiting for
the call to `pathExists` to complete before making the call
to `stat` the directory. When the directory does not
exist, then `stat` throws an error.
=> Avoid displaying irrelevant error

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/contextual/templateProvider.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts
This commit does two things:
1. Add more appropriate error messages when asts can't be viewed.
2. Make better use of cached operations for asts. In the past, we were
not actually using cached operations. Each time an ast view request
occurred, we created a new TemplatePrintAstProvider instance. With this
change, we reuse the TemplatePrintAstProvider between calls and ensure
that an AST that is called once is reused on subsequent calls.
I received complaints from users such as @sj that AST viewing was erroring out and it wasn't clear why it was happening.
And the second part of this change will make subsequent calls to view an AST of a file extremely fast.
- [n/a] `@github/docs-content-dsp` …
=> Fix error messages for ast viewers and update caching

CONTRIBUTING.md, README.md, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/vscode-tests/cli-integration/global.helper.ts, extensions/ql-vscode/src/vscode-tests/index-template.ts
Internal change. Also, updates the lock file format for compatibility with npm v7.
Also, see the second commit:
Fix globalSetup/teardown for mocha
Updating the typings for mocha uncovered an error in how we were
registering global setups and teardowns.
When calling `mocha.globalSetup` or `mocha.globalTeardown`, any
previously registered globals are overwritten. The workaround
is to attach globals directly to the internal options object.
This is a requirement because we are now registering globals in 
multiple files.
Unfortunately, the typings for mocha do not permit this and I may need
to fix them again.
- [n/a] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull …
=> Update typings for mocha

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/status-bar.ts
1. Wait a few seconds before updating the status bar after a version
change.
2. Ensure we are watching the correct configuration items for changes.
3. Ensure the cli version is refreshed correctly.
=> Fix issues with dynamic updating of the version status bar item

extensions/ql-vscode/package.json
The phrasing "This overrides all other CodeQL CLI settings" is a potential source of confusion, since it suggests the RAM and threads settings may not be passed to custom CLIs.  In fact, these settings are indeed passed to custom CLIs.
No significant user-facing changes.
=> Simplify description of executablePath setting

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/quick-query.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/config.test.ts
Only recreate the qlpack.yml file.
Also, add an integration test for quick-query creation.
=> Avoid clobbering quick-query file when re-opened

extensions/ql-vscode/src/vscode-tests/minimal-workspace/config.test.ts
Necessary because we just added some extra waiting
in order to ensure that config listeners have all
fired.
=> Bump test timeouts

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databaseFetcher.test.ts
The following is now acceptable for fetching the codeql lgtm database:
```
g/github/codeql
```
Fixes #755
=> Allow raw project slugs for fetching lgtm dbs

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/config.test.ts
When running `codeql bqrs interpret`, ensure the
`codeQL.runningQueries.numberOfThreads` setting is respected.
Fixes #764
=> Use codeQL.runningQueries.numberOfThreads to run interpretation

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/interface.ts
One way it can fail is if the SARIF is too large. We explicitly call
out that error because the raw message received from the node runtime
is not very understandable.
Fixes #759
=> Add error message when interpretation fails

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/upgrades.ts
When resolving "upgrades" also resolve downgrades when doing things non-destructively. This requires codeql `2.4.4`. This won't do anything until we start shipping downgrades.
=> Use downgrades when fixing dbscheme mismatches where possible.

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/queryserver-client.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/config.test.ts
This PR addresses #593 by expanding the options that can be passed to control how the evaluator handles the disk cache. In particular, it exposes to the user two settings - the first enables the saving of intermediate results to the cache, and the second allows limiting of the size of the cache. The default behaviour is unchanged from the current options - i.e. intermediate results are not saved to the disk cache, and the evaluator is allowed to choose its own limit on maximum cache size.
=> Expand disk cache evaluator options

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/config.ts
This PR addresses #606 by adding a configuration option to pass additional arguments to the CLI when running tests. By default, this option is empty and no additional arguments are passed.
=> Add option to pass additional arguments when running tests

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/run-queries.ts
This pull request addresses the second part of #342 by introducing an option when right clicking a completed query in the query history view to see a CSV of the results. If the CSV results for the query have been viewed before, the file is simply opened. If they have not been viewed before, the CSV is generated (in the temporary directory for the query's execution) using a call to the CLI, and is then opened.
=> Implement viewing of query results as a CSV

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/snippets.json
This PR addresses #392 by introducing some simple snippets for query metadata, classes, from/where/select statements, predicates, dataflow/taint tracking classes, and all the aggregates and quantifiers.
=> Add some commonly used QL snippets

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/test-adapter.ts
Addresses #774 by reading the `failureDescription` field for a test failure and when this is present reporting this instead of the diff. I believe this is the right choice since as I understand it when this field is present, the diff will not be useful as it means something went more catastrophically wrong (e.g. we couldn't find the expected output).
=> Report description for test failure when possible

.github/pull_request_template.md
The docs team has been through a slight restructuring. The DSP subteam still technically exists, but we have an automated "first responder" process to pick up team pings to `@github/docs-content-codeql` instead, so I'd like to change the template! 
- _N/A_ [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- _N/A_ Issues have been created for any UI or other user-facing changes made by this pull request.
- _N/A_ `@github/docs-content-codeql` has been cc'd in all issues for UI or other user-facing changes made by this pull request.
=> Update docs team ping in PR template

.github/workflows/main.yml
Deliberately keeping 2.4.5 as well, to keep testing enterprise compatibility.
- [N/A] `@github/docs-content-codeql` has been cc'd in all issues for UI or other user-facing changes made by this pull request.
=> Actions: Test against CodeQL 2.4.6

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/run-queries.ts
Fixes #800
This only became important because of #770 that also started showing this false-positive error.
=> Avoid showing an error when query has not @kind metadata

extensions/ql-vscode/src/cli.ts
Fixes #802 by manually implementing `startsWith`. This is probably a slight performance hit but I don't think we can do much about it.
This is the only place where we use the two argument version whcih is the one that becomes broken.
=> Fix running tests when ms-python is installed.

extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/run-queries.ts
Addresses #724 by limiting error messages in popups to 2 lines. Note that this required changing around a couple of error messages that were likely to be more than 2 lines but we wanted to show all of to ensure that they do not get trimmed.
=> Limit error messages shown in popups to 2 lines

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/run-queries.test.ts
Also, add a unit test for this area.
=> Avoid displaying error message for @kind table queries

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/contextual/templateProvider.ts
When codeql library developers are working on PrintAST queries, it is
not easy to use the AST Viewer. The AST Viewer caches results so that
multiple calls to view the AST of the same file are nearly
instantaneous.
However, this breaks down if you are changing the actual queries that
perform AST viewing. In this case, you do not want the cache to be
active.
This commit adds an undocumented setting that prevents caching. To
enable, set:
```
"codeQL.isCanary": true,
"codeQL.astViewer.disableCache": true
```
Note that *both* settings must be true for this to work.
This behaviour and all canary behaviour should be documented somewhere.
I will add that later.
Any suggestions on where this should go would be appreciated. 
- [n/a] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/ex …
=> Add a canary setting to avoid caching AST viewer queries

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/extension.ts
This PR adds an option to jump from a `.qlref` file to the `.ql` file it references. Note that it should not be merged yet, as it relies on a new CLI call `resolve qlref` which is not released yet.
Closes #654
=> Add feature to jump to the .ql file referenced by a .qlref

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/interface.ts
=> Avoid opening the results panel on db deletion

extensions/ql-vscode/src/interface.ts
I don't know exactly when this can happen, but a customer has just
shown me a stack trace like this:
```
TypeError: Cannot destructure property 'resultsPath' of 'resultsPaths' as it is undefined.
at Object.interpretResults (/xxx/.vscode/extensions/github.vscode-codeql-1.4.5/out/query-results.js:120:13)
at InterfaceManager._getInterpretedResults (/xxx/.vscode/extensions/github.vscode-codeql-1.4.5/out/interface.js:377:45)
at InterfaceManager.showResultsAsDiagnostics (/xxx/.vscode/extensions/github.vscode-codeql-1.4.5/out/interface.js:447:43)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async InterfaceManager.handleMsgFromView (/xxx/.vscode/extensions/github.vscode-codeql-1.4.5/out/interface.js:151:29)
```
This commit will avoid …
=> Avoid printing a stack trace when there is no resultsPath

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/query-results.ts
This PR forwards all the query metadata to the queryserver.
Currently, only `@kind` and `@id` are forwarded for most users.  This results in metadata errors when running some queries, even if the queries being run had the correct metadata.  For example, the `@kind metric` query requires either the `@tags summary` metadata or the `@metricType` metadata key to be defined.  However the VS Code extension doesn't currently forward the `@tags` and `@metricType` properties, so the queryserver reports errors whenever a user tries to run these queries.
With this PR, we forward all the query metadata to the queryserver, so queries like these will no longer report metadata errors.
=> Forward all query metadata to the queryserver

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/gulpfile.ts/webpack.config.ts, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
Webpack >v5 doesn't include polyfills for core modules from Node.js by default. Since we use `path` in the results table UI, we need to include our own polyfill. This PR adds `path-browserify` to the distributed extension.
As future work, we could move SARIF location rendering into the core extension so we don't need to use `path.basename` in the UI. This would allow us to remove the polyfill.
=> Add polyfill for path to fix a bug that prevented the results view from being loaded

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/qltest-discovery.ts
This ensures that directories renamed, added or deleted are
properly checked to see if they contain tests. The test tree
will be correctly updated when any directory changes.s
Fixes #799.
=> Watch for changes in directory structure

.github/ISSUE_TEMPLATE/bug_report.md, extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/status-bar.ts
Fixes https://github.com/github/vscode-codeql/issues/795.
You can now access version information from the status bar or by running `CodeQL: Copy Version Information` from the Command Palette.
- [n/a] ~`@github/docs-content-codeql` has been cc'd in all issues for UI or other user-facing changes made by this pull request.~ This doesn't need docs: the note in the issue template should be enough.
=> Add command to copy version information

.github/workflows/codeql.yml
This commit switches to the bleeding edge, main branch of the
codeql action. This helps us test the action before merging all
of the new changes into main, which occurs roughly once a week.
If there are commits that introduce bugs in codeql-action, then
we will be more likely to catch it before releasing to the world
if we are using it in this extension.
=> Use the main branch of the codeql action

.github/workflows/codeql.yml
Only adds permissions to the code scanning workflow. We should add to other workflows, but they require more complex permissions and I need to think about what to give them.
=> Actions: Add permissions block to code scanning workflow

.github/workflows/codeql.yml
The code scanning workflow has been failing with a syntax error, e.g. see https://github.com/github/vscode-codeql/actions/runs/786489168. Changed `_` to `-` to match the docs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions.
The workflow is now green ✔️ though it returns the [warning](https://github.com/github/vscode-codeql/actions/runs/792817144) `Did not find any lines of code in database.` I'm not sure if the warning is directly related to this PR, or a separate bug 🤔 
PS: I also changed the cron to run at a less common time. Actions tends to be overloaded at the start of each hour, so we can save resources a bit by shifting the time 🙂 (I have no strong preference btw, 17:21 on Sundays seemed arbitrary enough!)
- [n/a] …
=> Fix syntax in CodeQL code scanning workflow

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/extension.ts
Fixes https://github.com/github/vscode-codeql/issues/813 (commit https://github.com/github/vscode-codeql/commit/6c8121202a5a0cd9c9756f40abca2efb1b9a5ee9). I've expanded the LGTM download message to prompt users to choose a language:
👆🏽 This doesn't apply to all databases, hence "if available". (I hope that's clear enough, but otherwise we can try to _only_ display this message for multi-language databases. I haven't looked at how to do this yet 🙇🏽‍♀️)
(https://github.com/github/vscode-codeql/commit/281084e780f04c8f66d23b3684fc07d5fcb16df0 fixes some minor typos.) 
- n/a `@github/docs-content-codeql` has been cc'd in all issues for UI or other user-facing changes made by this pull request.
=> Improve LGTM download messages

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/distribution.ts
Does this warrant a changelog entry?
=> Add version info while downloading

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/view/alert-table.tsx, extensions/ql-vscode/src/view/raw-results-table.tsx, extensions/ql-vscode/src/view/result-table-utils.tsx
Empty table when no query results are returned is replaced by a message with documentation to the [CodeQL Language Guides](https://codeql.github.com/docs/codeql-language-guides/).
Fixes https://github.com/github/vscode-codeql/issues/551.
Please let me know if this warrants a change to the changelogs and if I should cc `@github/docs-content-codeql`.
=> Add link to language guides for empty query results

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/test-adapter.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/test-adapter.test.ts
This PR modifies the extension to reregister testproj databases around test execution.
Closes: #768
=> Reregister testproj databases around test runs

extensions/ql-vscode/src/view/result-table-utils.tsx, extensions/ql-vscode/src/view/resultsView.css
Increased the empty query output message's font size and added margins around the message using flex-box centering.
Closes https://github.com/github/vscode-codeql/issues/869
=> Increase font size and add margins to empty query message

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/logging.ts, extensions/ql-vscode/src/queryserver-client.ts, extensions/ql-vscode/test/pure-tests/logging.test.ts
Will fix https://github.com/github/vscode-codeql/issues/820.
- Docs-wise, we should probably mention this in https://codeql.github.com/docs/codeql-for-visual-studio-code/troubleshooting-codeql-for-visual-studio-code/.
=> Specify custom directory for storing evaluation logs

extensions/ql-vscode/.eslintrc.js, extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/astViewer.ts, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/compare/view/Compare.tsx, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/messages.ts, extensions/ql-vscode/src/qltest-discovery.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/view/raw-results-table.tsx, extensions/ql-vscode/src/view/result-tables.tsx, extensions/ql-vscode/src/view/results.tsx, extensions/ql-vscode/src/vscode-tests/.eslintrc.js, extensions/ql-vscode/src/vscode-tests/cli-integration/databases.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/global.helper.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/query.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/run-cli.test.ts, extensions/ql-vscode/src/vscode-tests/index-template.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/config.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/astBuilder.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/helpers.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts
Will fix https://github.com/github/vscode-codeql/issues/849 and will also (indirectly) fix https://github.com/github/vscode-codeql/issues/509. 
Uses the syntax from https://github.com/microsoft/vscode/issues/120251#issuecomment-825832603 to let the CodeQL extension work with workspace trust. For users who have enabled the workspace trust feature:
- If the user trusts the workspace: all CodeQL features are enabled
- If the user doesn't trust the workspace: Certain settings (that could execute arbitrary code from the workspace) are disabled at the workspace level, and the extension ignores them. This is what the UI looks like:
⚠️ ~Note: Currently, you can't use the CodeQL extension at all in untrusted workspaces. This is because it depends on the [Test …
=> Use the workspace trust feature

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/authentication.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/run-remote-query.ts
This branch is based on the `qc-development` branch, but (assuming the feature-flagging works) it should now be good to merge to `main` without disrupting our external users.
- First commit is from https://github.com/github/vscode-codeql/pull/874 (already reviewed)
- Second commit adds a basic workflow dispatch command (adapted from hackathon work in https://github.com/github/vscode-codeql/pull/701/files)
- Third commit hides these commands behind the "canary" flag 
More details in internal linked issue and demo!
(n/a—these features aren't useful to external users, so no need to publicize them)
- …
=> Workflow dispatch + dev branch tidy-up

.github/workflows/main.yml
By default, the [`pull_request`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request) event means "`opened`, `synchronize`, or `reopened`". Also adding `ready_for_review`, so that the check runs when we take a PR out of draft state. Hopefully this will help us kick off PR checks on version bump PRs (e.g. https://github.com/github/vscode-codeql/pull/887) more effectively 😃 
n/a
=> Run PR checks on "ready_for_review"

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/databases.ts
Will fix #798.
As described in the linked issue, we don't have an easy way of re-adding a database's source folder to the workspace. This PR adds a new command (in the Databases View) that lets you re-add a source folder.
(We also considered re-adding source folders automatically, similar to how the `codeQLDatabases.removeOrphanedDatabases` command is run, but I'm now wondering if that'll be annoying to users. They may have deliberately removed a source folder from their workspace, and don't want it included automatically 🤔 I'm open to suggestions though!)
PS: In the process, I found a small bug in how we upgrade databases. (Opened an issue here #890, but haven't worked out how to fix that yet! 😅)
- I don't think a docs change is necessary, since the docs don't describe database commands …
=> New command to add database source folder to workspace

.github/workflows/main.yml
CodeQL CLI v2.5.7 is now [released](https://github.com/github/codeql-cli-binaries/releases/tag/v2.5.7) 🎉
N/A - only affects tests
=> Update CLI integration tests with latest version of CLI

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/cli-integration/run-cli.test.ts, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
This PR changes the unit tests and integration tests to also download a nightly build of CodeQL and test against this in addition to the stable versions already being tested. This will allow us to catch compatibility issues that arise from changes to the CodeQL CLI _before_ we release them.
N/A: Only affects tests.
=> Run tests with nightly CLI

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json
Fixes https://github.com/github/vscode-codeql/issues/901. The description for the CLI setting is now rendered as markdown:
(Thanks to @Marcono1234 for pointing this out 🎉)
=> Fix markdown rendering for `codeQL.cli.executablePath` description

extensions/ql-vscode/src/test-adapter.ts
Closes https://github.com/github/vscode-codeql/issues/910
Currently QLTestAdapter.run() calculates the databases affected by a set of tests (those databases will be deleted and then reopened after test completion) using a nested filter-find expression. Which does not work because the predicate is an async function, so the expression is testing the truthiness of a Promise instead of the async result.
This commit fixes the problem by implementing the same check with a loop so that we can invoke the async predicate using await.
=> Calculate databasesUnderTest with a loop

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/query-history.ts
Fixes https://github.com/github/vscode-codeql/issues/906.
The "Open Query Results" button in the query history view currently doesn't work. Error: `Cannot read property 'result' of undefined (codeQLQueryHistory.itemClicked)`.
I experimented a bit with the `handleItemClicked`, and it looks like changing `singleItem` to `finalSingleItem` works as expected 🙂 
=> Fix error from "Open Query Results" button

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
Updates the package dependencies to avoid dependabot errors.
I updated the `@types/gulp` to avoid some typings errors that were
introduced by incompatible versions of `@types/undertaker`.
Also, I forced resolution on `"glob-parent": "~6.0.0"` that avoids
a vulnerability on earlier versions.
I did a smoke test of features that use glob, as well as running a few
queries. All looks good.
- [n/a] `@github/docs-content-codeql` has been …
=> Fix dependabot errors

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/run-queries.ts
Will fix #569.
First pass at adding a new command "CodeQL: Run Query on Multiple Databases", that lets you select multiple databases from a quick pick menu and run a query over all of them. This currently loops over all selected databases and displays results and query history runs for each database separately. If a database is incompatible, we display an error message and skip to the next database.
This might need some design input if we want to do anything fancy with results display 😅 
<details><summary>Expand for a (somewhat grainy) demo</summary>
</details>
**Notes**
- Would this be useful in its current form? (I was mainly experimenting, so suggestions are welcome 🙂)
- The database quick pick currently lists _all_ databases that are in your Databases UI, including those with the …
=> Add command to run queries on multiple databases

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/run-remote-query.ts
Adds a `findLanguage` function that uses `codeql resolve queries --format bylanguage` to detect a query's language. This might not work for some queries, so I've added a manual selection as a fallback.
This is used in two places:
- When running a query on multiple databases (we now only show the databases that correspond to the query language)
- When running a remote query (we can now autodetect a language when it isn't specified in the `.repositories` config. This config file is going to be replaced by a different UI soon.)
Question: Does this need tests? I wasn't sure where/how to go about that!
- Only the "multiple DBs" part is user-facing for now
- No docs update required (beyond pending update from https://github.com/github/codeql/pull/6322)
=> Autodetect what language a query is for

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/test-adapter.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/test-adapter.test.ts
Adjusted test log output to display diffs only when comparing failed test results with expected test results. For example, compilation errors will no longer compare expected results with error logs.
Example compilation error log BEFORE change:
```
Compiling queries in <path-to-test>.
[1/1 comp 5s] FAILED(COMPILATION) <path-to-test>
0 tests passed; 1 tests failed:
FAILED: <path-to-test>
errored: <path-to-test>
--- expected
+++ actual
@@ -1,1 +1,1 @@
-| main.go:15:41:15:52 | call to len |
+ERROR: Could not resolve predicate length/0 (<path-to-test>)
```
Same error AFTER change:
```
Compiling queries in <path-to-test>.
[1/1 comp 5.5s] FAILED(COMPILATION) <path-to-test>
0 tests passed; 1 tests failed:
FAILED: <path-to-test>
compilation error: <path-to-test>
ERROR: Could not resolve predicate …
```
=> Adjust test log output to display diffs only for failing test results

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/run-remote-query.ts
This PR tweaks how you run remote queries 😎 
Previously, each query needed a `.repositories` file that listed which repositories you wanted to analyze.
Now, you can save pre-defined "repository lists" in your VS Code settings, and choose one of those when you run a remote query. 
New flow:
1. If you still have a `.repositories` file, we use the information from there to run your remote query.
2. Otherwise, if you have saved repository lists in your VS Code settings, you can select one of those to run against.
3. If not, you can enter a single repo in a text input box and we run against that.
The `getRepositories` function should give an error if you end up with an empty string/array/object. It doesn't check if your repositories are valid, but the API call itself gives an error in that …
=> Running remote queries: Save repo lists in VS Code config

.github/workflows/main.yml
This PR changes our testing workflow to use a version of the `codeql` repository that is suitable for the CLI being tested against, instead of always checking out `main`. This is needed because some upcoming packaging changes have made the current `main` of `codeql` incompatible with old versions of the CLI that we still need to test against here.
=> PR Checks: Use version of `codeql` repo suitable for CLI version

extensions/ql-vscode/package.json
Tiny follow-up to #918. The setting I added was being autofilled in a weird way:
Allowing it to have type `null` seems to fix this 🙂
=> Fix type for "remote repo list" setting

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-results.test.ts
Allow users to see the filename in the query history view instead of the name from the metadata. Introduce the `%f` pattern in the history view, supporting full queries as well as quick eval queries. 
Reformatted the description of the format preference to better see the available patterns.
=> Add support for filename pattern in history view

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/contextual/locationFinder.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/run-queries.ts
Closes https://github.com/github/vscode-codeql/issues/832
This PR adds a new right click option in the Query History view called _Export Results (CSV)_ which will export the results of a non-alert query to a CSV file (as chosen in a save dialog displayed to the user).
=> Allow exporting of results for non-alert queries

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/config.test.ts
Will fix #919 .
Added a new setting `codeQL.runningQueries.maxPaths` that lets you configure how many paths to display 🙂 I tested this with a few databases/queries (e.g. [this one](https://lgtm.com/projects/g/codefollower/Tomcat-Research/alerts/?mode=list&id=java%2Fcommand-line-injection%2Cjava%2Fxss))
=> New setting to specify number of paths per alert

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/run-cli.test.ts
First stage of tidying up and adding tests. See https://github.com/github/vscode-codeql/pull/915#pullrequestreview-720517460 and the linked (internal) issue.
- I've moved `findLanguage` out of "run-remote-query" and into a more general place ("helpers"), since it's used in a few functions and this seemed like a more logical place
- Added a test for `resolveLanguages` (basically copied from the `resolveQlpacks` test above 😅) 
I haven't yet added a test for the other functions from https://github.com/github/vscode-codeql/pull/915, since they require a bit more setup. Stay tuned for a follow-up PR 😎 
_N/A: no user-facing changes_
=> Tidy and add tests for `resolveLanguages` commands

extensions/ql-vscode/src/vscode-tests/cli-integration/data/simple-javascript-query.ql, extensions/ql-vscode/src/vscode-tests/cli-integration/data/simple-query.ql, extensions/ql-vscode/src/vscode-tests/cli-integration/run-cli.test.ts
Adding another test! (follow-up to https://github.com/github/vscode-codeql/pull/937).
- Added a new query `simple-javascript-query.ql` with an import statement 
- Added test to check that the language resolves to `'javascript'`
N/A - not user-facing
=> Add test for `resolveQueryByLanguage`

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/contextual/queryResolver.ts, extensions/ql-vscode/src/contextual/templateProvider.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/quick-query.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/queryResolver.test.ts
Most of the languages have recently been refactored into separate library and query packs, with the contextual queries defined in the query pack. In the near future, these contextual queries will move to the library pack.
Current CLI releases throw an error in `codeql resolve queries` when the extension tries to search the library pack for contextual queries. This change makes two related fixes:
1. If the queries are not found in the library pack, it then scans the corresponding standard query pack as a fallback.
2. It detects the problematic combination of CLI and packs, and avoids scanning the library pack at all in those cases. If no queries are found in the problematic scenario, the error message instructs the user to upgrade to the latest CLI version, instead of claiming that the …
=> Fix AST viewer for refactored language packs

.vscode/settings.json
VS Code v1.60.0 uses TypeScript 4.4.2 by default, which gives a number of new errors (e.g. [in `catch` clauses](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables)). I had to change the `"typescript.tsdk"` setting to get VS Code to use the workspace version (TypeScript 4.3.2) instead. (I'm not sure if the setting was working previously: I didn't have a `common/temp` folder 🤔)
Also added `"typescript.enablePromptUseWorkspaceTsdk": true` to prompt users to choose the workspace version too. 
I tested this in a fresh codespace, which seemed to work. We'll probably want to upgrade to 4.4 at some point but, either way, I think this change is helpful to make sure we're all using the same workspace version 🙂 
N/A
=> Configure correct TypeScript version to use in VS Code

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/run-queries.ts
If `AUTOSAVE_SETTING` is `true` and I trigger the `Run Query` command, I occasionally see race conditions where the query is run before the file is saved, and I see results corresponding to the previous version of the query. I'm not sure how to test this and I haven't been able to reliably reproduce the problem (though it occurs often).
Intuitively, it seems like this change should fix it, since [`editor.document.save`](https://github.com/microsoft/vscode/blob/main/src/vs/vscode.d.ts#L143) returns a `Thenable`, which I think means it returns a promise or the function is async.
My javascript is very rusty, sorry if this is inaccurate!
=> Wait for document to be saved before running query

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/run-cli.test.ts, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
[CodeQL CLI 2.6.1 is](https://github.com/github/codeql-cli-binaries/releases/tag/v2.6.1) released! 🚢
=> Update CLI version for integration tests

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/run-remote-query.ts
Paired with @shati-patel to write this 🍐 
When a user tries to run a remote CodeQL query (Internal feature only) but it turns out that a subset of the repositories chosen are invalid, offer them the option to rerun their query but only on the subset of valid repositories. The full set of invalid repositories and reasons are included in the logs. It would be nice to also include this information in the popup message but we were struggling to find a convenient or good way to do this.
No changelog needed as this is an internal feature.
=> Offer option to rerun remote query on the subset of valid repositories

.github/workflows/main.yml, extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/contextual/queryResolver.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/run-cli.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/queryResolver.test.ts
The previous synthetic query suite was not finding the ast query because
the `qlpack` directive in a query suite only matches queries from the
default suite, which `printAST.ql` is not part of.
This changes to using `from` and `queries` directives.
Also, adds an integration test to ensure we find the queries using
different CLIs. However, this only tests using the latest `main` from
the codeql repository. I wonder if we should start testing using
different versions of the repo.
=> Fix AST Viewer

extensions/ql-vscode/src/authentication.ts, extensions/ql-vscode/src/run-remote-query.ts
[internal feature]
The API for remote querying has changed (see linked issue), so we no longer need to provide a token in the Octokit request 🙂 This is a partial revert of [this commit](https://github.com/github/vscode-codeql/pull/882/commits/3c678ca39f90a429999e4a197c2ccc64f2718c00#diff-39def7429bdcd0a61f1dab2ef3277a28e1f8ff7186cced600a49b10c8b9d8276).
N/A, no user-facing changes
=> Remove `token` for running a remote query

extensions/ql-vscode/src/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/run-remote-query.test.ts
First pass at adding tests:
- Tests for `getRepositories` ✔️ 
- Tests for ~`validateRepositories`~ `attemptRerun` ✔️ 
- Tests for `runRemoteQuery`: still TODO (I can follow-up in separate PR)
There's still more to test, but (to avoid this PR getting too big) it's probably helpful to get this reviewed and merged so far...
I've tried testing the main interesting cases for `getRepositories` and `attemptRerun`. Is there anything else that would be helpful to test? (Or not test? 🙃) 
N/A
=> Tests for run-remote-query

extensions/ql-vscode/package.json
There was a space missing for one of the items, making it not rendered correctly as list item
=> Fix formatting for history format preference

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
Update latest stable CodeQL CLI version for testing from 2.6.1 to 2.6.2, released today.
- [N/A] `@github/docs-content-codeql` has been cc'd in all issues for UI or other user-facing changes made by this pull request.
=> Update CLI tests to use 2.6.2

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/extension.ts
=> Fix version copy for missing cli

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/run-remote-query.test.ts
[Internal use only]
Instead of hard-coding the controller repo for viewing remote queries, let users specify a custom one in the settings. This works because we can use a dynamic workflow instead of a workflow file checked in to a controller repo. (Currently behind a feature flag - see linked issue or let me know if you need access for reviewing!) If there's no repo defined in the config, prompt user to enter it in a textbox.
Note: Slightly tangential, but I also renamed the `remoteRepositoryLists` setting and grouped everything related to remote queries under a `codeQL.remoteQueries` category. I'll update the internal instructions with the renamed setting.
N/A - no user-facing changes
=> Add option to specify a different "controller" repo

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/extension.ts
Closes [#894](https://github.com/github/vscode-codeql/issues/894)
**Changes made**: removed the line about selecting a language from the dropdown, which now makes the download progress visible even when the popup is collapsed.
=> Remove line about selecting a language from the dropdown.

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databaseFetcher.test.ts
Suggested feature added: add progress messages to the LGTM download option.
=> Add progress messages to LGTM download option.

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/extension.ts
=> Make "Open Referenced File" command functional on open .qlref

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/quick-query.ts, extensions/ql-vscode/src/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/data-remote-no-qlpack/in-pack.ql, extensions/ql-vscode/src/vscode-tests/cli-integration/data-remote-no-qlpack/lib.qll, extensions/ql-vscode/src/vscode-tests/cli-integration/data-remote-no-qlpack/not-in-pack.ql, extensions/ql-vscode/src/vscode-tests/cli-integration/data-remote-qlpack/in-pack.ql, extensions/ql-vscode/src/vscode-tests/cli-integration/data-remote-qlpack/lib.qll, extensions/ql-vscode/src/vscode-tests/cli-integration/data-remote-qlpack/not-in-pack.ql, extensions/ql-vscode/src/vscode-tests/cli-integration/data-remote-qlpack/qlpack.yml, extensions/ql-vscode/src/vscode-tests/cli-integration/index.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/run-remote-query.test.ts, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
Remote Queries: Create packs for remote queries
This PR handles two cases:
1. There is a qlpack.yml or codeql-pack.yml file in the same directory
as the query to run remotely. In this case, run `codeql pack
packlist` to determine what files to include (and also always include
the lock file and the query itself. Copy to a temp folder and run
`pack install`, then `pack bundle`. Finally upload.
2. There is no qlpack in the current directory. Just copy the single
file to the temp folder and generate a synthetic qlpack before
installing, bundling and uploading.
Two cases that are not handled:
1. The query file is part of a workspace. Peer dependencies will not be
found.
2. The query file and its qlpack file are not in the same directory.
These case should be possible to handle later. 
This PR …
=> Remote Queries: Create packs for remote queries

.github/workflows/main.yml, .vscode/launch.json, CONTRIBUTING.md, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
Also, fix documentation and launch configs to specify the correct and
complete set of environment variables we should be using.
This should fix the failing integration tests on our internal repository.
- [n/a Issues have been created for any UI or other user-facing changes made by this pull request.
=> Use the correct environment variable in integration tests

extensions/ql-vscode/src/vscode-tests/cli-integration/run-cli.test.ts, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
This should fix the failing CLI integration tests.
=> Avoid testing for the correct CLI_VERSION if CLI_PATH is set

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/run-cli.test.ts
The language dropdown for remote queries included some extra stuff like `xml`:
That list came from a call to `codeql resolve languages`, which I've now replaced with a hard-coded list of languages. (We already had a hard-coded list of supported languages, so I didn't feel too bad about reusing that one 🙃 )
N/A: this is only relevant for remote queries, which is still an internal-only feature.
=> Tidy up language dropdown

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
Version 2.7.1 was released this week: https://github.com/github/codeql-cli-binaries/releases/tag/v2.7.1 🎉
=> Update CLI version in tests

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/interface-utils.ts, extensions/ql-vscode/src/pure/bqrs-utils.ts
Previously, positions with end column of 0 were rejected by the
extension. CodeQL positions are supposed to be 1-based, but the CLI
does handle 0-based and negative positions by using character offsets
from the current line start.
Instead of rejecting these kinds of positions, the extension should
handle them as gracefully as possible.
Fixes #999
=> Add leniency in how positions are handled

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/extension.ts
Adds a "Generate Query Help" command which generates a .md file from a selected .qhelp file and opens it for preview in vscode. Implements [#481](https://github.com/github/codeql-coreql-team/issues/481)
=> Add Generate Qlhelp preview command

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/interface.ts
When the extension loads a sorted result set, it takes a shortcut and
avoids loads a file with only the bqrs results for that sorted table.
However, it does not load the results for any other table. This causes
result set names to go away. This change ensures that if we are loading
a sorted table, we also load the result set names for all other tables
in that query.
Fixes #1005.
=> Ensure all result set names are loaded

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases.ts
=> Emit more relevant error message when failing to add source folder

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases.test.ts
Fixes a bug where legacy databases with both unzipped and zipped sources
were incorrectly being loaded with the src folder.
Fixes #1020.
=> Ensure src.zip is prioritized over src folder

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/pure/messages.ts, extensions/ql-vscode/src/run-queries.ts
This functionality is for internal users only.  Do not use this functionality if you are not a GitHub employee.
This PR allows internal users to run queries that invoke ML models from CodeQL packs.  When a hidden setting is enabled, ML models are resolved using the CLI command `codeql resolve ml-models`.  To help prevent unintentional use of this functionality, we only respect the hidden setting if the workspace is trusted.
Available ML models are passed to the `availableMlModels` property of the `QueryToRun` object as part of the `evaluation/runQueries` queryserver message.  This makes them available for use in CodeQL queries.
=> [Internal only] Support running queries with ML models from CodeQL packs

extensions/ql-vscode/gulpfile.ts/typescript.ts, extensions/ql-vscode/package.json, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/src/remote-queries/view/remoteQueries.css, extensions/ql-vscode/src/view/octicons.tsx
This changeset builds up an initial remote queries view based on some mock data. The view will gradually be refined and hooked into real data with further PRs.
See internal issue for more context.
N/A: This is only relevant for remote queries, which is still an internal-only feature.
=> Remote queries view using mock data

extensions/ql-vscode/src/remote-queries/remote-query-submission-result.ts, extensions/ql-vscode/src/remote-queries/remote-query.ts, extensions/ql-vscode/src/remote-queries/repository.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/run-remote-query.test.ts
Small refactor to expose the result of a remote query submission. 
The remote query details will be used in future PRs.
=> Expose remote query submission result

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/queryserver-client.ts
This is in preparation of supporting structured query logs.
When passing this option, use the old format of query logs.
Later, when we want to add support for structured query
logs, we can add remove this option.
No changelog required since this is an internal change.
=> Pass `--old-eval-stats` to query server

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/view/result-tables.tsx
Only show it when there really is an alert table to see.
=> Avoid showing the alert option in the drop down

CONTRIBUTING.md
This PR adds a small clarification to the Contributing documentation. Previously it wasn't clear (to me ✨) which directory to run the commands for CLI testing from.
=> Docs: add clarification on directory for running tests via CLI

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-query.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/remote-queries/shared/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/src/remote-queries/view/remoteQueries.css
Adds some interaction to these buttons in the remote queries webview:
- The first one opens the query file that was run, if it exists (similar to what we do in the local results view). 
- The second one opens the exact query text that was run (in a virtual "read-only" file).
- Consolidate the `remote-query` and `codeql` text providers.
- Once #1037 is merged, extract that behaviour so it is used wherever we are opening editors.
N/A: Still an internal-only feature. No user-visible changes.
=> Remote queries: Open query file/text from webview

extensions/ql-vscode/src/vscode-tests/cli-integration/run-remote-query.test.ts
Starting in CLI 2.7.5, there will no longer be any
`codeql/javascript-upgrades` pack. Change the test so that it passes
using both old and new packs.
=> Handle different dependencies in remote queries tests

extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/remote-queries/download-link.ts, extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-query-result-index.ts, extensions/ql-vscode/src/remote-queries/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/shared/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/src/remote-queries/view/remoteQueries.css
Updates the download buttons in the remote queries view to download the results.
Once the file has been downloaded, a notification is shown
* Introduced the notion of a `DownloadLink` and used it in `RemoteQueryResult` entities and elsewhere.
* Introduced a `ResultIndex` entity that contains all the information we retrieve from the result-index file, as well as any other information needed from the workflow/API.
* Updated the actions API client to build up this new `ResultIndex` entity and also set DownloadLink information where appropriate.
* Updated the web view to send a message to the extension to initiate downloads.
Note that I think error handling in the API client can be improved, and I intend to do that in a separate PR.
N/A: Still an internal-only feature. No user-visible …
=> Implement download behaviour in remote queries view

extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/run-queries.ts
In the remote queries webview, display the actual query name (from the metadata) if available. Otherwise, fall back to the file name: 
I started from the existing [`getQueryName()`](https://github.com/github/vscode-codeql/blob/bf350779c9d1a722768ccbdc5d2da8418b5e6862/extensions/ql-vscode/src/query-results.ts#L158-L166) function, which does this exact thing for local queries. However, the types don't match up, so I couldn't work out how to re-use it directly 😕 
Instead, I separated out the code that gets query metadata, and re-used that for remote queries. Other suggestions are also welcome! 😇 
cc @charisk 
- Add a test for the metadata function
- Restructure/rename the function to make things cleaner (see https://github.com/github/vscode-codeql/pull/1049#discussion_r769411121)
N/A - …
=> Remote queries: Get query name from metadata (if possible)

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/interface.ts
Currently, the webview _always_ opens next to the currently active
editor. This is a pain if you already have 2 columns open since this
means that the webview will open in a third column, which is rarely
what you want.
This change uses a more sophisticated approach to opening the webview:
1. If there is only one column, open webview to the right of it
2. If there are multiple columns and the active editor is _not_ the
last column, open to the right of the active editor
3. Otherwise open in the first column.
This will avoid opening a new column unless there is only one column
open right now.
There is no native API that vscode exposed to compare column locations,
so this uses the `ViewColumn` api is a slightly non-standard way.
A limitation is that if the last column is empty and the active …
=> Be nicer about where to open the results webview

extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/data/simple-javascript-query.ql, extensions/ql-vscode/src/vscode-tests/cli-integration/helpers.test.ts
Follow-up to #1049.
- Move the function to the general `helpers.ts` file
- Rename it to `tryGetQueryMetadata`
- Add a CLI integration test
N/A, no user-facing changes
=> Tidy up and add test for getting query metadata

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/quickEvalCodeLensProvider.ts
Fixes https://github.com/github/vscode-codeql/issues/1051.
I've added a setting (and played around with it a bit to make sure it works ✔️)
- [ n/a?] `@github/docs-content-codeql` has been cc'd in all issues for UI or other user-facing changes made by this pull request.
=> Add setting to enable/disable Quick Eval codelens

extensions/ql-vscode/src/compare/compare-interface.ts, extensions/ql-vscode/src/interface.ts
The CSS files are inside /view sub-directories so the paths are currently incorrect.
N/A:
=> Fix CSS file paths

.github/pull_request_template.md
Update this repository's pull request template prompting the user to add the `ready-for-doc-review` label whenever the proposed changes touch upon the UI or introduce any user-facing elements.
The Docs Content team uses an automation which looks for this label to facilitate pings to the appropriate group of writers. This makes the old `@github/docs-content-codeql` team obsolete.
=> Update Docs ping in issue template

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/interface.ts
A user reported a bug where the results view is opened in the active editor, even if the results view is already visible in a different column:
<details><summary> 🖱️  Expand for example GIF</summary>
<p>
</p>
</details> 
This PR fixes that behaviour. I.e. when there's already a results view visible (not necessarily active), we display the results in that panel. 
A slight weirdness we could still find is that if the results view is open in a tab somewhere, but not visible, it can still move to a different place. I don't think this is a problem, but I can open an issue if it is!
<details><summary>🖱 Expand for details</summary>
<p>
In this case, the results view is open on the right, but it isn't currently visible. Since the right-hand side is the active editor, the new results open on the …
=> Results view: Don't reopen webview if it's already visible

extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/sample-data.ts
Adds a helper command that shows the Remote Queries Results view using mocked data instead of having to execute a query and wait for the results.
I found having this sort of thing helpful when working on the view so I thought we might want to check it in. If we don't want a command showing up even in canary, we could check in only the sample data and some commented out code. 
I believe the following isn't applicable:
=> Add helper command for working on the Remote Queries Results view

.vscode/launch.json
This change updates the `launch.json` arguments for the three integration test configurations to match the arguments used in https://github.com/github/vscode-codeql/blob/6bd7f0ae12d98752d87c97d07ad37761f4d61401/extensions/ql-vscode/src/vscode-tests/run-integration-tests.ts#L111-L144, which are much more recent. 
I have used the VSCode Debugger to test with these configurations locally and the tests work as expected. ✨ 
I also edited a comment in the `launch.json` file that was a bit difficult for me to understand initially. 
- [N/A] Issues have been created for any UI or other user-facing changes …
=> Standardize integration test args in VSCode debugger

extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/sample-data.ts, extensions/ql-vscode/src/remote-queries/shared/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/src/remote-queries/view/remoteQueries.css
Currently the term "analysis result" is used to refer to the summary of an analysis outcome. However, the term "result" means something else in terms of an analysis - it means an actual result of the query. 
I've renamed analysis result to analysis summary in order to avoid confusion.
N/A
=> Rename analysis result to analysis summary

extensions/ql-vscode/src/compare/compare-interface.ts, extensions/ql-vscode/src/interface-utils.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/view/Badge.tsx, extensions/ql-vscode/src/remote-queries/view/DownloadButton.tsx, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/src/remote-queries/view/SectionTitle.tsx, extensions/ql-vscode/src/remote-queries/view/VerticalSpace.tsx, extensions/ql-vscode/src/remote-queries/view/ViewTitle.tsx, extensions/ql-vscode/src/remote-queries/view/baseStyles.css, extensions/ql-vscode/src/remote-queries/view/remoteQueries.css
While working on some Remote Query view changes I found that the code was getting a bit difficult to manage so I've started extracting out some base components and styles. This could be the start of a component library we can re-use across the codebase.
Note that I looked into possibly using a more proper solution like [styled-components](https://styled-components.com/) but decided it wasn't appropriate/worth it. E.g. for styled-components (and I imagine others) we'd have to make a compromise in our CSP implementation to allow inline styles.
N/A
=> Extract base react components

extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts
Use paging when calling listWorkflowRunArtifacts against the GitHub API to ensure we get all artifacts.
Credit to @shati-patel for finding the actual issue.
N/A
=> Added paging to the listWorkflowRunArtifacts call

extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
We currently have a single action to download a results artifact which means that we lose some context about what we're downloading when we reach the extension code. In order to keep that context and make it easier to track which results have been downloaded, I split the action into two separate ones.
N/A
=> Split download actions in remote queries view

extensions/ql-vscode/package.json, extensions/ql-vscode/src/vscode-tests/run-integration-tests.ts
The CodeQL extension depends on `hbenl.vscode-test-explorer`, which in turn depends on `ms-vscode.test-adapter-converter`.
The former gets installed automatically, but there's a manual step for the latter:
VS Code does prompt you to install, but if you cancel or miss that notification (easily done!), it's hard to get to a usable state from there.
If we directly depend on `ms-vscode.test-adapter-converter`, it should get installed properly. Thanks to @KarlFuhlbrugge for helping to test!
PS: The [`hbenl.vscode-test-explorer`](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer) is deprecated, so eventually we should move to the VS Code native testing UI. But hopefully this fixes things in the meantime!
=> Make sure extension dependencies are installed

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/packaging.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/data-invalid-pack/qlpack.yml, extensions/ql-vscode/src/vscode-tests/cli-integration/packaging.test.ts
Adds commands to install and download packs 📦 
For the "Download Packs" command, I've added a hard-coded option to download all core packs, and a custom option if users want to specify a custom pack. 
<details><summary>Expand for demo GIF</summary>
<p>
</p>
</details> 
For "Install Packs", the user can select packs from their workspace
<details><summary>Expand for demo GIF</summary>
<p>
</p>
</details> 
~PS: I will add a test for these commands 🧪 But I'd be grateful for a quick review first to see if this is a plausible way of doing things!~ 🙈 Done!
=> Add "pack install" and "pack download" commands

extensions/ql-vscode/src/remote-queries/remote-queries-monitor.ts
We sometimes get an error where the extension successfully schedules a remote query run but then fails with an `HttpError: Not Found` error when it checks the workflow status. Waiting a few seconds before starting to check the status might help 🤞🏽 
See internal linked issue for more info!
n/a, internal feature
=> Wait a few seconds before monitoring remote query run

extensions/ql-vscode/src/packaging.ts
As @adityasharad suggested in https://github.com/github/vscode-codeql/pull/1076#discussion_r787067110, we can have more granular progress tracking by counting how many packs to install 📦 
This sort of works, except we can't set the `maxStep` until after the user has selected the packs... So for the first step ([here](https://github.com/shati-patel/vscode-codeql/blob/d534f88fad43410f07b8ed651726f31d4d55649d/extensions/ql-vscode/src/packaging.ts#L98-L102)) I just stuck with "2" as the max number of steps, which means that the first step takes up a disproportionate amount of space in the progress bar. This looks a bit odd, but I don't think it's a big problem 😅 
n/a - just a follow-up to #1076!
=> Update progress bar for "install pack dependencies"

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/shared/analysis-result.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
Adds logic to download analyses results, do some minimal processing and make them available to the web view.
Note that this solution doesn't work well with running multiple queries but I'm hoping to address that once we have some notion of query history.
Also it does not support bqrs files as there is some Product/UX work that needs to happen.
N/A:
=> Download and process analyses results

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/vscode-tests/no-workspace/helpers.test.ts
First step towards #1085. The native VS Code testing API is only available from v1.59.0 onwards, so I've upgraded here.
Minor impact: the only noticeable change was that the `Memento` class (which we use in tests) needed an extra method.
n/a
=> Update to VS Code 1.59.0

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts
Kick off auto-downloading of analyses results once a remote query has completed successfully.
N/A:
=> Auto-download analyses results

.github/workflows/codeql.yml
We need to run the CodeQL analysis with at least CodeQL CLI v2.7.6 to opt into the ML-powered queries beta. This CLI hasn't yet made it into the Actions VM images, so we add `tools: latest` to download the CodeQL Bundle v2.7.6 from `github/codeql-action`. Once CodeQL Bundle v2.7.6 ships in the Actions VM images, we will then be able to remove `tools: latest`.
=> Run CodeQL analysis with latest CLI to opt into ML-powered queries beta

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/compare/compare-interface.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/interface-utils.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/sample-data.ts, extensions/ql-vscode/src/remote-queries/shared/analysis-result.ts, extensions/ql-vscode/src/remote-queries/view/DownloadSpinner.tsx, extensions/ql-vscode/src/remote-queries/view/HorizontalSpace.tsx, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/src/remote-queries/view/baseStyles.css
Reports status of analyses results:
* Show spinner when downloading results
* Show notification if there was a failure
* Remove download button if results have downloaded successfully
* If all results have been downloaded successfully, hide the "Download all" button
This PR introduces the use of [Primer React](https://primer.style/react) to make use of the Spinner component. See the [Getting started guide](https://primer.style/react/getting-started) to understand some of the changes I've made.
Note that with styled-components being brought in (as a dependency of Primer React) we can now make use of that in our components. In order to keep the size/complexity of the PR reasonable, I didn't take advantage of that yet though.
I will do some more testing around the CSP changes I've made on …
=> Show remote analyses results status

extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-results.test.ts
And tweak the commands visible from the view.
No changelog entry needed since it is still part of the query history feature.
=> Add cancellation from query history view

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/contextual/templateProvider.ts, extensions/ql-vscode/src/extension.ts
Two small bugs:
1. The AST view command was viewing the wrong ast when the command was
selected from the context menu. It was always selecting the active
editor instead of the item selected in the file menu.
2. The `codeql.showLogs` command was not being registered properly.
With this change, there is uniform error handling, telemetry,
and disposal.
=> Fix ast view and command registration

extensions/ql-vscode/src/remote-queries/view/FullScreenModal.tsx
Adds a new full screen modal component that will be used to show code paths for path queries.
It uses React Portals to break out of the DOM tree. See https://reactjs.org/docs/portals.html
The component isn't currently in use as we don't have code paths yet, but you can see it in action on [this branch](https://github.com/github/vscode-codeql/tree/charisk/use-full-screen-modal). Usage commit [here](https://github.com/github/vscode-codeql/commit/5f475f5472a1cd0de1c3cf5a13c68f9a2e8eecf2).
N/A:
=> Add full screen modal component

extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-query-result-index.ts, extensions/ql-vscode/src/remote-queries/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/sample-data.ts, extensions/ql-vscode/src/remote-queries/shared/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
The all-results artifact is currently checked and a download link is created for it but it's not actually used anywhere, so I've removed it completely.
N/A:
=> Remove use of all-results artifact

extensions/ql-vscode/src/vscode-tests/no-workspace/telemetry.test.ts
Some of our internal integration tests are failing occasionally. I
think extending the wait time here will fix.
=> Add extra delay in telemetry test

extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/src/remote-queries/view/remoteQueries.css
Add a new button that lets users view the results of an analysis using the SARIF viewer extension.
This is a temporary solution until we have a proper way of rendering results. 
Co-authored with @rneatherway. 
N/A:
=> Use SARIF viewer extension for analysis results

extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
Analyses results can't be rendered fully yet so it's best to hide things away to avoid confusing users.
I've taken the approach of using a constant instead of fully removing the code to allow us to easily develop that piece of functionality when it's time.
N/A:
=> Hide analyses results until view is complete

extensions/ql-vscode/src/run-queries.ts
Ensure that upgrades can be resolved even when the upgrades pack is not
in the workspace. This is the situation when the core libraries are
resolved from the package cache.
This change works because `qlProgram.libraryPath` is the resolved
search path for compiling the query. We are guaranteed that the
appropriate core libraries are included in this query.
Note that this change avoids using extra source folders from the
workspace. Previously without using packages, we assume that all
relevant query paths are already inside the workspace. With
packaging, this is no longer the case.
It is theoretically possible that there will be extra upgrade scripts
that are not on the resolved search path, but are included in the
workspace. This situation would have worked in the past.This is not a …
=> Fix upgrades path

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/run-queries.ts
This functionality is now ready for use by all users, and should be enabled for everyone. I don't think now is the right time to advertise it though, so haven't added a changelog note.
**Removal of `workspace.isTrusted` guard**
The restriction to trusted workspaces only was only necessary to confirm secure usage of the `shouldInsecurelyLoadMlModelsFromPacks` setting (see the comment). This setting has now been removed, and the security mechanisms built into `codeql resolve ml-models` mean that we don't need or want to restrict loading ML models to trusted workspaces.
=> Remove feature flag for loading ML models from packs

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/contextual/locationFinder.ts, extensions/ql-vscode/src/contextual/templateProvider.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history-scrubber.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/activation.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-results.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/run-queries.test.ts
Successfully completed queries will be stored on disk and available
across restarts.
- The query results are contained in global storage.
- Metadata and a summary about a query are stored in workspace storage.
- There is a job that runs every 2 hours to determine if any queries are
old enough to be deleted.
=> Save query history across restarts

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/run-remote-query.test.ts
Uses the internal `clear-cache` CLI server command. This has been tested and works.
Note that we had to change some of the tests. Our integration tests were actually testing the case where the cache _was not_ cleared. So, the directory structure used previously reflects the old, name that was cached, not the name in the actual file.
Clearing the cache also placed the compiled query pack in the right location.
H/T: @alexet 
- [n/a] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the …
=> Fix race condition where packs with no name errored during remote query

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts, extensions/ql-vscode/src/remote-queries/download-link.ts, extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/sample-data.ts, extensions/ql-vscode/src/run-queries.ts
This moves all artifacts downloaded for a remote query into the global
storage directory. Each remote query gets its own directory. The
parent directory is the shared query storage directory.
Each remote query directory also gets a timestamp file.
With these changes, remote queries will be persisted across restarts
and deleted automatically on the same schedule as local queries.
Note: This does _not_ add remote queries to the query history view yet.
This part of the feature is coming next.
- [n/a] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, …
=> Store remote query artifacts in global storage

extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
Minor: Our design mockups use the "[file-code](https://primer.style/octicons/file-code-16)" icon instead of the "[file](https://primer.style/octicons/file-16)" icon: 
N/A 🎨
=> Use correct primer icon in results view

extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-query-result-index.ts, extensions/ql-vscode/src/remote-queries/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/sample-data.ts, extensions/ql-vscode/src/remote-queries/shared/analysis-failure.ts, extensions/ql-vscode/src/remote-queries/shared/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/src/remote-queries/view/remoteQueries.css
VS Code now reads error messages (for failed analysis runs) from the result index and displays those errors in the results view:
See linked issue + PR.
N/A: internal only! 🚪
=> Display analysis failures (for remote queries) in results view

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts
=> Ensure `--addtional-packs` arg not used for empty workspace

extensions/ql-vscode/src/compare/compare-interface.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/query-serialization.ts, extensions/ql-vscode/src/query-status.ts, extensions/ql-vscode/src/remote-queries/remote-query-history-item.ts, extensions/ql-vscode/src/remote-queries/remote-query-info.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-results.test.ts
This is a step on the way towards storing remote query history across
restarts.
This PR adds a `QueryHistoryInfo` type that is a union of two types:
`LocalQueryInfo` and `RemoteQueryInfo`.
`LocalQueryInfo` used to be called `FullQueryInfo` and `RemoteQueryInfo`
is only a skeleton right now. The body will be added later. This PR
only introduces it and changes types to make future PRs simpler.
Also, `slurp` and `splat` have been moved to the `query-serialization.ts`
module.
- [n/a] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a …
=> Refactor query history to handle remote and local

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/commandRunner.ts, extensions/ql-vscode/src/extension.ts
Because errors when running queries tend to have better explanations
in the query server log instead of the extension log, by default open
the query server log for query errors.
Fixes #1081
=> Open query server logger for query errors

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/query-serialization.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-query-history-item.ts, extensions/ql-vscode/src/remote-queries/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/remote-query.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/remote-queries/sample-data.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts
Remote query items will be stored in query history and will remain
available across restarts.
When the extension is restarted, any `InProgress` remote queries will
be monitored until they complete.
When clicked on, a remote query is opened and its results can be
downloaded. The query text and the query file can be opened from the
history menu. A remote query can be deleted as well, which will purge
all results from global storage.
Limitations:
1. Labels are not editable
2. Running multiple queries that each run on the same repository
will have conflicting results and there will be errors when trying
to view the results of the second query. This limitation is not new,
but it is easier to hit now. See #1089.
Both of these limitations will be addressed in future PRs.
- [n/a] …
=> Remember remote queries across restarts

extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/remote-queries/sample-data.ts
Removes the limitation specified in #1089 where analyses for the same
repo and different queries will overwrite each other.
This PR does not save analysis results across restarts. After restarting, results will need to be re-downloaded. That is what I will work on next.
=> Allow multiple analyses for same repo to be downloaded

extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
Quick PR to remove a warning generated by the new Failures component
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `Failures`. See https://reactjs.org/link/warning-keys for more information.
at Failures (https://file+.vscode-resource.vscode-webview.net/Users/charisk/dev/vscode-codeql/extensions/ql-vscode/out/remoteQueriesView.js:39823:21)
at Fe (https://file+.vscode-resource.vscode-webview.net/Users/charisk/dev/vscode-codeql/extensions/ql-vscode/out/remoteQueriesView.js:39163:17294)
at ThemeProvider (https://file+.vscode-resource.vscode-webview.net/Users/charisk/dev/vscode-codeql/extensions/ql-vscode/out/remoteQueriesView.js:4155:3)
at div
at RemoteQueries (https://file+.vscode-resource.vscode-webview.net/Users/charisk/dev/vscode-codeql/exten …
```
=> Fixed unique key warning

extensions/ql-vscode/src/query-serialization.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-results.test.ts
Since we are now storing query history on disk, we will need to handle
situations where versions change. For now, there is only version 1. In
the future, we may need to make breaking changes to this format and we
need the flexibility to detect and possibly handle different versions.
In this case, users don't often downgrade their vscode versions, so
most likely, we only need to be forward compatible. Ie- we need to
handle moving from v1 to v2, but not the other way around.
=> Preemptively add a version number to the query history json file

extensions/ql-vscode/package.json, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/queryserver-client.ts
This pull request is intended to ensure the query server runs correctly with structured evaluator logging enabled. It does not alert the user to the generated structured logfile, but a user could manually find it amongst other query artifacts. All structured logs related to all queries in a single query server instance will be output to a single file within `structured-evaluator-log.json` in the storage path that includes other query artifacts. The logs will not be minified for now, and will be set to the highest verbosity, as these are the use cases we expect from most of our users. 
Because we do not expose any configurations or indications to the user that we are integrating structured logging with this change, I have not updated the CHANGELOG. That said, we are now writing an extra …
=> Integrate evaluator structured logging per query server instance

extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/shared/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/src/remote-queries/view/remoteQueries.css
Adds a link to the GitHub Actions logs in the results view! (In line with our design mockups—see internal linked issue)
🖼️ 👀 
N/A - internal! 💅🏽
=> Add link to workflow run logs from results view

extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-query.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/remote-queries/sample-data.ts, extensions/ql-vscode/src/remote-queries/shared/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
Expose the language we're querying against so that it can be used for syntax highlighting configuration.
Note that the new information isn't actually used anywhere yet. It will be used in future PR.
N/A:
=> Expose Remote Query language

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
CLI version 2.8.2 is [released](https://github.com/github/codeql-cli-binaries/releases) 🎉 
N/A!
=> Bump CLI version in integration tests

extensions/ql-vscode/package.json, extensions/ql-vscode/src/query-history.ts
Command is available for remote queries that are in progress or
completed.
=> Add command to open remote query on github

extensions/ql-vscode/test/pure-tests/logging.test.ts
I believe this was accidentally checked in with [this](https://github.com/github/vscode-codeql/commit/2579d12f24bdbd6365762be567890ef376f3c613) commit.
This is a very easy mistake to make, so we should look at blocking the PR when a .only is left in.
N/A:
=> Remove .only from mocha test

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/remote-queries/sample-data.ts, extensions/ql-vscode/src/remote-queries/sarif-processing.ts, extensions/ql-vscode/src/remote-queries/shared/analysis-result.ts, extensions/ql-vscode/src/remote-queries/view/AnalysisAlertResult.tsx, extensions/ql-vscode/src/remote-queries/view/CodePaths.tsx
Adds the ability to read code flow information from SARIF files and render those in the Web View.
A few notes:
- I've used an RC version of the Primer React library to take advantage of some of the new menu/overlay stuff. I don't intend to merge the PR until the final version is released (see https://github.com/primer/react/discussions/1918).
- As discussed previously, we need a better solution for the validation aspect of SARIF data.
N/A:
=> Add support for showing code flows

extensions/ql-vscode/src/pure/bqrs-cli-types.ts, extensions/ql-vscode/src/view/RawTableValue.tsx, extensions/ql-vscode/src/vscode-tests/cli-integration/query.test.ts
`ColumnValue` seems to represent the value of a specific cell in a column, so to me it seems that `CellValue` is a better name for it.
N/A:
=> Rename ColumnValue to CellValue

extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts, extensions/ql-vscode/src/remote-queries/sample-data.ts, extensions/ql-vscode/src/remote-queries/shared/analysis-result.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-query-history.test.ts
We will soon be introducing support for non-alert results, so I've renamed `results` to `alertResults` to disambiguate between the two.
N/A:
=> Rename analysis alert results

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
Update `@primer/react` to latest stable version.
N/A:
=> Update Primer React to v35

.github/workflows/dependency-review.yml
:wave: Hello friends! You have been selected try a new offering from the Dependency Graph team. Thank you advance for your help as we test and iterate towards our GA launch.
This PR introduces the Dependency Review Action as a workflow on your repository. This Action will run on every pull request, scan changed dependencies, and alert you if the pull request is introducing vulnerabilities into your project. 
You can find more details in our [staff-ship announcement](https://github.com/orgs/github/teams/engineering/posts/787)!
In order to install the action and get going, **you simply have to merge this PR**!
❗ As long as you don't make this workflow a required CI job, you won't be blocked by the workflow at all as we refine and prepare for our GA launch. If you are getting failures on …
=> Install Dependency Review Action

extensions/ql-vscode/src/pure/sarif-utils.ts, extensions/ql-vscode/src/remote-queries/sample-data.ts, extensions/ql-vscode/src/remote-queries/sarif-processing.ts, extensions/ql-vscode/src/remote-queries/shared/analysis-result.ts, extensions/ql-vscode/src/remote-queries/view/CodePaths.tsx, extensions/ql-vscode/src/remote-queries/view/FileCodeSnippet.tsx, extensions/ql-vscode/test/pure-tests/sarif-processing.test.ts
Analysis messages can have tokens in them that need to be replaced to link to locations. This PR adds support for rendering these messages properly. Note that the link to the location isn't populated yet - once we have support for that we'll be able to take advantage of it here.
N/A:
=> Deal with analysis messages that have links to locations

extensions/ql-vscode/src/remote-queries/view/RawResultsTable.tsx, extensions/ql-vscode/src/text-utils.ts, extensions/ql-vscode/src/view/result-table-utils.tsx
`@aeisenberg` mentioned special handling we have on local queries around some non-printable characters  https://github.com/github/vscode-codeql/pull/1198#discussion_r825178324
This PR brings this logic to remote queries as well.
N/A:
=> Deal with non-printable characters when rendering raw results

extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-query-result-index.ts, extensions/ql-vscode/src/remote-queries/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/sample-data.ts, extensions/ql-vscode/src/remote-queries/shared/remote-query-result.ts
We want to be able to link from remote query results to the exact file that's being analysed (i.e. the correct GitHub URL for the repository + the exact commit SHA that the database was built from).
https://github.com/dsp-testing/qc-run2/pull/639 adds this to the result index, and this PR reads the SHA and adds it to the `AnalysisSummary`. (If no SHA is found, we use `HEAD` as a fall back) 
We don't use the SHA anywhere yet, but we'll need it in the webview soon. (I "tested" the change by setting some breakpoints and checking the variables, but there's no visible change 🤷🏽 ) 
N/A - internal only 🤫
=> Get database sha from result index

extensions/ql-vscode/src/remote-queries/view/FileCodeSnippet.tsx, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
Fixes for a couple of small styling issues I've noticed.
N/A:
=> Minor style fixes around result rendering

extensions/ql-vscode/src/remote-queries/sarif-processing.ts, extensions/ql-vscode/test/pure-tests/sarif-processing.test.ts
In a recent PR we took advantage of the `parseSarifRegion()` from `sarif-utils.ts` for remote queries. However, `parseSarifRegion` assumes the region will be used by VS Code tooling (the editor) so it offsets it by 1. This made highlights in the remote queries view miss out on the last character.
Ideally we should be updating `parseSarifRegion` to be more generic but that would have been a slightly bigger change than I would have liked right now.
N/A:
=> Fix highlight region end column calculation

extensions/ql-vscode/src/pure/bqrs-utils.ts, extensions/ql-vscode/src/pure/location-link-utils.ts, extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts, extensions/ql-vscode/src/remote-queries/bqrs-processing.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/sarif-processing.ts, extensions/ql-vscode/src/remote-queries/shared/analysis-result.ts, extensions/ql-vscode/src/remote-queries/view/AnalysisAlertResult.tsx, extensions/ql-vscode/src/remote-queries/view/CodePaths.tsx, extensions/ql-vscode/src/remote-queries/view/FileCodeSnippet.tsx, extensions/ql-vscode/src/remote-queries/view/RawResultsTable.tsx, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/test/pure-tests/sarif-processing.test.ts
Follow-up to #1205.
Creates a clickable link in the results view that links to the file location on GitHub. e.g.
links to 
https://github.com/meteor/meteor/blob/HEAD/npm-packages/meteor-installer/install.js#L253-L257 (using the exact SHA instead of HEAD, when available).
N/A - still internal only 🗳️
=> Create remote file links to GitHub URL

extensions/ql-vscode/src/remote-queries/view/FileCodeSnippet.tsx
Code highlighting looked funny in light mode 🙈  
I've used a variable instead, so it currently looks like this in dark/light mode:
or 
My choice of `--vscode-editor-findMatchHighlightBackground` was fairly random, but it looks plausible 😅
=> Use variable for highlighting code

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-queries-monitor.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/run-remote-query.test.ts
Renames "remote queries" to "variant analysis" (see internal issue).
I've covered any user-facing messages/settings/commands but I've deliberately left most internal things unchanged, like the file structure, names of types, tests etc
=> Change public occurrences of "remote queries"

extensions/ql-vscode/src/remote-queries/view/FileCodeSnippet.tsx, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
Puts the annotation for an alert below the highlighted line instead of above. (PS: I'm not sure if this is the right fix, but it _looks_ good at least 🤷🏽)
(Also converts a space to `&nbsp;` to stop an overenthusiastic linter from stripping it off the end of the line.)
=> Minor webview fixes

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts
The variant analysis API endpoint accepts a parameter to control the branch of an action used as part of running the queries. This is for internal testing of changes. The option is not available to users who aren't github staff. But it is useful and it'll be more useful if we could set it from the preferences.
I tested it briefly and it seems to be working correctly and passing the value from the preferences file to the API method.
- No visible changes
- No user-facing changes
- Not required
=> Allow a custom branch name in settings file

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/test-adapter.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
=> refactor: replace deprecated String.prototype.substr()

extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databaseFetcher.test.ts
Two small things I wanted to separate out from the main work for https://github.com/github/vscode-codeql/issues/1123:
- Rename `convertToDatabaseUrl` to `convertLgtmUrlToDatabaseUrl` (so we have space for a `convertGitHubUrlToDatabaseUrl` function in future)
- Make `promptForLanguage` accept a general array of languages instead of LGTM-specific metadata
cc @robertbrignull 
N/A - this is prep work for https://github.com/github/vscode-codeql/issues/1123.
=> Minor refactoring to support downloading GitHub databases

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/astViewer.ts, extensions/ql-vscode/src/contextual/astBuilder.ts, extensions/ql-vscode/src/contextual/templateProvider.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/astViewer.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/astBuilder.test.ts
This fixes a bug where the ast viewer was not updating its source
location when a user clicks on different parts of a file.
The problem was that the file name of the AST viewer was being stored as
a base name, which was getting compared with the full URI string of the
current file.
This fixes the comparison to ensure that the full URI strings are always
being compared.
Fixes #1224.
=> Fix invalid file comparison for changing ast viewer location

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/cli-version.ts, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/commandRunner.ts, extensions/ql-vscode/src/compare/compare-interface.ts, extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/pure/helpers-pure.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-serialization.ts, extensions/ql-vscode/src/quick-query.ts, extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/sarif-parser.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/databases.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/packaging.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/query.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/queryResolver.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/telemetry.test.ts, extensions/ql-vscode/test/pure-tests/helpers-pure.test.ts
The default version of tsc in vscode is now 4.5.4. This version
has changed the type of the variable in the catch block.
Previously, it was `any`. Now it is `unknown`.
This change updates vscode so that it can build with 4.5.4.
Previously, this had been a bit of a pain since sometimes running
a compile task in vscode will use the global default version of
tsc.
This is also a chance to try out the new dependency review workflow.
=> Update tsc to 4.5.5

extensions/ql-vscode/package.json, extensions/ql-vscode/src/cli.ts
This PR will make it so that the "Show Evaluation Log (Raw)" and "Show Evaluation Log (Summary)" commands in the query history view only if the CLI version is >2.9.0. Previously, the commands always showed regardless of CLI version, and the user received an error pop-up if their CLI checkout was an earlier version. Once this is merged to the appropriate base branch, this change will allow us to merge #1186 before CLI v2.8.4 is released.
=> Gate show eval log and summary commands behind CLI v2.8.4

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/messages.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/queryserver-client.ts, extensions/ql-vscode/src/run-queries.ts
Do not merge until the corresponding internal PR to the query server has been merged and the estimated version in this PR has been updated to match when we actually ship that.
This PR adds two new options to the Query History view:
1. _Show Evaluator Log (Raw)_ displays the raw JSON from the structured logs of a given query run.
2. _Show Evaluator Log (Summary)_ creates a human-readable summary of the structured logs and displays that.
=> Expose per-query structured evaluator logs

extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databaseFetcher.test.ts
Small follow-up to #1229. 
When downloading a GH database, you can now enter a GitHub URL as well as a "name with owner" (since this is slightly easier to copy-paste). I've used similar logic as the `looksLikeLgtmUrl` function. 
=> Allow GitHub URL as well as NWO

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts
Also, fix two smaller issues:
- Ensure the `Open Query Directory` command opens inside the specified
directory.
- Ensure label changes are saved across restarts.
Fixes #1204
=> Add query history sorting for remote queries

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json
This will fix a problem where settings sync will cause the cli not
to be found on codespaces.
Fixes https://github.com/github/vscode-codeql/issues/1251
=> Prevent cli path from being synced across remote instances

extensions/ql-vscode/src/remote-queries/sarif-processing.ts, extensions/ql-vscode/src/remote-queries/shared/analysis-result.ts, extensions/ql-vscode/src/remote-queries/view/FileCodeSnippet.tsx, extensions/ql-vscode/test/pure-tests/sarif-processing.test.ts
This reverts commit 006cc8c52a9ef4ed47e29b44c14468a1ddf5ca78.
Allows for SARIF that has regions but no code snippets.
=> Allow for undefined codeSnippets

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/pure/messages.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/queryserver-client.ts, extensions/ql-vscode/src/run-queries.ts
This change passes the `--end-summary=$eoq-evaluator-log.jsonl.summary` option to the CLI so that a separate file in the given location is written, with only the end-of-query summary information (most expensive predicate and timings). It then directly logs the contents of this file to the query server console.
It also changes the CLI version we gate all evaluator logs behind to 2.9.0 for simplicity. Otherwise, we would need to pass in one set of arguments to the CLI for 2.8.4 and another for 2.9.0. If in the future a user must be on a 2.8.x release and would like evaluator logs, we will be able to modify this for them easily.
This has been tested locally on VSCode (by modifying the CLI version expected to 2.8.3 and using the main checkout of the CLI) and works as we expect:
=> Print end-of-query summary logs to Query Server Console

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/helpers.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/index.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/packaging.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/query.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/run-remote-query.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/activation.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/config.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/index.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/qltest-discovery.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/astViewer.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/astBuilder.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/fileRangeFromURI.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/queryResolver.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databaseFetcher.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databases-ui.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/distribution.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/helpers.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/index.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-results.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/run-queries.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/run-remote-query.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/telemetry.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/test-adapter.test.ts
1. Source map support means that stack traces will point to the *.ts
file instead of the generated *.js file
2. Cleaning test dependencies means moving all mocha and chai
registration into the respective index files and removing unnecessary
imports.
Development only. No user facing changes.
=> Add source map support and clean test dependencies

extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/run-remote-query.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/remote-query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/repository-selection.test.ts
Some test files were already under a 'remote-queries' subdir but some weren't so I've moved everything.
N/A:
=> Move remote queries test files to be under remote-queries dir

.github/workflows/release.yml, extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json
The extension ms-vscode.test-adapter-converter is now available on
open-vsx, but under a different name.
Fixes https://github.com/github/vscode-codeql/issues/1085
I have verified that I can publish and install the extension by
manually publishing v1.6.4.
=> Reenable publishing to open-vsx

extensions/ql-vscode/package.json, extensions/ql-vscode/src/pure/location-link-utils.ts, extensions/ql-vscode/src/remote-queries/remote-queries-markdown-generation.ts, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/interpreted-results/data/analyses-results.json, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/interpreted-results/data/problem-query.json, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/interpreted-results/data/results-repo1.md, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/interpreted-results/data/results-repo2.md, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/interpreted-results/markdown-generation.test.ts
Eventually, users will be able to share results from variant analysis by linking to a generated markdown gist. We don't have the UX for this yet, so this just adds some backend functionality to generate markdown files for repos with results. The function isn't used anywhere yet, except in tests. You can see some example markdown output [here](https://github.com/github/vscode-codeql/blob/shati-patel/sharing-is-caring/extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/interpreted-results/data/results-repo1.md) and [here](https://github.com/github/vscode-codeql/blob/shati-patel/sharing-is-caring/extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/interpreted-results/data/results-repo2.md) 🖼️ 
See internal issue for details 👀 
Note: This just deals …
=> Create markdown files for sharing results

extensions/ql-vscode/src/remote-queries/remote-queries-markdown-generation.ts, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/interpreted-results/data/summary.md, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/interpreted-results/markdown-generation.test.ts
Follow-up to #1286. As well as generating individual markdown files for each repository, generate an overarching summary file. Example [here](https://github.com/github/vscode-codeql/blob/shati-patel/sharing-summary/extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/interpreted-results/data/summary.md) 🖼️ 
See internal issue for more info!
N/A - internal only 💌
=> Create markdown summary file for sharing MRVA results

extensions/ql-vscode/src/pure/sarif-utils.ts, extensions/ql-vscode/src/remote-queries/view/FileCodeSnippet.tsx
For sharing variant analysis results, we're building up a markdown copy of the results. See internal issue for more context!
I'd like to re-use the code that checks which sections of a code snippet to highlight in the results view, so I've moved it to a shared helper file 🤠
N/A - no visible changes
=> Split handling of highlighted code lines into helper function

extensions/ql-vscode/package.json, extensions/ql-vscode/src/compare/compare-interface.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/history-item-label-provider.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/query-serialization.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-query-history-item.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/history-item-label-provider.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-results.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/remote-query-history.test.ts
The labels for remote query items are interpolated using the same
strategy as local queries with two caveats:
1. There is no easy way to get the result count without reading files,
so, this value is kept empty.
2. There is no database name for remote queries. Instead, use the 
nwo of the controller repo.
=> Allow remote query items to have their labels edited

extensions/ql-vscode/gulpfile.ts/deploy.ts, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
This dependency was only used to parse package.json and
this can be just as easily parsed by regular JSON object.
jsonc can also parse JSON with comments, but there are no
comments in package.json.
See https://github.com/github/vscode-codeql/pull/1262
=> Remove jsonc dependency

extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databaseFetcher.test.ts
This will now name databases downloaded from github based on their nwo.
Also, this adds a new button to suggest downloading from github in an
empty databases view.
=> Display nicer names for github-downloaded databases

extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts
This fixes a bug where an open results view will accumulate results from
other queries who have their results downloaded while this view is open.
The fix is to ensure that the results view for the query is open when
some results are downloaded.
=> Avoid loading wrong results into an open window

extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/run-remote-queries.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/run-remote-query.test.ts
Two scenarios handled:
1. no database for existing repo
2. repo does not exits (or no access rights for current user)
In either case, an error message is sent to the logs, with a notificaiton
in a popup.
Log message looks like this:
```
Successfully scheduled runs. See https://github.com/dsp-testing/qc-run2/actions/runs/2164299232.
Some repositories could not be scheduled.
Invalid repositories: aeisenberg/xxx, other/idontexist
Repositories without databases: aeisenberg/actions-test, aeisenberg/actions-test2
```
=> Add better error messages for partial failing variant analysis

extensions/ql-vscode/src/remote-queries/view/CodePaths.tsx
=> Fix max-width for code paths

extensions/ql-vscode/package.json
I realized I had not opened a PR for this change. Previously, the options for showing raw evaluator logs and summaries only populated for full query runs but not quick evaluator runs. We discovered this was due to the [VSCode `when` clause](https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context) not supporting parentheses. This change is a quick fix to display the raw and summary logs for quick evaluation runs as well.
Note that I have not updated the CHANGELOG because these commands are gated behind CLI v.2.9.0, which is not yet released, so this should not affect any existing users.
=> Bug fix for evaluator log commands in query history view

extensions/ql-vscode/src/remote-queries/repository-selection.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/repository-selection.test.ts
We used to display 2 error/warning pop-ups if a user cancels out of selecting a repo for variant analysis 😅 See internal issue.
Instead:
- If a user just cancels without selecting anything, don't display a pop-up
- If a user enters an invalid repo, display a single pop-up
<details><summary>Expand for demo GIF</summary>
<p>
</p>
</details> 
N/A - internal only 🕳
=> MRVA: Be nicer about users cancelling out of the repository quickpick

extensions/ql-vscode/src/remote-queries/remote-queries-markdown-generation.ts, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/results-repo1.md, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/results-repo2.md, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/problem/analyses-results.json, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/problem/results-repo1.md, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/problem/results-repo2.md
A quick PR to remove some extraneous newlines in our markdown rendering! 🔪 (Because otherwise the code blocks looked huge) 
See [before](https://github.com/github/vscode-codeql/blob/1a03c0e4acc3a449b6e20ddc0e90c59d630273ba/extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/results-repo1.md) 😢 and [after](https://github.com/github/vscode-codeql/blob/b8fef48757f0a4090acbac731d317c757f3aff3a/extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/results-repo1.md) 😄 
N/A - internal only 🤭
=> MRVA: Make markdown code snippets look nicer

extensions/ql-vscode/src/remote-queries/remote-queries-markdown-generation.ts, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/analyses-results.json, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/results-repo1.md, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/results-repo2.md
_(based on #1312)_
Render path results in an expandable section (as shown in the example in the linked internal issue!) 
Click [here](https://github.com/github/vscode-codeql/blob/shati-patel/sharing-path-results/extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/results-repo1.md) for a cute rendered preview  🖼️ 
N/A - internal only 😄
=> Markdown rendering: Display paths

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
CLI version 2.9.0 is [released](https://github.com/github/codeql-cli-binaries/releases/tag/v2.9.0) 🎉 
N/A
=> Update CLI version used in tests

extensions/ql-vscode/src/pure/sarif-utils.ts, extensions/ql-vscode/src/remote-queries/remote-queries-markdown-generation.ts, extensions/ql-vscode/src/remote-queries/shared/analysis-result.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/raw-results/analyses-results.json, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/raw-results/query.json, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/raw-results/results-repo1.md, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/raw-results/results-repo2.md, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/raw-results/summary.md, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/markdown-generation.test.ts
First step towards rendering markdown for non-interpreted results (see internal issue).
This PR adds new test data and creates a summary file (example [here](https://github.com/github/vscode-codeql/blob/shati-patel/md-raw-result/extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/raw-results/summary.md)) 🖼️ 
I haven't yet added support for the rendering the actual results table (I'll do that in a follow-up PR 🔜 ) 
N/A - internal only 🔐
=> MRVA: Generate markdown summary for query with raw results

extensions/ql-vscode/src/remote-queries/view/FileCodeSnippet.tsx
Two small fixes!
- These file links now link to the specific highlighted section on GitHub, instead of the whole code snippet:  
- We now properly indent code snippets that use tabs 😇 
N/A - internal only 🦈
=> MRVA: Tweak code snippets and links in results view

extensions/ql-vscode/package.json
Allowed the "open on GitHub" action to cancelled/failed queries.
When a query fails, we set a value on the tree item to "cancelledResultsItem" (see [here](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/src/query-history.ts#L178)) - we then use that to decide whether to show the action or not. So the code could do with a bit of refactoring as it suggests that it only deals with cancelled queries, when in fact it deals with any failed queries. However, I won't be making that refactoring as part of this work.
N/A:
=> MRVA: Add open on GitHub action to cancelled/failed queries

extensions/ql-vscode/src/remote-queries/remote-queries-markdown-generation.ts, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/raw-results/analyses-results.json, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/raw-results/results-repo1.md, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/raw-results/results-repo2.md
Follow-up to #1318 for rendering raw results! This PR adds the actual table with results (see internal linked issue).
Some example rendered results [here](https://github.com/github/vscode-codeql/blob/shati-patel/md-raw-results/extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/raw-results/results-repo1.md) and [here](https://github.com/github/vscode-codeql/blob/shati-patel/md-raw-results/extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/raw-results/results-repo2.md) 🖼️ 🎨 
(It looks kinda ugly, but maybe that's mainly because these example results and column names are fairly meaningless 😂)
N/A - still internal only 🕳️
=> MRVA: Generate markdown for raw result tables

extensions/ql-vscode/src/remote-queries/remote-queries-markdown-generation.ts, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/results-repo1.md, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/results-repo2.md
Tweak the way we render path queries to display individual paths instead of the whole "show paths" section. (As suggested in internal linked issue 👀 )
Here is a [before](https://github.com/github/vscode-codeql/blob/ed84825e651bbb42ecd1106abe3e110ca8367ed1/extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/results-repo2.md) and [after](https://github.com/github/vscode-codeql/blob/24b84c7da06d90d5b5d1e9b1a5ea8723249cc209/extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/results-repo2.md)! 🖼️ 
N/A - internal only 🤠
=> MRVA: Expand path results individually

extensions/ql-vscode/src/remote-queries/remote-queries-markdown-generation.ts, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/markdown-generation.test.ts
We will need to support two types of links when generating markdown - gist links and local links. 
This PR adds support for both (but none are actually in use yet).
N/A:
=> MRVA: Support both local and gist links when generating markdown

extensions/ql-vscode/src/remote-queries/remote-queries-markdown-generation.ts, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/markdown-generation.test.ts
This PR updates the `MarkdownFile` type to include the filename as well as the file contents. This is so we can keep track of the filenames more consistently and link to them correctly, e.g. when uploading as a gist. _(Originally suggested in https://github.com/github/vscode-codeql/pull/1288#discussion_r847672799.)_
Note: there's no behaviour change here yet, I've just updated the existing functions/tests to work with the updated type. I will tweak the tests (to check that file name is expected) in a follow-up PR.
N/A - internal only 🦈
=> MRVA: Include filename when generating markdown files

.vscode/launch.json, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/telemetry.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/data/codeql-pack.lock.yml, extensions/ql-vscode/src/vscode-tests/cli-integration/databases.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/global.helper.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/index.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/packaging.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/run-cli.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/config.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/index.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/qltest-discovery.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/fileRangeFromURI.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/contextual/queryResolver.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databaseFetcher.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databases-ui.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/index.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/repository-selection.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/test-adapter.test.ts, extensions/ql-vscode/src/vscode-tests/run-integration-tests.ts, extensions/ql-vscode/test/pure-tests/sarif-processing.test.ts
The main problem this commit fixes is with vscode 1.67.0, an error is
thrown when inside of integration tests and a dialog box is opened. We
were opening the telemetry dialog box. Now, an env variable is set
during cli-integration tests that prevents the dialog from being
opened.
There are also other cleanups and improvements with cli-integration
tests that assist with running locally:
- `vscode-test` dependency has been renamed to `@vscode/test-electron`,
so use that instead and make the small API changes to support it.
- Commit the codeql-pack.lock.yml file so it isn't recreated on each
test run.
- Ensure all databases are removed before _and after_ each test run
that manipulates the set of installed databases
- Similarly, for quick query files, delete them before and after each
test.
- …
=> Fix cli-integration tests

extensions/ql-vscode/src/remote-queries/sarif-processing.ts
Tiny bug fix. When processing SARIF, we accidentally added some extra commas. Looks like this is because `.join()` uses commas as the default separator, instead of just concatenating the parts. I've changed the separator to be the empty string.
This was most visible in the MRVA results view when displaying paths. 
Before:
After: 
N/A - internal only 💅🏽
=> Remove unnecessary commas from alert `shortDescription`

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/export-results.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts
This is a follow-up to https://github.com/github/vscode-codeql/pull/1341#discussion_r870294911, to move the export functionality to a separate file (and avoid cluttering up `remote-queries-manager`).
I've also renamed the function to `exportRemoteQueryResults` so that we're at least being consistent with our incorrect naming 🙃  (All our internal functions still use "remote queries")
No behaviour change, just tidying!
N/A - internal only 🤘🏽
=> Move "exporting results" to a separate file

extensions/ql-vscode/package.json, extensions/ql-vscode/src/query-history.ts
Adds the "Export (variant analysis) results" command from #1341 to the query history menu for remote result items: 
This just executes the existing `codeQL.exportVariantAnalysisResults` command, which itself depends on information from the query history manager 🤔 This works, but feels like a slight circular dependency? (Other suggestions welcome, or maybe I'm just overthinking it 😄) 
N/A - internal only ⚔️
=> MRVA: Export results from query history menu

extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/view/ActionButton.tsx, extensions/ql-vscode/src/remote-queries/view/ExportButton.tsx, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
Adds a button to the webview that calls the "Export Results" command (from #1341). This makes the export functionality more discoverable:
I couldn't find an exact match for a Primer component (https://primer.style/react/Button wasn't quite right), so I copied the VS Code style. The button doesn't look _exactly_ like our design (padding/font look bit off), but it's close? 🤞🏽 😅 
N/A - internal only 🤫
=> MRVA: Add webview button to export results

extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/run-queries.ts
Previously, we were `await`ing the structured evaluator log summary to be fully generated before the query result and raw structured log could be viewed, even though they were already available.
This change allows the structured evaluator log summary to execute asynchronously. If the user attempts to click the "Show Structured Evaluator Log (Summary)" command on the query history item before the summary is complete, the user receives a popup saying "The evaluator log summary is still being generated. Please try again later. The summary generation process is tracked in the "CodeQL Extension Log" view." — 
The CodeQL Extension Log view will indicate the summary generation is in-progress and when it is complete. It will also log the same warning line as above every time the user attempts to …
=> Show query results before structured evaluator log summary completes

.github/workflows/main.yml, extensions/ql-vscode/src/authentication.ts, extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts, extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/shared/analysis-result.ts, extensions/ql-vscode/src/remote-queries/shared/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/src/remote-queries/view/SortRepoFilter.tsx, extensions/ql-vscode/src/remote-queries/view/StarCount.tsx, extensions/ql-vscode/src/remote-queries/view/remoteQueries.css, extensions/ql-vscode/src/vscode-tests/no-workspace/data/remote-queries/queries/MRVA Integration test 1-6sBi6oaky_fxqXW2NA4bx/query-result.json, extensions/ql-vscode/src/vscode-tests/no-workspace/data/remote-queries/queries/MRVA Integration test 2-UL-vbKAjP8ffObxjsp7hN/query-result.json, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/gh-actions-api-client.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/remote-query-history.test.ts
Sort by stars, number of results, and name.
This also includes a graphql query that retrieves all the stars
for relevant repositories.
Here is an example of what it looks like:
This PR also includes an integration test that ensures the graphql call to get the stargazers counts for each repo works.  I had to make a change to the credentials class to allow a way of instantiating based on an environment variable.
=> Add sorting to variant analysis results

extensions/ql-vscode/src/pure/time.ts, extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/view/LastUpdated.tsx, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/test/pure-tests/time.test.ts
Create the `time.ts` module as a place to put fime functions.
Move two time functions there and create tests for them.
The `humanizeUnit` function now uses ECMAscript apis. This ensures
that pluralization happens appropriately.
Also, fix a small bug in the results view to enure `repository`
is correctly pluralized.
=> Extract time functions

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/run-queries.ts
The new support will be available in the next
release of the CLI, ~most likely 2.9.3~, 2.10.0.
This change requires the query to be run to be
passed in to the call to resolve ml-models.
Not a user facing change.
=> Add new support for resolve ml-models

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/pure/helpers-pure.ts, extensions/ql-vscode/src/pure/time.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts
Moved time related constants out of `helpers-pure` and into `time`.
N/A:
=> Move time constants to time module

extensions/ql-vscode/src/pure/time.ts
Combine duplicate constants and unify naming.
N/A:
=> Combine time constants

extensions/ql-vscode/src/pure/bqrs-utils.ts, extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts, extensions/ql-vscode/src/remote-queries/bqrs-processing.ts, extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-queries-markdown-generation.ts, extensions/ql-vscode/src/remote-queries/remote-query-result-index.ts, extensions/ql-vscode/src/remote-queries/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/shared/analysis-result.ts, extensions/ql-vscode/src/remote-queries/shared/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/view/RawResultsTable.tsx, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/test/pure-tests/location.test.ts, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/raw-results/analyses-results.json
The MRVA action includes the `sourceLocationPrefix` in the result index. This PR updates the VS Code interface to use that prefix to construct links (instead of making a "best guess" based on the expected format). This is only used for raw (non-interpreted) results.
Main change is in https://github.com/github/vscode-codeql/commit/7b9e6a8effb57d08c34b4a0d4bb348f39b806ed2 (the other commits just pass `sourceLocationPrefix` around through various functions).
There shouldn't be any visible change, so I've tested this by running some queries and checking the resulting links. I've also updated the test data for markdown generation to use a `sourceLocationPrefix` for one of the repos, and the rendered links look fine there too.
See internal issue for more details.
N/A - internal only 🦒
=> MRVA: Get more accurate links using `sourceLocationPrefix`

CONTRIBUTING.md
Adding two things:
- A bit more detail on how to add a tag and how to delete a badly named one
- Switch to the official way of sharing tags according to the git docs [^1]
[^1]: https://git-scm.com/book/en/v2/Git-Basics-Tagging
=> Follow guidance for git tagging in contribution docs

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
We'd like to pave the way to upgrade from Node 16.13.0 (current version) to Node 18 (when VSCode decides to switch to it).
As we discovered in https://github.com/github/vscode-codeql/pull/1378, our build is currently breaking on Node 18 for two reasons:
- `source-map@0.7.3` does not work on Node 18
- our current version of `webpack` relies on OpenSSL for its hashing algorithm but OpenSSL is not supported by default from Node 17 onwards. While we can provide a legacy flag to revert to using OpenSSL in Node 18, this flag doesn't work with our current version of Node (16.13.0) and is actually re-activating insecure behaviour.
To address these issues we're:
- upgrading to `source-map@0.7.4` which has very recently been released and works with Node 18
- switch to a newer version of `webpack` …
=> Prepare for Node 18 upgrade

extensions/ql-vscode/src/pure/helpers-pure.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/repository-selection.test.ts
Turns out that repo names can include periods (e.g. https://github.com/mozilla/pdf.js)! This PR updates the regex for permitted repo names, so that we no longer throw an error: 
Note: There are possibly some restrictions around whether the period (or hyphen/underscore) can appear anywhere in the repo name or only in the middle. I don't think it's necessary to be that specific (especially because I don't know what the exact rules are 😄) 
N/A: This is currently only used in MRVA and for downloading databases from GitHub, both of which are still internal-only.
=> Allow repo names with periods

extensions/ql-vscode/src/remote-queries/view/CodePaths.tsx, extensions/ql-vscode/src/remote-queries/view/FileCodeSnippet.tsx, extensions/ql-vscode/src/remote-queries/view/RawResultsTable.tsx, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx
Since we're moving away from Primer, it makes sense to stop using `Box` for layout, so I've replaced usages of `Box` with simple `div`. 
BTW I noticed that we're using a mixture of ems and rems but I've decided to not touch that to allow minimal and straight-forward changes.
N/A
=> Remove use of Primer's box component

extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/run-remote-query.test.ts
Updates the MRVA log message and pop-up to include the number of repos that were scheduled (as requested from testers). We also include the list of repos in the logs, but this pop-up saves users from having to count them manually!
See internal linked issue.
N/A: internal only 💃🏽
=> MRVA: Include number of repositories queried in confirmation message

extensions/ql-vscode/src/remote-queries/view/DownloadSpinner.tsx
Another small migration from Primer to the VS Code UI toolkit.
To see this in action without running a whole query, replace `Completed` with `InProgress` on [this](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts#L148) line.
N/A:
=> Use VSCodeProgressRing instead of Primer's Spinner

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
CodeQL CLI v2.9.4 has been released 🥳 (See https://github.com/github/codeql-cli-binaries/releases/tag/v2.9.4)
N/A 😎
=> Bump CLI version used in integration tests

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/pure/bqrs-cli-types.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/run-queries.test.ts
Fixes two issues with CSV exporting and creates a unit test along with a generic framework for creating a mock CLI server. Commit-by-commit review is suggested.
Fixes https://github.com/github/vscode-codeql/issues/1377
Fixes https://github.com/github/vscode-codeql/issues/1376
=> Fix quoting of string columns in csv

extensions/ql-vscode/src/vscode-tests/cli-integration/global.helper.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/queries.test.ts
How did this ever work? It was using an old variant of the
qlpack name.
Also, this commit makes the unhandledRejection handler less
verbose. This gets hit when the tests end and there is a cancellation.
this is not an error.
@elenatanasoiu I hit some test failures when I was looking into your troubles this morning. I don't think this will fix what you've been seeing, but it's perhaps related.
=> Fix failing integration test

extensions/ql-vscode/src/remote-queries/run-remote-query.ts
The controller repo is set via the `codeQL.variantAnalysis.controllerRepo`
setting in VSCode.
While we have validation to check that the repo is not null and the
format of the controller repo is correct: `<owner>/<repo>`, we still
allow you to provide a non-existent repo (e.g. a mispelled one).
When the MRVA request is sent over to the API, it will verify that the
repo exists and return a very generic "Not Found" response.
This will then be logged out in the "Output" tab for VSCode.
We'd like to give users a better indication of what has gone wrong in
this case so we're making the error message more verbose.
=> MRVA: Improve experience when controller repo does not exist

CONTRIBUTING.md, extensions/ql-vscode/src/vscode-tests/cli-integration/global.helper.ts
In order to run our cli-integration tests, we're required to have a
local copy of the `github/codeql` repo. We can then run the tests by 
running the `Launch Integration Tests - With CLI` task from inside 
VS Code.
(See CONTRIBUTING.md for details.)
If we don't have the repo cloned locally or we're not pointing to it
in `launch.json`, we don't get a clear indication of what the problem is.
The tests will still attempt to run.
Let's fail fast instead and add an actionable error message to the output.
We're also updating `CONTRIBUTING.md` to make it a bit friendlier for 
newcomers.
=> Fail fast if codeql repo is missing from the workspace

extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/run-remote-query.test.ts
Handle when the MRVA API returns that some repositories were skipped because they are private and you are using a public controller repository. The API change to start returning this will also be made, but it should be safe to merge these changes in any order.
=> Show in log message when repos are filtered out for being private

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/remote-query-history.test.ts
Currently, the `RemoteQueriesManager` depends on the `QueryHistoryManager` and related models e.g. `QueryHistoryInfo`. This is a bit problematic because the `RemoteQueriesManager` ends up having knowledge about query history stuff and can receive events that are potentially for local queries. 
This PR inverts that dependency and makes `RemoteQueriesManager` a dependency of QueryHistoryManager. The `RemoteQueriesManager` is completely independent of query history and simply publishes events that the `QueryHistoryManager` can consume. I think this way makes more sense because the query history area **has** to be aware of local/remote queries, but remote queries don't have to necessarily be aware of the query history.
N/A
=> Refactor: Invert dependency between query history and remote quries managers

extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/shared/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/view/RemoteQueries.tsx, extensions/ql-vscode/src/remote-queries/view/RepoListCopyButton.tsx
Add the ability to easily create a new repository list from previous MRVA results. This is done by adding a copy to clipboard button in the results and history views.
N/A:
=> Add ability to create repo list from MRVA results

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/remote-queries/repository-selection.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/repository-selection.test.ts
Adds a new `repositoryListsPath` setting that allows users to define repository lists for MRVA outside of their settings.json file.
N/A:
=> Add ability to define repo lists in a file outside of settings

extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/run-remote-query.test.ts
The queries API is changing so that it won't fail when you try to run a query on more than 1000 repos. Instead it'll  cap the repos off at 1000 and tell you in the response which repos weren't queried (up to a limit of 100 repos).
This PR is for handling that change in the API and display the information in the log message. While there I also updated the log message in general to include the counts of the repositories in the various states. I think this makes it more consistent if we're including the count for the cutoff repositories case.
Any input on the wording of the log message is very welcome. Writing these messages is very hard 😢
=> Add cutoff repos and counts to error message

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
CodeQL CLI v2.10.0 is [released](https://github.com/github/codeql-cli-binaries/releases/tag/v2.10.0)! 🎉
=> Bump CLI version for integration tests

.github/workflows/main.yml
We officially only support the previous 4 minor versions of the CLI, so we can remove v2.3.3 to v2.5.9 from the tests 🧹 
N/A!
=> Remove older CLI versions from testing matrix

extensions/ql-vscode/src/remote-queries/view/FileCodeSnippet.tsx
Show the alert message, even if the location of a result isn't defined. See internal issue for details. I've also done some minor refactoring/renaming to make things easier to read.
Before:
After:
N/A:
=> MRVA: Display alert text even if location is undefined

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/quick-query.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/queries.test.ts
This ensures the pack lock file is in place after the quick query is generated.
Fixes a bug where quick queries cannot be compiled if the core libraries are not in the workspace.
=> Invoke `codeql pack install` after adding a quick query

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/run-queries.ts
Currently `resolve ml-models` only supports queryspecs, i.e. .ql, .qls, directory, and query pack specifications. However, a quick evaluation within a library will have a path ending in .qll, and currently the extension tries to call `resolve ml-models` on this path, logging an error message like this to the extension log:
```
[2022-06-29 10:15:25] Calling plumbing command: codeql resolve queries --additional-packs=/home/edoardo/semmle-code/ql --qlconfig-file=/home/edoardo/semmle-code/ql/qlconfig.yml --format startingpacks -- /home/edoardo/semmle-code/ql/cpp/ql/lib/semmle/code/cpp/internal/ResolveClass.qll
A fatal error occurred: /home/edoardo/semmle-code/ql/cpp/ql/lib/semmle/code/cpp/internal/ResolveClass.qll is not a .ql file, .qls file, a directory, or a query pack specification. …
```
=> Fix error messages in extension log when quick evalling library files with CodeQL CLI v2.10.0

extensions/ql-vscode/src/remote-queries/repository-selection.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/repository-selection.test.ts
We currently show a notification if a user presses "escape" after they selected to run a MRVA against a repo or an owner. This change removes that behaviour and leaves the user alone 😸 
N/A:
=> MRVA: Don't show notification if user aborts firing off a query

extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/run-remote-query.test.ts
Very minor, but the message `Successfully scheduled runs on 1 repositories.` has been bugging me for a while 😅
Just a bit of minor polish to pluralize (and singularize?) "repositories" appropriately! Happy to change if there are nicer ways of doing this 😀 
(Also fixes 2 unrelated typos while I'm here)
=> MRVA: Fix grammar in pop-up message

extensions/ql-vscode/src/remote-queries/view/CodePaths.tsx
Moves the `Source`/`Sink` label with to a VSCodeTag component. This is another step of the transition from Primer to the VS Code UI Toolkit. See internal linked issue for more details! 🎨 
Before:
After:
=>  Use `VSCodeTag`s instead of Primer `Label`s in webview

extensions/ql-vscode/src/remote-queries/view/CodePaths.tsx
Another step towards transitioning to the VS Code UI Toolkit! See internal issue for more details.
This PR replaces the dropdown in the "code paths" view with a more VS Code native one:
| Before 😿  |  After 😸 |
|--------|--------|
| ![F36A257D-A5E9-4A46-8AF1-FE93A909B028](https://user-images.githubusercontent.com/42641846/179027093-fadf4ac1-20e5-4edb-8e8f-7df22a88f15e.GIF) | ![72959120-8613-4E8D-9A17-660BDFDE4B06](https://user-images.githubusercontent.com/42641846/179027120-3f287bd5-3e6a-4561-9ea4-23b57aed935e.GIF) |
=> Replace code paths dropdown with VS Code UI Toolkit

extensions/ql-vscode/src/history-item-label-provider.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-query.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/history-item-label-provider.test.ts
Updates the default query history label for remote items to also include the language and number of repos queried. See internal issue for more details.
- Before: 
- After: (Note: old query items still say `xxx on <controller-repo>`, but new ones give the number of repos)
---------
- I'm not particularly happy about the different behaviour for older runs (i.e. using the controller repo name vs # repositories), but I couldn't see an obvious way to "backfill" the number of repos for older items 🤔 Happy for any suggestions!
- I've currently added the `(language)` to the end of the "query name" (`%q`) for remote queries. Do we want to make the `(language)` label a separate interpolated "thing" (e.g `%l`) or is this okay? 🔍 If we add it as a new interpolation option, we'd also need to handle it …
=> MRVA: Include more info in query history label

extensions/ql-vscode/src/remote-queries/export-results.ts, extensions/ql-vscode/src/remote-queries/shared/analysis-result.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/data/remote-queries/query-with-results/analyses-results.json, extensions/ql-vscode/src/vscode-tests/no-workspace/data/remote-queries/query-with-results/query.json, extensions/ql-vscode/src/vscode-tests/no-workspace/index.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/export-results.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/telemetry.test.ts
Depends on https://github.com/github/vscode-codeql/pull/1427 getting merged first so that we have access to query results.
All exported MRVA gists are given the name `CodeQL variant analysis results`, 
which makes it hard to work out what it contains at a glance.
We're adding more information in the gist title to make it useful.
Example of the new title:
`Empty Block (Go) x results (y repositories)`
This translates to:
`<query name> (<query language>) <number of results> results (<number of repositories> repositories)`
While we're here we're also adding a test for this functionality, as
there were no tests for the `export-results.ts` file.
We initially attempted to add the test to the pure-tests folder, but the
`export-results.ts` file imports some components from `vscode`, which
meant we …
=> Add useful information to MRVA gist titles

extensions/ql-vscode/package.json, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/history-item-label-provider.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/export-results.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-query-history-item.ts, extensions/ql-vscode/src/remote-queries/remote-query-result.ts, extensions/ql-vscode/src/remote-queries/remote-query.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/data/remote-queries/query-with-results/query.json, extensions/ql-vscode/src/vscode-tests/no-workspace/history-item-label-provider.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts
When you run a remote query, we'd like to display more information about
it in the Query History panel.
At the moment [we've improved this][1] by adding the language and number of repositories.
Here we're also adding the number of results for a remote query.
So the final format of the query history item will change from:
`<query_name> - <query_status>`
to
`<query_name> (<language>) on x repositories - <query_status>  (y results)`
While we're here we're also:
- changing local queries to display number of results in parentheses to match remote queries
- make remote queries sortable by number of results
[1]: https://github.com/github/vscode-codeql/pull/1427
=> Add result count to remote queries in Query History 

extensions/ql-vscode/src/remote-queries/export-results.ts
Fixes a minor bug in exporting results to Gist. For queries in your history that were run before #1431, the `repositoryCount` property is undefined, so the Gist description looks like:
```
Empty Block (go) 10 results ()
``` 
This PR updates that Gist description so that we don't show those empty parentheses.
=> MRVA: Fix Gist description when repository count is undefined

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
CLI v2.10.1 is [released](https://github.com/github/codeql-cli-binaries/releases/tag/v2.10.1) ✨
=> Bump CLI version to 2.10.1 for integration tests

extensions/ql-vscode/src/pure/log-summary-parser.ts
We were splitting JSONL records based on the current OS newline sequence. In order to handle reading of logs from the opposite OS, I've switched our split to handle both flavors of line ending. This originally showed up as log parser unit tests failing on Windows (the checked-in log used Unix line endings), but could affect real world usage as well.
=> Fix newline handling for cross-platform logs

extensions/ql-vscode/src/history-item-label-provider.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/history-item-label-provider.test.ts
We missed a place where we needed to check if results are present before attempting to show them.
=> Don't show parentheses when results are not yet fetched in Query History

extensions/ql-vscode/src/vscode-tests/no-workspace/telemetry.test.ts
This change adds a 50 ms waiting period in the `should request permission if popup has never been seen before` telemetry test. We believe the test is flaky due to the `ENABLE_TELEMETRY` value sometimes not propagating quickly enough before its value is checked in the test. 
- [N/A] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/code …
=> Add 50ms wait for flaky telemetry popup test

extensions/ql-vscode/src/query-history.ts
Very tiny fix, just spotted in passing! 🙈 
I've deleted the comment `In the future, we may support cancelling remote queries, but this is not a short term plan.`, since we do in fact support cancelling remote queries 😄 (as implemented [here](https://github.com/github/vscode-codeql/pull/1291/files#diff-cf43a74569f5e6eea483a9178f5de8fc372f8ca652017d3f1451dd2640876874R839-R848))
n/a
=> (Minor) Remove outdated comment

extensions/ql-vscode/src/query-history.ts
Added refreshing of the tree view (which in turn persists the query history data on disk) when a new remote query is added. See internal issue for bug repro steps and context.
N/A:
=> Ensure query history state is persisted after new query is added

extensions/ql-vscode/src/remote-queries/remote-queries-markdown-generation.ts, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/problem/analyses-results.json, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/problem/expected/_summary.md, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/problem/expected/meteor-meteor.md
Our MRVA markdown export uses HTML `<pre>` and `<code>` blocks to render code snippets. When the code snippet itself is HTML (or XML or similar), the snippet is treated as HTML instead of raw code. To fix this, we can escape certain HTML characters (such as `<`).
See internal linked issue for some examples and a bit more context! 🖼️ 
N/A - this is part of the internal variant analysis feature 🦺
=> Escape HTML characters when rendering MRVA results as markdown

extensions/ql-vscode/src/vscode-tests/no-workspace/telemetry.test.ts
This test is failing occasionally on our CI system. Let's see if this
change prevents the failures.
See https://github.com/github/vscode-codeql/pull/1449
=> Bump telemetry test timeout

extensions/ql-vscode/src/archive-filesystem-provider.ts, extensions/ql-vscode/src/cli.ts
Greatly improves #1065
In both these cases we have a cache initialised by a promise. However if we call the method again before the promise finishes we start another copy. This makes it so we cache the promise instead and only do the work once. I also applied the transformation it to `getVersion` as I noticed multiple calls to codeql to get the version as well (much less important as the codeql work is parallel to npm).
=> Improve startup time

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts
This adds the ability for users to download CodeQL databases from GitHub without the canary flag being set. Since this feature requires GitHub authentication, the "Authenticate to GitHub" command is now also available.
=> Remove canary requirement for GitHub database download

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
The latest version of webview-ui-toolkit contains a fix for long links. See https://github.com/microsoft/vscode-webview-ui-toolkit/issues/388.
Before:
After:
=> Upgrade webview-ui-toolkit version with long link fix

extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts
When the MRVA results panel is closed (so the panel gets disposed) and opened again, it would not load the MRVA data (such as whether a query has already been downloaded). This fixes it by also resetting the internal state of whether the panel is loaded when the panel is disposed.
=> Fix data not being loaded in MRVA results panel

extensions/ql-vscode/package.json, extensions/ql-vscode/src/remote-queries/run-remote-query.ts
This will improve the prompt for the controller repo by making clear that the GitHub Actions workflow will be run in the specified repo.
=> Improve prompot for controller repo

extensions/ql-vscode/src/abstract-interface-manager.ts, extensions/ql-vscode/src/compare/compare-interface.ts, extensions/ql-vscode/src/interface-utils.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts
This will add a new abstract class that implements the creation of the panel and webview to reduce duplication across the different interface managers.
=> Add abstract interface manager

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/extension.ts
Closes https://github.com/github/vscode-codeql/issues/1486
@aschackmull encountered a bug where after he'd rebuilt his CodeQL dist, he did _Restart query server_ so was running with a new query server, however was still using an old CLI because the CLI server had not been restarted. This led to a bug because the old CLI did not understand the evaluator logs produced by the new query server. The solution, I think, is for the extension to also restart the CLI server when it restarts the query server in order to ensure they are the same version.
=> Restart CLI server too when restarting query server

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/run-queries.ts
Two fixes, both serious regressions introduced by the "bad join order detection" feature.
See individual commit messages for details.
=> Check CLI version and fix race condition in join-order scanning

extensions/ql-vscode/gulpfile.ts/webpack.config.ts, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/abstract-interface-manager.ts, extensions/ql-vscode/src/interface-utils.ts, extensions/ql-vscode/src/remote-queries/remote-queries-interface.ts, extensions/ql-vscode/src/view/webview.tsx
This will include the Codicons inside the webview bundle, reducing the number of files that need to be loaded and the resource roots that need to be included.
The only place where a codicon is currently used is in the repository search bar for MRVA results.
=> Bundle Codicons using Webpack

extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts, extensions/ql-vscode/src/remote-queries/remote-queries-monitor.ts
It seems like the result-index artifact may not be available immediately after the workflow run has finished. This adds a retry mechanism to wait for the result-index to be available. It will retry at most 10 times with a wait of 1 second between each retry.
=> Add retry for finding result-index artifact

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/run-queries.ts, extensions/ql-vscode/src/upgrades.ts
We prompt for destructive upgrades once at the start of running multiple queries so the user doesn't get repeated prompts but with non-destructive they wouldn't any way and it would be worse. This also moves the version check to live with all the other version checks.
I pulled this out of #1498 because it isn't directly related.
=> Avoid prompting for upgrades when they wouldn't be prompted.

extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts
This will remove the query name from the query ID for MRVA queries to ensure we don't generate invalid directory names.
=> Remove query name from query ID for MRVA queries

extensions/ql-vscode/package.json, extensions/ql-vscode/src/query-history.ts
This will make a distinction between cancelled local and remote results, allowing us to hide the *Open Variant Analysis on GitHub* item from local failed/cancelled items. It also hides the *Show Evaluator Log* items for cancelled/failed remote queries.
Closes #1495
=> Remove open on GitHub item from cancelled local results

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
CLI v2.10.5 is [released](https://github.com/github/codeql-cli-binaries/releases/tag/v2.10.5) 🦄 🌈 ✨ 
N/A
=> Bump CLI version to 2.10.5 for integration tests

.vscode/settings.json
The working directory of ESLint was not set directly, so ESLint warnings did not show up in VSCode. This sets the working directory properly such that ESLint warnings are shown in VSCode.
See: https://github.com/Microsoft/vscode-eslint#settings-options
@charisk This should resolve the error you saw yesterday in VSCode.
=> Fix ESLint VSCode configuration

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/interface-utils.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-interface.ts, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/src/view/variant-analysis/index.tsx
Add a new variant analysis view that will support live results and will eventually replace the current remote queries view.
Mobbed with @koesie10 @robertbrignull and @shati-patel 
As part of this we:
- Added a new configuration setting to control whether to enable new variant analysis live result flows.
- Added a new web view that will be used to render the outcome of a variant analysis.
- Added a new command that will be used to easily load up the view with some mock data. The command will be removed when we have implemented the required functionality.
N/A - internal feature:
=> Add new variant analysis view

extensions/ql-vscode/src/compare/compare-view.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/remote-queries/remote-queries-view.ts, extensions/ql-vscode/src/view/compare/index.tsx, extensions/ql-vscode/src/view/remote-queries/index.tsx, extensions/ql-vscode/src/view/results/index.tsx, extensions/ql-vscode/src/view/variant-analysis/index.tsx, extensions/ql-vscode/src/view/webview-interface.ts, extensions/ql-vscode/src/view/webview.tsx
We currently have different message types for when a view is loaded. However, they're all handled in the same way. I've consolidated them all into one.
=> Consolidate view loading messages into one

extensions/ql-vscode/src/view/common/HorizontalSpace.tsx, extensions/ql-vscode/src/view/common/SectionTitle.tsx, extensions/ql-vscode/src/view/common/VerticalSpace.tsx, extensions/ql-vscode/src/view/common/ViewTitle.tsx, extensions/ql-vscode/src/view/common/index.ts, extensions/ql-vscode/src/view/remote-queries/CodePaths.tsx, extensions/ql-vscode/src/view/remote-queries/FileCodeSnippet.tsx, extensions/ql-vscode/src/view/remote-queries/RemoteQueries.tsx, extensions/ql-vscode/src/view/variant-analysis/QueryDetails.tsx
This moves the common React components between the remote queries and variant analysis views to a `common` directory, as discussed [here](https://github.com/github/vscode-codeql/pull/1512#discussion_r972764156).
=> Move common React components to separate directory

extensions/ql-vscode/src/pure/zip.ts, extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts
Started a new `zip` module to put utility functions around zipping/unzipping. I've only updated one location in the codebase to use it for now, other code can take advantage when its being changed.
N/A: Refactoring
=> Move zipFile util to its own module for easy re-use

extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts, extensions/ql-vscode/src/remote-queries/export-results.ts, extensions/ql-vscode/src/remote-queries/gh-api/gh-actions-api-client.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-queries-monitor.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/export-results.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/gh-api/gh-actions-api-client.test.ts
Moved the `gh-actions-api-client` into a `gh-api` subdir. We will soon have a few more files around calling the GitHub API so I think it's worth starting a subdir for them.
I've also noticed that the `gh-actions-api-client` also has logic around non-action stuff, but I'll leave that as a separate change.
N/A - refactoring.
=> Move GitHub Actions API client to gh-api directory

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/upgrades.ts
The `runUpgrade` query server command is mistakenly caching the old dbscheme in memory after running the upgrade. The problem is in the CLI. The workaround is to restart the query server after running an upgrade. This is not a great solution, but considering that explicit upgrades are now very rare. I do not think it is worth putting in too much effort for a proper fix.
=> Avoid error after upgrading a database

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
PR for v1.7.0 release.
Bumping to 1.7.0 because of two potentially breaking changes, though each is mitigated:
- Remove ability to download databases from LGTM.
- This is still available behind the canary flag, to be removed at a later date.
- Removed the ability to manually upgrade databases from the context menu on databases.
- This is still available in the command palate.
=> Release PR for v1.7.0

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/export-results.ts, extensions/ql-vscode/src/remote-queries/remote-queries-view.ts, extensions/ql-vscode/src/view/remote-queries/RemoteQueries.tsx
The "Export All" button was always exporting the selected query, while a different query could be open in a VSCode panel. This will ensure that the query ID is passed to the export function, so that the correct query is exported.
=> Fix "Export All" not always exporting the correct query

extensions/ql-vscode/src/stories/common/CodePaths.stories.tsx, extensions/ql-vscode/src/stories/common/FileCodeSnippet.stories.tsx, extensions/ql-vscode/src/view/common/CodePaths/CodePaths.tsx, extensions/ql-vscode/src/view/common/CodePaths/index.ts, extensions/ql-vscode/src/view/common/FileCodeSnippet/FileCodeSnippet.tsx, extensions/ql-vscode/src/view/common/FileCodeSnippet/index.ts, extensions/ql-vscode/src/view/common/index.ts, extensions/ql-vscode/src/view/remote-queries/AnalysisAlertResult.tsx
This moves the `CodePaths` and `FileCodeSnippet` components to the common directory since they will be reused by the live results view.
=> Move CodePaths and FileCodeSnippet to common directory

extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisHeader.stories.tsx, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisStats.stories.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisHeader.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisRepositoriesStats.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisStats.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisStats.spec.tsx
This will change the VariantAnalysisHeader to take the VariantAnalysis domain model instead of a large amount of props.
It also adds the `canceled` status to the `VariantAnalysisStatus` to represent a stopped variant analysis.
=> Use domain model for VariantAnalysisHeader

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/stories/.eslintrc.js, extensions/ql-vscode/src/view/.eslintrc.js
This will add the ESLint plugin for React hooks which will automatically check that all dependencies are listed in `useMemo`, `useEffect`, etc.
See: https://www.npmjs.com/package/eslint-plugin-react-hooks
=> Add ESLint plugin for React hooks

extensions/ql-vscode/src/log-insights/join-order.ts
I came across this when I had a query that threw an error while running for unrelated reasons. At this point, the query results were in a bad state, but this caused `safeMax` to be called with `undefined` and it prevented the extension from starting. This changed fixed the error.
=> Ensure `safeMax` is safe for undefined values

extensions/ql-vscode/src/stories/common/Alert.stories.tsx, extensions/ql-vscode/src/view/common/Alert.tsx, extensions/ql-vscode/src/view/common/__tests__/Alert.spec.tsx, extensions/ql-vscode/src/view/common/index.ts
This adds an `Alert` component which is able to show warnings and errors in the correct styles.
=> Add Alert component for showing warnings and errors

extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisLoading.stories.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisLoading.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisLoading.spec.tsx
Implements a component to show when the variant analysis submission is being processed. This component doesn't have any props as there's only state it needs to show. The decision on whether to show it or not based on the variant analysis status will be decided by the parent component.
Storybook screenshot:
See the internal issue for how it's meant to look. I've tried to copy the style as closely as possible but please do tell me if this could fit in better.
=> Add loading component

extensions/ql-vscode/src/remote-queries/run-remote-query.ts
The `controllerRepo` parameter was being encoded/escaped by Octokit, resulting in a URL like
`repos/dsp-testing%2Fqc-controller/code-scanning/codeql/queries` rather than `repos/dsp-testing/qc-controller/code-scanning/codeql/queries`.
This switches it to use the ID instead, since we already have the ID and do not have access to the owner and repo separately anymore.
=> Fix not being able to run variant analyses

extensions/ql-vscode/src/view/remote-queries/RemoteQueries.tsx
Currently, when running a query which produces raw results, we will show all repositories, even if they do not have any results. This change will ensure that we are only showing repositories which have results. This matches the behavior for queries which produce interpreted results.
=> Hide repositories with raw results without rows

extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts, extensions/ql-vscode/src/stories/remote-queries/data/rawResults.json, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisAnalyzedRepoItem.stories.tsx, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisAnalyzedRepos.stories.tsx, extensions/ql-vscode/src/view/common/icon/LoadingIcon.tsx, extensions/ql-vscode/src/view/common/icon/index.ts, extensions/ql-vscode/src/view/variant-analysis/AnalyzedRepoItemContent.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisAnalyzedRepoItem.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisAnalyzedRepos.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisOutcomePanels.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/AnalyzedRepoItemContent.spec.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisAnalyzedRepoItem.spec.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisAnalyzedRepos.spec.tsx
This adds the analyzed repositories component for showing within the "Analyzed" tab. I wasn't completely sure whether there should be a difference between "Pending" and "In progress", but pending will now not show an icon, while in progress will show a spinner.
For the collapsible items, it does not reuse the `CollapsibleItem` component because that component is tightly coupled with the styles of the remote queries component.
=> Add analyzed repositories component

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/gh-api/variant-analysis.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/remote-queries/shared/variant-analysis-monitor-result.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-monitor.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-processor.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/run-remote-query.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-monitor.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-processor.test.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/gh-api/scanned-repositories.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/gh-api/skipped-repositories.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/gh-api/variant-analysis-api-response.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/shared/variant-analysis-submission.ts
🚨 Please review this PR commit-by-commit.
Continues from a [previous PR](https://github.com/github/vscode-codeql/pull/1538) which introduced a way to submit new
variant analyses to the API.
Here we're creating a way to keep track of variant analysis results as
they become ready. To do this we're introducing a new 
`VariantAnalysisMonitor` class. This will poll the API every 5 seconds 
for changes to the variant analysis. By default it will continue to run for 
a maximum of 2 days, or when the user closes VSCode.
The monitor will receive a `variantAnalysis` summary from the API that
will contain an up-to-date list of scanned repos and will return a list of
scanned repo ids.
In a future PR, we'll add the functionality to:
- update the UI for in-progress/completed states
- raise an error on …
=> Implement monitoring for variant analysis live results 

extensions/ql-vscode/src/abstract-webview.ts, extensions/ql-vscode/src/extension.ts
The results view will always open next to the current editor.
This restores previous behaviour of the results view. Question: Do we want our other views to have the same behaviour? 
Previously, our users specifically asked for the results view to open in a way that would not block the currently active editor.
Fixes https://github.com/github/vscode-codeql/issues/1556
=> Ensure results view is opened in column beside 

extensions/ql-vscode/README.md
LGTM.com is due to be deprecated (https://github.com/orgs/community/discussions/29534) so this PR updates the readme for the new 'Download database from GitHub' feature.
See also https://github.com/github/vscode-codeql-starter/pull/132.
=> Remove mentions of lgtm.com from README

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-view.ts
This will open the variant analysis view after the variant analysis has been submitted. It will also show a notification that the analysis has been submitted, which includes the query name.
=> Open variant analysis view after submission

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases-ui.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/helpers.test.ts
Small fix that allows users to add databases even if the database root folder starts with `db-`.
Fixes https://github.com/github/vscode-codeql/issues/1561
=> Use better heuristics when checking db folders

.vscode/launch.json
I wasn't able to run the React/Jest unit tests from the Debug view (on Windows):
(Running the tests directly from the command line worked fine 🤷🏽 )
We found an existing issue and the potential solution in https://github.com/facebook/jest/issues/3750, so hopefully this will work here too!
N/A
=> Fix running Jest unit tests from the debugger on Windows

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/gh-api/gh-api-client.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-monitor.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/run-remote-query.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-monitor.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-processor.test.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/gh-api/variant-analysis-api-response.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/gh-api/variant-analysis-repo-task.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/shared/scanned-repositories.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/shared/skipped-repositories.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/shared/variant-analysis-submission.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/shared/variant-analysis.ts
🚨 Please review this PR commit-by-commit.
Follow-up from [this PR](https://github.com/github/vscode-codeql/pull/1545) where we introduced a monitor to check on the status of the variant analysis. 
We'd like to auto-download results from the variant analysis as they become ready. 
Based on a previous [discussion](https://github.com/github/vscode-codeql/pull/1545#discussion_r982591809) while implementing the variant analysis monitor, we decided that we'd like to trigger separate commands for actually downloading the results rather than performing it in the same process as the monitor.
The reason for this is that it would delay the polling and isn't really connected to what the monitor is supposed to do.
In a separate PR, we'll also change the monitor and manager in order to emit events to …
=> Download variant analysis results

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/remote-queries/gh-api/variant-analysis.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-monitor.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-processor.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-view-manager.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-view.ts, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-processor.test.ts
It's probably easiest to review this PR commit-by-commit.
This implements the `setVariantAnalysis` message, both in the extension host and in the webview. This will only send this message when the monitor retrieves a new variant analysis summary, but this should be extended in the future once we have a central place for managing variant analyses. Then, the view could receive the variant analysis message when the view is loaded (i.e. https://github.com/github/vscode-codeql/pull/1550/files#diff-29b0e9f4687addd3c5aaa5c980a9d079de9f0e1e804cd79aacf81f3239fcd2d1R50-R53).
I was able to test that this (merged in with `main` to open the view automatically) will open the view, show the incorrect data until the first poll returns data. When the polling has properly started, it will show the correct …
=> Implement `setVariantAnalysis` message

extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-view.ts, extensions/ql-vscode/src/stories/variant-analysis/RepoRow.stories.tsx, extensions/ql-vscode/src/view/variant-analysis/RepoRow.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisAnalyzedRepos.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisOutcomePanels.tsx
This implements a message for setting the download status and adds the code on the receiving side for the `setRepoResults` message.
Since there is no "manager" to keep track of actual download results yet and the results are not yet read, this does not implement sending the actual results to the webview.
It's easiest to review this PR commit-by-commit.
=> Implement message for setting download status

extensions/ql-vscode/.storybook/preview.ts, extensions/ql-vscode/package.json, extensions/ql-vscode/src/abstract-webview.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-view-serializer.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-view.ts, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysis.stories.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/src/view/vscode-api.ts
This implements persistence for the variant analysis webview, allowing the webview panel to be restored when VSCode is restarted. It's probably easier to add this now than to try to add it later.
The basic idea is that there are no real differences when opening the webview for the first time. However, when VSCode is restarted it will use the `VariantAnalysisViewSerializer` to restore the webview panel. In our case this means recreating the `VariantAnalysisView`.
To fully test this, I've also added a mock variant analysis ID as the state of the webview. This value is now randomly generated when calling the `codeQL.mockVariantAnalysisView` command. This allows us to test opening multiple webviews and that the webviews are restored with the correct state.
See: …
=> Restore variant analysis view on restart of VSCode

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-results-manager.ts, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisAnalyzedRepos.stories.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisAnalyzedRepos.spec.tsx, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-results-manager.test.ts
This adds a new variant analysis results manager which is responsible for downloading and loading variant analysis results to/from the filesystem. It is essentially the `AnalysesResultsManager` modified to suit the variant analysis results.
=> Add variant analysis results manager

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/run-remote-query.test.ts
When we first submit the variant analysis for processing, we'd like to update
the query history panel.
At the moment we're just adding the setup for triggering the event. In a future
PR we'll consume this event and change the query history panel accordingly.
In order for this second part to happen we will need to introduce a new 
`VariantAnalysisHistoryItem` type which will massage the data we get from the 
API into a type which the QueryHistory panel can consume.
=> Emit `variantAnalysisAdded` event

extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/run-remote-query.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-monitor.test.ts
This will change tests that are using a mocked `CancellationTokenSource` to use a real `CancellationTokenSource` instead. Tests are run inside VSCode, so we can use these without mocking.
=> Use real `CancellationTokenSource` in tests

extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx
It's probably easiest to review this PR commit-by-commit; these also contain some more detailed information about why certain things are necessary. In summary, on every rerender we were registering a new message listener. This would cause every message sent by the extension to trigger N+1 rerenders for the Nth render. The renders would look as follows:
1. 1 message listener, new listener registered. Total rerenders: 1
2. 2 message listeners, new listener registered. Total rerenders: 2
3. 3 message listeners, new listener registered. Total rerenders: 3
4. 4 message listeners, new listener registered. Total rerenders: 4
This would continue forever and would sometimes result in 10's of thousands of renders happening. This caused the live results view to be unresponsive until no more messages …
=> Fix freezing of live results view

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
CLI v2.11.1 is [released](https://github.com/github/codeql-cli-binaries/releases/tag/v2.11.1) 🎈 
=> Bump CLI version to 2.11.1 for integration tests

extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-view.ts, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx
This makes it possible to open the query file in the editor when clicking on the query filename.
This is a slightly different implementation from the remote queries implementation. The remote queries implementation will send the file path to open to the extension host, and the extension host will simply open the given file path. If someone is able to inject JavaScript into the webview, this would allow them to open an arbitrary file in VSCode.
By moving the file path logic to the extension host, we can ensure that we only allow opening the actual query file.
=> Add ability to open the query file

extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts
To make debugging the view easier and prevent needing to run a variant analysis for each change, this will add a simple command which opens a variant analysis by its ID. This it not intended to be visible to users at any point.
=> Add command for opening existing variant analysis

extensions/ql-vscode/src/databases.ts
A few users have been mentioning that databases are being removed upon restarting vscode. This PR adds some extra logging to help debug this situation.
Logging will look like this:
```
Initializing database manager.
Found 1 persisted databases: file:///Users/andrew.eisenberg/codeql-home/databases/db1
Initializing database panel.
Registering database panel commands.
...many more log messages...
Loaded database db1 at URI file:///Users/andrew.eisenberg/NonEclipse/codeql-home/databases/db1.
Finished loading persisted databases.
```
- [n/a] Issues have been created for any UI or other user-facing changes …
=> Add better logging while loading databases

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-content-provider.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-processor.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-view.ts, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisAnalyzedRepos.spec.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisOutcomePanels.spec.tsx, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-processor.test.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/shared/variant-analysis-submission.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/shared/variant-analysis.ts
This makes it possible to view the query text of a variant analysis. It adds the `queryText` property to the variant analysis and implements all necessary components to open a virtual file.
It's probably easiest to review this commit-by-commit.
=> Add ability to open the query text

extensions/ql-vscode/src/contextual/locationFinder.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/legacy-query-server/run-queries.ts, extensions/ql-vscode/src/query-history-scrubber.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/query-server/run-queries.ts, extensions/ql-vscode/src/run-queries-shared.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-results.test.ts
I'm making some changes to the query history, and spotted a few minor typos. I've pulled these out to this separate PR, to avoid cluttering up the "actual" changes later! Lots of changed files, but no actual impact 🤞🏽 
(PS: I double-checked the currently-open PR, and this shouldn't conflict with anything there)
=> Typo fixes in query history methods/properties

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/vscode-tests/cli-integration/index.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/index.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/index.ts, extensions/ql-vscode/src/vscode-tests/run-integration-tests.ts
The `vscode-test` package was renamed to `@vscode/test-electron` in December of last year. This commit updates the extension to use the new package name.
The reason for this change is that the `vscode-test` package was somewhat flaky in actually starting VSCode to run the tests from the command line. The new package also has some bugfixes and other improvements which would normally have been part of a new version of the `vscode-test` package.
See: https://github.com/microsoft/vscode-test/blob/main/CHANGELOG.md
=> Upgrade from vscode-test to @vscode/test-electron

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/global.helper.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/run-remote-query.test.ts, extensions/ql-vscode/src/vscode-tests/index-template.ts, extensions/ql-vscode/src/vscode-tests/test-config.ts
This will introduce a new helper that can be used to set config values in VSCode. Instead of the previous behaviour where it would retain the value after the tests had finished (resulting in e.g. the `codeQL.variantAnalysis.controllerRepo` setting being changed when you run the CLI tests from VSCode's Run and Debug menu), this will restore the value set by the user after finishing all tests. It will also set the value of specified config settings to a known value before each test.
It's probably easiest to review this PR commit-by-commit.
=> Reset VSCode configuration between tests

extensions/ql-vscode/src/vscode-tests/factories/local-queries/local-query-history-item.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/remote-query-history-item.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/history-item-label-provider.test.ts
We had some existing functions for creating a mock local query history item and a mock remote query history item. I plan to re-use those for some new `query-history-info` unit tests (see https://github.com/github/vscode-codeql/pull/1600#discussion_r995676466). This PR pre-emptively moves those helper functions into separate files in the `factories` folder.
=> Move helper functions (for creating mock query history items) to shared location

extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/index.ts
Also, add stub to logger in tests.
This fixes some occasionally failing tests on main.
=> `loadPersistedState` should happen outside of dbm constructor

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/vscode-tests/cli-integration/index.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/index.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/index.ts, extensions/ql-vscode/src/vscode-tests/run-integration-tests.ts
Reverts github/vscode-codeql#1586
If you look at every windows CLI test run after this change goes in, you can see that the CLI tests first fail with exit code 7, then an automatic retry kicks in.  It then fails with exit code 1, and retries. Finally, there is an exit code 0, but only because the tests don't actually run.
Example is here: https://github.com/github/vscode-codeql/actions/runs/3251885347/jobs/5338773016#step:9:292
=> Revert "Upgrade from vscode-test to @vscode/test-electron"

extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-monitor.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-monitor.test.ts
I believe this log entry was added for debugging purposes and should be removed - we don't want to flood the user's extension log with entries.
=> Remove debug log entry

.github/workflows/main.yml
We officially only support the previous 4 minor versions of the CLI, so v2.6.3 can go 🥲 (see https://github.com/github/vscode-codeql/pull/1410 for the previous clean-up PR)
(Since we've been dealing with some flaky tests lately, this seems like a good time to clean-up any unnecessary ones!)
=> Clean-up: Remove unsupported CLI version from testing matrix

extensions/ql-vscode/test/pure-tests/query-history-info.test.ts
Follow-up to #1600 and #1603. Adds tests for the `getRawQueryName` helper function. 
(Nothing particularly interesting yet, but once I've implemented more helpers for handling `QueryHistoryInfo`, I'll add tests for them here too!)
N/A - internal only 🍕
=> Add unit tests for `query-history-info`

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-monitor.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-monitor.test.ts
Previous attempt: https://github.com/github/vscode-codeql/pull/1584
In the existing remote queries implementation, we make use of batching when we download results. 
For the `variantAnalysisMonitor`, [we spin off](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/src/remote-queries/variant-analysis-monitor.ts#L76) the download part into its own command so that it doesn't hold up the monitor. 
Let's improve this further by batching download requests. This uses `p-queue` to add download tasks to a queue. We've configured the queue to only run three concurrent download requests at a time. The queue will wait for these to complete before starting new ones. 
Because the queue is stored on the `variantAnalysisManager`, we're able to keep adding new download tasks to it …
=> Download variant analysis results in batches - take two

extensions/ql-vscode/src/mocks/gh-api-request.ts
Paired with: @koesie10 
This adds some types that will be used for recording and replaying HTTP requests.
N/A - testing only.
=> Add GitHub API requests that will be mocked

extensions/ql-vscode/src/config.ts
Add new setting under `variantAnalysis` that allows using a mock GitHub API server. This setting could in theory be top level and not scoped to variant analysis, but it made sense to leave it scoped for now, since all the implementation will be targeting variant analysis.
Also added a config listener to help us detect changes and start/stop the server based on that. 
=> Add mock GitHub API server setting

extensions/ql-vscode/src/mocks/gh-api-request.ts
We were still missing the `SubmitVariantAnalysisRequest` type and a type to represent the union of all request types. This adds both of them.
=> Add missing request type for mock GitHub API

extensions/ql-vscode/src/query-history.ts
Adds the ability to open the query directory for a variant analysis history item. The "Open Query Directory" command in the query history context menu should now work for all kinds of history items 🎉 
❓ Note: I've left a question [inline](https://github.com/github/vscode-codeql/pull/1622#discussion_r998442728) about whether we need a `timestamp` file.
N/A - internal only 🐘
=> Implement "open query directory" for variant analysis history items

extensions/ql-vscode/src/query-server/run-queries.ts, extensions/ql-vscode/src/run-queries-shared.ts
This makes the new queryserver write the DIL to the DIL path which should make it work. It also fixes the error message to report the DIL location.
I can't get extension development to work currently so I can't test this so whoever reviews this should test it.
=> Fix missing DIL for new query server

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/mocks/mock-gh-api-server.ts, extensions/ql-vscode/src/mocks/recorder.ts, extensions/ql-vscode/test/pure-tests/command-lint.test.ts
This adds three commands for recording mock scenarios:
- "CodeQL Mock GitHub API Server: Start Scenario Recording"
- "CodeQL Mock GitHub API Server: Save Scenario"
- "CodeQL Mock GitHub API Server: Cancel Scenario"
The first one will only be visible when the setting is enabled and you are not yet recording. The latter two will only be visible when recording. On save, it will ask for a scenario save path and a name and will write all files to this directory.
=> Add recording of mock scenarios

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
[This PR](https://github.com/github/vscode-codeql/pull/1555) upgraded to the latest version of [husky](https://github.com/typicode/husky), but unfortunately it has broken our hooks.
In this PR, I'm reverting back to the original version used so that we can do the upgrade properly.
N/A:
=> Revert to previously used version of husky

extensions/ql-vscode/src/config.ts
Created a top level setting for `mockGitHubApiServer` and moved the two settings related to this inside it.
=> Restructure configuration around mock GitHub API

.github/workflows/main.yml, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/scripts/lint-scenarios.ts
This adds a linter for JSON scenario files which will validate the JSON files in the scenarios directory against the TypeScript types. It will convert the TypeScript types to JSON schema to simplify this process.
Unfortunately, this will not currently allow adding scenarios with failing requests since the types do not allow this. Rather than removing this validation, we should fix the types. This can be done in a follow-up PR.
=> Add linter for scenario files

extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/remote-query-history.test.ts
Copies remote queries rehydration implementation in remote-queries-manager to be used for variant analysis. Establishes an `onVariantAnalysisRemoved` for this.
=> Implement rehydration for variant analysis

extensions/ql-vscode/package.json
When the mock GitHub API server setting was moved to the top-level (https://github.com/github/vscode-codeql/pull/1643), we forgot the comamnds in the `package.json`. This updates the commands to have the correct visibility.
=> Fix scenario commands visibility

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/mocks/gh-api-request.ts, extensions/ql-vscode/src/mocks/mock-gh-api-server.ts, extensions/ql-vscode/src/mocks/request-handlers.ts, extensions/ql-vscode/src/pure/files.ts, extensions/ql-vscode/test/pure-tests/files.test.ts
Adds a command to load a mock scenario for the mock GitHub API server to replay.
N/A:
=> Add loading of mock scenarios

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts
This PR starts using QLX in the packs that are sent to MRVA. Sample run using this [here](https://github.com/edoardopirovano/vscode-codeql-starter/actions/runs/3311989032) which shows the QLX being picked up by MRVA. It would be nice to have an automated test too, but I wasn't sure where to include one: if someone more familiar with this part of the code has any suggestions I'd be keen to hear them.
cc. @hmakholm This code is mostly as you wrote it, with a couple of minor fixes.
=> MRVA: Use QLX to precompile queries

extensions/ql-vscode/src/mocks/request-handlers.ts
Updated the handlers created for replaying scenarios in the mock GitHub API server so that a single handler is used for each type of request. This is not required but I thought it would make things a bit more consistent.
=> Tidy up msw handlers used for scenario replay

extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/query-status.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/remote-query-history.test.ts
Update the state of a query history item when the status of the variant analysis has changed.
=> QueryHistory: Consume event when variant analysis status is updated

extensions/ql-vscode/src/mocks/gh-api-request.ts, extensions/ql-vscode/src/mocks/recorder.ts, extensions/ql-vscode/src/mocks/request-handlers.ts
This will store binary scenario bodies as files. It will create a separate file `4-getVariantAnalysisRepoResult.body.zip` for the request `4-getVariantAnalysisRepoResult.json` which contains the file. The request JSON will then refer to this file:
```json5
{
"request": {
"kind": "getVariantAnalysisRepoResult",
"repositoryId": ...
},
"response": {
"status": 200,
"body": "file:4-getVariantAnalysisRepoResult.body.zip",
"contentType": "application/zip"
}
}
```
There are some workarounds because msw for Node doesn't support seem to support binary response bodies, so we need to fetch the file separately instead.
It's probably easiest to review this commit-by-commit.
=> Store binary scenario bodies as files

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
CLI v2.11.2 is [released](https://github.com/github/codeql-cli-binaries/releases/tag/v2.11.2) 🎊 🥳 
N/A
=> Bump CLI version to 2.11.2 for integration tests

extensions/ql-vscode/src/query-history.ts
We decided to allow having multiple query history items for the same variant analysis. This PR ensures that all places in the code deal with this possibility. 
=> Allow multiple query history items for a single variant analysis

extensions/ql-vscode/src/query-history-info.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-history-item.ts, extensions/ql-vscode/test/pure-tests/query-history-info.test.ts
The query history item id is only used in [one place](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/src/query-history.ts#L1114-L1116) and in general we're not relying on uniqueness of query history items.
This PR removes `historyItemId` from variant analysis items. As part of that it also renames `getQueryHistoryItemId` to `getQueryId` as it now seems like a slightly more appropriate name. Open to suggestions though!
=> Remove historyItemId for variant analyses

extensions/ql-vscode/CHANGELOG.md
If the workspace is restarted while databases are being loaded, this change prevents any from being lost.
The bug was that each time a database was added when rehydrating a db from persisted state on startup, the persisted db list was being updated. Instead of updating the list each time we add a db, on restart, instead update the persisted list only after all are added.
Note that we need to update the persisted list after reading it in since the act of rehydrating a database _may_ change its persisted state. For example, the primary language of the database may be initialized if it was not able to be determined originally.
Fixes https://github.com/github/vscode-codeql/issues/1489
=> Fix bug where dbs are lost on restart

extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts
Makes it possible to open the variant analysis results view by single-clicking a query history item: 
See internal issue for context/related work 🔍 
N/A - internal only 🦈
=> Implement `openQueryResults` for variant analysis items

extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-results-manager.ts
Previous attempt: https://github.com/github/vscode-codeql/pull/1655
At the moment we have a no-op placeholder for when we try to remove 
a variant analysis from our query history.
This adds the actual implementation by:
- removing the item from the query history list
- cleaning up any existing result files attached to the variant analysis
NB: For remote queries, we would store all their results in a single folder.
For variant analyses, we store results per repo. The folder names are 
generated using a `cacheKey` which is built from the variant analysis ID and
the repo name. The resulting `cacheKeys` are stored in `cachedResults`.
Since we need to know the repo name when we want to delete a results 
folder,  we've had to pass in the full variant analysis object to the manager 
and call …
=> Implement `handleRemoveHistoryItem` for variant analysis history items - take two

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/run-remote-query.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts
At the moment we create the results manager as a private property on the `VariantAnalysisManager`. 
If we instead created it at the extension level and passed it to the `VariantAnalysisManager`, we would have more freedom to write unit tests for the `VariantAnalysisManager` without needing to reach into a private results manager property.
=> Decouple VariantAnalysisManager from VariantAnalysisResultsManager

extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts
This should fix a bug with opening variant analysis results from the query history. See internal issue!
N/A - internal only 🍌
=> Update `variantAnalyses` and view when "rehydrating" variant analyses

CONTRIBUTING.md
Add some initial documentation around using the mock GitHub API server.
N/A:
=> Add mock GitHub API server docs

extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts
We introduced this method in https://github.com/github/vscode-codeql/pull/1656 but didn't add tests.
Thanks to https://github.com/github/vscode-codeql/pull/1657 we can now add a test for this method without having to make the results manager a public property.
Aside from this:
- We are also introducing a helper method to return the size of `variantAnalysisManager.variantAnalyses`. This is something we can check in the test to be able to see the method is doing what it's supposed to without having to reach in and read the private `variantAnalyses` property.
- We've had to make `onVariantAnalysisUpdated` public in order to add a variant analysis in our test setup. This is a much smaller change in terms of privacy (and perhaps harmless?) since:
- we also have `onVariantAnalysisSubmitted` …
=> Add test for `removeVariantAnalysis`

extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts
We weren't updating the cache as soon as the variant analysis is submitted so I've updated to do that. I've also consolidated the logic into one function. 
=> Set in memory variant analysis on submission

CONTRIBUTING.md, extensions/ql-vscode/scripts/fix-scenario-file-numbering.ts
This is a rather hacky script I put together when collecting test data. I thought it might be useful for others in the future.
=> Add script to help with scenario recording

.vscode/launch.json, extensions/ql-vscode/.mocharc.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/mocks/mock-gh-api-server.ts, extensions/ql-vscode/src/mocks/vscode-mock-gh-api-server.ts, extensions/ql-vscode/test/mocha.setup.js, extensions/ql-vscode/test/pure-tests/remote-queries/gh-api/gh-api-client.test.ts, extensions/ql-vscode/test/tsconfig.json
This adds some really simple tests for the `gh-api-client` file to ensure that we can use msw mocks in pure tests.
=> Add msw tests for gh-api-client

extensions/ql-vscode/src/vscode-tests/no-workspace/data/variant-analysis/q0.ql, extensions/ql-vscode/src/vscode-tests/no-workspace/data/variant-analysis/q1.ql, extensions/ql-vscode/src/vscode-tests/no-workspace/data/variant-analysis/workspace-query-history.json, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/remote-query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/variant-analysis-history.test.ts
🚨 Please review this PR commit-by-commit.
We're repeating what we've done for the `RemoteQueryHistoryItem` tests for now.
Separately we'll think about setting up tests that check for both remote queries and variant analysis in the query history.
At the moment we'd like to focus on just adding some test coverage for `VariantAnalysisHistoryItem`.
=> Add tests for variant analysis history item

extensions/ql-vscode/src/abstract-webview.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts
This will close the variant analysis view when the corresponding variant analysis history item is deleted from the query history. This required some extra code to handle `dispose` being called on the view to ensure this actually disposes the panel, but we can now call `dispose()` on the view to close it.
=> Close view when variant analyis is deleted from query history

extensions/ql-vscode/src/abstract-webview.ts, extensions/ql-vscode/src/compare/compare-view.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/remote-queries/remote-queries-view.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-view.ts
This sets the title of the variant analysis view to `{queryName} - CodeQL Query Results`. It does so by retrieving the variant analysis in the `getPanelConfig` method and updating the title whenever the variant analysis is updated.
It's probably easiest to review this commit-by-commit. The actual change for setting the view title is quite small, but we first need to allow `getPanelConfig` to return a promise.
=> Set variant analysis view title to query name

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts
Added new database panel that will be used for the new query run experience. 
The panel is currently empty and is hidden behind a config setting (`codeQL.newQueryRunExperience`).
Paired with @shati-patel. 
=> A new experimental database panel

extensions/ql-vscode/src/query-history-info.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-monitor.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-processor.ts, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysis.stories.tsx, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisAnalyzedRepos.stories.tsx, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisHeader.stories.tsx, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisOutcomePanels.stories.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisAnalyzedRepos.spec.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisOutcomePanels.spec.tsx, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-processor.test.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/shared/variant-analysis.ts, extensions/ql-vscode/test/pure-tests/query-history-info.test.ts
See the two separate commits: this adds the `controllerRepo` to the shared `VariantAnalysis` type and then uses it for constructing the actions workflow run URL.
=> Add opening on GitHub of live results variant analyses

extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/query-history-info.ts, extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-view.ts, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/test/pure-tests/variant-analysis.test.ts
This will hook up the "View logs" link to make it open the variant analysis actions workflow run. The method for creating the actions workflow run URL has been extracted from the query history to make it callable without a history item.
=> Open Actions workflow run when clicking on "View logs"

extensions/ql-vscode/src/remote-queries/export-results.ts, extensions/ql-vscode/src/remote-queries/gh-api/gh-actions-api-client.ts, extensions/ql-vscode/src/remote-queries/gh-api/gh-api-client.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/export-results.test.ts
The `createGist` function was part of `gh-actions-api-client`, while it didn't actually involve anything related to the GitHub Actions API. This moves it to the non-Actions-specific `gh-api-client` module.
Another candidate for moving to `gh-api-client` is `getRepositoriesMetadata`, but that one is a bit more involved since it uses `showAndLogErrorMessage`, so depends on the `vscode` module. This means it would not be possible to test in the "pure" tests and we would need to move all our `gh-actions-api` tests to the integration tests. It will not be used for variant analysis queries anymore, so I don't think it's worth moving or refactoring to not depend on `vscode`.
=> Move `createGist` to `gh-api-client`

extensions/ql-vscode/src/extension.ts
We have a problem that rehydrating the query history can lead to triggering the `codeQL.monitorVariantAnalysis` command.  This is a problem because we start loading the query history before we register the `codeQL.monitorVariantAnalysis` command with the extension. This leads to the following error:
```
Activating extension 'GitHub.vscode-codeql' failed: command 'codeQL.monitorVariantAnalysis' not found
```
So this PR moves the query history loading to be right at the end of the extension-loading process. I've confirmed locally that doing this allows me to open the extension when there is a variant analysis in progress.
Is there any problem of moving this to be the last thing in the method? @aeisenberg, do you have any thoughts?
=> Move loading query history to after registering commands

extensions/ql-vscode/package.json
This takes down the feedback loop from 5-10 seconds to half a second since we're not running through the setup for minimal workspace tests.
=> Introduce command to run no-workspace tests separately

extensions/ql-vscode/src/remote-queries/shared/variant-analysis-monitor-result.ts, extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-monitor.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-processor.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-monitor.test.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/gh-api/variant-analysis-api-response.ts
This PR aims to make the variant analysis monitoring command able to handle all states and also be slightly cleaner in its logic. I don't think any of the changes in this PR are critical, but I think they are all improvements.
The changes made are:
- Instead of firing `_onVariantAnalysisChange` from three different places under various conditions, fire it from one place and always fire it in every loop right after getting the updated variant analysis summary.
- I'm not sure why we fired the event before the loop. This is before we fetched the new updated state so we're just emitting the old state that the monitor was passed when it started up. In the case of rehydrating query history this state could be very old. My only thought is that it's to ensure that the event always fires at least …
=> Make the monitoring command slightly simpler and handle being called on any variant analysis

extensions/ql-vscode/src/remote-queries/remote-queries-markdown-generation.ts, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/analyses-results.json, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/expected/github-codeql.md, extensions/ql-vscode/test/pure-tests/remote-queries/markdown-generation/data/interpreted-results/path-problem/expected/meteor-meteor.md
This PR fixes the markdown export for remote query results. Previously, paths with more than 100 steps had their code snippets badly indented, which caused the markdown to render badly on GitHub Gists. 
I've changed the indentation to match the length of the list number, and updated tests to check this variable indentation size.
N/A - this is a private beta feature. See internal issue for more details!
=> Fix indentation in exported markdown results

extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts
Awaiting a command means it waits for the command to finish and gives you its return value. We don't want that in this case because the monitoring command takes a long time.
=> Don't await the monitoring command

extensions/ql-vscode/src/history-item-label-provider.ts, extensions/ql-vscode/src/query-status.ts, extensions/ql-vscode/src/vscode-tests/factories/local-queries/local-query-history-item.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/remote-query-history-item.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/variant-analysis-history-item.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/history-item-label-provider.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history-info.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts, extensions/ql-vscode/src/vscode-tests/utils/query-history-helpers.ts
🚨 Please review this PR commit-by-commit.
This PR holds part of the clean-up work to allow us to write more tests for the `QueryHistoryManager` and `HistoryTreeDataProvider` by re-organising tests to make it clear what they're checking and removing
some duplication in the process. This unfortunately results in a lot of noisy diffs as I shuffle things into 
`describe` blocks.
We're also changing part of these tests to work with `RemoteQueryHistoryItem`s and 
`VariantAnalysisHistoryItem`s, instead of just testing local query history items.
The query history now has increased test coverage in terms of how items of different types interact
together, specifically:
- handling an item being clicked / double clicked
- ~~removing and selecting an item~~ this has been reverted, see …
=> Make query history tests work with remote queries & variant analyses

extensions/ql-vscode/src/query-history.ts
We were trying to show the "Open variant analysis on github" link before we knew what the actions workflow run ID was, and therefore we were generating links like https://github.com/dsp-testing/qc-controller/actions/runs/undefined
See the individual commits on this PR. The first does some drive-by recfactoring and then the second commit actually implements the change in behaviour. I've tested it manually and it seems to be working as expected.
I went with just pulling `getIconPath` and `getContextValue` out to methods in `query-history.ts` because they unfortunately have references to instance variables and to imports from `vscode`. Otherwise I would have moved them to `query-history-info.ts`, but maybe we can do that in the future. For this PR I just wanted to make an improvement and not …
=> Don't show "open on github" link when we don't yet have anything to show

extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysis.stories.tsx, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisAnalyzedRepos.stories.tsx, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisHeader.stories.tsx, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisOutcomePanels.stories.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisAnalyzedRepos.spec.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisOutcomePanels.spec.tsx, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-monitor.test.ts, extensions/ql-vscode/src/vscode-tests/factories/local-queries/local-query-history-item.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/remote-query-history-item.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/shared/variant-analysis.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/variant-analysis-history-item.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/history-item-label-provider.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history-info.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts, extensions/ql-vscode/test/pure-tests/variant-analysis.test.ts
🚨 Please review this commit-by-commit.
This is a follow-up to https://github.com/github/vscode-codeql/pull/1688 where we first started converting our query history tests to check all types of history items instead of just local query ones. 
In order to test sorting with local queries, remote queries and variant analyses, we've had to make a few changes:
1. Allow `createMockVariantAnalysis` and `createMockVariantAnalysisHistoryItem` to receive named params so that we can set `resultCount` and `executionStartTime`. We need this in order to test sorting by result and date.
2. We do the same for `createMockRemoteQueryHistoryItem`.
3. We're combining the two existing factory methods for creating a `LocalQueryInfo` into a single `createMockLocalQueryInfo` method.
4. For …
=> Make sorting tests work with remote queries & variant analysis history items

extensions/ql-vscode/src/databases/ui/db-tree-data-provider.ts, extensions/ql-vscode/src/databases/ui/db-tree-view-item.ts
Co-authored-by: Charis Kyriakou <charisk@users.noreply.github.com>
We want to show an error to the user in case the workspace databases file is corrupted. As a proof of concept this PR adds a sample error to the panel.
=> Introduce error in new db panel

extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/gh-api/gh-actions-api-client.ts, extensions/ql-vscode/src/vscode-tests/factories/local-queries/local-query-history-item.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/shared/variant-analysis.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/gh-api/gh-actions-api-client.test.ts
This makes it possible to cancel a variant analysis from the query history by right-clicking on it. This will trigger a request to the GitHub API to cancel the workflow run. Once that happens, the variant analysis will be updated via the monitor with a `canceled` state.
NB: We only attempt to cancel if the item is in progress. 
While we're here we're also adding tests for cancelling local queries and remote queries.
=> Implement query history "cancel" option

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-monitor.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-processor.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-results-manager.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-monitor.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-results-manager.test.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/shared/variant-analysis-repo-tasks.ts, extensions/ql-vscode/test/pure-tests/remote-queries/variant-analysis-processor.test.ts
This removes all usages of the `gh-api` types from the variant analysis code by replacing it by the same types defined in `shared`.
This is a breaking change for the query history since the files serialized to disk now also change. However, since this is still behind a feature flag the change should be safe to make now.
=> Remove `gh-api` usage from variant analysis code

extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/src/databases/db-tree-creator.ts, extensions/ql-vscode/src/databases/ui/db-item-mapper.ts, extensions/ql-vscode/src/databases/ui/db-tree-data-provider.ts, extensions/ql-vscode/src/databases/ui/db-tree-view-item.ts, extensions/ql-vscode/test/pure-tests/databases/db-tree-creator.test.ts
Adds some logic to create and render db tree view items based on the user's db config file. Currently only deals with remote dbs.
=> Create remote db tree view items based on the user's db config

extensions/ql-vscode/package.json, extensions/ql-vscode/src/databases/db-config-store.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/test/pure-tests/command-lint.test.ts
Adds a UI icon in the new databases panel to open the `workspace-databases.json` config file.
~Note: I couldn't quite decide whether to call the command `codeQLDatabases.openConfigFile` or `codeQLDatabasesExperimental.openConfigFile`, so I've gone with the former for now. (Which saves us from adding a case to the [command-lint](https://github.com/github/vscode-codeql/blob/93054e14a27f2001dac4b6230fe2b47870d31aa6/extensions/ql-vscode/test/pure-tests/command-lint.test.ts#L30-L53) test.) Happy to switch over again though~ 🤷🏽 😅  EDIT: switched to `codeQLDatabasesExperimental`.
See internal linked issue for more details!
N/A - internal only 📝
=> Add button to open database config from the new databases UI

.github/workflows/codeql.yml, .github/workflows/main.yml, .github/workflows/release.yml
`set-output` is deprecated:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Uses newer actions versions and avoids `set-output`

extensions/ql-vscode/package.json
It seems like the expansion of the test files pattern is different between Windows and Linux/macOS. This fixes it by allowing Mocha to expand the glob pattern rather than the shell which should fix the inconsistency.
=> Run all unit tests on Linux/macOS

extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysis.stories.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisOutcomePanels.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisOutcomePanels.spec.tsx
The variant analysis view was missing an alert when the variant analysis was canceled. This adds it, and also adds a story for checking what the view of a canceled variant analysis looks like.
=> Handle canceled status in variant analysis view

extensions/ql-vscode/src/vscode-tests/cli-integration/queries.test.ts
This tests occasionally times out during setup. This change attempts to avoid this problem by increasing the max length of the test.
@elenatanasoiu this fix might be an alternative to https://github.com/github/vscode-codeql/pull/1695.
- [n/a] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add …
=> Bumps timeouts in tests

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/contextual/locationFinder.ts, extensions/ql-vscode/src/contextual/queryResolver.ts, extensions/ql-vscode/src/contextual/templateProvider.ts
If the library pack containing the AST query does not have a lock file, it is likely to be in the package cache, not
a checkout of the CodeQL repo.
In this case, use `codeql pack resolve-dependencies` to create a temporary lock file, and `codeql pack install`
to install the dependencies of this library pack.
This allows the CLI to resolve the library path and dependencies for the AST query before running it, in the use case where the standard library packs are installed in the package cache rather than present in the workspace. Otherwise, in the absence of a lock file, `codeql resolve library-path` finds the standard library pack that contains the AST query, but not the `codeql/ssa` shared pack that this library pack depends on.
- I've tried to keep this change minimal so that it doesn't …
=> Contextual queries: Support running when the library pack is in the package cache

extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisOutcomePanels.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisOutcomePanels.spec.tsx
This uses the correct title and message for all warnings currently supported.
=> Update messages for variant analysis warnings

extensions/ql-vscode/src/stories/variant-analysis/RepoRow.stories.tsx, extensions/ql-vscode/src/view/variant-analysis/AnalyzedRepoItemContent.tsx, extensions/ql-vscode/src/view/variant-analysis/RepoRow.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/AnalyzedRepoItemContent.spec.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/RepoRow.spec.tsx
We were not yet showing any errors when a result download had failed. This adds a warning icon to any repositories for which the download has failed and allow expanding the item to show an alert.
=> Handle failed result download in view

extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/README.md, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts
Adds some initial integration tests for the new db panel area.
=> Add some integration tests for the db panel

extensions/ql-vscode/src/databases.ts
The argument doesn't seem to be used anywhere so I've deleted it.
N/A:
=> Remove unused method argument

extensions/ql-vscode/src/remote-queries/run-remote-query.ts
There is some common logic between remote queries and the variant analysis flows which deals with parsing the query and asking the user how to run the query. This extracts that part of the logic to a separate method such that the only logic left in the actual `runRemoteQuery` method is related to submitting the query.
=> Extract remote query preparation to separate method

extensions/ql-vscode/src/pure/date.ts
This will make the date format more consistent, and will ensure that ['date.test.ts'](https://github.com/github/vscode-codeql/blob/03e48b7ae0c0a1f23b0ab43251b763a2b02b17b7/extensions/ql-vscode/test/pure-tests/date.test.ts#L8-L9) doesn't depend on your system's locale. 
⏲️ See internal issue for more context! 📆 
No user impact 🦏
=> Fix date format to 'en-US'

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/remote-queries/gh-api/gh-api-client.ts, extensions/ql-vscode/src/remote-queries/gh-api/remote-queries.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/remote-queries/shared/remote-queries.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/run-remote-query.test.ts, extensions/ql-vscode/src/vscode-tests/utils/bundled-pack-helpers.ts
The remote queries tests were testing the data on the filesystem, rather than the data submitted to the server. This required using a `dryRun` parameter to prevent deleting the temporary directory, while we can actually just test against the submitted data.
This will create an in-memory filesystem of the submitted query pack by un-tar-gz'ing the query pack into memory and using that to test the existence of certain files.
=> Change remote queries to test against submitted data

extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/run-remote-query.test.ts
This removes the `dryRun` parameter from the `runRemoteQuery` parameter since the tests don't use the dry run anymore (since #1746).
=> Remove `dryRun` parameter from `runRemoteQuery`

extensions/ql-vscode/src/remote-queries/run-remote-query.ts
Now that we do not have a dry run mode, we can create and clean up the temporary directory in the same function. This allows us to remove the complete `try`..`finally` block inside `runRemoteQuery` and move it to a much more local spot.
It's easiest to review this by hiding whitespace, this should only show the actual changes.
=> Reduce nesting in `runRemoteQuery`

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
CLI v2.11.3 is [released](https://github.com/github/codeql-cli-binaries/releases/tag/v2.11.3) 🎊 🥳 
N/A
=> Bump CLI version to 2.11.3 for integration tests

extensions/ql-vscode/src/common/app.ts, extensions/ql-vscode/src/common/events.ts, extensions/ql-vscode/src/common/vscode/events.ts, extensions/ql-vscode/src/common/vscode/vscode-app.ts, extensions/ql-vscode/src/pure/disposable-object.ts
Currently, classes/modules that interact with events (raising or catching) have to import [Event](https://code.visualstudio.com/api/references/vscode-api#Event%3CT%3E)/[EventEmitter](https://code.visualstudio.com/api/references/vscode-api#EventEmitter%3CT%3E) which couples them to the VS Code API and as a consequence it means we're no longer able to write unit tests. It pushes us towards writing slow integration tests that require the whole extension host. 
This PR introduces some custom abstractions that we can use instead of bringing in the VS Code API. 
N/A:
=> Add event emitter abstraction

extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-view.ts, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx
This will allow a user to use the "Copy repository list" button in the view to copy a repository list.
=> Add copying of repository list to view

extensions/ql-vscode/src/databases/db-config-store.ts, extensions/ql-vscode/src/databases/db-config.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts, extensions/ql-vscode/test/pure-tests/databases/data/workspace-databases.json, extensions/ql-vscode/test/pure-tests/databases/db-config-store.test.ts, extensions/ql-vscode/test/pure-tests/databases/db-config-validator.test.ts, extensions/ql-vscode/test/pure-tests/databases/db-tree-creator.test.ts, extensions/ql-vscode/workspace-databases-schema.json
Adds support for local databases the config for the new databases panel. Note: this only changes the config - we don't yet render the local items (that's a follow-up issue).
See internal issue for context!
N/A - internal only 🖌️
=> Add support for local dbs in config

extensions/ql-vscode/src/common/app.ts, extensions/ql-vscode/src/common/vscode/vscode-app.ts, extensions/ql-vscode/src/databases/db-config-store.ts, extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/src/vscode-tests/factories/extension-context.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts, extensions/ql-vscode/test/__mocks__/appMock.ts, extensions/ql-vscode/test/pure-tests/databases/db-config-store.test.ts, extensions/ql-vscode/test/tsconfig.json
Added some information typically retrieved from the extension context, to our new App container and updated the `DbConfigStore` to use this new App container.
N/A:
=> Add extension and storage paths to App container

extensions/ql-vscode/src/databases/ui/db-tree-view-item.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts
This reverts commit 93b6abeeb4657bbd756ee8807e870b8769182ff0 which has broken the icons in the db panel.
I forgot that we have to use the same name as `vscode.TreeItem`s! 🤦‍♀️ 
N/A:
=> Revert "Rename iconPath to icon"

extensions/ql-vscode/src/common/app.ts, extensions/ql-vscode/src/common/vscode/vscode-app.ts, extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/test/__mocks__/appMock.ts
Adds two more pieces of information to the App container:
- The mode we're running in
- Any subscriptions for objects that need to be disposed.
I then took advantage of that in the `DbModule`. I also released that we were registering the `DbPanel` to be disposed twice so I removed that (see second commit).
N/A:
=> Add mode and subscriptions to App container

extensions/ql-vscode/src/mocks/mock-gh-api-server.ts
Currently we see unhandled requests logged in the debug console which seems to cause confusion so we should turn that off.
N/A:
=> Stop showing warnings for unhandled requests by the mock API server

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/config.ts
The new query server is no longer experimental. Enable it by default. We do not remove the old query server code for 2 reasons:
1. We need to support older versions of the CLI
2. We want to give a back door and allow users to explicitly opt-out of the new query server if there is ever a problem.
This is an internal change and does not require a change note.
=> Enable the new query server by default

extensions/ql-vscode/test/tsconfig.json
Turns out [`rootDirs`](https://www.typescriptlang.org/tsconfig#rootDirs) is to do with virtual directories so we should be using [`rootDir`](https://www.typescriptlang.org/tsconfig#rootDir) instead😅 
N/A:
=> Fix rootDir used in test tsconfig

extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts
The `codeQL.openVariantAnalysis` was only intended to be temporary until we had implemented query history for live-result variant analyses. We want to remove it now before we start looking at releasing live results.
=> Remove the openVariantAnalysis command

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/pure/variant-analysis-filter-sort.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisAnalyzedRepos.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/filterSort.spec.ts
This will use the selected repositories to limit which repositories are included in the copied repo list. If there are both selected repositories and a search filter (on the full name), the search filter will be ignored and the selected repositories will be used in full.
=> Use selected repositories for copying repo lists

.gitignore, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/data-remote-qlpack-nested/qlpack.yml, extensions/ql-vscode/src/vscode-tests/cli-integration/data-remote-qlpack/qlpack.yml, extensions/ql-vscode/src/vscode-tests/cli-integration/global.helper.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/remote-queries-manager.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts, extensions/ql-vscode/src/vscode-tests/test-config.ts
`${workspace}` references are new in CLI version 2.11.3. These mean that
the version depended upon in a pack must be the version available in the
current codeql workspace.
When generating a variant analysis pack, however, we copy the target
query and generate a synthetic pack with the original dependencies.
This breaks workspace references since the synthetic pack is no longer
in the same workspace.
A simple workaround is to replace `${workspace}` with `*` references.
I wanted to ensure the tests exercise this feature, so I altered one of our test qlpacks to use the `${workspace}` reference. This will work on CLI v2.11.3 and later. For earlier versions, I needed to change that reference to a `*` reference.
I also fixed a problem I was having locally where the CLI tests were timing out. By …
=> Allow synthetic variant analysis packs to handle `${workspace}`

extensions/ql-vscode/gulpfile.ts/tsconfig.json, extensions/ql-vscode/tsconfig.json
Update compiler target version in gulp and extension tsconfig to adjust it to our node version.
Tested locally (a couple of normal Query runs with `Run Query` and `Run Query on Multiple Databases`)
All in all we have 7 relevant `tsconfig` files, 2 are adjusted here, 3 others already use `es6`, 2 extend a config that uses `es6`.
=> Update compiler target version in gulp and extension tsconfig

.github/workflows/main.yml
The unit tests and linting is now run separately, which will hopefully speed up the time it takes for the integration tests to complete.
This also adds caching of npm dependencies, which should also provide a slight speed-up.
=> Split workflow run into more jobs

extensions/ql-vscode/test/pure-tests/variant-analysis-filter-sort.test.ts
The filter and sort tests were located inside the React tests since they were already using Jest. Now that the pure tests have been switched to Jest, these tests can finally be moved to the "normal" pure tests.
=> Move filter and sort tests to pure tests

extensions/ql-vscode/jest.config.js, extensions/ql-vscode/package.json, extensions/ql-vscode/src/vscode-tests/minimal-workspace/activation.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/config.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/determining-selected-query-test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/index.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/jest-runner-vscode.config.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/jest.config.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/qltest-discovery.test.ts
This migrates all minimal-workspace VSCode integration tests to Jest by running npx jest-codemods, followed by manual fixes (mostly for Sinon and Proxyquire).
N/A:
=> Migrate minimal-workspace integration tests to Jest

.vscode/launch.json, extensions/ql-vscode/src/vscode-tests/jest-runner-vscode.config.base.ts
Since we are launching a completely different process for the extension tests than the process that is launched by VSCode, we need to add some special handling for the debugging.
This will let the extension host/VSCode expose a debugging port, which VSCode will then connect to. This is "less desirable than letting the bootloader do its thing", but a packaged VSCode application does not allow using the bootloader (`NODE_OPTIONS=--require=...`). Therefore, we have to fallback to this option.
See: https://github.com/microsoft/vscode-js-debug/blob/47c60558ec31902f42c255abb9b460078df02f9d/src/configuration.ts#L405-L411
=> Add debugging support for Jest integration tests

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
CLI v2.11.4 is [released](https://github.com/github/codeql-cli-binaries/releases/tag/v2.11.4) 🎊 🥳 
N/A
=> Bump CLI version to 2.11.4 for integration tests

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/patches/jest-runner-vscode+3.0.1.patch, extensions/ql-vscode/src/vscode-tests/cli-integration/legacy-query.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/query-results.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/remote-query-history.test.ts
This will apply the same change as the PR on `jest-runner-vscode` in the local `node_modules` on every install, ensuring that we have Windows support.
=> Use `patch-package` to add Windows support

.vscode/extensions.json, .vscode/settings.json, CONTRIBUTING.md, extensions/ql-vscode/src/vscode-tests/jest-runner-vscode.config.base.js
This adds documentation for running a single test and adds Jest Runner extension support.
=> Add documentation for running a single test

extensions/ql-vscode/src/view/common/__tests__/path.spec.ts, extensions/ql-vscode/src/view/common/path.ts, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisHeader.tsx
On Windows, we were showing the full path to the query, rather than just the filename. This is because the `path` package being imported was actually `path-browserify` which only claims support for POSIX. Since Windows uses backslashes rather than forward slashes for paths, this resulted in the full path being shown.
This creates a new `basename` function that works on both POSIX and Windows by detecting whether a POSIX or Windows path is given. This ensures that the correct path is shown on Windows, and will also ensure that we show the correct path on Linux if the user has opened a variant analysis that was originally created on Windows.
=> Show correct query filename on Windows

extensions/ql-vscode/src/view/variant-analysis/AnalyzedRepoItemContent.tsx
Just a teeny typo fix in the MRVA results view!
N/A - internal only 🦏
=> MRVA: Fix typo in repo cancellation message

extensions/ql-vscode/src/remote-queries/variant-analysis-results-manager.ts
When results were already cached in memory and the view requested the result, it would not be loaded because the event would not be fired. This fires the event when the result is loaded from cache as well, to ensure that the view always receives the result.
=> Fix loading results in second opened view

extensions/ql-vscode/.storybook/vscode-theme-addon/theme.ts, extensions/ql-vscode/.storybook/vscode-theme-addon/withTheme.ts, extensions/ql-vscode/src/stories/vscode-theme-dark-high-contrast.css, extensions/ql-vscode/src/stories/vscode-theme-github-dark-default.css, extensions/ql-vscode/src/stories/vscode-theme-github-light-default.css, extensions/ql-vscode/src/stories/vscode-theme-light-high-contrast.css
This adds four new VSCode themes to Storybook which will allow us to more easily test these themes in Storybook. These themes were chosen because they are either used for accessibility (the high contrast themes) or are currently not compatible with the variant analysis UI (there are items that are not visible).
=> Add additional Storybook VSCode themes

extensions/ql-vscode/patches/jest-runner-vscode+3.0.1.patch, extensions/ql-vscode/src/vscode-tests/cli-integration/jest-runner-vscode.config.js, extensions/ql-vscode/src/vscode-tests/jest-runner-vscode.config.base.js, extensions/ql-vscode/src/vscode-tests/minimal-workspace/jest-runner-vscode.config.js, extensions/ql-vscode/src/vscode-tests/no-workspace/jest-runner-vscode.config.js
This will patch `jest-runner-vscode` to retry tests. See the separate commits for more information about each step.
=> Add retries of CLI integration tests

extensions/ql-vscode/src/view/variant-analysis/StatItem.tsx
The header color of a stat item was using the badge foreground color, but badges can have a different background color than the editor. For some themes, this would result in unreadable text. By using the editor foreground color, the header should be readable in many more themes.
=> Fix header color of stat item

extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysis.spec.tsx
If a variant analysis fails because there are no repos to query (or the repos don't have databases) then it doesn't get as far as creating an actions workflow. This means that using the presence of that field alone is problematic for determining the status of a variant analysis.
This PR will avoid cases like:
=> Don't show pending state when analysis has failed

extensions/ql-vscode/src/remote-queries/shared/variant-analysis-monitor-result.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-monitor.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-monitor.test.ts
The monitor return value was only used in tests, but we can also assert the correct behavior using the calls it makes, rather than using the result of the monitor.
=> Remove variant analysis monitor return value

extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisHeader.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisStats.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisStatusStats.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisStatusStats.spec.tsx
This PR avoids showing a spinning spinner when the variant analysis has in fact failed and won't make any more progress.
We're using the `completedAt` field to tell if the analysis is finished or not instead of the variant analysis status. This causes problems when the variant analysis failed to start a workflow because there were no repos to query. In this case it didn't get as far as creating a workflow run, and so there is no `completedAt` value. Possibly we should be setting `completedAt` in the API in this case, but we also can handle this in the extension.
Also, if we just show the non-spinner bit of this component then we start showing the "view logs" link in cases when we shouldn't be. For example when the variant analysis fails before it can start the actions workflow, e.g. if …
=> Don't show spinner for a failed analysis

extensions/ql-vscode/src/view/common/CodePaths/CodePaths.tsx, extensions/ql-vscode/src/view/common/CodePaths/__tests__/CodePaths.spec.tsx, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/shared/AnalysisMessage.ts, extensions/ql-vscode/src/vscode-tests/factories/remote-queries/shared/CodeFlow.ts
In our push to remove the dependency on Primer we accidentally broke the rendering of paths. This PR adds in a `ThemeProvider` which is what's needed to get it working again. Although this is a slight step in the wrong direction it's probably the best thing to do right now before the release, and then we'll look at doing it properly later on as we continue with the Primer migration.
Also I added some tests as this component. The tests would actually have caught the error when render, so at least this means we won't break it again next time.
=> Add theme provider when rendering code flows

extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-results-manager.test.ts
This adds tests for the `loadResults` method of the variant analysis results manager. It tests that SARIF results can be successfully loaded and that the `onResultLoaded` event is fired.
See https://github.com/github/vscode-codeql/pull/1806#issuecomment-1330758936
=> Add tests for loading results

extensions/ql-vscode/src/mocks/scenarios/submission-failure/1-submitVariantAnalysis.json, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-submission-integration.test.ts
Creating a new MRVA will lead to different error responses which are now reflected in our MockApi tests.
=> Adjust for new GitHub Api response

extensions/ql-vscode/src/remote-queries/variant-analysis-view-manager.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-view-serializer.ts
When deserializing a webview, it could happen that a view was already manually opened by the user before the webview was deserialized. This would result in duplicate webview tabs, which is not supported by the manager.
This will close the webview that is being deserialized and focus on the existing view. This should ensure that we never have duplicate loaded webview tabs. There could still be duplicate webview tabs if there are non-deserialized tabs, but once it is opened it should be closed automatically.
=> Close serialized webview when another view already exists

extensions/ql-vscode/src/remote-queries/export-results.ts, extensions/ql-vscode/src/remote-queries/remote-queries-markdown-generation.ts
The Gist title in the result export didn't take into account the actual number of exported repositories, it only used the scanned, unfiltered, repositories in the variant analysis. This switches it to use the actual exported repositories for determining the result and repository counts.
This is somewhat more complicated than we'd expect it to be since the results are being read in async, so we need to switch the order of operations and store some additional information for being able to compute this information. However, this also makes the code somewhat easier to understand since the summary file is now being created in only 1 location, rather than being split between a method and a for-loop.
=> Fix Gist title in result export

extensions/ql-vscode/src/remote-queries/export-results.ts, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysis.stories.tsx, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisActions.stories.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisActions.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisHeader.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisActions.spec.tsx
This will allow exporting results for a variant analysis which is cancelled or in-progress. Repositories for which the results are not yet available or which have not yet been downloaded will not be exported. This will also conditionally disable the buttons, based on whether any results would be exported (based on the filters). Please review this commit-by-commit.
The header of the summary file is incorrect, but this will be fixed in a follow-up PR.
=> Add exporting of in-progress/cancelled results

extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/src/databases/ui/db-selection-decoration-provider.ts, extensions/ql-vscode/src/extension.ts
Adds a [FileDecorationProvider](https://code.visualstudio.com/api/references/vscode-api#FileDecorationProvider) which displays a ✔ label next to the selected item in the new DB panel. E.g.
It currently doesn't have any clicky UI actions, but that will come in a follow-up issue! 
Note: I'm not sure if/how to test this "file decoration". I'm wondering whether to wait until we have UI actions too, but I'm open to other suggestions about tests! 
N/A - internal only 🦑
=> Show selected item in new DB panel

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/export-results.ts
This will add a progress notification to exporting results to give users feedback about what's happening.
Unfortunately, we need to change some things in how we handle the actions on completion notifications since we want the progress notification to disappear when that notification shows. This results in us having to remove the `await` on the
`showInformationMessageWithAction` calls.
https://user-images.githubusercontent.com/1112623/205052741-89026a7c-2330-40b3-af85-8c9035593981.mov
=> Add progress notification to exporting results

extensions/ql-vscode/src/pure/sarif-utils.ts, extensions/ql-vscode/src/remote-queries/sarif-processing.ts, extensions/ql-vscode/test/pure-tests/sarif-processing.test.ts
This adds a new filtering on SARIF code snippets for very large code snippets (defined as 8KB or more). If less than 1% of such a snippet is highlighted, it will not include the code snippet in the analysed results, and it will thus not be shown in the UI.
This is to avoid very large SARIF files that can cause the extension host to crash when the analysis results are send to the UI. I don't think any of these snippets would ever be useful to show, so it should be fine to just not include them.
=> Limit SARIF code snippet size

extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/remote-queries/gh-api/variant-analysis.ts, extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts
The extension doesn't actually use anything regarding the language of variant analyses, so this just updates some types.
The actual Swift support is done in the CLI, which is also used for determining which languages are actually supported. So, the environment variable is already used by the CLI for showing supported languages.
=> Add basic Swift support

README.md, extensions/ql-vscode/README.md
This is a follow-up of my suggestion in https://github.com/github/vscode-codeql/issues/1542#issuecomment-1336254688  (cc @aeisenberg).
It adds a clarification in README.md that two additional extensions are installed, being dependencies required for proper functionality.  
This PR changes both README.md files, as my suggestion is to also include this clarification in the [Marketplace](https://marketplace.visualstudio.com/items?itemName=github.vscode-codeql) page, as well as in the 'Details' tab of the VSCode's Extensions panel. 
The markdown changes rendered:
<details>
<summary>Repo README.md</summary>
</details>
<details>
<summary>Marketplace README.md</summary>
</details>
=> Update README.md to clarify that vscode-codeql also installs 'Test Adapter Converter' and 'Test Explorer UI'

extensions/ql-vscode/src/databases/db-item-selection.ts, extensions/ql-vscode/src/databases/db-item.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/test/pure-tests/databases/db-item-selection.test.ts
When running a query we need to know which DbItem is selected in the new DB panel. This PR adds a method to the DbManager that returns the currently selected item.
=> Create method that returns selected DbItem

extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts
When rehydrating remote queries, we were awaiting the monitoring command. Since this command may take minutes to hours to complete, it seems like this would block the extension from loading. This is the same issue as in https://github.com/github/vscode-codeql/pull/1698, but for remote queries instead of variant analyses.
=> Fix incorrect await for monitor

extensions/ql-vscode/package.json, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/databases/ui/db-selection-decoration-provider.ts
Adds a UI action that lets you select a database item. This displays a ⚫ next to the selected item and sets the item as "selected" in the db config file.
See internal issue for more details 🌶️ 
N/A - internal only 🍛
=> New DB panel: Add UI command to select database item

extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/config/db-config.ts, extensions/ql-vscode/src/databases/db-item-expansion.ts, extensions/ql-vscode/src/databases/db-item.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/db-tree-creator.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/databases/ui/db-tree-view-item.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts, extensions/ql-vscode/test/factories/db-item-factories.ts, extensions/ql-vscode/test/pure-tests/databases/config/data/without-selected/workspace-databases.json, extensions/ql-vscode/test/pure-tests/databases/config/data/workspace-databases.json, extensions/ql-vscode/test/pure-tests/databases/config/db-config-validator.test.ts, extensions/ql-vscode/test/pure-tests/databases/db-item-expansion.test.ts, extensions/ql-vscode/test/pure-tests/databases/db-item-selection.test.ts, extensions/ql-vscode/test/pure-tests/databases/db-tree-creator.test.ts, extensions/ql-vscode/workspace-databases-schema.json
Adds logic to track expanded state for db items:
- Adds an `expanded` property in the db config, which contains an array of items that are expanded
- Adds an `expanded` property on some kinds of db items
- Updates to db item creation to look at the `expanded` property in the db config and set the db item's `expanded` property where appropriate.
- Adds `expanded` to a lot of test data
N/A:
=> Track expanded state of db items

extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/repository-selection.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/repository-selection.test.ts
When running a MRVA while the new Query Run Experience feature flag is enabled we want to use the new DB panel to inform on which repositories to run the query.
=> Use currently selected remote DB when Variant Analysis is run

extensions/ql-vscode/src/view/variant-analysis/RepoRow.tsx
This will add a spinner to each repo row when the results for a particular repo are loading. It will also disable the row to make clear that it is loading and not clickable.
https://user-images.githubusercontent.com/1112623/205326625-b31369f3-41b1-4d28-ba75-b366494825a3.mov
=> Add spinner when loading results

.github/workflows/main.yml
This upgrades the action to remove a deprecation warning about Node 12.
=> Upgrade actions/upload-artifact to v3

extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts
This restructures the variant analysis manager tests to follow this pattern:
- Class
- Method
- Context 
- Context
- ...
- Test
Before, we were only using this pattern for some of the tests and this made it confusing were which method was being tested.
By splitting this off, it will also be easier to move some of these tests out of the cli-integration tests and into the no-workspace or minimal-workspace tests.
=> Restructure variant analysis manager tests

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
The `vsce` package has been replaced by `@vscode/vsce`, as announced in the VSCode 1.74.0 release notes. There should be no functional changes between 2.7.0 and 2.15.0 for our use case.
See: https://code.visualstudio.com/updates/v1_74#_renaming-of-vsce-to-vscodevsce
=> Replace vsce by @vscode/vsce

extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts
We need to enable checks to only initialize the DbManager when the respective feature flags are turned on.
=> Initialize DbManager when newQueryRun is enabled

extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/databases/github-nwo.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/databaseFetcher.test.ts
Moves the `looksLikeGithubRepo` and `convertGitHubUrlToNwo` functions into a separate helper file. We plan to use these helpers in the new database panel, so let's put them in a shared location 🗺️ 
N/A: not user-visible
=> Extract github nwo helper functions

extensions/ql-vscode/src/remote-queries/repository-selection.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/repository-selection.test.ts
When creating a new DB List in the panel it will be empty at first. We are now showing an error if one tries to run a query on an empty remote DB list.
=> Show error message when running query on empty list

extensions/ql-vscode/workspace-databases-schema.json
This to stop users from entering empty db/db list names etc.
N/A:
=> Add min length constraints to various properties in the db config schema

.github/workflows/main.yml, extensions/ql-vscode/src/vscode-tests/ensureCli.ts
CLI v2.11.6 is [released](https://github.com/github/codeql-cli-binaries/releases/tag/v2.11.6) ✨ 🚀
=> Bump CLI version to 2.11.6 for integration tests

extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/config/db-config-validator.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/db-validation-errors.ts, extensions/ql-vscode/src/databases/ui/db-tree-data-provider.ts, extensions/ql-vscode/src/text-utils.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts, extensions/ql-vscode/test/factories/db-config-factories.ts, extensions/ql-vscode/test/pure-tests/databases/config/db-config-validator.test.ts, extensions/ql-vscode/test/pure-tests/text-utils.test.ts
This PR adds validation for duplicate names in the db config. As part of that we also needed to update the logic that renders errors to allow for 2 different kinds of errors:
a) Ones that the db config is just simply not valid based on the JSON schema
b) Ones that the db config is not valid for other reasons e.g. naming
Please feel free to suggest better names!
N/A:
=> Add validation for duplicate names in the db config

extensions/ql-vscode/src/databases/config/db-config-store.ts
More details in the code comment!
N/A:
=> Enable awaitWriteFinish for the db config file watcher

extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts
https://user-images.githubusercontent.com/311693/207660342-c6387599-b72e-4768-92ca-5524def9c7b3.mov
N/A:
=> Stop user from adding a db list with the same name

extensions/ql-vscode/package.json, extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts
Hides the "Add list" button when the DB config contains errors. Note: We'll need to add this functionality to the upcoming "Add database" button too (see #1870)
I wanted to add a test to check that the context value for `codeQLDatabasesExperimental.configError` had been set to `true`/`false` as appropriate. Annoyingly, I couldn't find a way to access context values in a test 🤔 
N/A - internal only 🦝
=> Hide DB panel UI actions when config is broken/undefined

extensions/ql-vscode/src/databases/config/db-config-store.ts
In order to avoid flooding the log, we only add log messages only for the initial load of the config.
N/A:
=> Add logging around db config loading

extensions/ql-vscode/src/vscode-tests/factories/db-config-factories.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts, extensions/ql-vscode/test/pure-tests/databases/config/db-config-validator.test.ts, extensions/ql-vscode/test/pure-tests/databases/db-tree-creator.test.ts, extensions/ql-vscode/test/tsconfig.json
Since integration tests don't have access to files in the `test`-directory but vice versa we moved the `db-config`-factories to the `src` directory. This 'new' factory is also applied in the relevant tests now.
=> Move DbConfig Factories to src directory

extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisAnalyzedRepos.stories.tsx
This adds a Storybook story for testing the performance of having a large number of results in one repository. This is in addition to the story for testing the performance of having many repositories.
=> Add Storybook story for many results performance

extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/databases/db-panel.test.ts
In order to be able to write this test I had to allow for the `DbModule` to be initialized so I've changed the conditions in which its initiatialized. See 8d52e8b14a188d51b7a082822c2b427268380f95 for details.
I wrote a simple test in 9b6c4410f4e664da87ceea090502f78dcb6a33f6. I've tried writing some more complex tests but kept hitting issues/tech-debt.
N/A:
=> Add basic integration test for 'add db list' functionality

extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts
This wasn't handled in the UI flow so I've added an extra check, and some tests.
N/A:
=> Stop user from adding a db list with an empty name

extensions/ql-vscode/package.json, extensions/ql-vscode/src/databases/ui/db-selection-decoration-provider.ts
Use ✓ for db item selection both in terms of action and decoration.
https://user-images.githubusercontent.com/311693/208654213-a890ba01-e34b-4e09-8d99-4592ec65571e.mov
N/A:
=> Use ✓ for db item selection

extensions/ql-vscode/src/databases/db-item.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts
We want to know what item is currently highlighted in the DB panel, so that we can add the user's new database or list in the right place.
Currently, we only support adding remote lists, but in future we can handle the other cases too. 
N/A - internal only 🥨
=> Get highlighted item in DB panel

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/github-url-identifier-helper.ts, extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/test/pure-tests/common/github-url-identifier-helper.test.ts
To add new databases to the new DB panel we want to have an "Add database" button (using the ["add" icon](https://microsoft.github.io/vscode-codicons/dist/codicon.html)), which lets a user add a new database or an owner item through the UI.
=> Create "Add database" button in DB panel 

extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts
Follows a similar pattern to the validation checks around db lists.
N/A:
=> Stop user from adding a db or owner with the same name

extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/db-item.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts
We have a mixture of validation checks and unhandled exceptions in various places. This PR aims to tidy that up so that:
- Validation errors are handled gracefully in the UI (`DbPanel`), using error notifications rather than triggering the global error handler.
- The `DbConfigStore` throws exceptions in the unlikely event that a caller has asked it to do something that would get the config in an invalid state (e.g. to add a list with an empt name).
- The `DbManager` should just pass through without doing the same checks. 
N/A:
=> Handle db validation errors gracefully

.github/dependabot.yml
I'd expect dependabot to update dependencies in our actions workflows (specifically, I noticed that we're using an old version of https://github.com/peter-evans/create-pull-request in our [release workflow](https://github.com/github/vscode-codeql/blob/082d4b8c78236c82dbeab7ad1377e1c2d740fa71/.github/workflows/release.yml#L119), which has an outdated version of `node` and outdated `set-output` syntax. See warnings [here](https://github.com/github/vscode-codeql/actions/runs/3685687906).)
It looks like our dependabot configuration for `github-actions` was wrong: we need to set the directory to `"/"` instead of `".github"`. (Found this in the docs [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directory)!) …
=> Update dependencies in workflow files

extensions/ql-vscode/src/common/app.ts, extensions/ql-vscode/src/common/memento.ts, extensions/ql-vscode/src/common/vscode/vscode-app.ts, extensions/ql-vscode/test/__mocks__/appMock.ts, extensions/ql-vscode/test/__mocks__/mementoMock.ts
We'd like to be able to set the workspace state without necessarily depending on the VS Code API. In this PR we add a `workspaceState` to the `App` container.
N/A:
=> Add workspace state to app container

extensions/ql-vscode/src/remote-queries/export-results.ts, extensions/ql-vscode/src/remote-queries/remote-queries-markdown-generation.ts
This will sort the files in an exported Gist by the user-defined sort order. It does so by prefixing the files with `result-{index}-` where the `index` is the 1-based index of the repository in the sort order. It will automatically pad the index with leading zeros to ensure that the files are sorted in the correct order.
Unfortunately, we can't just use `{index}-` because numbers sort before the `_` character, which is used in the summary filename to place it first.
There are also some changes in how we determine which repositories to export since we need to know in advance how many zeroes we need to pad the index with. There should be no functional changes in which repositories are actually exported.
=> Sort Gist files by user-defined sort order

extensions/ql-vscode/src/authentication.ts, extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/src/remote-queries/analyses-results-manager.ts, extensions/ql-vscode/src/remote-queries/export-results.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts, extensions/ql-vscode/src/remote-queries/remote-queries-monitor.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-monitor.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-monitor.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/export-results.test.ts, extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/remote-query-history.test.ts
The main thing being changed here, is that we remove the illusion that we prompt the user for authorization lazily, and instead we always fetch credentials and construct an authenticated octokit instance when calling `Credentials.initialize()`. I have a suspicion that a lot of the code in `Credentials` was unreachable, because the `octokit` field couldn't actually be undefined.
It's possible I am missing something here and the `Credentials` class really does need to be the way it is. If this is the case I'd like to know, and I'm happy to close or amend this PR as appropriate.
Secondly, and this is what tipped me off to this, we had a few places where we were doing
```typescript
if (!credentials) {
throw Error("Error authenticating with GitHub");
}
```
but the problem is that `credentials` …
=> Simplify the credentials class, and clear up impossible error cases

extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts
When a remote user defined list is highlighted when pressing the 'Add new Database'-Button we only want to show the option to add a new repository (instead of also adding a new owner) and add the new database to the highlighted list.
=> Add new repositories to a highlighted user defined list

extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts
Found a small bug where we previously allowed duplicate repos within the same list. Fixed by passing in the `parentList` to `doesRemoteRepoExist`. 
(https://github.com/github/vscode-codeql/commit/161e342ff2deb5a9442d6b0546f12fcc7b027dc1 is an unrelated typo fix)
N/A - internal only 🥦
=> Check for duplicate repo within parent list

extensions/ql-vscode/src/databases/ui/db-selection-decoration-provider.ts, extensions/ql-vscode/src/databases/ui/db-tree-view-item.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts
Without using the constant, it's not clear how the two things (resource URI and decorator) work together.
N/A:
=> Use constant for selected db item resource uri

extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/vscode-tests/cli-integration/databases/db-panel.test.ts, extensions/ql-vscode/src/vscode-tests/minimal-workspace/databases/db-panel.test.ts
Allows adding a new local db list. It shows a quickpick item to select what kind of list to select if nothing is highlighted.
N/A:
=> Add support for adding local db lists

extensions/ql-vscode/.eslintrc.js
Moving the VS Code integration tests (https://github.com/github/vscode-codeql/pull/1912) without adding the project to the eslint config meant that we'd get the following error when running `npm run format-staged`:
```
ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel.test.ts
0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: test/vscode-tests/minimal-workspace/databases/db-panel.test.ts.
The file must be included in at least one of the projects provided
```
N/A:
=> Add test tsconfigs in eslint projects

extensions/ql-vscode/package.json, extensions/ql-vscode/src/databases/ui/db-tree-view-item.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel.test.ts
Renamed context value `selectableDbItem` -> `canBeSelected` in preparation for adding more actions.
N/A:
=> Renamed selectable context value

extensions/ql-vscode/package.json, extensions/ql-vscode/src/databases/ui/db-panel.ts
We're gradually adding context menu actions for the new DB panel.
=> Add select context menu

extensions/ql-vscode/package.json, extensions/ql-vscode/src/databases/ui/db-tree-view-item-action.ts, extensions/ql-vscode/src/databases/ui/db-tree-view-item.ts, extensions/ql-vscode/test/unit-tests/databases/ui/db-tree-view-item-action.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel.test.ts
The various context menu actions that we want to add for the new db panel should only be visible under certain conditions (mostly based on the db item kind). This change updates the `contextValue` of db tree view items to include strings like `canBeSelected`, `canBeRemoved` etc. so that the command can easily check if the action should be allowed for a specific tree view node or not using a regex match.
N/A:
=> Set db tree item context value to drive actions

extensions/ql-vscode/package.json, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/databases/ui/db-tree-view-item-action.ts, extensions/ql-vscode/test/unit-tests/databases/ui/db-tree-view-item-action.test.ts
Adds an "Open on GitHub" context menu action for remote repos/owners in the DB panel:
N/A—internal only 🍝
=> Add context menu command to open repo/owner on GitHub

extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/test/unit-tests/databases/config/db-config-store.test.ts
This change tidies up code around the db config store. Please check the individual commits for details.
N/A:
=> Minor refactoring of the db config store and tests

extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/config/db-config.ts, extensions/ql-vscode/test/unit-tests/databases/config/db-config-store.test.ts, extensions/ql-vscode/test/unit-tests/databases/config/db-config.test.ts
This adds some functions to the db config store to allow renaming of dbs and lists. It's not wired up to anything yet as I thought there's quite a bit of code in here already (mainly test code!)
N/A:
=> Add db and list rename functionality to db config store

extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts
The "Copy Repository List" command lets you copy the list of repos with results, for a MRVA run. If you're using the new experimental query run experience (i.e. with the new DB panel), that command should return the list in a slightly different format.
Old format:
```json
"new-repo-list": [
"foo/bar",
"foo/baz"
],
```
New format (if you have `newQueryRunExperience` enabled):
```json
{
"name": "new-repo-list",
"repositories": [
"foo/bar",
"foo/baz"
]
}
```
N/A—internal only 🎠
=> Support new DB config format in "copy repo list" function

extensions/ql-vscode/package.json, extensions/ql-vscode/src/databases/db-item-expansion.ts, extensions/ql-vscode/src/databases/db-item-naming.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/test/unit-tests/databases/db-item-expansion.test.ts, extensions/ql-vscode/test/unit-tests/databases/db-item-naming.test.ts
Implements logic to add "rename" functionality in the db panel as a context menu action.
N/A:
=> Add 'rename' context menu action for dbs/lists

extensions/ql-vscode/test/vscode-tests/cli-integration/remote-queries/remote-queries-manager.test.ts
I am removing these assertions so that our internal integration tests can pass. They are currently failing because the number of dependencies of the `codeql/javascript-all` pack has changed. It no longer makes sense to test this value as newer versions of this pack will have more dependencies and we expect this value will continue to go up.
=> Remove assertion in tests

extensions/ql-vscode/src/databases/db-item-expansion.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/test/unit-tests/databases/db-item-expansion.test.ts
See individual commits for details.
N/A:
=> Some minor tidy up around db item expansion

extensions/ql-vscode/src/databases/db-item-expansion.ts, extensions/ql-vscode/src/databases/db-item.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/test/unit-tests/databases/db-item-expansion.test.ts, extensions/ql-vscode/test/unit-tests/databases/db-item.test.ts
Added logic to remove non existent expanded items every time expanded state is updated. 
As part of this I added a `flattenDbItems` function that turns a tree of DbItems into a flat list. We can use that in other places if we want (e.g. tests).
N/A:
=> Added logic to clean expanded state when it's updated

extensions/ql-vscode/test/vscode-tests/cli-integration/jest.setup.ts
Some checkouts of the github/codeql repo, such as the internal submodule, may be named `ql` rather than
`codeql`. Allow this folder name when running tests.
Passing improvement noticed when diagnosing and testing https://github.com/github/vscode-codeql/pull/1932.
- [N/A] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visu …
=> Integration tests: Accept github/codeql checkouts named `ql`

extensions/ql-vscode/src/commandRunner.ts, extensions/ql-vscode/src/telemetry.ts
Mark the type of `telemetryListener` as `TelemetryListener | undefined` which is more accurate, because it is undefined before `initializeTelemetry` is called. This forces us to use `?.` when logging telemetry of commands, which makes things slightly safer in case a command is accidentally run before `initializeTelemetry` is called.
Also checks that we aren't calling `initializeTelemetry` twice. We shouldn't be because it's only called on extension startup, but it's probably good to check. If it were called twice we wouldn't log telemetry twice, but we might end up doing things like prompting for permission twice.
=> Acknowledge that telemetryListener may be undefined

extensions/ql-vscode/src/telemetry.ts
I think this is a race condition, because `setTelemetryRequested` is setting `telemetry-request-viewed` to false but `requestTelemetryPermission` is checking `telemetry-request-viewed`. So this could get the value false or it could get whatever the existing value is.
My understanding of the intention of this code is that if the user has canary mode enabled but not telemetry then we always want to prompt them to enable telemetry and we want to ignore if they've already been prompted. So therefore the intention is to set `telemetry-request-viewed` to false first and the use of `Promise.all` seems like a bug.
It's been this way all the way since 292e695646186d5b2d700aac1fc8dcdd0fbf08f2 when telemetry was first added.
=> Avoid race condition requesting telemetry permissions

extensions/ql-vscode/test/unit-tests/databases/db-manager.test.ts
Follow-up to https://github.com/github/vscode-codeql/pull/1928 to add some "integration" tests (specifically testing the integration between the db manager and db config store).
These tests check renaming lists and local databases.
N/A—internal only 🎭
=> Add db manager tests for "rename" functions

extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/config/db-config.ts, extensions/ql-vscode/src/databases/db-item-selection.ts, extensions/ql-vscode/test/unit-tests/databases/config/db-config.test.ts
Created helper functions in `DbConfig` and used those in `DbConfigStore` to break up the function and remove the use of `compareSelectedKindIsEqual`.
N/A:
=> Refactor logic to remove db or list from config

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-view.ts
Moves the work for opening the logs for a variant analysis into a command. The primary motivation here is to get telemetry logged for it. The alternative would be outputting telemetry explicitly, but using a command seems cleaner, and makes the code more reusable.
This only affects when opening the logs from the variant analysis results webview. The query history has its own implementation. We could look at unifying these implementations but I think we should wait until the remote queries code has been deleted first.
=> Convert opening variant analysis logs to a command

extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/data-remote-qlpack-nested/codeql-pack.yml, extensions/ql-vscode/test/vscode-tests/cli-integration/data-remote-qlpack/qlpack.yml, extensions/ql-vscode/test/vscode-tests/cli-integration/remote-queries/remote-queries-manager.test.ts
This updates one of our integration tests so that it uses `codeql-pack.yml` instead of `qlpack.yml`.
=> Ensure remote queries can handle codeql-pack.yml files

extensions/ql-vscode/package.json, extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/test/unit-tests/command-lint.test.ts, extensions/ql-vscode/test/unit-tests/databases/config/db-config-store.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/databases/db-panel.test.ts
- Renamed the panel: `Databases` -> `Variant Analysis Repositories` (a21382b05394eab1136cd2465b0674b589b799ae)
- Renamed the panel id: `codeQLDatabasesExperimental` -> `codeQLVariantAnalysisRepositories` (1c3a6154c9220fde1c7cc54fad830d4e58f0e906)
N/A:
=> Rename new db panel to 'Variant Analysis Repositories'

extensions/ql-vscode/test/unit-tests/databases/db-manager.test.ts
[This follows the pattern of the rename tests from #1939.]
Follow-up to #1925, to add some "integration" tests. These test the integration between the db manager and db config store. (Don't require integration with the VS Code API, which is why they are in the "unit tests" folder.)
I've added a test for each of the removable db items, and checked that it's correctly removed from the config:
- remote user-defined list
- remote owner
- remote repo
- local list
- local db 
N/A—internal only 🎩
=> Add db manager tests for "removeDbItem" functionality

extensions/ql-vscode/test/vscode-tests/cli-integration/remote-queries/variant-analysis-submission-integration.test.ts
This test consistently times out for me locally, and sometimes times out on CI too (e.g. [here](https://github.com/github/vscode-codeql/actions/runs/3901556902/jobs/6663550979#step:8:133)). The timeout of 30s works for me, and will hopefully reduce some CI flakiness.
=> Increase timeout for "variant analysis submission" test

extensions/ql-vscode/src/databases/db-item-expansion.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts
To improve readability we did some renaming and restructuring.
=> Minor refactoring for expanded things

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/remote-queries/repository-selection.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/remote-queries/repository-selection.test.ts
Renames the `codeQL.newQueryRunExperience` feature flag to `codeQL.variantAnalysis.repositoriesPanel`. 
- The first two commits just rename some internal methods/variables (to make them more consistent with the public names).
- The third commit actually changes the user-facing feature flag in the config.
N/A—internal only 🎨
=> Rename feature flag

extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel.test.ts
Tidies the `db-panel.test.ts` file by grouping the tests into `describe` blocks. Probably best to review this with [whitespace hidden](https://github.com/github/vscode-codeql/pull/1965/files?w=1) 🙈 
Next step will probably be to split them into separate files. See internal linked issue 🔗 
N/A—internal only 🎃
=> Add "describe" blocks around `db-panel` tests

extensions/ql-vscode/src/common/app.ts
This would give compile time errors if someone tried to change a property of the App container.
N/A:
=> Mark App interface properties as read-only

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/README.md, extensions/ql-vscode/package.json
Renamed the "CodeQL: Run Query" command to "CodeQL: Run Query on Selected Database".
See internal issue for details.
- Docs PR: https://github.com/github/codeql/pull/11882
=> Renamed Run Query command

.github/workflows/release.yml, extensions/ql-vscode/gulpfile.ts/deploy.ts, extensions/ql-vscode/gulpfile.ts/dev.ts, extensions/ql-vscode/gulpfile.ts/webpack.config.ts
This will set the `mode` of Webpack to `production` for release builds. It will also stop inlining the sourcemap and instead produce a separate file which is excluded by `.vscodeignore`.
In terms of the bundled extension, this will add 1 file (`out/webview.js.LICENSE.txt`). It decreases the size of the VSIX file from 4.28MB to 1.77MB.
=> Use Webpack in production mode for releases

extensions/ql-vscode/src/query-history.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history.test.ts
When you attempt to delete a query that's still in progress from your
query history, you get a prompt asking if you're sure.
If you pick "Yes", the item is removed and you see a toast notification
with a link to the GitHub Action.
=> Display modal when removing an item from query history

extensions/ql-vscode/src/authentication.ts, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/run-cli.test.ts
This will supply the GitHub access token to certain CodeQL CLI commands such that private packages can be resolved. It will only do so if the user has an existing auth session. If they don't, they will now get a prompt to login. However, this will only happen for commands which actually use authentication, which is limited to packaging commands.
=> Use stdin for supplying auth to CodeQL

extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel.test.ts
[in the variant analysis repo panel]
Fixes a bug where you couldn't add a repo to list if that name existed, even outside of that list 🐛 
I've now passed in the `parentList` to the method that checks for the repo's existence, so that it knows to check inside the correct list. The tests didn't flag this, so I've tweaked one of the existing tests to cover this behaviour in future 🧪 
N/A—internal only 🦀
=> When adding repo, check whether name exists in specified parent list

extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/view/results/RawTableHeader.tsx, extensions/ql-vscode/src/view/results/alert-table.tsx, extensions/ql-vscode/src/view/results/raw-results-table.tsx, extensions/ql-vscode/src/view/results/result-table-utils.tsx, extensions/ql-vscode/src/view/results/result-tables.tsx
This PR adds telemetry for all UI interactions in the local results view.
We use the same telemetry message type that was used for the variant analysis results view, but we have to use a slightly different technique for sending the message when state changes. The local results view is not a modern react component and it uses `setState` rather than `useState`, which means we can't use `useEffect` here and instead have to add a call to the telemetry every time we call `setState`.
I've managed to trigger each of these telemetry events apart from `local-results-show-raw-results`. I can't quite work out the series of conditions that need to happen to be able to trigger this code. But I think if it ever does trigger then telemetry is reasonable.
=> Emit telemetry for user interactions in the local results view

extensions/ql-vscode/src/compare/compare-view.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/view/compare/CompareTable.tsx
Emits telemetry events for UI interactions in the "compare results" view.
There's not much here so it's quite simple. All the interactions are clicking on links or checkboxes, and some already send messages that we can append extra telemetry to to avoid sending extra messages.
=> Telemetry for compare view

extensions/ql-vscode/test/unit-tests/databases/config/db-config-store.test.ts
The functions are synchronous so they don't need to be awaited.
N/A:
=> Removed unnecessary awaits

extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel-rendering.test.ts
This will make it easier to make changes to the db tree (e.g. removing local)
N/A:
=> Update db panel rendering tests to not rely on order of root nodes

extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/db-item-expansion.ts, extensions/ql-vscode/src/databases/db-item-naming.ts, extensions/ql-vscode/src/databases/db-item-selection.ts, extensions/ql-vscode/src/databases/db-item.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/db-tree-creator.ts, extensions/ql-vscode/src/databases/ui/db-item-mapper.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/databases/ui/db-tree-view-item-action.ts, extensions/ql-vscode/src/databases/ui/db-tree-view-item.ts, extensions/ql-vscode/src/remote-queries/repository-selection.ts, extensions/ql-vscode/test/factories/db-item-factories.ts, extensions/ql-vscode/test/unit-tests/databases/config/db-config-store.test.ts, extensions/ql-vscode/test/unit-tests/databases/db-item-expansion.test.ts, extensions/ql-vscode/test/unit-tests/databases/db-item-naming.test.ts, extensions/ql-vscode/test/unit-tests/databases/db-item-selection.test.ts, extensions/ql-vscode/test/unit-tests/databases/db-item.test.ts, extensions/ql-vscode/test/unit-tests/databases/db-manager.test.ts, extensions/ql-vscode/test/unit-tests/databases/db-tree-creator.test.ts, extensions/ql-vscode/test/unit-tests/databases/ui/db-tree-view-item-action.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel-rendering.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/db-panel-selection.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/remote-queries/repository-selection.test.ts
It looks like I went a bit too far with the `remote -> variantAnalysis` rename (https://github.com/github/vscode-codeql/pull/1960) and accidentally renamed one of the domain entities 🤦  Since all others use `remote`, I decided to roll this one back.
N/A:
=> Fix rename that went too far

extensions/ql-vscode/databases-schema.json, extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/config/db-config-validator.ts, extensions/ql-vscode/src/databases/config/db-config.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/test/unit-tests/databases/config/data/databases.json, extensions/ql-vscode/test/unit-tests/databases/config/data/without-selected/databases.json, extensions/ql-vscode/test/unit-tests/databases/config/db-config-store.test.ts, extensions/ql-vscode/test/unit-tests/databases/config/db-config-validator.test.ts, extensions/ql-vscode/test/unit-tests/databases/db-manager.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/databases/db-panel.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel-rendering.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/db-panel-selection.test.ts
Since support for local dbs is only partially implemented in the new panel, we've decided to turn it off for now. In this PR we:
- [Turn off support for local dbs in new panel](https://github.com/github/vscode-codeql/commit/65623c07a247c9466b0998a2a2fb7609e4c4084a)
- [Remove root 'remote' node](https://github.com/github/vscode-codeql/commit/526c4f3ab7fa004e40b3010fd1c7f384110836e3)
As part of this it means that we have to mark a few tests as skipped. 
N/A:
=> Turn off support for local dbs and remote root 'remote' node from new db panel

extensions/ql-vscode/package.json
Temporarily disable the select action in the new panel, until we decided what to do to address UX issues. See internal linked issue for details.
N/A:
=> Disable select item button in new db panel

extensions/ql-vscode/test/vscode-tests/no-workspace/query-serialization.test.ts
This was just testing local queries.
Extracted from: https://github.com/github/vscode-codeql/compare/elena/protobuf
=> Add remote queries and variant analyses to our serialization tests   

.github/actions/create-pr/action.yml, extensions/ql-vscode/.prettierignore
We took @tjgurwara99's new `bump-cli` workflow for its first test run in #1995, which worked great! 🙏🏽 🎉 
This PR polished a few minor things noticed during testing: 💅🏽 
- Tell Prettier to ignore `supported_cli_versions.json` when linting/formatting
- Open the generated PR as a draft: CI doesn't run on PRs opened by the github-actions bot, so we need a human to manually prod them. Our existing approach (e.g. in the [releases workflow](https://github.com/github/vscode-codeql/blob/bd74b410f651ab5254f3f1efa281c2dbfe9def12/.github/workflows/release.yml#L134)) is to open the bot PR as a draft, and then [run CI](https://github.com/github/vscode-codeql/blob/b0168aa04a6763eb41897c6989933aef7e9a51ea/.github/workflows/main.yml#L5) when a human marks it as ready-for-review.
=> Minor polish to the "bump CLI" automation

extensions/ql-vscode/src/commandRunner.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/pure/helpers-pure.ts, extensions/ql-vscode/src/run-queries-shared.ts
This PR updates a few places that were doing their own `e instanceOf Error` check to instead use `asError` or `getErrorMessage` as appropriate.
Also updates the types of the helper methods to be more restrictive, as I believe using `unknown` instead of `any` where possible is generally best practice. I haven't gone any further than this with annotating things as `unknown` to avoid going down too much of a rabbit hole.
=> Make use of asError instead of reimplementing

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/contextual/queryResolver.ts, extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/legacy-query-server/legacyRunner.ts, extensions/ql-vscode/src/legacy-query-server/queryserver-client.ts, extensions/ql-vscode/src/legacy-query-server/run-queries.ts, extensions/ql-vscode/src/legacy-query-server/upgrades.ts, extensions/ql-vscode/src/packaging.ts, extensions/ql-vscode/src/query-server/query-runner.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/legacy-query.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/contextual/queryResolver.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/run-queries.test.ts
This removes all CodeQL CLI version constraints for unsupported CLI versions (< 2.7.6). The oldest supported CLI version is 2.7.6 since GHES 3.4 recommends using CodeQL CLI 2.7.6.
I've also removed a constraint on version 2.7.1, but I'm not sure if we still support all 2.7.x versions. 
Please double check that I made the correct transformations in call-sites, especially with regards to if conditions being `true`/`false`.
=> Remove unsupported version constraints

extensions/ql-vscode/.eslintrc.js, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/scripts/add-fields-to-scenarios.ts, extensions/ql-vscode/scripts/fix-scenario-file-numbering.ts, extensions/ql-vscode/scripts/lint-scenarios.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/discovery.ts, extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts
This PR adds the following eslint rule: https://github.com/cartant/eslint-plugin-etc/blob/main/docs/rules/no-implicit-any-catch.md
This enforces that whenever you use `catch` for a promise rejection value, the value is typed as `unknown`. This is safer than the default of `any` and will avoid us accidentally passing incorrectly typed values around.
There already exists https://www.typescriptlang.org/tsconfig#useUnknownInCatchVariables which does the same thing for `catch` statements for exceptions. We already have this enabled because we are using `strict` mode.
Unfortunately I had to add a whole new eslint plugin for this because I couldn't find another rule that implemented this. If there's a better rule to add I'm all for using that instead.
=> Enforce that promise rejection values must have unknown type

extensions/ql-vscode/src/helpers.ts
The idea here is to standardise how our `showAndLogXMessage` methods behave. Currently they're each a little different. This PR should mean that the arguments for all the methods stay in sync, and also the default values are only defined in one place instead of multiple places.
I'm also possibly about to introduce another variant of `showAndLogErrorMessage` so I'll want to be able to easily make that consistent too.
=> Introduce ShowAndLogOptions

extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-scrubber.test.ts
=> Extract query history scrubber tests

extensions/ql-vscode/src/remote-queries/variant-analysis-manager.ts, extensions/ql-vscode/src/remote-queries/variant-analysis-results-manager.ts, extensions/ql-vscode/src/view/common/DeterminateProgressRing.tsx, extensions/ql-vscode/src/view/variant-analysis/RepoRow.tsx, extensions/ql-vscode/test/vscode-tests/cli-integration/remote-queries/variant-analysis-results-manager.test.ts
This adds a determinate download progress indicator for MRVA downloads:
Please review this commit-by-commit since there are also some other fixes.
Depends on #2014
=> Add download progress indicator for MRVA downloads

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/databases/ui/db-tree-data-provider.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/remote-queries/variant-analysis-submission-integration.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel-rendering.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/db-panel-selection.test.ts, extensions/ql-vscode/test/vscode-tests/utils/configuration-helpers.ts
This will add a welcome view to the database panel which is shown when the controller repository is not setup. This welcome view will show a button which can be used to set up the controller repository.
=> Show welcome view when controller repo is not setup

extensions/ql-vscode/src/remote-queries/variant-analysis-view.ts
Please review this commit-by-commit. This updates the view title to "{name} - Variant Analysis Results" instead of "{name} - CodeQL Query Results".
=> Update variant analysis view title

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/telemetry.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/telemetry.test.ts
I'm thinking we may have jumped the gun slightly by implementing the new telemetry before the privacy document has been updated. This hasn't been a huge problem in practice because we haven't actually released a new extension version. But we don't want this to be a blocked on releasing.
I'm proposing we make the new telemetry opt-in behind a new secret config option. We can then leave it this way as long as we like until the privacy document has been updated, and then we enable the new telemetry when we're ready. It'll also make the changelog easier, rather than a mess of a dozen PRs over a 2 month period.
=> Don't send new telemetry data unless opted-in

extensions/ql-vscode/src/common/github-url-identifier-helper.ts, extensions/ql-vscode/test/unit-tests/common/github-url-identifier-helper.test.ts
=> DP Panel: Drop protocol check when creating a new item

extensions/ql-vscode/src/databases-ui.ts
Makes this possible: https://github.com/github/codespaces-codeql/pull/4
We have a codespace template which houses our CodeQL tour: https://github.com/github/codespaces-codeql
This contains a repo with a default databases already loaded for the user so that they can start writing queries more quickly.
At the moment we're asking the user to manually right click on the database folder (`codeql-tutorial-database`) and set it as the current database.
We can take this one step further by defining a command that gets triggered when we arrive at the step for setting up the database.
The command (`codeQL.setDefaultTourDatabase`) will build the URI pointing to our preloaded database and set it as the current one.
We initially considered whether we can re-use the `setCurrentDatabase` command and …
=> Introduce command to set default Code Tour database

extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts
These tests are blocking us from merging new PRs so while we figure out a fix, let's skip them. 
For full context: the tests started failing when a new version of VSCode was released (1.75.0).
=> Skip failing tests

extensions/ql-vscode/test/vscode-tests/cli-integration/databaseFetcher.test.ts
These are not testing anything in the databases.ts file as we're invoking functions from the DatabaseFetcher.
Let's name the file accordingly.
=> Small tidy-up: Rename test file for databaseFetcher tests

extensions/ql-vscode/src/config.ts
We'll use this flag for commands that are specific to the tutorial code tour and "quick setup" in https://github.com/github/codespaces-codeql. We can wrap those commands in some sort of `if(isCodespacesTemplate()) { ... }` check.
PR to enable the flag in the codespaces template: https://github.com/github/codespaces-codeql/pull/5
N/A - no user-visible impact
=> Add feature flag for codespaces-codeql template workspace

extensions/ql-vscode/package.json
We run `npm run lint` every time we do a `git push`.
This takes quite a long time, and the lint command has already been run when we created the commit in the first place.
Could we instead skip this and rely on CI to tell us if we've failed to address a linting issue?
=> Don't lint on `git push`

extensions/ql-vscode/docs/test-plan.md, extensions/ql-vscode/src/view/variant-analysis/RepositoriesSort.tsx
Last commit is confusing because it's actually the `updated_at` of the repository. By renaming it, this will be clearer to users.
=> Rename "Last commit" to "Last updated"

extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/config.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/helpers.test.ts
We'd like to make it easier for a user going through the CodeQL Tour to write their queries.
To help them along, we can generate skeleton QL packs once we know which database they're using, instead of expecting them to know how to create this themselves.
We're then able to download the necessary dependencies for their CodeQL queries.
=> Introduce command for creating skeleton QL packs

extensions/ql-vscode/scripts/source-map.ts
This adds a script that can be used for retrieving the original source location when given a location in the released extension. It will download the source map from the Actions workflow run of the release and use the `source-map` library to extract the original location.
Example input:
```shell
npx ts-node scripts/source-map.ts v1.7.8 "/Users/user/.vscode/extensions/github.vscode-codeql-1.7.8/out/extension.js:131164:13"
```
Output:
```
/Users/user/.vscode/extensions/github.vscode-codeql-1.7.8/src/cli.ts:281:12
```
=> Add script for retrieving original source location

CONTRIBUTING.md
=> Add recommendation for version number bumps

extensions/ql-vscode/src/contextual/queryResolver.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/pure/ql.ts, extensions/ql-vscode/src/quick-query.ts, extensions/ql-vscode/src/remote-queries/run-remote-query.ts, extensions/ql-vscode/test/unit-tests/pure/ql.test.ts
This will add support for the `codeql-pack.yml` filename in all places where we currently support `qlpack.yml`. It centralizes the list of the supported filenames in a single place and a method that can figure out the correct filename to use.
=> Handle `codeql-pack.yml` files everywhere

extensions/ql-vscode/package.json
Change to use the "json" icon instead of the edit icon.
N/A:
=> Update edit db config icon

extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/databases/ui/db-tree-data-provider.ts, extensions/ql-vscode/src/databases/ui/db-tree-view-item.ts
This removes the delay between the user selecting a new db/list and the UI updating.
See internal linked issue with more details.
N/A:
=> Optimistically update the UI when user selects db/list

extensions/ql-vscode/src/stories/variant-analysis/RepoRow.stories.tsx, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisAnalyzedRepos.stories.tsx, extensions/ql-vscode/src/view/common/CodePaths/CodeFlowsDropdown.tsx
These castings weren't necessary.
N/A:
=> Remove some as unknown as X usages

.vscode/settings.json
Small changes that will help with debugging custom codeql instances.
=> Add some better sample env vars in settings.json

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/databases.ts, extensions/ql-vscode/src/qlpack-generator.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/qlpack-generator.test.ts
Follow-up to https://github.com/github/vscode-codeql/pull/2036 where we set up the check for existing QL packs and offer to help the user download the packs.
This PR contains the "doing the thing" part --> downloading the QL packs. 
When you run the [codespace template](https://github.com/github/codespaces-codeql) for the first time, you will automatically have QL packs downloaded for you.
It creates:
- an `example.ql` file
- a `qlpack.yml` file
- a `codeql-pack.lock.yml` file
=> Generate QL pack for CodeTour

extensions/ql-vscode/src/cli.ts
Follow-up to https://github.com/github/vscode-codeql/pull/2055.
Once we create a `qlpack.yml` file for you, we run the `codeql pack add` command to install all the dependencies for it.
For this [we added a wrapper](https://github.com/github/vscode-codeql/blob/95f46b3b3a69889532b504dbd8ccad3958da0f16/extensions/ql-vscode/src/cli.ts#L1227) around the `codeql pack add` command in the extension. 
By default, a `--format` option is added to the command when we call `runJsonCodeQlCliCommandWithAuthentication`.
However, `codeql pack add` doesn't support this option so we need to turn it off.
=> Don't send `--format` option for `codeql pack add` command

.vscode/launch.json
If you uncomment this, you'll be able to test the [codespaces-codeql](https://github.com/github/codespaces-codeql) tour locally. It's quite handy so adding it here for convenience.
=> Add an extra line for testing the codespace-codeql tour

extensions/ql-vscode/test/vscode-tests/cli-integration/remote-queries/variant-analysis-manager.test.ts
The `DbManager` was never set.
We were also using a mock app when the real one is available and suitable.
N/A:
=> Correctly initialize App and DbManager in variant analysis tests

extensions/ql-vscode/src/query-history/history-item-label-provider.ts, extensions/ql-vscode/test/factories/query-history/variant-analysis-history-item.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/history-item-label-provider.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts
This adds tests for the history item label of variant analyses. This is based on the tests for [the remote queries](https://github.com/github/vscode-codeql/blob/e5a48fb46f5f522f1224308980fe4836274fa874/extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/history-item-label-provider.test.ts#L89-L232) which were removed.
=> Add tests for variant analysis history item label

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/variant-analysis/repository-selection.ts, extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/variant-analysis/repository-selection.test.ts
The db panel has now been released so we can remove the old code.
N/A:
=> Remove isVariantAnalysisReposPanelEnabled feature flag and old flows

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
These settings are no longer used.  
N/A:
=> Remove obsolete config settings

extensions/ql-vscode/src/extension.ts
Reverts github/vscode-codeql#2076
We think this listener may be reporting errors from other extensions, and we don't want this. See https://github.com/github/vscode-codeql/pull/2104 for extra context. I'm suggesting we revert this PR immediately, and then investigate what's going on without time pressure.
=> Revert "Add unhandled rejection listener"

extensions/ql-vscode/src/qlpack-generator.ts
We mark this generated query as `@kind problem`.
We'll need to change the query a bit to make it fit this type of ...
erm... kind.
This means the results view will be formatted to display the file name
next to each of the results.
We're also getting rid of any mentions of an empty block query since
that's no longer what it checks.
=> Update skeleton query

extensions/ql-vscode/package.json
We're no longer using this setting but the `contributions` part was accidentally left in.
N/A:
=> Remove obsolete config setting

extensions/ql-vscode/src/pure/bqrs-cli-types.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/qlpack-generator.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/contextual/astBuilder.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/contextual/queryResolver.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-results.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/run-queries.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/test-adapter.test.ts, extensions/ql-vscode/test/vscode-tests/utils/mocking.helpers.ts
This will remove some instances where we're using `as unknown as T` and replace them by a call to `mockedObject<T>()`. The `mockedObject` function is a bit more explicit about what it does and has types which ensure that the methods that are set on the object actually exist.
Unfortunately, we can't fully get rid of `as unknown as T` in the `mockedObject` function. However, this construct is more localized and does not need to be used in as many places. If we do enable an ESLint rule to prevent the use of `as unknown as T`, I would feel comfortable with disabling the rule for the `mockedObject` function.
=> Add new `mockedObject` function

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/telemetry.test.ts
Enables the new telemetry events. Previous this was opt-in on top of the existing telemetry, but now it'll be included for anyone that is opted in to existing telemetry.
This new telemetry currently only includes clicking on UI elements in web views, such as buttons and links. See https://codeql.github.com/docs/codeql-for-visual-studio-code/about-telemetry-in-codeql-for-visual-studio-code/ for the full information on what telemetry we collect.
Also see https://github.com/github/vscode-codeql/pull/2115 for cleaning up afterwards, but I'll avoid merging that PR until after the next release to reduce code churn and make reverting easier.
=> Enable new telemetry by default

extensions/ql-vscode/src/local-databases-ui.ts
Required by this PR: https://github.com/github/codespaces-codeql/pull/6
When a user goes through the Code Tour, we select a dummy `csv` database
for them to get them up and running.
Once they complete the code tour and would like to continue writing
queries, they will need to add their own database.
After they do that, we check the language of their new database and
generate a skeleton QL pack for them so that they don't need to create
these files by hand. See [1] for details.
This skeleton pack folder will be called
`codeql-custom-queries-<language>` and it comes with its own example
query: `example.ql`.
When we try to run this example query, the query gets confused about
which `dbscheme` to pick, as it sees a `qlpack.yml` file in the new
skeleton pack folder, as well as one in the …
=> Install dependencies for tutorial query in codespace

.github/codeql/queries/unique-command-use.ql
Introduces a new CodeQL query for detecting when a VS Code command is used in more than one location. By "location" we mean a UI element or being called from the code or being available in the command palette. The intention is to make our telemetry more useful, because in the telemetry we can't tell which place the command was called from. To remedy an alert, the command should effectively be duplicated with a new name but referencing the same implementation.
This is still a draft, to share the query and get thoughts. I'll come and add more comments, and I'm sure the CodeQL team will have some helpful advice.
=> Add unique-command-use.ql

extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts
Since we're tracking user behaviour through command usage we need to split them by action.
=> Split usage of runQuery and runQueryOnMultipleDatabases

extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/qltest-discovery.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/history-item-label-provider.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/history-tree-data-provider.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-scrubber.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/variant-analysis-history.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/test-adapter.test.ts, extensions/ql-vscode/test/vscode-tests/utils/mocking.helpers.ts
See the individual commits for the full changes. This removes `as unknown as` for some more types.
=> Remove more instances of `as unknown as`

extensions/ql-vscode/src/local-databases-ui.ts
In https://github.com/github/codespaces-codeql/pull/12 we moved the source for our tutorial database into `.tours` in order to avoid confusing the user when we load the database into the workspace, since they'd see two databases.
Since this is just the source, we'd like to hide it.
=> Update path to codespace tutorial database

extensions/ql-vscode/src/distribution.ts
(Paired with @robertbrignull)
CodeQL CLI v2.12.3 was released with a bug that causes the extension to fail so we force the extension to ignore it.
Raising the PR against main for now, but we might need to target a different branch.
The CHANGELOG will need to be updated.
=> Hack to avoid CodeQL CLI v2.12.3

extensions/ql-vscode/test/vscode-tests/no-workspace/astViewer.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/contextual/astBuilder.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/contextual/fileRangeFromURI.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/contextual/queryResolver.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/interface-utils.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/test-adapter.test.ts, extensions/ql-vscode/test/vscode-tests/utils/mocking.helpers.ts
This removes `as unknown as DatabaseItem` and `as unknown as FullDatabaseOptions`.
=> Remove additional `as unknown as` for database items

extensions/ql-vscode/src/interface.ts
When deleting a query history item and the "next" query is still running, the `completedQuery` is `undefined`. This commit fixes it by using optional chaining to ensure that the `completedQuery` is defined before accessing its `successful` property.
=> Fix error while deleting query history item

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/extension.ts
This is a second attempt at https://github.com/github/vscode-codeql/pull/2076. That PR worked a bit too well, in that it was picking up errors from other extensions and presenting them to the user. The fix for this that we discussed was to check the stack trace to see if it's from our extension or somewhere else.
I've implemented this by checking for `/extensions/ql-vscode/`. I couldn't think of a better string to check for. We might actually have trouble in the future if we move the extension to the top level of the repo. I'm not sure if that means we should look for a different approach now, or save that problem for if/when we do move the code in the repo.
I've tested this using https://github.com/robertbrignull/error-extension. I created a new extension (from a template) that provides …
=> Report unhandled errors, but only those that are from our extension

extensions/ql-vscode/src/extension.ts
The default id is the lowerase of the name. This is particually wordy and looks wierd.
This is only used for the lsp internal settings root which will now be things like `codeQL.lsp.trace.server`,  rather than `codeql langauge server.trace.server`. 
All these intenral settings are undocumented and for debugging on our side so changing them shouldn't matter.
=> Give the LanguageClient an easier id to use.

README.md
The current badge is broken so this attempts to fix it. I'm not sure I'm using the right source for it. I used https://vsmarketplacebadges.dev/ 
N/A:
=> Fix VS Marketplace badge

.husky/pre-commit, .husky/pre-push, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
This upgrades [Husky](https://typicode.github.io/husky/) from version 4 to version 8. In version 4, the `pre-commit` and `pre-push` hooks were located in the `package.json` file. Now, they are located in the `.husky` directory, which is located next to the `.git` directory. When you run `npm install`, the `prepare` script should automatically make the necessary changes to upgrade your local Husky installation.
=> Upgrade to Husky 8

docs/releasing.md
This is to avoid PRs getting merged while we're in the process of releasing.
The solution isn't perfect but I think it's good enough. 
N/A:
=> Update release process to lock/unlock the main branch

README.md, docs/test-plan.md, extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/variant-analysis/repository-selection.ts, extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-submission-integration.test.ts
- Move MRVA out of canary
- Add controller repo 'learn more' link
This PR has cherry-picked commits from https://github.com/github/vscode-codeql/pull/2120 and https://github.com/github/vscode-codeql/pull/2121
=> Prepare for MRVA public beta

.github/codeql/codeql-config.yml
This adds security-experimental queries to run during PRs. If it is too noisy, we can remove it.
=> Add security experimental queries

extensions/ql-vscode/CHANGELOG.md
The release happened today, not yesterday.
N/A:
=> Fix date of last release on changelog

extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts
Since we track usage behaviour by command usage at the moment, we have to use different commands for different user interactions. Each command has to be unique. Even if the underlying behaviour in the extension is identical.
=> Extension Telemetry: Split `runVariantAnalysis` and `viewAst` command

extensions/ql-vscode/package.json, extensions/ql-vscode/src/extension.ts
Since we track usage behaviour by command usage at the moment, we have to use different commands for different user interactions. Each command has to be unique. Even if the underlying behaviour in the extension is identical.
To prevent merge conflicts the branch is based on https://github.com/github/vscode-codeql/pull/2142
=> Extension Telemetry: Split `viewCfg`,`quickEval`, `openReferencedFile` command

extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
This commit adds back the variant analysis tests that were inadvertently deleted after this commit
https://github.com/github/vscode-codeql/blob/82ada54103f591228d9c61ac6b3c93c85d6ffd1c/extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/run-remote-query.test.ts#L67
They are not identical to the removed tests. I refactored them so that there is a single test function invoked three times with different parameters.
=> Add back variant analysis tests

extensions/ql-vscode/src/common/logging/index.ts, extensions/ql-vscode/src/common/logging/logger.ts, extensions/ql-vscode/src/common/logging/tee-logger.ts, extensions/ql-vscode/src/common/logging/vscode/output-channel-logger.ts, extensions/ql-vscode/src/legacy-query-server/queryserver-client.ts, extensions/ql-vscode/src/legacy-query-server/run-queries.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/query-serialization.ts, extensions/ql-vscode/src/query-server/queryserver-client.ts, extensions/ql-vscode/src/query-server/run-queries.ts, extensions/ql-vscode/src/run-queries-shared.ts, extensions/ql-vscode/test/__mocks__/loggerMock.ts, extensions/ql-vscode/test/common/logging/output-channel-logger.test.ts, extensions/ql-vscode/test/factories/query-history/local-query-history-item.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-results.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-serialization.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/run-queries.test.ts
This PR refactors the existing implemention of "side logs" to avoid the need to remove additional log locations once logging is complete. This simplifies some in-flight work on debugging context by removing the need for the result of `QueryRunner.compileAndRunQueryOnDatabase()` to be disposable.
- Removed the `additionalLogLocation:` option to `Logger.log()`
- Removed `Logger.removeAdditionalLogLocation()`
- Created the new class `TeeLogger`, which wraps an existing `Logger` and also sends output to the specified file. The banner that was previously emitted when a particular side log path was first used is now emitted on the first message logged to `TeeLogger`
- Updated the query server clients to track `activeQueryLogger` instead of `activeQueryLogFile`.
- Created a `TeeLogger` for each …
=> Use `TeeLogger` instead of `additionalLogLocation:` option

extensions/ql-vscode/src/commandRunner.ts, extensions/ql-vscode/src/contextual/templateProvider.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/local-databases.ts
See the two separate commits. This will make `withProgress` easier to use by removing the required options argument and making it optional instead. This brings it in line with how `commandRunnerWithProgress` calls this function.
=> Simpler `withProgress` calls

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/pure/ql.ts, extensions/ql-vscode/src/quick-query.ts, extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/data-extension-pack/extension-file.yml, extensions/ql-vscode/test/vscode-tests/cli-integration/data-extension-pack/qlpack.yml, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
If the user requests that extension packs be included in their MRVA run,
then do the following:
1. Search the workspace for all extension packs
2. Add each extension pack as an explicit and direct dependency on
the generated pack.
It is ok to use `*` as a dependency since we are guaranteed that
exactly one version of each injected extension pack dependency is
available when the pack is being compiled.
If we find multiple paths to an extension pack of the same name, this
is an error since it is ambiguous which path to use.
Commit-by-commit review is recommended.
The first commit introduces a refactoring with no behavioural changes. Second commit introduces the actual change for this PR.
=> Inject extension pack dependencies into MRVA packs

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
This replaces the run variant analysis commands by an implementation based on the new commands package. There should be no changes in behaviour.
Based on #2157
=> Convert run variant analysis command to new commands package

extensions/ql-vscode/package.json, extensions/ql-vscode/src/query-history/query-history-manager.ts
Splits up the `codeQLQueryHistory.removeHistoryItem` command so we don't use the same command from more than one location. This makes our telemetry better because we can tell how users are interaction with features.
=> Split up the codeQLQueryHistory.removeHistoryItem command

extensions/ql-vscode/package.json, extensions/ql-vscode/src/query-history/query-history-manager.ts
Splits up the `codeQLQueryHistory.openQuery` command so we don't use the same command from more than one location. This makes our telemetry better because we can tell how users are interaction with features. It's ok to rename these commands because they are not visible to users in the command palette.
=> Split up codeQLQueryHistory.openQuery command

extensions/ql-vscode/package.json, extensions/ql-vscode/src/interface-utils.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/variant-analysis/data-flow-paths-view.ts, extensions/ql-vscode/src/variant-analysis/shared/data-flow-paths.ts, extensions/ql-vscode/src/view/data-flow-paths/DataFlowPathsView.tsx, extensions/ql-vscode/src/view/data-flow-paths/__tests__/DataFlowPathsView.spec.tsx, extensions/ql-vscode/src/view/data-flow-paths/index.tsx, extensions/ql-vscode/test/factories/variant-analysis/shared/data-flow-paths.ts
Add a new webview that will be used to show the data flow paths, instead of the full screen overlay that we use currently. See linked internal issue for more details. 
This is currently not in use - it will be wired up in a follow-up PR.
N/A:
=> Add new data flow paths view (empty)

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-view-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-view.ts, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx
I'm not sure if this PR is the right way to go, but I want to open it to ask the question. What's wrong with doing this?
To make clear what's going on here, the `codeQL.openVariantAnalysisQueryFile` is only used internally from code and is not available to the user in the command palette. In the two places we use this command, we could instead just call the `openQueryFile`  method on the variant analysis manager directly. We have access to the variant analysis manager object already.
The reasons I can see for using a command are:
- It reduces coupling between the variant analysis manager and other parts of the codebase, but in this case the coupling is already there and unlikely to be removed.
- It adds more error handling/logging, but I don't think it adds much because we're always …
=> Remove codeQL.openVariantAnalysisQueryFile command

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts
This converts the query history commands to the new typed commands package. There should be no behaviour changes.
=> Convert query history commands to typed commands

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-view-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-view.ts, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/variant-analysis-history.test.ts
Removes the `codeQL.cancelVariantAnalysis` and `codeQL.openVariantAnalysisQueryText` commands. I've done these two together in one PR since they both also use the approach from https://github.com/github/vscode-codeql/pull/2179.
Check the individual commits for changes relevant to each command. For each one we essentially inline the implementation so we call the method on the variant analysis manager directly instead of going through a command. The only case where we're not already inside a command is when triggered from the variant analysis view, so we add dedicated telemetry to cover that.
=> Remove two more internal-only commands
