extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/extension.ts
This converts the new database panel to use typed commands. There should be no changes in behaviour.
=> Convert new database panel to typed commands

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/local-databases-ui.ts
This converts the local databases UI to use typed commands. Please review this commit-by-commit since this also does some clean-up of the commands itself.
=> Convert local database commands to typed commands

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/run-queries-shared.ts
EntityValues are currently exported in the CSV as `[Object object]`, this PR returns the label for the EntityValue instead, which is more useful.
Fixes https://github.com/github/vscode-codeql/issues/981
=> Display EntityValue labels in CSV export

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/eval-log-viewer.ts, extensions/ql-vscode/src/extension.ts
This converts the `codeQLEvalLogViewer.clear` command to a typed command.
=> Convert codeQLEvalLogViewer.clear to a typed command

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/extension.ts
Please review this commit-by-commit. This converts the `codeQL.restartQueryServer` command to a typed command. I couldn't really find a good place for it, so for now it's just in `extension.ts`.
=> Convert codeQL.restartQueryServer to a typed command

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/packaging.ts
Please review this commit-by-commit. This converts the packaging commands to typed commands.
=> Convert packaging to typed commands

extensions/ql-vscode/src/astViewer.ts, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/extension.ts
This converts the commands in the `astViewer` file to use typed command registration. There are no changes in behaviour.
=> Convert AST viewer commands to typed commands

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/log-insights/summary-language-support.ts
This converts the summary language support commands to typed commands. There are no changes in behaviour.
=> Convert summary language commands to typed commands

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/mocks/vscode-mock-gh-api-server.ts
This converts the mock GitHub API server commands to typed command registration. There should be no changes in behaviour.
=> Convert mock API server commands to typed commands

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-editor.ts
Please review this commit-by-commit. This splits up the query editing commands into a separate file and converts their registration to using typed commands. If this split doesn't make sense, I'm open to finding another split to avoid all remaining commands ending up in the `BaseCommands`.
=> Convert query editing commands to typed commands

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/extension.ts
This converts these commands to typed commands:
- `codeQL.showLogs`
- `codeQL.authenticateToGitHub`
- `codeQL.copyVersion`
=> Convert some base commands to typed commands

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/extension.ts
The `codeQL.checkForUpdatesToCLI` command is registered pre-activation, and we don't really want to create the command manager before activation, so this will just add the correct type without registering it using the command manager.
=> Add `codeQL.checkForUpdatesToCLI` type for command

extensions/ql-vscode/src/common/vscode/commands.ts, extensions/ql-vscode/src/extension.ts
There were still some unintentional references to `commandRunner`. This PR removes them.
=> Remove remaining references to `commandRunner`

extensions/ql-vscode/src/cli.ts, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/legacy-query-server/queryserver-client.ts, extensions/ql-vscode/src/local-databases-ui.ts, extensions/ql-vscode/src/local-databases.ts, extensions/ql-vscode/src/query-editor.ts, extensions/ql-vscode/src/test-ui.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/databaseFetcher.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/legacy-query.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/new-query.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/helpers.test.ts
This PR converts some places that call commands to use typed commands. This isn't everything but I'll try to open a few smaller PRs instead of one giant PR. That way it'll be easier to review and easier to adapt thoughts and ideas before getting too deep into things.
Each commit converts a single file, so if you want to review commit-by-commit then that is an option.
This PR involves:
- Documenting new builtin commands whenever we encounter a new one.
- I'm working out parameter types from the usages we have in the codebase and from the [VS Code docs](https://code.visualstudio.com/api/references/commands).
- Passing either `App` or `AppCommandManager` to wherever it is needed.
- When deciding between the two, my thought process so far has been that when we're constructing a long-lived …
=> Convert call sites to use typed commands (part 1)

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/src/vscode-utils/external-files.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/history-tree-data-provider.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/variant-analysis-history.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/vscode-utils/external-files.test.ts
Following on from https://github.com/github/vscode-codeql/pull/2217, this PR converts some more places to call typed commands, focussing on the `QueryHistoryManager` class because that turned out to need some non-trivial refactoring to make it work.
The problem was because the tests used `tryOpenExternalFile = (QueryHistoryManager.prototype as any).tryOpenExternalFile;` to access and call the `tryOpenExternalFile` method but without actually constructing a `QueryHistoryManager` instance. Somehow this worked for calling the actual method, but it was a problem when we needed to check that it called `this.app.commands.execute` because we couldn't pass in the correct `app`.
To get around this I pulled the `tryOpenExternalFile` method out to a separate file so it's no longer defined on the …
=> Convert call sites to use typed commands (part 2): QueryHistoryManager

.github/workflows/main.yml, extensions/ql-vscode/test/vscode-tests/jest.activated-extension.setup.ts, extensions/ql-vscode/test/vscode-tests/jest.setup.ts
We introduced this change to help with [reducing flakiness in CI][1].
This has a slightly different effect locally, where every failed test will output three times.
This in turn makes it harder to read, especially when you have multiple failing tests.
Since the original intent for this behaviour was to be used in CI, I'm proposing we disable it when the CI env variable isn't set.
I've opted to set it for all jobs involving tests, just for consistency. I'm happy to limit it to just the places where it's required.
[1]: https://github.com/github/vscode-codeql/pull/2059
=> Only retry tests in CI

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/databases/db-panel.test.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-manager.test.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-monitor.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/databaseFetcher.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/helpers.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/legacy-query.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/new-query.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/packaging.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/run-cli.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-submission-integration.test.ts, extensions/ql-vscode/test/vscode-tests/global.helper.ts, extensions/ql-vscode/test/vscode-tests/jest.activated-extension.setup.ts
The main aim of this PR is to make activating the extension more type safe and less error prone.
A problem I've had a few times in tests is unexpectedly getting an `undefined` value because the `extension` variable was not a `CodeQLExtensionInterface` like I thought but actually a `Record<string, never>` which we are using as an error type. This means the type system will happily let you access any field on it, but it may be undefined and you can't tell.
The changes to `extension.ts` should be limited only to changing the error type from `Record<string, never>` to `undefined`. I'm hoping not to make any major behavioural changes here. There are some small changes such as around `variantAnalysisViewSerializer.onExtensionLoaded`, but previously we were just passing an `undefined` into the …
=> Use undefined instead of Record<string, never> type when unable to activate extension

extensions/ql-vscode/src/legacy-query-server/run-queries.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/src/query-history/store/query-history-store.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/run-queries-shared.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/store/query-history-store.test.ts
This PR is part of an endeavour to separate data and domain model for the query history. We are just renaming the methods responsible for reading and writing query history data to disk here.
=> Rename query history read and write methods

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/log-insights/summary-language-support.ts, extensions/ql-vscode/src/mocks/vscode-mock-gh-api-server.ts, extensions/ql-vscode/src/query-server/queryserver-client.ts, extensions/ql-vscode/src/variant-analysis/export-results.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-monitor.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-monitor.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/new-query.test.ts
Follows on from earlier PRs and converts some more places to call typed commands.
The only non-trivial bit of this PR is around `VariantAnalysisMonitor`:
- This class already took credentials, but in this case I decided to instead provide a full app and moved it to the constructor instead of the `monitorVariantAnalysis` method.
- The tests were asserting that the `codeQL.autoDownloadVariantAnalysisResult` command was called, but then also asserting that the `VariantAnalysisManager. autoDownloadVariantAnalysisResult` method was called. This only works if it's actually executing commands rather than using a mock, and is also not very necessary. I decided to remove these and just check that the command was called, and this made the tests a lot simpler.
=> Convert call sites to use typed commands (part 3)

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-view-serializer.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-view.ts
Converts `VariantAnalysisView` to call typed commands.
This PR is simpler than I originally expected. I pulled this out to a separate PR because I thought it was going to be hard, but in the meantime someone has fixed the main issue which is that the app wasn't available when we constructed `VariantAnalysisViewSerializer`. But now we create the app much earlier in activation, so this PR is very simple.
=> Convert call sites to use typed commands (part 5): VariantAnalysisView

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/extension.ts
Ensure that the language server is restarted when the "Restart Query Server" command is invoked.
This PR fixes the first part of https://github.com/github/vscode-codeql/issues/2199 where there are spurious red squiggles when upgrading to a new CLI version.
=> Restart language server on command

extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/helpers.test.ts
Follow-up to https://github.com/github/vscode-codeql/pull/2188#pullrequestreview-1350910732, which didn't quite work on Windows due to URI parsing issues.
Using `Uri.file` instead of `Uri.parse` works on Windows and I'll test in a codespace to make sure it also works there! (update: it works)
N/A
=> Open correct tutorial workspace on Windows

.github/workflows/release.yml
This switches the release workflow to use [`gh release create` ](https://cli.github.com/manual/gh_release_create) instead of the deprecated `actions/create-release` and `actions/upload-release-asset`. The `gh release create` supports uploading assets to the release using the same command invocation, so this also simplifies the creation of the release.
=> Use gh release create instead of deprecated actions

extensions/ql-vscode/test/vscode-tests/activated-extension/databases/db-panel.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/sourcemap.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-submission-integration.test.ts
We have quite a few tests that trigger commands as part of them. They do this to call code that isn't accessible otherwise. The easiest way to convert these tests to use typed commands is to use `createVSCodeCommandManager` to get a real command manager than will trigger real commands. By doing this the the behaviour should be exactly the same except that the commands are type checked.
It would likely be better overall if these tests were able to call code without using commands. That would likely lead to better organised code. However, that is more of a long term goal.
Does this make sense? Or should we put in more effort to refactor the tests? Or something else entirely?
=> Convert call sites to use typed commands (part 6): createVSCodeCommandManager in tests

extensions/ql-vscode/src/variant-analysis/variant-analysis-monitor.ts
This will improve the error message shown when monitoring fails. Instead of showing "Error while monitoring variant analysis: Not Found", this will now show "Error while monitoring variant analysis "Empty block (javascript) [29/3/2023 10:45:10]: Not Found". This should make it easier for the user to figure out which query history item is problematic.
We're not using the full query history item label here because that would require access to the query history item, which we don't yet have here. Adding it here would add a dependency on the query history, which seems undesirable.
=> Improve monitor error message

extensions/ql-vscode/src/ast-cfg-commands.ts, extensions/ql-vscode/src/common/logging/logger.ts, extensions/ql-vscode/src/contextual/astBuilder.ts, extensions/ql-vscode/src/contextual/locationFinder.ts, extensions/ql-vscode/src/contextual/queryResolver.ts, extensions/ql-vscode/src/contextual/templateProvider.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/legacy-query-server/legacyRunner.ts, extensions/ql-vscode/src/legacy-query-server/run-queries.ts, extensions/ql-vscode/src/legacy-query-server/upgrades.ts, extensions/ql-vscode/src/local-databases.ts, extensions/ql-vscode/src/local-queries.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/query-server/query-runner.ts, extensions/ql-vscode/src/query-server/run-queries.ts, extensions/ql-vscode/src/queryRunner.ts, extensions/ql-vscode/src/run-queries-shared.ts, extensions/ql-vscode/test/common/logging/output-channel-logger.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/contextual/astBuilder.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/run-queries.test.ts
_Review tip: This PR will probably make more sense if you step through the code. I suggest that you do so after you've read the PR description, but before you try to make sense of the diffs. Set a breakpoint at `compileAndRunQuery()`, select the `Run query against a single database...` command, and follow along._
This PR refactors our existing code path for local query evaluation so that it can be used by the CodeQL Debug Adapter, which will be added in an upcoming PR.
Our existing code path for local query evaluation goes through several layers of code, but there is no clear separation of concerns between those layers. As one extreme example, the `LocalQueryInfo` object, which handles the UI presentation of the query evaluation in the query history view, is passed all the way down the …
=> Refactor local query evaluation to prepare for debug adapter

extensions/ql-vscode/src/local-queries.ts
This PR implements a [review suggestion](https://github.com/github/vscode-codeql/pull/2244#discussion_r1150312991) from #2244. I've made it a separate, dependent PR to avoid making the original PR's diffs even worse.
=> Move `LocalQueries` commands to be member functions

extensions/ql-vscode/src/view/jest.config.ts, extensions/ql-vscode/src/view/results/__tests__/results.spec.tsx
This adds a really simple regression unit test for the results view which checks that the results view can render a SARIF file. This is in preparation for the upgrade to React 18 to ensure that we don't break the basic functionality of the results view.
=> Add simple regression unit test for the results view

CODEOWNERS, extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/interface-utils.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/index.tsx, extensions/ql-vscode/src/view/vscode-api.ts
This adds an empty data extension editor view which is only available behind the `codeQL.dataExtensions.editor` and `codeQL.canary` settings.
This is a split-up from #2257.
=> Add empty data extension editor view

extensions/ql-vscode/src/variant-analysis/store/repo-states-store.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
This is a first step to separate the repo-states domain and data model. This PR creates a new repo-states store that hosts the read- and write methods.
=> Repo States: Extract read/write methods to repo states store

extensions/ql-vscode/src/legacy-query-server/run-queries.ts, extensions/ql-vscode/src/query-history/store/data-mapper.ts, extensions/ql-vscode/src/query-history/store/domain-mapper.ts, extensions/ql-vscode/src/query-history/store/local-query-data-item.ts, extensions/ql-vscode/src/query-history/store/query-history-data.ts, extensions/ql-vscode/src/query-history/store/query-history-store.ts, extensions/ql-vscode/src/query-history/store/variant-analysis-data-item.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/run-queries-shared.ts
To prevent changes in our domain to impact what and how we store the query history directly, we separated both worlds by creating specific data models.
This PR: 
- Creates new interfaces (data models) for local queries and variant analysis query history storage
- Rewrites constructors for the following classes: 
- LocalQueryInfo
- CompletedQueryInfo
- Maps new data models to domain model and vice versa
=> Query History: create and map data model to domain model

extensions/ql-vscode/src/variant-analysis/store/repo-states-data-types.ts, extensions/ql-vscode/src/variant-analysis/store/repo-states-store.ts, extensions/ql-vscode/src/variant-analysis/store/repo-states-to-data-mapper.ts, extensions/ql-vscode/src/variant-analysis/store/repo-states-to-domain-mapper.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-manager.test.ts
This PR introduces new data types for storing repo states and uses them to map between data and domain model.
=> Repo States: new data model and mapping

extensions/ql-vscode/src/variant-analysis/variant-analysis-view-serializer.ts
This fixes the "Webview is disposed" error which occurs when the user closes the variant analysis webview while the extension is still activating. We will now check whether the webview is disposed before restoring the view.
=> Fix error when closing MRVA webview during extension activation

extensions/ql-vscode/src/variant-analysis/store/repo-states-store.ts, extensions/ql-vscode/src/variant-analysis/store/repo-task-data-types.ts, extensions/ql-vscode/src/variant-analysis/store/repo-task-store.ts, extensions/ql-vscode/src/variant-analysis/store/repo-task-to-data-mapper.ts, extensions/ql-vscode/src/variant-analysis/store/repo-task-to-domain-mapper.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-results-manager.ts
This PR introduces new data types for storing the repo task and uses them to map between data and domain model.
=> Repo task:  new data model and mapping

extensions/ql-vscode/.babelrc.json, extensions/ql-vscode/.storybook/main.ts, extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx, extensions/ql-vscode/src/stories/data-extensions-editor/MethodRow.stories.tsx, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
This adds stories for the two components included in the data extensions editor. This is dependent on #2257 and on #2258.
=> Add stories for data extension editor

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/view/data-flow-paths/DataFlowPaths.tsx
Fixes a bug where the code flows aren't updated.
=> Update selected code flow when data flow paths change

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts, extensions/ql-vscode/src/data-extensions-editor/external-api-usage-query.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/external-api-usage-query.test.ts
The data extension editor was only using the default data extensions found in the `ql` submodule to find external API calls. This will add support for using data extensions found in the workspace.
Rather than using the `codeQL.runningQueries.useExtensionPacks` setting, this will always include data extensions since the editor doesn't make sense to use without data extensions. We will also forbid the user from opening this view unless they are using a CLI which supports data extension packs.
=> Use data extensions for finding external API calls

extensions/ql-vscode/src/distribution.ts
This PR helps to avoid a specific case where your managed CodeQL CLI gets uninstalled (not sure how, but it can happen during extension upgrades) and then the extension refuses to install a new one because it tried that within the last 24 hours. This PR makes it so that if no CLI is installed then it'll always try installing one.
I'm able to reproduce the bug easily by adding a simple "removeDatabase" command. I didn't include it in this screenshot but the extension fails to load and you're totally stuck.
With this PR it always installs the CLI if it couldn't find one.
=> Don't rate limit if no CLI is installed

extensions/ql-vscode/src/view/results/__tests__/results.spec.tsx, extensions/ql-vscode/src/view/results/result-tables.tsx
When updating to React 18, we removed the loading step from the updating of the state of the result view since React would batch the updates anyway. However, this caused a bug where the result view would be empty when switching between queries. This is because the result view would retain the old selected result set name. This would not happen previously because React would re-render the view at least once, which would cause the result view to be unmounted and re-created.
This fixes it by resetting the selected result set if we can't find the result set in the new result sets. It also adds a test to ensure we don't have a regression in this behavior in the future.
=> Fix empty result view when switching between queries

extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/local-databases.ts, extensions/ql-vscode/src/skeleton-query-wizard.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts
Please review this PR commit-by-commit. 
Follow up to https://github.com/github/vscode-codeql/pull/2250 where we added a wizard which will guide you through generating an example query based on the language of your choice. 
The wizard would then create a skeleton QL pack and download an appropriate database for you, so that you could focus on just writing your query. 
We've received some feedback on improvements for this flow:
1. If a database using the same language is already downloaded, re-use that database instead of downloading a new one.
2. Show the user a selection box before downloading our suggested database. The selection box will have our suggested database pre-filled but will require the user to press "Ok" to download it. The user can choose to type in a different database …
=> Improvements to skeleton query flow

extensions/ql-vscode/src/local-databases.ts, extensions/ql-vscode/src/skeleton-query-wizard.ts, extensions/ql-vscode/test/factories/databases/databases.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts
Came out of https://github.com/github/vscode-codeql/pull/2250#discussion_r1157191375
This required moving the `digForDatabaseItem` & `digForDatabaseWithSameLanguage` methods into the `SkeletonQueryWizard` class. 
In order to do this we had to:
- extract some factories from the `local-databases.test.ts` file so we can set up a mock database manager
- move the methods
- adapt our tests
We're also:
- renaming the methods to make them more consistent with other search methods for database items.
=> Refactor `digForDatabaseItem` and `digForDatabaseWithSameLanguage` methods for skeleton wizard

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/local-queries.ts, extensions/ql-vscode/src/skeleton-query-wizard.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts
Discovered by @shati-patel [here](https://github.com/github/vscode-codeql/pull/2250#discussion_r1158611185). 
The `getFirstStoragePath()` method would break on windows:
```
Path contains invalid characters: /c:/git-repo/codespaces-codeql (codeQL.createSkeletonQuery)
```
This makes sense, since we're looking to get the parent folder by splitting for `/`. In Windows, paths use `\` instead of `/`. So let's detect the platform and add a test for this case.
=> Fix problem with detecting storage folder on windows 

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/local-queries.ts, extensions/ql-vscode/src/skeleton-query-wizard.ts
Came out of final set of reviews for https://github.com/github/vscode-codeql/pull/2250#discussion_r1164275045
- Fixes progress indicator to provide the correct max steps
- Fixes regex expression
- Moves up place where we catch errors if we fail to open an example file
- Renames `codeQL.createSkeletonQuery` to `codeQL.createQuery`
- Import individual methods instead of whole databaseFetcher object
- Corrects some error messages
- Temporarily adds `codeQL.createQuery` command behind a canary flag
=> Small fixes to skeleton query wizard

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/local-queries.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/variant-analysis-history.test.ts
This PR aims to make our types for commands that operate on selections more precise and correct. It's possible for a lot of these commands to receive `undefined`s that they weren't expecting, and the behaviour is different for different places where the commands are registered.
I've done a lot of manual testing, logging the arguments of commands and triggering them in as many different ways as I could think of. It turns out that tree views behave differently from the file explorer, and title menus also behave differently from context menus. I've split the types in to the various cases and tried to summarise all my findings in the comments.
(btw, I know the type names are quite long. Any suggestions for better names are welcome.)
I then went and corrected types throughout the application. …
=> Make types for selection commands more precise

extensions/ql-vscode/src/skeleton-query-wizard.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts
Came out of https://github.com/github/vscode-codeql/pull/2250#discussion_r1164267824
When we create a skeleton query, we check whether you already have an
existing database with the same name (e.g. `github/codeql`). If we can't
find one, we also check for an existing database with the same language.
If we find a matching database, we select it instead of downloading a new 
database.
Here we're filtering out databases with errors so that we don't accidentally
select an invalid database for you.
=> Filter out databases with errors

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/data-extensions-editor/data-schema.json, extensions/ql-vscode/src/data-extensions-editor/external-api-usage-query.ts, extensions/ql-vscode/src/data-extensions-editor/generate-flow-model.ts, extensions/ql-vscode/src/data-extensions-editor/yaml.ts, extensions/ql-vscode/test/unit-tests/data-extensions-editor/yaml.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/external-api-usage-query.test.ts
This improves the error handling in the data extension editor by showing more errors to the user and adding validation to data extension model files.
=> Improve error handling in data extension editor

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/databases/db-panel.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/helpers.test.ts
This PR updates the extension to use a more recent version of the `@types/vscode` package, and fixes a couple naming conflicts that came up as part of that upgrade.
=> Update `@types/vscode` and fix naming conflicts

extensions/ql-vscode/src/data-extensions-editor/extension-pack-picker.ts, extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/extension-pack-picker.test.ts
This adds the ability to create a new extension pack when opening the data extension editor. It lets the user select a workspace folder and package name, but does not currently allow selecting the actual directory where it will be saved. For now, this is always in a subfolder of the workspace folder.
https://github.com/github/vscode-codeql/assets/1112623/534588bf-764c-4abb-a025-f3085feffd09
Based on #2296
=> Add creating extension packs when opening the editor

extensions/ql-vscode/test/vscode-tests/cli-integration/databaseFetcher.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/helpers.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/jest.config.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/legacy-query.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/new-query.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/packaging.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/run-cli.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/sourcemap.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-submission-integration.test.ts
This sets a default timeout of 3 minutes on CLI integration tests. This is because these tests call into the CLI and execute queries, so these are expected to take a lot longer than the default 5 seconds. This allows us to remove all the individual `jest.setTimeout` calls with different values from the test files.
=> Set default higher timeout on CLI integration tests

extensions/ql-vscode/src/data-extensions-editor/queries/csharp.ts, extensions/ql-vscode/src/data-extensions-editor/queries/index.ts, extensions/ql-vscode/src/data-extensions-editor/queries/java.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/external-api-usage-query.test.ts
This adds support for extracting external API information for C# to the data extension panel.
It is mostly trivial with a few notes:
- I updated the Java query to not look at `FlowSummaryImpl::Public::NeutralCallable` anymore to match the C# query.
- I updated the test to be generic in the language and run for both.
N/A
=> Add support for running C# query.

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts
This will not allow the user to open the data extensions editor for a database if it is not one of the supported languages. The supported languages is a list of `string` rather than a list of `QueryLanguage` because a database item's language is also a `string`.
=> Add database language check to data extensions editor

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/json-rpc-server.ts, extensions/ql-vscode/src/local-databases.ts, extensions/ql-vscode/src/query-server/queryserver-client.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts
This commit addresses various test flakiness:
1. Bump timeouts for queries tests
2. Add a dispose handler to queryserver-client. This will help us during tests because if there is a test that timesout while a query is running, the query's progress callback won't be invoked. We will still get a timeout error in the first test, but the second test will not get a spurious error.
3. Handle a disposed query server in `deregisterDatabase`. This method will remove the database from the currently running query server. If there is no query server, then there is nothing to remove. So, this error is safe to ignore.
4. Explicitly `end()` a connection `ServerProcess`. I'm not 100% sure if this is necessary, but it seems like it prevents responses from being handled and erroring out.
5. Better handling …
=> Fix various test flakiness

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/databaseFetcher.ts
Introduce a new config option to allow requests over HTTP when fetching a database from a URL.
Closes #2324
=> Allow HTTP connections to fetch database

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
When you have just created a model file using the quick picker/input box, the data extension editor will try to read it and fail with an error message. This adds a check to ensure the model file exists and if it doesn't, it will not try to read in the file.
This should always be safe since the model file picker will only allow you to select existing files.
=> Fix error when model file does not exist

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
This adds the model filename to the data extensions editor and will also allow the user to go to the model file by clicking on the filename.
This also updates the general UI to be somewhat more compact by moving the modeled percentages to be below the header in 1 line:
=> Show model filename in data extensions editor

extensions/ql-vscode/src/data-extensions-editor/queries/csharp.ts
C# didnt recognize the modeled methods because the api name differed from the Java one and therefore the split up didnt work as expected. This makes a change to fix that. We'll look at whether this is something that should be upstreamed or whether it only makes sense for the extension.
=> Fix C# query to give results in the same format as java.

extensions/ql-vscode/src/data-extensions-editor/extension-pack-picker.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/extension-pack-picker.test.ts
This will filter the extension packs shown to the user when selecting an extension pack to use in the data extension editor to only include the extension packs that are compatible with the language of the database item.
Unfortunately, this required quite some changes to the tests to ensure the extension packs are actually setup properly since it's now reading the extension pack files.
=> Filter extension packs by database item language

extensions/ql-vscode/src/skeleton-query-wizard.ts
We want users to be able to quickly get started with running queries, so let's suggest smaller databases (which won't take too long to download). 
These databases come from the "Top XXX" lists that we use for variant analysis. See internal issue for more details 👀 
N/A—this is still feature-flagged 🎏
=> Suggest smaller databases in "create query" setup

extensions/ql-vscode/src/databaseFetcher.ts, extensions/ql-vscode/src/local-databases-ui.ts, extensions/ql-vscode/src/local-databases.ts, extensions/ql-vscode/src/skeleton-query-wizard.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts
After some testing of the skeleton pack wizard with a single rooted 
workspace (`github/code-scanning`) we discovered a general VSCode 
extension bug whereby after we download a database, we don't select it.
This isn't an issue in the wizard, but it does affect us as it means
we'll generate the QL pack, download the db for you but then you won't
know that we haven't selected your database.
So let's make sure our flow works for this case by explicitly selecting
the database once it's downloaded.
=> Ensure we're selecting database in single rooted workspace

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/data-extensions-editor/extension-pack-picker.ts, extensions/ql-vscode/src/data-extensions-editor/shared/extension-pack.ts, extensions/ql-vscode/src/data-extensions-editor/shared/view-state.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/extension-pack-picker.test.ts
This removes the link to the model file when it does not exist. It will still show the filename of the model file. When clicking on "Apply", it will refresh whether the model file exists after writing the file.
=> Hide link when model file does not exist

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/skeleton-query-wizard.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts
Offer non-codespace users the option to configure their storage folder for skeleton packs.
Suggested here: https://github.com/github/vscode-codeql/pull/2310#issuecomment-1507428217
At the moment we're choosing to create our skeleton packs in the first folder in the workspace.
This is fine for the codespace template because we can control the folder structure in that repo.
For users outside of this we'd like to offer them the option to choose where to save their skeleton packs.
=> Prompt non-codespace users for storage path

extensions/ql-vscode/src/skeleton-query-wizard.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts
The skeleton query process tries to choose an existing database for you instead of downloading a new one. 
When deciding which database to select, this is the process it goes through:
1. Is there one with the same name as the one we'd be downloading?
2. If that doesn't exist, is there one with the same language? 
3. If that doesn't exist either, it will go ahead and download one for you.
When we were designing how to find an existing database, we weren't sorting them by their creation date. This means that we might be selecting an older one, instead of the latest.
So let's sort our databases by `dateAdded` before attempting to select one.
=> Select latest database when creating skeleton query

extensions/ql-vscode/src/ast-cfg-commands.ts, extensions/ql-vscode/src/debugger/debug-configuration.ts, extensions/ql-vscode/src/debugger/debugger-factory.ts, extensions/ql-vscode/src/debugger/debugger-ui.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/local-queries/local-queries.ts, extensions/ql-vscode/src/local-queries/local-query-run.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts
- creates a new folder for `local-queries`
- splits classes `local-queries` and `local-queries-run` into their own files
=> Break down local-queries.ts

extensions/ql-vscode/package.json, extensions/ql-vscode/test/vscode-tests/no-workspace/helpers.test.ts
Once we're satisfied with testing this flow (including with a [single rooted workspace](https://github.com/github/vscode-codeql/pull/2328)) we can enable it in the codespaces-template.
=> Enable skeleton wizard in codespaces-codeql template

extensions/ql-vscode/src/extension.ts
We were only clearing the pack cache when a pack file was modified. When using a script to create a new pack, the pack file is created at once without a change event firing. This will change the behavior to also clear the pack cache when a pack file is created or deleted.
=> Clear pack cache on create and delete

extensions/ql-vscode/src/skeleton-query-wizard.ts
Small tweak: When running "Create Query", if the user escapes out of the language quickpick we don't need to throw an error. Instead we can just show a [`UserCancellationException`](https://github.com/github/vscode-codeql/blob/dbdab13d03cd38032bf6e8f427bc4a2d92f7535c/extensions/ql-vscode/src/helpers.ts#L728-L730) notice.
N/A—this is still behind a feature-flag.
=> Don't throw error if user cancels out of choosing a language

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/language-support/ide-server.ts, extensions/ql-vscode/src/language-support/index.ts, extensions/ql-vscode/src/language-support/language-support.ts, extensions/ql-vscode/src/language-support/query-editor.ts
This PR is part of an endeavour to order files in the codebase according to the domain model. Here files related to the language support are moved to one folder.
Nothing unexpected came up during the work.
=> Move language support files

extensions/ql-vscode/src/helpers.ts, extensions/ql-vscode/src/test-manager.ts
This was only a problem for the new test UI, because the third-party Test Explorer extension we used before must have had this filter in its implementation.
=> Only attempt to discover QL tests in on-disk workspace folders

extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx, extensions/ql-vscode/src/stories/data-extensions-editor/MethodRow.stories.tsx, extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx
This renames `Argument[-1]` to `Argument[this]` to match the corresponding change in CodeQL.
See: https://github.com/github/codeql/pull/12556
=> Rename `Argument[-1]` to `Argument[this]`

docs/test-plan.md, extensions/ql-vscode/src/view/common/LastUpdated.tsx, extensions/ql-vscode/src/view/variant-analysis/RepositoriesSort.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/RepoRow.spec.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisAnalyzedRepos.spec.tsx, extensions/ql-vscode/test/unit-tests/variant-analysis-filter-sort.test.ts
Renames the following "sorting keys" in the results view:
- "Name" -> "Alphabetically"
- "Results" -> "Number of results"
- "Stars" -> "Popularity"
- "Last updated" -> "Most recent commit"
- I've also updated the hover text for the "RepoRow" component here. This wasn't necessary for the other renamings.
See linked internal issue for more details! 
This is still in beta, so I don't think we need a changelog update. The docs will require some [screenshot updates](https://codeql.github.com/docs/codeql-for-visual-studio-code/running-codeql-queries-at-scale-with-mrva/#exploring-your-results), but we'll save that until the follow-up tasks are also complete.
=> Update wording in the "sorting dropdown" of the variant analysis results view

extensions/ql-vscode/src/pure/variant-analysis-filter-sort.ts, extensions/ql-vscode/src/stories/variant-analysis/RepositoriesSort.stories.tsx, extensions/ql-vscode/src/view/variant-analysis/RepositoriesSort.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisAnalyzedRepos.spec.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisSkippedRepositoriesTab.spec.tsx, extensions/ql-vscode/test/unit-tests/variant-analysis-filter-sort.test.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-manager.test.ts
Follow-up to https://github.com/github/vscode-codeql/pull/2373. That PR changed the user visible elements—this one also changes the internal names, for consistency (as suggested [here](https://github.com/github/vscode-codeql/pull/2373#pullrequestreview-1403558327)).
@robertbrignull, I've just changed the `SortKey` enum values here. I haven't updated the name of the [`LastUpdated`](https://github.com/github/vscode-codeql/blob/af75fa9f2fa65f9baf1c9567a4d5a895b56cdc67/extensions/ql-vscode/src/view/common/LastUpdated.tsx) or [`StarCount`](https://github.com/github/vscode-codeql/blob/af75fa9f2fa65f9baf1c9567a4d5a895b56cdc67/extensions/ql-vscode/src/view/common/StarCount.tsx) components themselves yet, but do you think that would also make sense? 
N/A—no user-visible changes
=> Change internal name for variant analysis `SortKey` values

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases/local-databases-ui.ts, extensions/ql-vscode/src/databases/local-databases.ts, extensions/ql-vscode/src/test-runner.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/test-runner.test.ts
This PR should fix a bug where we aren't able to set a database as the selected database. There are two bugs which are each independently causing this behaviour:
- In `addExistingDatabaseItem` if we find that a database item with that URI exists already then we return immediately, without checking `makeSelected` and therefore without setting the database as selected.
- In `handleSetCurrentDatabase` and `chooseAndSetDatabase` we weren't setting `makeSelected` to true.
This PR hopefully addresses both points. We now check `makeSelected` in both branches in `addExistingDatabaseItem`. We also change the default value of `makeSelected` to true, because we believe this is always the desired behaviour, except in one case in the test runner.
I've structured the commits so that …
=> Fix not setting database as selected if it already exists

extensions/ql-vscode/CHANGELOG.md
I forgot to include a changelog entry in https://github.com/github/vscode-codeql/pull/2349
=> Add missing changelog entry for #2349

extensions/ql-vscode/src/language-support/ast-viewer/ast-cfg-commands.ts, extensions/ql-vscode/src/local-queries/local-queries.ts
After some bit of refactoring, the templates are no longer being passed to the CFG viewer and this is preventing the viewer from running.
This change fixes it.
=> Fix CFG viewer

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/language-support/contextual/template-provider.ts
An internal option to help library authours to run and debug the find references and find dependencies contetextual queries without relying on the implicit cache.
Fixes https://github.com/github/vscode-codeql/issues/2378
=> Add `codeQL.contextualQueries.disableCache`

extensions/ql-vscode/src/variant-analysis/bqrs-processing.ts
For `@kind problem` queries, it seems like the BQRS contains four result sets: `edges`, `nodes`, `subpaths`, and `#select`. The user is probably interested in the results of `#select` since that contains the direct result of the query. This changes the extraction of raw (BQRS) results to always prefer `#select` over any other result set. If it can't find a result set named `#select`, it will fall back to the first result set in the BQRS like before.
=> Prefer `#select` result set over other result sets

extensions/ql-vscode/src/variant-analysis/variant-analysis-monitor.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-monitor.test.ts
This will suppress showing the same error message when monitoring the variant analysis fails multiple times in a row. This is useful when e.g. the internet is disconnected or the endpoint is non-functional for any other reason.
This will show the error message at least once, and then only show it if there has been a successful attempt in between or when the error message is different. This should result in a much less noisy experience.
=> Suppress similar error messages when monitor MRVA

docs/releasing.md
To help avoid me having to look up how to do this every time I get to this step.
=> Add note about how to find VSCode node version

extensions/ql-vscode/test/vscode-tests/jest-runner-vscode.config.base.js
This avoids a bug on 1.78.0 on linux. See
https://github.com/github/vscode-codeql/issues/2402
This should fix the integration tests.
=> Run integration tests on 1.77.3

extensions/ql-vscode/src/codeql-cli/distribution.ts, extensions/ql-vscode/src/databases/local-databases.ts, extensions/ql-vscode/src/pure/files.ts, extensions/ql-vscode/test/unit-tests/pure/files.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts
This replaces access to the deprecated `storagePath` and `globalStoragePath` to use `storageUri` and `globalStorageUri` instead.
=> Replace deprecated `storagePath` by `storageUri`

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts
This is currently an empty placeholder, and is hidden behind a feature flag (the `codeQL.queriesPanel` setting). This will let us work on the functionality without disrupting users. (Inspired by https://github.com/github/vscode-codeql/pull/1682)
So beautiful:
N/A—not user-facing. See linked internal issue for more details.
=> Add a new blank "queries" panel

extensions/ql-vscode/src/common/discovery.ts, extensions/ql-vscode/src/query-testing/qltest-discovery.ts
We'll also use this for discovering query files for the new Queries panel (see #2412)
N/A
=> Move `Discovery` class into `common` folder

extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/query-server/query-server-client.ts
This tries to improve the case where the query server terminates unexpectedly by printing more information about the failure (the last stout chunk) and restarting a limited number of times.
Restarting and the backup case of a full abort have the side effect of actually rejecting any pending promises from the vscode side so crashes don't look like hangs. 
The better error reporting should apply to all severs (old, new, ide). 
I have only implemented restarting for the new queryserver. The ide server already restart itself. I didn't think it worth handling the old QS case but I could if we wanted to improve that as well.
=> Better error handling for unexpected query server termination.

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/common/vscode/authentication.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-monitor.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-monitor.test.ts
This will cancel the monitoring of a variant analysis when a 404 response is returned. If a 404 response is returned, that probably means the user lost access or the repository has been deleted. We would almost never expect a variant analysis to start returning a 200 response after a 404 has been encountered, unless the user switches user accounts.
Therefore, this will stop monitoring a variant analysis when a 404 is encountered. When the user changes their VS Code GitHub session, we will restart monitoring.
=> Cancel monitoring variant analysis on 404 response

extensions/ql-vscode/src/compare/compare-view.ts, extensions/ql-vscode/src/view/compare/Compare.tsx, extensions/ql-vscode/src/view/compare/CompareSelector.tsx
The compare view typically works by matching the results sets of queries. It only allows the results sets of queries with identical names to be compared.
Manually run queries use `#select` as the default result set. However, quick eval queries use a different, generated, name. Therefore, these two kinds of queries cannot be compared.
This commit changes the heuristics so that if there are no identical;y named results sets, the first result set of each query that is prefixed with `#` is used (this is the default result set).
It also makes a slightly nicer error message if there are no comparable results sets.
- [n/a] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the …
=> Allow compare view to work with quick-eval

extensions/ql-vscode/src/queries-panel/query-tree-data-provider.ts, extensions/ql-vscode/src/queries-panel/query-tree-view-item.ts
Small follow-up to https://github.com/github/vscode-codeql/pull/2418, to handle expanding/collapsing nodes in the Queries panel. (Still using mock data for now.)
N/A—internal only ✨ 🦄
=> Queries panel: Expand/collapse child nodes

extensions/ql-vscode/src/queries-panel/query-tree-data-provider.ts, extensions/ql-vscode/src/queries-panel/query-tree-view-item.ts
Implements opening a file on click from the queries panel. Also adjusts how we construct `QueryTreeViewItem` a little bit and provides some different dummy data. Instead of passing in all bits separately, just pass in a file path and work out the label and tooltip from that.
I'm thinking that in the future we'll want to construct these from a file path, but if that's not the case just say and I can adjust or remove that change from this PR. I think we will need to know the file path to be able to open the file when clicked.
=> Open query file on click

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/common/vscode/commands.ts, extensions/ql-vscode/src/helpers.ts
Pass in the `fullMessage` to `internalShowAndLog` so that stack traces aren't truncated.
=> Ensure full stack traces are included in log messages

extensions/ql-vscode/src/common/app.ts, extensions/ql-vscode/src/common/vscode/vscode-app.ts, extensions/ql-vscode/test/__mocks__/appMock.ts
Adds knowledge of workspace folders to the `App` interface. This is going to be used very soon by the queries panel, and adding this to the `App` means that the queries panel itself will depend less on VS Code internals and will be easier to test.
=> Add workspace folders to App interface

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisActions.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisHeader.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisActions.spec.tsx
This changes the text of the export/copy buttons on a variant analysis when at least one repository is selected or a filter is applied which filters out part of the repositories. This makes it more clear that the user is only exporting/copying the results of the selected/filtered repositories.
https://github.com/github/vscode-codeql/assets/1112623/1e036099-4e4b-4919-9d98-c3626b980118
=> Update export/copy buttons copy when repositories are selected

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/extension.ts
This adds a warning when the user is using an unsupported version of the CodeQL CLI. The warning is shown once per session, and only if the version is older than the oldest supported version.
=> Add warning when using unsupported CLI version

extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/queries-panel/queries-module.ts, extensions/ql-vscode/src/queries-panel/queries-panel.ts, extensions/ql-vscode/src/queries-panel/query-discovery.ts, extensions/ql-vscode/src/queries-panel/query-tree-data-provider.ts, extensions/ql-vscode/src/queries-panel/query-tree-view-item.ts
This PR implements supplying the queries panel with real data from the workspace. We make use of the `Discovery` class, which is already used by the QL Test panel feature and has a very similar set of requirements to us. A lot of inspiration has come directly from the `QLTestDiscovery` class.
Tested locally using the codeql starter workspace:
It successfully handles updating when there's changes to the filesystem, and the automatic remembering of which items are expanded or collapsed seems pretty good.
There are some rough edges that can be improved but I think this is a good starting point. The main thing I'd like to look at in future PRs is single vs multi-root workspaces. In a single-root workspace maybe we hide the top-level item which is just the workspace name.
=> Hook queries panel up to real data

extensions/ql-vscode/src/common/events.ts, extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/db-module.ts, extensions/ql-vscode/test/__mocks__/appMock.ts
Makes `AppEventEmitter` implement `Disposable`. This class is mirroring the VS Code `EventEmitter` class, and that does have a `dispose` method.
This means in places where we use `app.createEventEmitter` we can track the object and dispose of it, which helps mirror the places where we use `EventEmitter` directly and we already do this.
=> Mark AppEventEmitter as disposable

extensions/ql-vscode/src/queries-panel/query-discovery.ts
Remove a small dependency that `QueryDiscovery` has on VS Code classes. I'm not sure if this one is strictly a blocker for making unit tests, but the method on `App` is already there so it costs us nothing to use it.
=> Use app.createEventEmitter in QueryDiscovery

extensions/ql-vscode/src/common/file-tree-nodes.ts
The `createDirectory` method that we use for populating the Queries Panel and Test Explorer tree view had a slight bug. If a query/test was directly under the root directory, we'd unnecessarily create an empty subdirectory called `.` 
(instead of directly adding the query/test). 
This PR prevents us from creating a directory when there's none to create. Thanks to @robertbrignull for the fix 🙇🏽‍♀️ 
(see internal linked issue for more details)
N/A—feature-flagged for internal development only 🎏
=> Don't create `"."` directory in queries/tests tree view

extensions/ql-vscode/src/queries-panel/queries-module.ts, extensions/ql-vscode/src/queries-panel/queries-panel.ts
Just noticed we currently don't use any of these variables outside of the constructor, so they don't technically have to be member variables. We could make them local variables instead and I think this makes things a bit cleaner.
What do you think? We can always change them back to member variables if we need them again in the future.
=> Remove member variables that could be local variables

extensions/ql-vscode/src/queries-panel/query-discovery.ts, extensions/ql-vscode/src/queries-panel/query-tree-data-provider.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/queries-panel/query-tree-data-provider.test.ts
This PR adds tests of the `QueryTreeDataProvider` class.
I investigated if we could make these unit tests rather than integration tests, but sadly it proved too complicated and not worth it for the benefit it gives.
To make this easier, I introduced a new `QueryDiscoverer` interface which allows us to easily instantiate `QueryTreeDataProvider` in the tests without dealing with the more complicated `QueryDiscovery` class and without Jest mocking. Do you think this interface is helpful and worth it? Suggestions on naming welcome?
=> Add tests of QueryTreeDataProvider

extensions/ql-vscode/src/databases/local-databases/database-item-impl.ts, extensions/ql-vscode/src/databases/local-databases/database-item.ts, extensions/ql-vscode/src/databases/local-databases/database-manager.ts, extensions/ql-vscode/test/factories/databases/databases.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-testing/test-runner.test.ts
This moves the `DatabaseItem.refresh` method out of the `DatabaseItem` interface and moves it to the `DatabaseManager` itself. This makes the `DatabaseItem` interface smaller and ensures that the `refresh` method is not called outside of the `DatabaseManager`.
=> Extract `DatabaseItem.refresh` method to `DatabaseManager`

extensions/ql-vscode/src/queries-panel/query-discovery.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/queries-panel/query-discovery.test.ts
This PR introduces integration tests of the `QueryDiscovery` class.
Includes one fix for something I discovered while writing the tests. If a workspace folder doesn't include any query files, we probably don't want to create a `FileTreeDirectory` for it. This does raise some questions about what the panel will look like when there's no queries at all, but I think we can solve that and do it separately after this PR.
I've made the tests work with the code is it is now, but honestly after this PR I'm considering removing some of the vscode abstractions. So that basically means reverting https://github.com/github/vscode-codeql/pull/2437 and https://github.com/github/vscode-codeql/pull/2431 because they arguably make the code more confusing and testing harder.
=> Add integration tests of QueryDiscovery

extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
Generated variant analysis packs will use the original name of the pack that the query is located in. This is to support some future work where we do extra validation of data extensions.
If the query is not in a pack, the default name is used.
Do not merge until after https://github.com/github/codeql-variant-analysis-action/pull/823 is merged.
=> Use the original pack name for generated pack

extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-results-manager.ts
Even with a good internet connection I sometimes have seen the error "failed to download results". When doing a MRVA on a 1000 top projects this results in that either you admit your run has incomplete results or have to rerun whole 1000 repositories query run, which is time consuming.
I have noticed that the url in the error message is still valid and I'm able to download the zip manually.
The change makes up to 3 retry attempts in a specific cases like timeout.
=> Retry results download if connection times out

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/data-extensions-editor/auto-model-api.ts, extensions/ql-vscode/src/data-extensions-editor/auto-model.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/data-extensions-editor/shared/view-state.ts, extensions/ql-vscode/src/pure/interface-types.ts, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/test/unit-tests/data-extensions-editor/auto-model.test.ts
This adds an initial implementation of auto-modeling using the `/repos/:owner/:name/code-scanning/codeql/auto-model` endpoint. The button is hidden behind the `codeQL.dataExtensions.llmGeneration` setting.
=> Add initial implementation of auto-modeling

extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/variant-analysis/run-remote-query.ts
When I made the global compialtion cache I missed this place that relied on the old location of the compilation cache. As it is global we now don't need to override the default so we can just not override.
=> Cache MRVA queries correctly

extensions/ql-vscode/src/data-extensions-editor/external-api-usage-query.ts, extensions/ql-vscode/src/data-extensions-editor/generate-flow-model.ts, extensions/ql-vscode/src/debugger/debug-configuration.ts, extensions/ql-vscode/src/debugger/debug-session.ts, extensions/ql-vscode/src/debugger/debugger-ui.ts, extensions/ql-vscode/src/language-support/ast-viewer/ast-cfg-commands.ts, extensions/ql-vscode/src/local-queries/local-queries.ts, extensions/ql-vscode/src/pure/messages-shared.ts, extensions/ql-vscode/src/query-server/query-runner.ts, extensions/ql-vscode/src/query-server/run-queries.ts, extensions/ql-vscode/src/run-queries-shared.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/determining-selected-query-test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/external-api-usage-query.test.ts
This only adds support internally to the query runner, without any UI support. I will add basic support (command palette only) in a separate PR.
I'm not completely happy about the api as we switch between an enum and booleans. The issue is that before running for quick eval we simply have a boolean and afterwards we have an optional position. It should then really become a optional (position and count enabled) but in a bunch of places we need backwards compatibility as we persist it as json. So we end up with an invalid state (no quick eval position, but quickEvalCountOnly  is set), and a difference between the initial enum and the later boolean state. However I couldn't think of much better as I don't want to add yet more boolean arguments to the initial query.
- No user visible changes …
=> Add support for quick eval count to the query runner

.github/codeql/queries/assert-pure.ql
Expands the `assert-pure.ql` query in a couple of ways:
- Covers stuff in the `src/common` directory as well as `src/pure`. Stuff in this directory should also be independent of vscode, unless it is in the `src/common/vscode` directory.
- Convert the query to a `path-problem` query. My aim here is to make this query easier to use, by explaining where an import comes from. It can otherwise be a bit hard to understand when the import chain gets more than a couple of files.
The query now has 10 alerts 🎉 😱 
All of these alerts are because of logging, either from importing `extLogger` or `OutputChannelLogger` or `showAndLogErrorMessage`.
The reason there's 6 alerts for `selection-commands.ts` is because there's 6 separate vscode imports that it transitively imports, via the giant `helpers.ts` …
=> Expand assert-pure.ql to cover common and be a path-problem query

extensions/ql-vscode/src/common/vscode/selection-commands.ts, extensions/ql-vscode/src/databases/local-databases-ui.ts, extensions/ql-vscode/src/local-queries/local-queries.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts
Should fix https://github.com/github/vscode-codeql/security/code-scanning/521
The VS Code dependency we have is on `showAndLogErrorMessage` and I can't see a way to remove it without reducing functionality. But we can move it to the vscode directory and I don't think this is a huge problem compared to it being just in the common directory. The places where we'll want to use these methods from are going to already have VS Code dependencies.
=> Move selection-commands.ts to be in the vscode directory

extensions/ql-vscode/src/common/discovery.ts, extensions/ql-vscode/src/queries-panel/queries-module.ts, extensions/ql-vscode/src/query-testing/qltest-discovery.ts, extensions/ql-vscode/src/query-testing/test-adapter.ts, extensions/ql-vscode/src/query-testing/test-manager.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/queries-panel/query-discovery.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/query-testing/qltest-discovery.test.ts
The intent of this PR is to give you access to a promise for the `Discovery` class refresh. This allows us to make the tests more type safe and less prone to flakiness.
One part of this PR is making `refresh` itself return a promise. This means in the tests we can do `await discovery.refresh()` instead of having to do `await (discovery as any).discover()` and calling the private `discover` method. This means we're no longer circumventing the public interface of the `Discover` class.
Another part of this PR is adding a `getCurrentRefreshPromise` method which means even if we weren't the ones to kick off the refresh directly we can still safely wait for it to be finished. This is useful when we are testing listeners to events that trigger a refresh, such as the listener for files changing …
=> Add ability to await the discovery refresh promise

.github/codeql/queries/assert-pure.ql
In https://github.com/github/vscode-codeql/pull/2455 I made `assert-pure.ql` cover all of `/src/common` except for `/src/common/vscode` but I didn't realise we also have directories like `/src/common/logging/vscode`. So in this PR I change the query to ignore all directories containing `/vscode/` anywhere in their path, and not just `/src/common/vscode`.
=> Make assert-pure.ql ignore all /vscode/ directories

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/databases/config/db-config-store.ts, extensions/ql-vscode/src/databases/db-manager.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/databases/ui/db-tree-view-item-action.ts, extensions/ql-vscode/src/variant-analysis/gh-api/gh-api-client.ts, extensions/ql-vscode/test/unit-tests/databases/config/db-config-store.test.ts, extensions/ql-vscode/test/unit-tests/databases/db-manager.test.ts, extensions/ql-vscode/test/unit-tests/databases/ui/db-tree-view-item-action.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/databases/db-panel-rendering.test.ts
This PR adds the option to feed code search results directly to an existing variant analysis repositories list. By entering a code language and a search query that can be developed and refined using the GitHub Code Search UI the user can now feed results directly into a MRVA list.
Additionally this PR introduces a restriction on list size. When using the new code search or adding a repo using the UI actions only up to 1000 items will be stored on a list. This restriction can be circumvented by adding repos to the config json directly and is not enforced with validation.
=> Feed code search results into variant analysis repo lists

extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/queries-panel/query-discovery.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/run-cli.test.ts
To keep the Queries Panel up to date, the CLI runs the `resolve queries` command every time a `.ql` file or surrounding folder changes.
The logging output is very noisy, so we'd like to remove it from the CodeQL Extension Log. I've passed in an optional `silent` flag to the `runCodeQlCliInternal` method, which just skips calling `logger.log`.
I've also added a basic test to check the behaviour with/without the flag.
N/A—internal only 🐕
=> Don't log the `resolve queries` CLI command

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
Shows a slightly more helpful message when we receive 429s from the auto-model endpoint.
=> Handle 429 from auto-model service

extensions/ql-vscode/src/common/file-tree-nodes.ts, extensions/ql-vscode/src/queries-panel/query-discovery.ts, extensions/ql-vscode/src/queries-panel/query-tree-data-provider.ts, extensions/ql-vscode/src/queries-panel/query-tree-view-item.ts, extensions/ql-vscode/src/query-testing/qltest-discovery.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/queries-panel/query-tree-data-provider.test.ts
Updates the `QueryTreeViewItem`, so that it can display the language of a CodeQL query (and display it in the UI). This involved updating the shared `FileTreeNode` class to accept a generic `data` property. 
This will hook in to https://github.com/github/vscode-codeql/pull/2471 (which gets the actual query language). For now, I've hard-coded a placeholder string: 
N/A—internal only 🌍 See internal linked issue for more details! 🤫
=> Queries panel: display the query language in the UI

extensions/ql-vscode/src/common/app.ts, extensions/ql-vscode/src/common/file-tree-nodes.ts, extensions/ql-vscode/src/common/vscode/environment-context.ts, extensions/ql-vscode/src/common/vscode/vscode-app.ts, extensions/ql-vscode/src/queries-panel/query-discovery.ts, extensions/ql-vscode/src/query-testing/qltest-discovery.ts, extensions/ql-vscode/test/__mocks__/appMock.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/queries-panel/query-tree-data-provider.test.ts
Adds `EnvironmentContext` to the `App` which allows access to the `vscode.env.language`, for use with calls to `localeCompare` and similar. This PR shows how much change is needed in order to support passing the env data to where it's needed in `FileTreeNode`.
I've done just this one usage because it will fix https://github.com/github/vscode-codeql/security/code-scanning/518, but obviously in future we could use this in more places. we've got an internal issue to track this and make sure we're doing localisation consistently.
=> Add EnvironmentContext so common code can do localisation

extensions/ql-vscode/src/data-extensions-editor/extension-pack-picker.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/extension-pack-picker.test.ts
When packaging an extension pack, unscoped extension pack names are not allowed and calling `codeql pack bundle` will fail with an error. This command will be called when running a variant analysis, so these packs will not work for a variant analysis.
To improve the user experience, we now only allow scoped extension pack names. This means that the user will now have to enter a scope when creating a new extension pack.
=> Only allow scoped extension pack names

extensions/ql-vscode/src/databases/code-search-api.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/variant-analysis/gh-api/gh-api-client.ts
Instead of using repo search we want to use the code search api for this feature. Since the search api returns an error if two language parameters are added we made the entry of a language through the UI optional.
Items:
- uses correct api
- implements throttling
- makes 'no language' available
=> Code search: use code search api

extensions/ql-vscode/src/common/vscode/abstract-webview.ts, extensions/ql-vscode/src/common/vscode/webview-html.ts, extensions/ql-vscode/src/interface-utils.ts
This moves the Webview HTML generation used by `AbstractWebview` out of `interface-utils.ts` and into a new file `webview-html.ts` in the `common/vscode` directory.
=> Move Webview HTML generation out of `interface-utils.ts`

extensions/ql-vscode/src/data-extensions-editor/auto-model.ts, extensions/ql-vscode/test/unit-tests/data-extensions-editor/auto-model.test.ts
Tweak candidate selection:
- Do not send methods modeled outside the file as candidates.
- At most 6 usages.
- Send -1 for `this` argument.
- Do not send only some arguments for candidate or sample.
=> Tweak candidate selection

extensions/ql-vscode/CHANGELOG.md
A tiny fix to the changelog to say "variant analysis" (since we haven't been using "MRVA" in public-facing docs). As @norascheuch mentioned offline, this got fixed but accidentally overridden in https://github.com/github/vscode-codeql/pull/2466, but we didn't want to hold up the release at the time!
=> Update changelog (MRVA -> variant analysis)

extensions/ql-vscode/package.json
To match what the code actually does.
=> Expand description for `codeQL.cli.executablePath`

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
We don't seem to be using this dependency anymore, so we can remove it.
=> Remove `@types/xml2js` dependency

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/interface.ts, extensions/ql-vscode/src/local-queries/index.ts, extensions/ql-vscode/src/local-queries/local-queries.ts, extensions/ql-vscode/src/local-queries/local-query-run.ts, extensions/ql-vscode/src/local-queries/webview.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/local-queries/webview.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts
This moves the two remaining methods in `interface-utils.ts` to `local-queries/webview.ts`. This removes the ambiguously named `interface-utils.ts` file.
=> Move interface-utils to local-queries/webview

extensions/ql-vscode/src/databases/local-databases/database-item-impl.ts, extensions/ql-vscode/src/databases/local-databases/database-manager.ts, extensions/ql-vscode/src/pure/files.ts, extensions/ql-vscode/test/matchers/toEqualPath.ts, extensions/ql-vscode/test/unit-tests/pure/files.test.ts
For context, in https://github.com/github/vscode-codeql/pull/2490 I started added my own method to determine if one paths contains another, but then I realised that we already have `files.ts` and `containsPath`.
Unfortunately `containsPath` uses a `startsWith` implementation and this isn't correct for examples like `/foo` and `/foobar`. In this case neither path is a parent of the other, but they do share `/foo` as a prefix.
This PR changes the implementation to use `path.relative` to do the work of deciding if a path contains another. We can also now remove the call to `normalizePath` from this method, as `relative` performs the same normalization as the `resolve` method. The only catch is we have to handle different drives on windows. See …
=> Fix containsPath for paths that share a prefix

extensions/ql-vscode/src/data-extensions-editor/bqrs.ts, extensions/ql-vscode/src/data-extensions-editor/external-api-usage.ts, extensions/ql-vscode/src/data-extensions-editor/queries/csharp.ts, extensions/ql-vscode/src/data-extensions-editor/queries/java.ts, extensions/ql-vscode/src/data-extensions-editor/queries/query.ts, extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx, extensions/ql-vscode/src/stories/data-extensions-editor/MethodRow.stories.tsx, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx, extensions/ql-vscode/test/unit-tests/data-extensions-editor/auto-model.test.ts, extensions/ql-vscode/test/unit-tests/data-extensions-editor/yaml.test.ts
This adds a new library column to the data extensions editor containing the JAR or DLL file the method is defined in. This will be used to group methods by library in the future. For now, it just shows in a column.
=> Add library to data extensions editor

extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx
This groups the modeled methods in the data extensions editor by library:
For now, it's sorted by name. Follow-up PRs will change this to be based on other factors, such as usages and the modeled percentage.
=> Group modeled methods by library in the data extensions editor

extensions/ql-vscode/src/data-extensions-editor/bqrs.ts, extensions/ql-vscode/src/pure/word.ts, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx, extensions/ql-vscode/src/view/data-extensions-editor/formatters.ts, extensions/ql-vscode/test/unit-tests/data-extensions-editor/bqrs.test.ts, extensions/ql-vscode/test/unit-tests/pure/word.test.ts
This implements the following improvements to the grouping of libraries:
- Libraries can now be collapsed
- Libraries which are fully modeled are collapsed by default
- Each library shows the number of methods, the number of usages, and the modeled percentage
- When a library is collapsed, the number of methods and the modeled percentage are shown in the row with the library name
- Libraries are sorted by their modeled percentage and the number of usages rather than name
https://github.com/github/vscode-codeql/assets/1112623/d0b53104-e8a2-4b52-9de6-eb8a43a4039f
=> Improve grouping of libraries

extensions/ql-vscode/src/queries-panel/queries-module.ts
It's still hidden behind two feature flags, so won't disrupt general users. But at least this will allow non-developers more easy access to the panel. (For testing/feedback)
N/A—internal only 🐸
=> Allow queries panel to be visible in non-dev mode

extensions/ql-vscode/test/unit-tests/command-lint.test.ts, extensions/ql-vscode/test/unit-tests/pure/helpers-pure.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/debugger/debug-controller.ts
Should we be using the `fail` method? We seem to be using it in a few tests to catch incorrect setup, so if everything is correct then this code path doesn't run. But when it does run it appears the `fail` method isn't defined. See the following error:
I haven't looked deeply into this yet, so I'm not sure if there's something else causing the above failure and maybe we do still want to use `fail`. But I wonder is there any downside to throwing an exception in any of these cases instead?
=> Throw error instead of using fail method

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/common/path.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/data-extensions-editor/extension-pack-picker.ts, extensions/ql-vscode/src/data-extensions-editor/shared/extension-pack.ts, extensions/ql-vscode/src/data-extensions-editor/shared/view-state.ts, extensions/ql-vscode/src/data-extensions-editor/yaml.ts, extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisHeader.tsx, extensions/ql-vscode/test/unit-tests/common/path.test.ts, extensions/ql-vscode/test/unit-tests/data-extensions-editor/yaml.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/extension-pack-picker.test.ts
This will remove the user input for a model file and will instead create 1 model file per library (JAR/DLL). The model filename will be based on the JAR/DLL name, but will remove the version number and the file extension. It will also normalize the name.
These files will be created automatically, and the editor now also reads in all files contained in an extension pack to read the modeled methods. This could result in duplicates if the user has created a different file to contain the same modeled methods, but this is an edge-case that we're explicitly not handling.
=> Automatically create different model files per library

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/data-extensions-editor/auto-model-usages-query.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/data-extensions-editor/extension-pack-name.ts, extensions/ql-vscode/src/data-extensions-editor/external-api-usage-query.ts, extensions/ql-vscode/src/data-extensions-editor/queries/csharp.ts, extensions/ql-vscode/src/data-extensions-editor/queries/java.ts, extensions/ql-vscode/src/data-extensions-editor/queries/query.ts, extensions/ql-vscode/src/data-extensions-editor/shared/mode.ts, extensions/ql-vscode/src/data-extensions-editor/shared/view-state.ts, extensions/ql-vscode/src/data-extensions-editor/yaml.ts, extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx, extensions/ql-vscode/test/unit-tests/data-extensions-editor/yaml.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/external-api-usage-query.test.ts
This adds an initial rough implementation of framework mode for the data extensions editor. Framework mode will do the following:
- Load public methods instead of external API calls
- Group by package instead of library
- Remove the usages in the table because we do not have access to usages
- Change "Download and generate" to "Generate"
Short demo:
https://github.com/github/vscode-codeql/assets/1112623/b985942b-a9aa-4c64-b025-c8c14157214c
=> Add initial implementation of framework mode

extensions/ql-vscode/src/view/results/raw-results-table.tsx
Converts the `RawTable` from a class component to a function component.
Paired on this with @norascheuch and @shati-patel.
As far as I can tell, all the behaviour still works. The only complicated bit is the scroller. You can trigger this behaviour by using the `codeQLQueryResults.down` command (and similar commands for other directions) to navigate around the raw results table. When the selection goes off the screen it'll scroll to bring it back to the centre.
=> Convert RawTable to a function component

extensions/ql-vscode/src/data-extensions-editor/auto-model.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/data-extensions-editor/shared/modeled-percentage.ts, extensions/ql-vscode/src/data-extensions-editor/shared/sorting.ts, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx, extensions/ql-vscode/test/unit-tests/data-extensions-editor/auto-model.test.ts, extensions/ql-vscode/test/unit-tests/data-extensions-editor/shared/modeled-percentage.spec.ts
This changes the sorting of the methods sent to LLM to match the order shown in the data extensions editor. This will ensure that the methods which are shown first in the data extensions editor are also modeled first.
=> Sort methods sent to LLM the same way as the UI

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/local-queries/local-queries.ts
Based on https://github.com/github/vscode-codeql/pull/2534. Adds an extra command to run a local query from the right-click context menu (only for an individual `.ql` file, not for folders of queries):
PS: I'm happy to change the approach here, depending on changes to #2534! 
N/A—still feature-flagged 🏴
=> Run local query from Queries Panel context menu

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/local-queries/local-queries.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/run-queries-shared.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-results.test.ts
This allows using quick-eval-count via the command palette. Quick eval count generates column counts and overall count of the results instead of generating locations and strings. As generating locations and strings can be expensive and the number of results is often more useful this can shave time off debugging complex queries. As this is fairly advanced and to avoid cluttering the context menu I have not added a context menu. We can revisit this in future.
@dbartol I am leaving it to you to decide how to integrate this into the debugging workflow. This should probably be treated like a quick-eval option there.
=> Add quick eval count to the command palette

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
Based on https://github.com/github/vscode-codeql/pull/2546. Adds an extra command to run a local query from the right-click context menu of the queries panel (only for an individual `.ql` file, not for folders of queries):
N/A—still feature-flagged 🏳
=> Run variant analysis from Queries Panel context menu

extensions/ql-vscode/src/data-extensions-editor/queries/csharp.ts, extensions/ql-vscode/src/data-extensions-editor/queries/java.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/external-api-usage-query.test.ts
This refactors the data extensions editor queries to use a new `AutomodelVsCode` module. This module is based on the `ExternalApi` module, but is more general and can be used for retrieving public methods from the source as well. The actual conditions are now in the queries themselves.
This reduces the duplicated module in the framework mode query and will mean that when we update the `ExternalApi` module, we will just have to port it to the `AutomodelVsCode` module, and not to the `ExternalApi` and a separate framework mode query.
=> Refactor data extensions editor queries to reduce duplication

extensions/ql-vscode/src/data-extensions-editor/queries/java.ts
This changes the Java `CallableMethod.getApiName()` to use `nestedName` instead of `getSourceDeclaration`. `getSourceDeclaration` would return a `RefType`, on which the `toString()` method returns its `getName`(). However, for nested types this wouldn't work and wouldn't include the enclosing type. This fixes it by using `nestedName` which matches the method that is also used for determining whether a type matches an extensible predicate.
=> Use `nestedName` for getting the name of an API

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/local-queries/local-queries.ts, extensions/ql-vscode/src/queries-panel/query-tree-view-item.ts
Adds a run-all icon to folder elements in the new panel to run local queries.
=> Queries Panel: run-all queries of a folders

extensions/ql-vscode/src/data-extensions-editor/queries/csharp.ts
Similar to https://github.com/github/vscode-codeql/pull/2553, this changes the C# query to correctly report the name of nested types. I couldn't find a `nestedName` method for C#, so this adds one in the `AutomodelVsCode` library.
C# seems to use `+` as a separator for nested types, as reported by `getQualifiedName()`:
```
GitHub.Nested.MyFirstClass+NestedClass
```
The `getApiName()` will now report:
```
GitHub.Nested#MyFirstClass+NestedClass.Test()
```
=> Add `nestedName` function for C#

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/local-queries/local-queries.ts
Adds a command to run all queries in a certain folder. This uses the existing `runQueries` command, which lets you run multiple queries against the selected local database.
⚠️ We don't have a corresponding command for running multiple variant analysis queries, so I haven't implemented that. It's probably a separate product discussion of whether we want to allow users to start multiple variant analysis runs in one click? 🤔 
N/A (feature-flagged for internal use)
=> Queries panel: Run all queries in folder (context menu)

extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx
This makes the method name and parameters in framework mode a link to the definition of the method. In framework mode, the `usages` contains 1 element, which is the location of the definition of the method. Therefore, we can simply use `jumpToUsage` to jump to the definition.
=> Add jump to definition in framework mode

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
This adds a refresh button to the data extensions editor when the framework mode feature flag is enabled. If you are using framework mode, you can have multiple tabs of the data extensions editor open in which you are modeling the library separately from the application. When you save the library in framework mode, the application mode will not refresh and show that these calls have been modeled. Rather than using apply, which might also save all modeled methods, you can now use the refresh button to refresh the external API usages and whether they are supported.
=> Add a refresh button to the data extensions editor

extensions/ql-vscode/src/view/results/alert-table.tsx, extensions/ql-vscode/src/view/results/result-tables.tsx
In preparation for converting `PathTable` to a function component, rename it to a clearer name.
The file is called `alert-table.tsx` and I think that `AlertTable` is a more understandable name than `PathTable`. This table is used whenever there are "SarifInterpretationData", which includes `problem` and `path-problem` queries.
=> Rename PathTable => AlertTable

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/vscode/file-path-discovery.ts, extensions/ql-vscode/src/local-queries/local-queries.ts, extensions/ql-vscode/src/queries-panel/query-discovery.ts, extensions/ql-vscode/src/queries-panel/query-pack-discovery.ts, extensions/ql-vscode/src/queries-panel/query-tree-data-provider.ts, extensions/ql-vscode/src/queries-panel/query-tree-view-item.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/common/vscode/file-path-discovery.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/queries-panel/query-discovery.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/queries-panel/query-tree-data-provider.test.ts
Displays a "loading" message while query discovery has not yet finished, and a separate message when no queries have been found. This should help avoid confusing users by saying there are no queries when really the discovery is just in progress.
The approach I've taken is to make the welcome message the "loading" message, and display a custom text node for the "no queries" case. This helps avoid the effect seen in https://github.com/github/vscode-codeql/pull/2523#issuecomment-1597245642 where it flips between the two options before the extension has started initialising.
For the datatypes I opt to create subclasses for `QueryTreeQueryItem` and `QueryTreeTextItem`, where `QueryTreeQueryItem` is identical to the old `QueryTreeViewItem`. We could maybe split this up further into "node" and …
=> Display different message when queries are loading vs no queries found

extensions/ql-vscode/src/view/results/alert-table-header.tsx, extensions/ql-vscode/src/view/results/alert-table.tsx
This PR tries to pull out the table header to a separate file to make the `PathTable` component and file a bit smaller. This is a stepping stone to converting `PathTable` to a function component.
I think this is worth it because the props for the header are surprisingly small, and there are quite a few supporting functions that we can also move. So overall I think it removes a moderate amount of complexity from `PathTable`. It's unlikely that the `AlertTableHeader` component could be reused, but reuse wasn't really a driving factor and the main focus is on reducing the size of `alert-table.tsx`.
The new class is named `AlertTableHeader` rather than `PathTableHeader` because I'm assuming that https://github.com/github/vscode-codeql/pull/2570 will also be merged.
=> Pull out AlertTableHeader to a separate component/file

extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx
Updates the title bar of the modelling tables to match the new designs:
I removed the old status info, since that is not present in the new designs.
A lot of manual styling was needed to get these new elements looking like the designs. Hopefully that's ok, but if it's too complicated or it's straying a bit too far from VS Code design principles then we can look at that.
The "Model with AI" / "Model from source" buttons and the "UNSAVED" label aren't hooked up to anything yet, but we'll get to those in a later PR. I gave them all no-op handlers for now. Since the data extensions view is not released yet we're not too worried about how the view looks while this work is in progress.
=> Update data extensions modelling table title bar

extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx
Adds a dividing line after the title.
=> Data extensions UI: Add divider between title and status containers

extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx
Add save button to the "bottom bar" of each individual library model:
(The button doesn't do anything yet, but stay tuned!)
N/A - internal only for now
=> Data extensions UI: Add save button

extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx
Encases each "library" container in a snazzy background with rounded corners: 
N/A - feature-flagged for internal users 🦺
=> Data extensions UI: Change background colour of library container

extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx
The main goal here is making the number of usages not all be single-digit numbers. This helps show up errors in the column alignment of the table much more easily.
Rather than writing out each array element, I'm using `Array(10).fill(...)` to create an array of arbitrary size. Each element of the array will be the same object, but I think that's fine for this story.
=> Use more varied data for the number of usages

extensions/ql-vscode/src/view/common/Dropdown.tsx, extensions/ql-vscode/src/view/data-extensions-editor/KindInput.tsx, extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodDataGrid.tsx
Converts the data extensions table to match the new designs:
The changes are:
- Merge data into the "API or method" column, which now includes:
- the package, class, method name, and parameter
- a checkbox (which later on will show modelling status)
- the usage count
- an explicit link to view usages (though clicking the usage count number does still work)
- The inputs in the table are disabled but still visible, instead of being completely hidden
- The value in the cell is still hidden, otherwise I think it's odd seeing content in the disabled inputs
- The red/green colouring is removed
- It's my understanding this isn't mean to be a part of the new design. If that's not the case I can easily add it back in.
The bit I'm most unsure of is whether the whole "API or method" bit should be …
=> Update data extensions modelling table to new designs

extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx
Some minor adjustments to the saved/unsaved buttons: 
- Uses the "VS Code Tag" from the UI toolkit for the "UNSAVED" label
- Moves the "Save" button further away from the border
N/A—internal only 🎃
=> Data extensions editor: Update styling of "unsaved" tag

extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx
Changes these buttons to use `appearance='icon'` instead of custom styling.
Light mode (showing hovering and non-hovering):
Dark mode (showing hovering and non-hovering):
=> Use better colours for title buttons

extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx
Paired with @shati-patel on this.
Hooks up the "Save" button in each collapsible section to save only the changes made to that model. Thankfully this turned out not to be too hard since the implementation of `saveModeledMethods` already (perhaps unintentionally) handles being gives only the methods from one model, because it splits the methods it's given into models and then saves only those files. Therefore it won't overwrite or delete other models that aren't being saved.
We also had to change how `setUnsavedModels` is called. I think what we were doing before was not quite fully correct but we were getting away with it. Now that we can save just one model at a time we need to be more granular.
We've tested this manually but checking that each model is saved individually and none of the …
=> Implement saving only one model at a time

extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx
Addresses two points that were previously forgotton:
- Only shows the "Model with AI" button when the view state says we should do.
- Adds the "Model dependency" (i.e. framework mode) button.
Screenshots with and without settings enabled:
=> Only show LLM / framework mode when the view state says to show the button

extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx
Hooks up the "Model with AI" in each collapsible section to work on just methods from that model. Follows a very similar approach to the "save" button. This thankfully is quite easy since we pass all the data back to the extension host, so we can just send only the data for that model. From then on the extension host sends back some modelled methods and it all works the same as it did before.
The old "Generate using LLM" in the header still works on everything. This button will be removed at a later date once we've finished redesigning the collapsible sections.
Note: the "unsaved" label is a little broken and doesn't update correctly when modelling with AI. It's already broken before this change too so so my rough plan was to go forward with this PR and address it in a separate PR. That …
=> Use AI to model just a single section

extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx
This hooks up the existing handler that sends a `generateExternalApi` message to the new collapsible sections. I believe that the behaviour for the button in the header and button in each section basically needs to be the same.
When used it will prompt the user for a github repository name, attempt to download the CodeQL database, and then generate some models. In the future we hope to not have to ask for the repository name and instead determine it from the dependency name, but right now we haven't implemented that. So for right now the button on each section is identical and it doesn't matter which one you click. It's my understanding that this is ok for now. If we want it'll be easy to hide the button on each section and only show a single button in the header, so this PR is pretty low …
=> Hook up generating from source in the new collapsible section

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
This is an attempt to fix the behaviour around showing the "unsaved" label and enabling the save button. Previously it wasn't correctly showing a model as unsaved when generating from the LLM or modelling from source.
The approach in this PR works, but it feels a bit inelegant and brute-forcey. I also don't love that the listener has gained dependencies on a couple of different bits of state, but maybe it's ok as those bits of state don't actually change too often.
Any other suggestions for how to implement this? I tried a few variations of putting names of the affected models in `AddModeledMethodsMessage`, or putting the library/packageName on `ModeledMethod`, but both turned out to be pretty hard to do as we just don't have the info available when generating the modelled methods.
=> Include in addModeledMethods whether the methods are unsaved or not

extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx
I realised we were passing in both `ViewState` and `Mode` to some components. This is a mistake I made earlier and didn't realise the view state was already available.
I also take the opportunity to simplify the types and avoiding passing a possibly-undefined view state around as much as possible. This shouldn't ever be undefined in practice because the first thing we do once the view is loaded is to send a `setDataExtensionEditorViewState` message. The fact that we have to do this is a drawback of the webview model where we have to send initialisation data only after the view is loaded. I think we can treat the brief window where the view state is undefined as a "loading" phase and display a message. This way for the rest of the code we are sure that the variable is defined. In practice …
=> Clear up how we pass around view state

extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx
This PR does some refactoring of the `MethodRow` component to split it into two cases:
- When the method can be modeled, which is most of the implementation.
- When the method cannot be modeled, because it is already modeled by another source such CodeQL or another extension pack than the one we're currently editing.
We then finally add a simple message saying that a method is already modeled and cannot be edited.
The refactoring is not strictly necessary, and I can remove it or pull it out to two separate PRs if that would be easier. What I like about the refactoring and splitting into two components is that we don't have to define all the various handlers and other computation for the unmodelable case where we don't use any of them.
Note that right now I don't think we can tell between …
=> Show more clearly when a method is already modeled

extensions/ql-vscode/src/data-extensions-editor/bqrs.ts, extensions/ql-vscode/src/data-extensions-editor/external-api-usage.ts, extensions/ql-vscode/src/data-extensions-editor/queries/csharp.ts, extensions/ql-vscode/src/data-extensions-editor/queries/java.ts, extensions/ql-vscode/src/data-extensions-editor/queries/query.ts, extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx, extensions/ql-vscode/src/stories/data-extensions-editor/MethodRow.stories.tsx, extensions/ql-vscode/src/view/data-extensions-editor/MethodClassifications.tsx, extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx, extensions/ql-vscode/test/unit-tests/data-extensions-editor/auto-model.test.ts, extensions/ql-vscode/test/unit-tests/data-extensions-editor/yaml.test.ts
This will add a "Test" or "Generated" tag on the method if it's only used in tests or generated code and not in the actual application source code. It also adds retrieving the method "type" (e.g. source or sink) to the queries, but does not show these yet.
=> Add call classification and supported kind to data extensions editor

extensions/ql-vscode/src/data-extensions-editor/bqrs.ts, extensions/ql-vscode/src/data-extensions-editor/external-api-usage.ts, extensions/ql-vscode/src/data-extensions-editor/library.ts, extensions/ql-vscode/src/data-extensions-editor/queries/csharp.ts, extensions/ql-vscode/src/data-extensions-editor/queries/java.ts, extensions/ql-vscode/src/data-extensions-editor/queries/query.ts, extensions/ql-vscode/src/data-extensions-editor/yaml.ts, extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx, extensions/ql-vscode/test/unit-tests/data-extensions-editor/bqrs.test.ts, extensions/ql-vscode/test/unit-tests/data-extensions-editor/library.test.ts, extensions/ql-vscode/test/unit-tests/data-extensions-editor/yaml.test.ts
This adds the versions of libraries to the data extensions editor and hides the filename for Java libraries.
=> Add library versions to data extensions editor

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/databases/database-fetcher.ts, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx
This PR adds the implementation for the "model dependency" button. This prompts the user for a repository name, then downloads that repository and opens a new data extensions window in framework mode.
This shares a bunch of implementation with the "model from source" button because they both prompt the user to download a new database. I think both of these will continue to share implementation, so any improvements we make will apply to both.
I have encountered problems when the new databases causes the workspace to transition from single-root to multi-root. I have some ideas for things we can do about this, and these might help with "model from source" as well if that shares the same issue. However I'm thinking about raising those changes as separate PRs.
=> Implement "model dependency" button in application mode

extensions/ql-vscode/src/common/query-language.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/data-extensions-editor/extension-pack-picker.ts, extensions/ql-vscode/src/data-extensions-editor/shared/extension-pack.ts, extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/test/vscode-tests/cli-integration/data-extensions-editor/modeled-method-fs.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/extension-pack-picker.test.ts
Changes the title from this:
to this:
See internal issue for the linked designs! 
N/A: this is still internal and feature-flagged 🏴
=> Update title in Data extensions editor tab

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/databases/database-fetcher.ts
For "model from source" and "model dependency" we were importing the new database, setting it as the current database, and then resetting the current database back to what it was before. Instead we can pass through `makeSelected = false` all the way to `openDatabase` and therefore not have to remember and reset the current database.
Needs some testing for edge cases, but it seems to work for me.
=> Instead of resetting the database after importing, pass through makeSelected = false

extensions/ql-vscode/package.json, extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/src/query-server/legacy/query-server-client.ts, extensions/ql-vscode/src/query-server/legacy/run-queries.ts, extensions/ql-vscode/src/query-server/query-server-client.ts
We dropped support for CLI versions older than 2.9.4 in https://github.com/github/vscode-codeql/pull/2610.
This PR removes conditionals and version constraints for unsupported CLI versions.
See individual commits for more details.
N/A:
=> Remove conditionals and version constraints for unsupported CLI versions

extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
Removes/renames some buttons. See internal issue for more details!
✌🏽 Application mode:
😎 Framework mode: 
N/A: feature-flagged for internal use ⛳
=> Data extensions editor: Remove buttons that are no longer needed

extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx
Minor change to simplify the message when a method is already modeled: 
See internal linked issue! 
N/A: internal only 🦒
=> Data extensions editor: Change "already modeled" message

extensions/ql-vscode/src/data-extensions-editor/generate-flow-model.ts, extensions/ql-vscode/src/language-support/contextual/location-finder.ts, extensions/ql-vscode/src/language-support/contextual/query-resolver.ts, extensions/ql-vscode/src/language-support/contextual/template-provider.ts, extensions/ql-vscode/src/local-queries/index.ts, extensions/ql-vscode/src/local-queries/query-resolver.ts, extensions/ql-vscode/src/local-queries/standard-queries.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/language-support/contextual/query-resolver.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/local-queries/query-resolver.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/local-queries/standard-queries.test.ts
This will make the query resolving functionality currently used for contextual queries more generic and usable for resolving other types of queries as well (e.g. based on `tags` instead of on `id`). This is in preparation for https://github.com/github/vscode-codeql/pull/2633. There should be no changes in behavior, except for a single changed error message (which adds `kind "definitions",` to the error message, so shouldn't really have any influence).
=> Make query resolver more generic

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
This PR removes the custom progress bar that the data extensions editor used and instead uses the regular `withProgress` function to get a native VS Code notification with a progress bar. All behaviour is otherwise the same. I recommend trying it out to see what it looks like.
I also recommend reviewing with "ignore whitespace" enabled.
=> Remove custom progress bar and use normal VS Code notification for progress

extensions/ql-vscode/src/local-queries/standard-queries.ts
Fixes a semantic merge-conflict between https://github.com/github/vscode-codeql/pull/2634 and https://github.com/github/vscode-codeql/pull/2631.
Hopefully we won't see this again. It should only affect PRs that were open before https://github.com/github/vscode-codeql/pull/2631 was merged and don't re-run their `Lint` CI check.
=> Unexport LockFileForStandardQueryResult

extensions/ql-vscode/gulpfile.ts/webpack.config.ts, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/view/results/locations/SarifLocation.tsx
This will remove our dependency on `path-browserify` and replace one last instance of an import from `path` to using `src/common/path.ts`.
If you now try to import the `path` module, you'll get an error from Webpack:
=> Remove path-browserify

extensions/ql-vscode/src/view/results/result-tables.tsx
This should hopefully fix https://github.com/github/vscode-codeql/security/code-scanning/547 by replacing the inefficient regex with `path.basename`. As far as I can tell, this is the job that the regex is performing.
Is there are a need for us to do anything more complicated than `path.basename`? I believe all of this is happening locally, so there's no need to do anything fancy like handle paths from other operating systems.
=> Fix alert by replacing regex with path.basename

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
The "Model from source" and "Model dependency" buttons currently automatically prompt you to download a database, even if you already have a relevant DB in your workspace. This PR changes that behaviour, so that users can choose a local one if they want to:
N/A: Internal only 🦀
=> Data extensions editor: Allow users to pick an existing database from their workspace

extensions/ql-vscode/src/query-history/query-history-scrubber.ts
This PR aims to fix https://github.com/github/vscode-codeql/security/code-scanning/384
We could maybe also get away with just closing the alert as "wont fix". It's not the most important of use-after-check errors. But I think we can make things a little bit better.
I'm not sure there's a way to rewrite the check to use file descriptors as the alert suggests. Although we could pass a file descriptor to `readFile`, I don't think `pathExists` or `stat` support them.
I think a better solution may be to rewrite the function to only make a single access to the file. All we need to do is to attempt to read its contents and then we can determine a lot of the rest from whether that succeeds or fails. We do lose some information so we can't keep 100% of the different error messages, but it's …
=> Fix alert by rewriting query history scrubbed to do fewer file operations

.github/codeql/queries/unique-command-use.ql
Fixes https://github.com/github/vscode-codeql/security/code-scanning/546
The first commit fixes all the indentation in the query, so I suggest ignoring that or at least reviewing with whitespace ignored.
The second commit updates the query to know about built-in VS Code commands and not to create an alert for those commands.
My reasoning for not alerting on built-in commands is that:
- We don't emit telemetry from them, because we haven't provided the implementation.
- We can't avoid calling them from multiple places, again because we haven't provided the implementation we can't make duplicate commands with different names.
=> Don't alert for multiple usages of built-in VS Code commands

extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx
Makes the "Hide modeled APIs" checkbox actually hide modeled APIs from the view! ✅ (With help from @robertbrignull 🙏🏽)
See internal issue for more details 🔍 
N/A: Internal only 🐄
=> Data extensions editor: Implement "Hide modeled APIs" checkbox and make it the default

extensions/ql-vscode/test/vscode-tests/cli-integration/legacy-query.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/new-query.test.ts
This PR modifies `legacy-query.test.ts`, which tests integration with the legacy query server in the CodeQL CLI (i.e., `codeql execute query-server`), to run only for CLI versions that are too old to support the new query server (i.e., `codeql execute query-server2`).  The vscode extension automatically selects the new query server whenever possible, so it should be sufficient to test legacy query server integration only with old CLI versions.
See back-linked internal issue for additional context.
=>  legacy-query.test.ts: skip if CLI supports new query server

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-view-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-view.ts, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts
Fixes https://github.com/github/vscode-codeql/security/code-scanning/461
`codeQL.copyVariantAnalysisRepoList` is used from two places, but they're both internal so it's trivial to split the command into two.
=> Split codeQL.copyVariantAnalysisRepoList into two commands

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
We currently show the button for both Java and C# and the solution doesn't work for C#.
N/A:
=> Only show automodel button for Java

extensions/ql-vscode/package.json
Sometimes the tests can fail to run and cleaning the `.vscode-test` dir is necessary to fix them. This PR adds this as a npm script so it's easier to remember that this option exists and what to do.
Is using `rm` and this path ok? Will this be ok for all operating systems?
Alternative suggestions for naming are also welcome.
=> Add `npm run clean-test-dir`

extensions/ql-vscode/test/vscode-tests/cli-integration/data-extensions-editor/modeled-method-fs.test.ts
#2655 was not sufficient in fixing the integration test. I forgot that we
need to install all transitive dependencies of `java-all` as well. This will do it.
=> Install `java-all` and transitive dependencies

extensions/ql-vscode/src/view/results/result-tables.tsx
It was introduced in https://github.com/github/vscode-codeql/pull/602 and as far as I can tell it's always been unused. It seems just to be an error in that PR and the actual setting of state is done in `handleCheckboxChanged`.
Our deadcode detection seems to not be working for public methods on components like this.
=> Delete untoggleProblemsView as it is unused

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/language-support/query-editor.ts
This commit fixes a bug in the extension where the qhelp preview was not being refreshed after the first time the preview was rendered. The reason is that vscode will not refresh the markdown preview unless the original file with the markdown in it is already open in the editor.
This fix will briefly open the raw markdown, refresh the preview and close the raw markdown.
=> Ensure the qhelp preview is refreshed after editing

extensions/ql-vscode/src/query-history/query-history-scrubber.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-scrubber.test.ts
I believe that these changes might help with the flakes in the query history scrubber tests.
Most of the test failures that I've seen look like:
```
FAIL query-history/query-history-scrubber.test.ts (5.957 s)
● query history scrubber › should not throw an error when the query directory does not exist
expect(received).toBe(expected) // Object.is equality
Expected: 0
Received: 16
69 |     await wait();
70 |     // "Should not have called the scrubber"
> 71 |     expect(runCount).toBe(0);
|                      ^
72 |
73 |     jest.advanceTimersByTime(ONE_HOUR_IN_MS - 1);
74 |     await wait();
```
So this means when the test started the `runCount` variable wasn't set to zero! 🤯 
I believe this is because individual test run is receiving a reference to the same `runCount` variable, because …
=> Try to fix flakes in query history scrubber tests

extensions/ql-vscode/src/variant-analysis/gh-api/mocks/gh-api-request.ts, extensions/ql-vscode/src/variant-analysis/gh-api/mocks/recorder.ts, extensions/ql-vscode/src/variant-analysis/gh-api/mocks/request-handlers.ts
This follows the same approach as other API requests we mock out.
Appreciate that the mock API server currently lives inside /variant-analysis. I'll create an internal issue to move it out.
N/A:
=> Add support for automodel requests in the mock API server

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
I ran [depcheck](https://www.npmjs.com/package/depcheck) and then manually went through the results looking at which ones were genuinely unused. As far as I can tell, all of these are unused and can be removed.
After removing each dependency I ran `npm install` and `npm run build && npm run check-types`. I've also tried building and running the extension in development mode and installing from a file.
Of these:
- I'm fairly confident that the `@types` packages are correct. If any of these were used then the `check-types` script would fail.
- It may appear that `stream` is used from `cli.ts` and other files, but that is actually the built-in node.js stream implementation. The `stream` package is for providing the same implementation inside the browser/webviews, and we aren't using it in …
=> Remove unused NPM dependencies

extensions/ql-vscode/src/data-extensions-editor/auto-model-codeml-queries.ts, extensions/ql-vscode/src/data-extensions-editor/auto-model-v2.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/test/unit-tests/data-extensions-editor/auto-model-v2.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/auto-model-codeml-queries.test.ts
This implements batched LLM querying with the following logic:
- From the external API methods in context, get a slice (size 20) of un-modeled methods to consider candidates.
- Create an filter-pack for those candidates.
- Run the automodel candidate queries with that filter-pack in context.
- Send SARIF to LLM.
- Post-progress the results from the LLM, and consider all candidates without an explicit classification as netutral elements.
=> Use filtering queries to do batched AI querying

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
This is a very small refactor that splits the code paths between automodel v1 and automodel v2 further up. I got the original `generateModeledMethodsFromLlm` method and copy pasted it, named one of the functions `generateModeledMethodsFromLlmV1` and the other `generateModeledMethodsFromLlmV2`, then simply cleaned up the code to only to do v1 stuff in one `generateModeledMethodsFromLlmV1` and v2 stuff in `generateModeledMethodsFromLlmV2`. I haven't any other significant changes.
The two code paths are about to diverge further, so having separate functions will make it easier to make changes to them independently. We could also jut get rid of V1 for now, but that seemed like a bigger change to take on right now.
N/A:
=> Move automodel version split further up

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/InProgressDropdown.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx
Add the ability to mark methods as being "in progress" for modeling. This will be used for the AI modeling flows. The exact UX is still TBD, but some initial mock-ups show a progress ring and drop-downs being replaced with "Thinking...".
I followed the same approach as the one we use to track modified methods which unfortunately has a bit of prop drilling but I don't think it's too bad and we can improve that separately if we like.
Note that this new state and view message is not used yet - it'll be plugged in in a later PR. It can be seen in action using the storybook.
N/A:
=> Add in-progress UI state for modeling methods

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/data-extensions-editor/external-api-usage.ts, extensions/ql-vscode/src/data-extensions-editor/model-details/model-details-data-provider.ts, extensions/ql-vscode/src/data-extensions-editor/model-details/model-details-panel.ts
This PR adds `ModelDetailsPanel` and `ModelDetailsDataProvider`, and populates the tree view with data whenever new external API usages are calculated.
This isn't perfect, but everything is hidden behind a feature flag so I think this is a suitable step in the right direction. There are still lots of changes to make, which we'll do in future PRs. For example:
- Handling when there are multiple data extensions editor windows open at once.
- Making sure data is always updated when new external API usages are calculated.
- Styling of the details panel, with icons and better labels.
- Jumping to definition when clicking an item.
=> Populate details panel with external API usages

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/data-extensions-editor/auto-modeler.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx
We will need the dependency name in order to manage automodeling jobs so this is a quick PR to make sure it's available.
N/A:
=> Pass dependency name around when automodeling

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/data-extensions-editor/model-details/model-details-data-provider.ts, extensions/ql-vscode/src/data-extensions-editor/model-details/model-details-panel.ts, extensions/ql-vscode/src/databases/local-databases/locations.ts, extensions/ql-vscode/test/unit-tests/command-lint.test.ts
The feature being implemented here is that you can click on an entry in the CodeQL model details panel and it'll open that code location in the main editor. This doesn't implement selecting the correct usage when clicking on the "view" button and that will be a different PR.
I've implemented this using a new `codeQLDataExtensions.jumpToUsageLocation` command. I did first try out using `vscode.open` and passing it a URI, but sadly I don't believe we can use that. Instead we can call the existing `showResolvableLocation` method, but making that work involves a few steps:
- We'd like some error handling, and we currently already perform this same error handling in two places. I move the error handling to be inside `showResolvableLocation` so we avoid duplication.
- We need the `DatabaseItem` …
=> Implementing jumping to location when clicking on a usage in the details panel

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/data-extensions-editor/auto-model-codeml-queries.ts, extensions/ql-vscode/src/data-extensions-editor/auto-model-v2.ts, extensions/ql-vscode/src/data-extensions-editor/auto-modeler.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx, extensions/ql-vscode/test/unit-tests/data-extensions-editor/auto-model-v2.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/auto-model-codeml-queries.test.ts
Add batching of automodeling requests and also the ability to stop. See individual commits for the two steps.
Note that there is a bug around progress that I'd like to fix separately as it requires some refactoring of the in progress state. The bug shows up if a user starts modeling a dependency before the previous one has finished. 
The progress and stopping notifications can also do with a bit of improvement, but this is a good enough start in my opinion.
N/A:
=> Batch automodeling

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/data-extensions-editor/auto-modeler.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx
The term 'package' makes more sense for framework more so we're standardising on that, at least for this specific area of the codebase.
N/A:
=> Rename 'dependency' to 'package' in auto-modeling code

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/data-extensions-editor/auto-modeler.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/data-extensions-editor/shared/in-progress-methods.ts, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodsList.tsx
This fixes the bug around starting to model a package before the previous one has finished.
N/A:
=> Improve auto-modeling in-progress state handling

extensions/ql-vscode/src/data-extensions-editor/auto-model-codeml-queries.ts, extensions/ql-vscode/src/data-extensions-editor/auto-modeler.ts
Two changes:
- Adds some code comments around the automodeler
- Removes the various progress notifications since these are visible in the view. We still have the junky progress notifications around query running but I'm unsure how to fix that and think it's okay for now.
N/A:
=> Minor auto-model polish

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
This reverts commit e938a6a9cb935abc86091b1c96c0cb42ea222a27 (#2602)
`@octokit/plugin-retry` version 5 (and thus 6) drops support for Node 16, which we're still required to use because VS Code is still running on Node 16. Therefore, we shouldn't upgrade this dependency yet. This reverts that upgrade.
=> Revert "Bump @octokit/plugin-retry from 4.1.6 to 6.0.0"

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/data-extensions-editor/model-details/model-details-data-provider.ts, extensions/ql-vscode/src/data-extensions-editor/model-details/model-details-panel.ts
Adds styling to the new Mode Details View.
=> Add icons and main badge to Model Details View

extensions/ql-vscode/src/view/data-extensions-editor/ModeledMethodDataGrid.tsx
Oops, I made a mistake when specifying the sizes for the columns and included too many columns. This meant we weren't taking up the full width of the screen.
Before:
After:
=> Fix spacing of columns

extensions/ql-vscode/src/data-extensions-editor/shared/in-progress-methods.ts, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
A small modification that makes `setPackagedMethods` return a new object instead of mutating the existing object. The current code is correct, but I worry the chance of the class accidentally being used incorrectly is a bit too high.
The danger of having `InProgressMethods` be mutable is that we use it as react state, and react tracks state changes only by object identity. This means if a developer do something like:
```typescript
setInProgressMethods((oldInProgressMethods) => {
oldInProgressMethods.setPackagedMethods(packageName, methods);
return oldInProgressMethods;
);
```
then react would not see that the object was modified and would not trigger a re-render of the component. When the next render happened for whatever other reason, the change in state would be rendered. This leads to …
=> Make InProgressMethods immutable so it's safer to use as react state

extensions/ql-vscode/patches/jest-runner-vscode+3.0.1.patch
When running tests using `--runTestsByPath <some-path>`, the tests were being run twice because jest-runner-vscode
[resolves test paths](https://github.com/adalinesimonian/jest-runner-vscode/blob/0c98dc12adac536a200e836b77e186b8c2ba8326/packages/jest-runner-vscode/src/runner.ts#L57-L66), while the original arguments were also still passed to Jest. So, the arguments Jest would receive would look something like `test/vscode-tests/no-workspace/databases/local-databases/locations.test.ts /Users/koesie10/github/vscode-codeql/extensions/ql-vscode/test/vscode-tests/no-workspace/databases/local-databases/locations.test.ts` which would cause Jest to run the tests twice. This fixes this by resolving the paths to their absolute paths, and then removing any duplicates.
=> Fix running tests twice when test paths are passed

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/local-queries/open-referenced-file-code-lens-provider.ts
Makes the "Open referenced file" command more discoverable by adding a code lens: 
Click that prompt to jump to the referenced QL file 😎 See internal issue for more details! 🔍 
- I put this in the `local-queries` folder, which seemed reasonable 😅 Happy to be pointed to a more suitable location!
- I couldn't think of a useful way to test this, since it just calls out to the existing `codeQL.openReferencedFile` command...
=> Add code lens for "Open referenced file"

extensions/ql-vscode/src/view/results/graph.tsx
Grapviz no longer sets it when it is the default so we don't have anything to override.
This just overrides all text which seems to work.
This fixes the graph viewer with dark themes.
=> Graph: Set fill color for all graph text

extensions/ql-vscode/src/view/results/ProblemsViewCheckbox.tsx, extensions/ql-vscode/src/view/results/ResultCount.tsx, extensions/ql-vscode/src/view/results/ResultTables.tsx
Converts `ResultTables` from a class-based component to a function component. Then goes through and updates a few aspects to be cleaner. Every change is a separate commit, so feel free to review by commit or do the whole thing at once.
Tested locally and appears to work exactly as it did before.
There are some values that I haven't converted to `useMemo` because I don't believe it would help. The places where `useMemo` is helpful are for non-primitive values passed as props to other components, or for computationally expensive calculations. In cases where the calculation is cheap and the value is rendered directly instead of passed as a prop, my understanding is that `useMemo` is not helpful.
=> Convert ResultTables to a function component

extensions/ql-vscode/src/data-extensions-editor/model-details/model-details-data-provider.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/model-details/model-details-data-provider.test.ts
The idea here is to only emit the `onDidChangeTreeData` event when data has really changed.
This means we can call `setState` more liberally, such as on all webview visibility changes, without worrying about the performance impact of re-rendering the details with with the same content.
This relies on the contract that data won't be mutated while reusing the same object/array. So it's the same rules that React uses. I believe we currently abide by these rules and it's unlikely we'd want to break them, due to the way we generate external API usages we always end up with a new array object.
I've added some tests for the behaviour being changed in this PR. We could easily add more tests for the data provider, but to stop this PR from growing in scope I've opened an issue to cover adding more …
=> Only update the details view when data has changed

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
When there are multiple data extensions editors open, have the details view track whichever one was active (i.e. focussed by the user) the most recently. I believe this is the behaviour the user would expect when they have multiple editors open.
Note that while there can be at most one active data extensions editor at a time, there also could easily be zero active. If the user clicks over to a different tab, such as when viewing usages of a method, we want the details view to still be correct.
This PR introduces a couple of big changes to the `DataExtensionsEditorView` class:
- Adds a static variable tracking the `WebviewPanel` that has most recently been active.
- If there's another better way to implement this behaviour I'm very open to it.
- Stores most recent `ExternalApiUsage[]` …
=> Allow the details view to handle multiple open data extensions editors

extensions/ql-vscode/package.json, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
Implements only showing the details view when at least one data extensions editor is open. When a new editor is opened we set the `codeql.dataExtensionsEditorOpen` context key to true, and when an editor is closed we check to see if there are any others remaining and set the context value accordingly.
In my local testing it's working pretty well.
=> Only show the details view when a data extensions editor is open

extensions/ql-vscode/package-lock.json
On my local machine, I wasn't able to run Storybook anymore due to some errors. After upgrading Storybook, it did start again.
This is the command I ran to upgrade Storybook:
```shell
npm upgrade @storybook/addon-actions @storybook/addon-essentials @storybook/addon-interactions @storybook/addon-links  @storybook/components @storybook/csf @storybook/manager-api @storybook/react @storybook/react-webpack5 @storybook/theming storybook
```
There should be no other changes.
=> Upgrade Storybook

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/test/vscode-tests/test-config.ts
Grouped the extension settings into categories, so you can more easily jump to the right section in the sidebar ⚙
I haven't changed any of the settings, and I've just grouped them roughly based on their name (e.g. `codeQL.runningQueries.memory` under "Running queries", `codeQL.cli.executablePath` under "CLI" etc). Happy for alternative suggestions for naming and ordering! 
See internal linked issue for more details 👀
=> Group extension settings in the VS Code UI

extensions/ql-vscode/CHANGELOG.md
The changelog entry from https://github.com/github/vscode-codeql/pull/2706 ended up in the wrong section (probably due to an incorrect merge from 'main` 🥲 
N/A
=> Fix changelog entry

extensions/ql-vscode/src/stories/results/AlertTable.stories.tsx, extensions/ql-vscode/src/view/common/TextButton.tsx, extensions/ql-vscode/src/view/results/AlertTable.tsx, extensions/ql-vscode/src/view/results/AlertTableDropdownIndicatorCell.tsx, extensions/ql-vscode/src/view/results/resultsView.css
This fixes the accessibility linting violations of the `AlertTable` component. The violations are present on the dropdown cell `<td>` components. This replaces them by `<td><button>` so that the clickable behavior is on the `button` instead of the `td`.
=> Fix accessibility of alert table

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
This effectively ships the data extensions model details view, though it is still hidden behind the main feature flag for the data extensions editor.
I've opened this PR but it doesn't have to be merged until we're happy with the state of the new panel.
=> Remove config.codeQL.dataExtensions.modelDetailsView feature flag

.github/workflows/cli-test.yml, .github/workflows/main.yml, docs/releasing.md
We currently run all CLI integration tests for every supported version of the CodeQL CLI, for windows and linux and for every commit of every PR. This is wasteful and it also adds minutes and chance of hitting flakiness.
We've also not generally seen tests succeed on one version and fail on another (outside of flakes), so pragmatically it doesn't make a huge amount of sense to run these tests so often. There aren't a lot of code changes that are related to different CLI versions.
This PR changes the workflows so that instead of running the whole matrix every time, we:
- Run only against the latest released CLI version for PR workflows
- We have a daily run of the CLI version tests
If we're finding that we're missing legit failures on the new workflow, we can add a process to notify the …
=> Split out CLI version tests to separate workflow

extensions/ql-vscode/src/view/results/AlertTable.tsx, extensions/ql-vscode/src/view/results/AlertTableNoResults.tsx, extensions/ql-vscode/src/view/results/AlertTablePathNodeRow.tsx, extensions/ql-vscode/src/view/results/AlertTablePathRow.tsx, extensions/ql-vscode/src/view/results/AlertTableResultRow.tsx, extensions/ql-vscode/src/view/results/AlertTableTruncatedMessage.tsx
Refactors the rendering in `AlertTable`. Previous it was multiple nested `foreach` loops adding components to a `rows` array from multiple places, including the rendering of zero results or truncated results. As of this PR it's a series of hierarchical components.
Each small change is done as a separate commit, so theoretically you should be able to follow along with them. Or it may be easier to review the end result on its own if that's what you prefer.
I've tried to test manually and as far as I can tell, everything looks and behaves exactly the same as before 🎉
=> Split AlertTable into smaller components

extensions/ql-vscode/src/view/results/AlertTable.tsx, extensions/ql-vscode/src/view/results/AlertTablePathNodeRow.tsx, extensions/ql-vscode/src/view/results/AlertTablePathRow.tsx, extensions/ql-vscode/src/view/results/AlertTableResultRow.tsx
Final PR to convert `AlertTable` into a function component. See each individual commit for the individual steps.
Uses the same solution for the `ScrollIntoViewHelper` as we did in `RawTable`. And I also have a further idea for how to make it more react-y that I'll open at a later date.
From my manual testing it appears to look and behave exactly as it did before.
=> Convert AlertTable to a function component

extensions/ql-vscode/src/common/vscode/abstract-webview.ts, extensions/ql-vscode/src/common/vscode/webview-html.ts
The term WebviewView has a specific meaning in VS Code extensions (see [docs](https://code.visualstudio.com/api/references/vscode-api#WebviewView)), so this PR renames our own WebviewView to avoid confusion.
N/A:
=> Rename WebviewView to WebviewKind

extensions/ql-vscode/src/query-history/store/query-history-variant-analysis-domain-mapper.ts, extensions/ql-vscode/src/query-history/store/query-history-variant-analysis-dto-mapper.ts, extensions/ql-vscode/src/query-history/store/query-history-variant-analysis-dto.ts, extensions/ql-vscode/src/variant-analysis/shared/variant-analysis.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-processor.ts, extensions/ql-vscode/test/factories/variant-analysis/shared/variant-analysis-submission.ts, extensions/ql-vscode/test/unit-tests/variant-analysis/variant-analysis-processor.test.ts
In a follow-up PR, we'll use this to determine whether the MRVA results view needs to show an option to switch between raw/interpreted results.
See internal linked issue for more details! 
N/A—no user impact yet 🐯
=> Store query `@kind` when running a variant analysis

extensions/ql-vscode/test/factories/data-extension/external-api-factories.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/model-details/model-details-data-provider.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/model-details/model-details-panel.test.ts
Adds tests for
- model details panel set state
- reveal logic
- model details provider getChildren
=> Add tests for Model Details View

extensions/ql-vscode/src/variant-analysis/variant-analysis-results-manager.ts
Once https://github.com/github/codeql-variant-analysis-action/pull/854 is merged, a succesful variant analysis run will always have the `result.bqrs` file available. 
Instead of choosing to read interpreted results _or_ raw results, we should support having both. (This is so that users will be able to toggle between raw and interpreted results in the results view.)
N/A—no user impact yet 🦁
=> Variant analysis: Always read BQRS results file if it's available

extensions/ql-vscode/src/stories/variant-analysis/RepositoriesResultFormat.stories.tsx, extensions/ql-vscode/src/variant-analysis/shared/variant-analysis-result-format.ts, extensions/ql-vscode/src/view/variant-analysis/RepositoriesResultFormat.tsx
I've added a new component for picking the format for MRVA results:
It follows the style of the existing [Sort and Filter dropdowns](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/src/view/variant-analysis/RepositoriesSort.tsx):
Note that I haven't hooked this new component up to the rest of the view yet, so it won't show up anywhere (except in Storybook). See internal linked issue for details!
N/A—no user impact yet 🐘
=> Add a dropdown for choosing MRVA result format

extensions/ql-vscode/src/stories/variant-analysis/RepositoriesSearchSortRow.stories.tsx, extensions/ql-vscode/src/view/variant-analysis/RepositoriesSearchSortRow.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisOutcomePanels.tsx
For variant analyses with interpreted results (i.e. problem queries or path-problem queries), users should have the option to display raw results (see internal linked issue for details).
This PR adds the new dropdown from https://github.com/github/vscode-codeql/pull/2743 to the MRVA results view, but only for queries that have a `path-problem` or `problem` kind. (Otherwise there's only one display format anyway)
Note: The dropdown currently has no effect 🙃 For the final piece of the puzzle, I'll open a PR that actually uses the result format to control the result display! (It's in progress, stay tuned 😎)
N/A (I'll update the changelog in the final PR that strings things together)
=> Display "result format" dropdown in results view for (path-)problem queries

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/view/variant-analysis/AnalyzedRepoItemContent.tsx, extensions/ql-vscode/src/view/variant-analysis/RepoRow.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisAnalyzedRepos.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisOutcomePanels.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/AnalyzedRepoItemContent.spec.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisAnalyzedRepos.spec.tsx
Follow-up to https://github.com/github/vscode-codeql/pull/2745. Display variant analysis results as rendered alerts or a raw table, depending on the user's selection in the dropdown: 
https://github.com/github/vscode-codeql/assets/42641846/e9e8124c-37f0-4f49-b379-2411f2f8d2f5
For queries that have alerts available (`path-problem` or `problem` queries), we display as alerts by default, with the option to swap to raw results. For other queries, we can only show a raw results table, so we don't show the dropdown at all.
- https://github.com/github/codeql/pull/14051
=> Make "result format" dropdown determine result display

extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/data-extensions-editor/methods-usage/methods-usage-data-provider.ts, extensions/ql-vscode/src/data-extensions-editor/methods-usage/methods-usage-panel.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/methods-usage/methods-usage-data-provider.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/methods-usage/methods-usage-panel.test.ts
This is the final rename of the CodeQL Model Details view code to Methods Usage.
N/A:
=> Rename ModelDetail to MethodsUsage in types and functions

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts, extensions/ql-vscode/src/data-extensions-editor/shared/view-state.ts, extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx, extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx, extensions/ql-vscode/src/view/data-extensions-editor/LibraryRow.tsx
Remove the feature flag and always allow framework mode to be used.
N/A:
=> Remove codeQL.dataExtensions.frameworkMode setting

extensions/ql-vscode/src/data-extensions-editor/queries/java.ts
This fixes a crash when loading models using the latest QL submodule. This was due to a change in the libraries the java query dependended on.
=> Fix ql code in neutral fetch.

extensions/ql-vscode/src/data-extensions-editor/auto-model-codeml-queries.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts, extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-queries.ts, extensions/ql-vscode/src/data-extensions-editor/external-api-usage-queries.ts, extensions/ql-vscode/src/data-extensions-editor/flow-model-queries.ts, extensions/ql-vscode/src/language-support/contextual/query-resolver.ts, extensions/ql-vscode/src/local-queries/query-resolver.ts, extensions/ql-vscode/src/local-queries/run-query.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/auto-model-codeml-queries.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/data-extensions-editor-queries.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/local-queries/query-resolver.test.ts
Resolve automodel and flow queries without submodule.
=> Make automodel and flow queries work without submodule.

extensions/ql-vscode/src/data-extensions-editor/queries/java.ts
This is a follow up to https://github.com/github/vscode-codeql/pull/2755. By fixing the query against main in the submodule we broke it against the released package :/
This _hopefully_ tweaks the predicate to work in both versions, but we should get started on moving the query out I think.
=> Change the java query to work for multiple java versions.

extensions/ql-vscode/package.json
We'll need access to the "create query" command from the queries panel. This PR updates the command's feature flags so that they also align with the queries panel's flags:
https://github.com/github/vscode-codeql/blob/a85e7c9707128ea6a9523b3136c2f41959087d10/extensions/ql-vscode/package.json#L1735-L1739
N/A: no visible impact yet, all of this is feature-flagged 🎏  See internal linked issue for more details.
=> Make "create query" command available when queries panel is enabled

extensions/ql-vscode/src/stories/model-editor/ExternalApiUsageName.stories.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MethodModeling.spec.tsx, extensions/ql-vscode/src/view/model-editor/ExternalApiUsageName.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ExternalApiUsageName.spec.tsx, extensions/ql-vscode/test/factories/data-extension/external-api-factories.ts
Extracts the `ExternalApiUsageName` component into a standalone component and re-uses that across the model editor and the method modeling view.
N/A:
=> Extract external api usage name component and reuse it

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/local-queries/skeleton-query-wizard.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-queries/local-databases.test.ts
If a user picks a folder in which to create custom queries (`createQuery.qlPackLocation`), that should be saved in workspace settings, rather than global settings by default. See internal linked issue for details! 📦 
I've also changed `createQuery.autogenerateQlPacks` to get written to workspace settings, for consistency. There's no harm either way, but I think we should default to workspace settings, and only write to global settings for "higher-level" settings (such as enabling/disabling telemetry) ⚙
N/A—this is still feature-flagged 🎁
=> Make the "Create query" location workspace-specific

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/local-queries/local-queries.ts
Adds a button to the Queries panel that calls the `createQuery` command:
https://github.com/github/vscode-codeql/assets/42641846/398a9692-1e25-41d3-8330-aa45840fa86a
❓ Note: I've added this command as a `LocalQueryCommand`, since that's what we do for the other query panel commands (such as "Run Query"). I think this is fine for now, but I wonder whether we should create a new group of `QueriesPanelCommand`s instead 🤔 
N/A—no user impact, this is still feature-flagged 🐳
=> Add "create query" button to queries panel

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/extension-pack-picker.test.ts
This renames the feature flags from:
```
"codeQL.dataExtensions.editor": true,
"codeQL.dataExtensions.llmGeneration": true,
"codeQL.dataExtensions.disableAutoNameExtensionPack": true,
"codeQL.dataExtensions.extensionsDirectory": true,
```
to
```
"codeQL.model.editor": true,
"codeQL.model.llmGeneration": true,
"codeQL.model.disableAutoNameExtensionPack": true,
"codeQL.model.extensionsDirectory": true,
```
=> Rename feature flags.

extensions/ql-vscode/package.json
Renames the `codeQL.modelEditor.methodModelingView` feature flag to `codeQL.model.methodModelingView` so that it matches the prefix of the other modeling feature flags.
I'm guessing what happened is we were trying to preempt the change in https://github.com/github/vscode-codeql/pull/2766, but then we changed our mind to use `codeQL.model` instead of `codeQL.modelEditor`, so the `codeQL.modelEditor.methodModelingView` doesn't match the other flags now.
=> Make methodModelingView match the naming of other flags

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-panel.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx
This PR adds some initial wire-up for the method modeling panel. It first adds the ability to set the method that is being modeled, and then adds some basic wire up so that a dummy method is shown when the user clicks the "View" button in the editor. I've not wired up the actual method information yet because it requires some refactoring to make that available (we only have the `Usage` at the minute). This will be done in a following PR.
Note that I've broken this into 3 commits for ease of review.
N/A:
=> Add ability to set method for modeling in the modeling panel

extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/methods-usage/methods-usage-panel.test.ts
This is one possible solution to the conversation from https://github.com/github/vscode-codeql/pull/2735/files#r1303916205.
Effectively this is still using `as unknown as X` but at least that's now contained within `mockedObject` which mocks all other fields and methods and throws a helpful error message when code tries to use them.
I think using `mockedObject` for the `TreeView` type makes sense. It's a hard type to provide a "real" instance of, because:
- It's not a type we own or control.
- It's quite a large type with lots of methods we often don't care about.
- It's an interface that "does stuff" rather than being a data type that just contains static data.
Also importantly, we don't ever do type checking on this type, so fields being mocked doesn't cause problems with this. In the …
=> Use mockedObject for TreeView

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-data-provider.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx
Updates the jump to usage message and related functions to include the method. This allows us to surface method information in the method modeling panel when "View" is clicked.
Note that I've not renamed the message - let me know if you think it should be renamed.
N/A:
=> Update jump to usage to include the method

extensions/ql-vscode/src/model-editor/model-editor-view.ts
This PR should ensure that we have sufficient telemetry of actions users are taking in the model editor.
Some actions are already covered because we emit telemetry for all commands that get executed. This PR then covers all places where we send a message from the view to the extension host. Theoretically there could also be UI interactions that don't result in a message being sent to the host, but in the case of the model editor I don't believe there are any.
If in the future we do find we've missed something that we would like to have telemetry on, we can always add it.
=> Emit telemetry for all messages sent from model editor

extensions/ql-vscode/package.json, extensions/ql-vscode/src/queries-panel/queries-module.ts, extensions/ql-vscode/src/queries-panel/queries-panel.ts, extensions/ql-vscode/src/queries-panel/query-tree-data-provider.ts, extensions/ql-vscode/src/queries-panel/query-tree-view-item.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/queries-panel/query-tree-data-provider.test.ts
Removes the "Looking for queries..." loading message and replaces it with a welcome view that prompts users to create a query if their panel is empty. 
See internal linked issue for details and design discussions 🖼️
N/A—nothing publicly visible yet 🦺
=> Queries Panel: Create query from welcome view

extensions/ql-vscode/src/view/common/Dropdown.tsx
This PR makes three changes to dropdowns:
- When disabled, shows a dash/hyphen instead of nothing
- When disabled, sets the opacity value lower (this matches how the `VSCodeDropdown` component behaves)
- Moves the arrow further away from the right-hand edge
Screenshot:
=> Adjust styling of disabled dropdowns to make their state clearer

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/model-editor/extension-pack-picker.ts, extensions/ql-vscode/src/model-editor/extensions-workspace-folder.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/extension-pack-picker.test.ts
Removing this feature flag and deleting the now-unused code turned out to be quite a large code change. In `extension-pack-picker.ts` we delete everything after the `if (!disableAutoNameExtensionPack())` branch, including deleting the `pickNewExtensionPack` method. Then the `autoCreateExtensionPack` method is inlined into `pickExtensionPack` to simplify arguments, avoid calling another function unnecessarily, and avoid the "autoCreate" naming which now doesn't make sense when the other option has been removed.
There are more changes in `extension-pack-picker.test.ts` where some tests were no longer needed at all, and others could be modified to test the new code path instead of the old code path.
<details><summary>The changes made to the various tests are as follows:</summary>
<p>
```
- …
```
=> Remove the disableAutoNameExtensionPack feature flag

extensions/ql-vscode/src/model-editor/shared/modeled-percentage.ts, extensions/ql-vscode/test/unit-tests/model-editor/shared/modeled-percentage.spec.ts
I believe this method is accepting `Pick<Method, "supported">` in order to make the testing easier, but we now have better ways around that so it isn't necessary. Also this was making it difficult for me when I wanted to use another field from the `method` object.
=> Change calculateModeledPercentage to accept Method instead of using Pick

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/shared/view-state.ts, extensions/ql-vscode/src/stories/model-editor/ModelEditor.stories.tsx, extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx
This adds a new `codeQL.model.flowGeneration` feature flag for hiding the "Generate" and "Model from source" options from the model editor by default. It uses the same approach as the LLM generation.
=> Add feature flag for flow generation

extensions/ql-vscode/src/local-queries/run-query.ts, extensions/ql-vscode/src/model-editor/auto-model-codeml-queries.ts, extensions/ql-vscode/src/model-editor/extension-pack-picker.ts, extensions/ql-vscode/src/model-editor/external-api-usage-queries.ts, extensions/ql-vscode/src/model-editor/flow-model-queries.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/extension-pack-picker.test.ts
This improves the responsiveness of the model editor. It is not necessary to create a lock file when running the external API usage queries because the pack has already installed the dependencies in `setUpPack`. By skipping this step, refreshing becomes almost instant with no changes rather than requiring a 5 second wait to re-install pack dependencies.
This also improves the progress notifications so it feels more responsive and is more accurate as to what the editor is doing.
I tested this both in a the `vscode-codeql-starter` and in an empty workspace, so I believe this should still work even when you do not have the `ql` submodule.
=> Improve responsiveness of model editor

extensions/ql-vscode/package.json
Moves the databases panel to the top (since it'll later control the language that's displayed across all panels). See internal issue.
N/A—this is only visible to people who also had the queries panel visible (feature-flagged)
=> Make "databases" the top panel in the CodeQL sidebar

extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx
This sets the loading state when switching between application and framework mode. It does this by setting the `methods` to an empty array, which will show the loading state ([`methods.length === 0`](https://github.com/github/vscode-codeql/blob/b0eab8b9fed827a565abb1b4985d3a8a2db24df2/extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx#L291)).
=> Set loading state when switching between modes

extensions/ql-vscode/src/model-editor/extension-pack-name.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeled-method-fs.ts, extensions/ql-vscode/src/model-editor/yaml.ts, extensions/ql-vscode/test/unit-tests/model-editor/yaml.test.ts
This groups the framework mode model files by the package name rather than creating a single file for the library. This re-uses the existing logic from application mode and creates a new method which takes in a method to group by.
The actual grouping follows the approach the files are structured in the CodeQL repo: following the package name exactly. For C#, this means that the file names contain capital letters, like their respective namespaces do.
=> Group framework mode model files by package

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
Before this change and starting with CLI v2.14.3, if you wanted to run a variant analysis query and the pack it is contained in has at least one query that contains an extensible predicate, this would be an error.
The reason is that v2.14.3 introduced deep validation for data extensions. We are not copying the query that contains an extensible predicate to the synthetic pack we are generating. This means that deep validation will fail because there will be extensions that target the missing extensible predicate.
This change avoids the problem by copying any query files that contain extensible predicates to the synthetic pack. It uses the internal `generate extensible-predicate-metadata` command to discover which query files contain extensible predicates and copies them.
- [n/a] …
=> Copy more files into the synthetic variant analysis pack

extensions/ql-vscode/package-lock.json
This upgrades all semver dependencies which are not on the latest version to the newest version of that major version. This means that it will upgrade all dependencies depending on semver 5 to 5.7.2 and all dependencies depending on semver 6 to 6.3.1.
=> Upgrade transitive semver dependencies

extensions/ql-vscode/src/databases/database-fetcher.ts, extensions/ql-vscode/src/databases/local-databases-ui.ts, extensions/ql-vscode/src/databases/local-databases/database-manager.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-queries/local-databases.test.ts
When importing a database through "Model dependency" in the model editor, this will stop adding the source archive folder to the workspace. This will ensure that the window does not reload if the user is in a single-folder workspace.
=> Do not add source archive folder for "Model dependency"

extensions/ql-vscode/src/view/model-editor/HiddenMethodsRow.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodDataGrid.tsx
The aim of this is help users understand the effect of the "Hide modeled APIs" option. So if methods are hidden then we'll show how many there were. This PR also improves the experience when the table all methods are hidden by not showing the table header when there is no table content.
Screenshot showing a non-empty and empty table:
Suggestions about styling very welcome.
=> Add a row to the model editor tables showing how many methods have been hidden

extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx
Makes the user-visible rename for "Hide modeled APIs" to "Hide modeled methods"
See https://github.com/github/vscode-codeql/pull/2808 for the PR that updates all the internal code references.
=> Rename checkbox for hide modeled APIs => methods

extensions/ql-vscode/src/model-editor/bqrs.ts, extensions/ql-vscode/src/model-editor/external-api-usage-queries.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/test/unit-tests/model-editor/bqrs.test.ts
All references to "external API usage" should be renamed to "method" but I spotted a couple of references remaining in the code.
None of these changes are user-visible.
=> Renames remaining references to "external API usage" in the code

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts
This fixes two things to do with the `codeQLModelEditor.jumpToUsageLocation` command.
When clicking a new usage, we now jump to the location in the code.
When clicking a usage from a different method, we now update the method modeling panel to show to the method.
=> Fix jumping to usage and updating method modeling panel

extensions/ql-vscode/src/common/vscode/abstract-webview.ts, extensions/ql-vscode/src/common/vscode/webview-html.ts, extensions/ql-vscode/src/compare/compare-view.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/local-queries/results-view.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-panel.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/variant-analysis/data-flow-paths-view.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-view-serializer.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-view.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-manager.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
This will switch all `AbstractWebview`-derived classes to use `App` instead of `ExtensionContext`. This makes it easier to test classes derived from `AbstractWebview`.
=> Use `App` instead of `ExtensionContext` for webviews

extensions/ql-vscode/src/model-editor/method.ts, extensions/ql-vscode/src/view/model-editor/__tests__/HiddenMethodsRow.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/KindInput.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/MethodName.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModelingStatusIndicator.spec.tsx
This adds or expands some simple React tests for these components:
- `HiddenMethodsRow`
- `KindInput`
- `MethodName`
- `ModelingStatusIndicator`
=> Add some simple model editor React unit tests

extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/model-editor-view.test.ts
This adds a simple test for ModelEditorView which checks that it sets up the view.
=> Add simple test for ModelEditorView

extensions/ql-vscode/src/model-editor/auto-model-codeml-queries.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/auto-model-codeml-queries.test.ts
This cleans up the two temporary directories we create in the model editor:
- When opening the model editor, a temporary directory with the query files is created. This will clean it up after either the panel or the view is disposed. This is just temporary, the `queryDir` will be removed once the queries have been moved to `github/codeql`.
- When using the automodel functionality, a temporary directory with an extension pack containing the filter is created. This will clean it up after running the query.
=> Cleanup temporary directories in model editor

docs/test-plan.md, extensions/ql-vscode/package.json
Makes the model editor available without either the `codeQL.model.editor` or `codeQL.canary` feature flags.
=> Remove codeQL.model.editor feature flag

extensions/ql-vscode/CHANGELOG.md
Add changelog entry for model editor. @jf205
=> Add changelog entry for model editor

extensions/ql-vscode/gulpfile.ts/deploy.ts, extensions/ql-vscode/gulpfile.ts/package.ts, extensions/ql-vscode/gulpfile.ts/tsconfig.json
Technically we could satisfy the linter by just removing the explicit typing and let it implicitly be typed as `any`, but that seems like cheating. This PR adds a type for the fields we actually reference and does a quick check that those fields exist.
Maybe not very necessary. If you think this is over the top for this piece of code feel free to say so.
=> Avoid use of "as any" in gulpfile.ts/deploy.ts

extensions/ql-vscode/.storybook/preview.ts, extensions/ql-vscode/scripts/find-deadcode.ts, extensions/ql-vscode/src/view/vscode-api.ts, extensions/ql-vscode/tsconfig.deadcode.json
Avoids the use of `window as any` in `.storybook/preview.ts` by declaring what the type of `Window` should be.
=> Avoid using "as any" in .storybook/preview.ts

extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/common/helpers-pure.ts, extensions/ql-vscode/src/common/sarif-parser.ts
This PR removes any cases of `as any` in error handling.
There were quite a few cases where we were checking to see if `err.stderr` existed. As far as I can tell, this is useful in one case where `child_process.execFile` throws error with this field and it gives a slightly nicer error message for the user. In all of the other cases I cannot see why that field would be there and I think it's just a case of copy-pasting other code.
I wasn't sure where to put `getChildProcessErrorMessage` so I went with `helpers-pure.ts` alongside `getErrorMessage`. But I'm happy to put it in `cli.ts` or somewhere else if that would be cleaner.
=> Avoid use of "as any" during error handling

extensions/ql-vscode/src/model-editor/model-editor-queries.ts
Only download the automodel query pack for java and only if the relevant feature flag is enabled.
N/A:
=> Only download automodel query pack when relevant

extensions/ql-vscode/src/view/model-editor/MethodRow.tsx
There is 1 instance of `ReturnType` in the model editor instead of `ReturnValue`. All other instances already say `ReturnValue` and this is also correct based on occurrences in the `github/codeql` repository. This fixes this last instance.
=> Fix incorrect `ReturnType` instead of `ReturnValue`

extensions/ql-vscode/src/model-editor/method.ts, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelTypeDropdown.tsx
This will allow us to reuse logic for the new method modeling panel.
I've not added any unit tests/stories - we can do that in a separate issue.
N/A:
=> Extract model type dropdown to its own component

extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelInputDropdown.tsx
This will allow us to reuse code for the new method modeling panel.
See similar PR: https://github.com/github/vscode-codeql/pull/2833
N/A:
=> Extract model input dropdown to its own component

extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelOutputDropdown.tsx
This will allow us to reuse code for the new method modeling panel.
See similar PR: https://github.com/github/vscode-codeql/pull/2833
N/A:
=> Extract model output dropdown to its own component

extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodsList.tsx
I noticed that we weren't using the `modelName` in the `onChange` callback of the `ModelEditor` so I've removed it and cleaned up.
N/A:
=> Clean up model editor onChange callback

extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelKindDropdown.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModelKindDropdown.spec.tsx, extensions/ql-vscode/test/factories/model-editor/modeled-method-factories.ts
Updates the `KindInput` component to make it more self contained and more in line with the other dropdown components (e.g. https://github.com/github/vscode-codeql/pull/2833).
Please review commit by commit - the first commit renames the component to `ModelKindDropdown`.
N/A:
=> Update KindInput component to bring it inline with others

extensions/ql-vscode/src/stories/model-editor/MethodRow.stories.tsx
I noticed that all the stories for the `MethodRow` component were. showing as `Method already modeled` so this fixes that.
N/A:
=> Fix MethodRow stories to not all show as modeled

extensions/ql-vscode/src/stories/method-modeling/MethodModelingInputs.stories.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingInputs.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MethodModeling.spec.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MethodModelingInputs.spec.tsx
Adds the `Model Type`, `Input`, `Output` and `Kind` drop-downs to the method modeling panel
N/A:
=> Add modeling inputs to method modeling panel

extensions/ql-vscode/src/stories/method-modeling/MethodModelingInputs.stories.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingInputs.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MethodModelingInputs.spec.tsx, extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/ModelInputDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelKindDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelOutputDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelTypeDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodsList.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/MethodRow.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModelKindDropdown.spec.tsx
I noticed that the only thing we needed from the `Method` object in the various `onChange` callbacks was the `signature` which is also available in the `ModeledMethod` so I've removed the `method` from all the `onChange` callbacks.
N/A:
=> Remove redundant argument from onChange

extensions/ql-vscode/package.json, extensions/ql-vscode/src/model-editor/model-editor-view.ts
We don't want to show the modeling panel if the main editor window is active, since they show similar things.
N/A:
=> Hide modeling panel when modeling editor is active

extensions/ql-vscode/src/model-editor/model-editor-view.ts
Minor change to remove an `as any` casting. Suggested [here](https://github.com/github/vscode-codeql/pull/2851#discussion_r1335571640).
As part of that we're extracting a `isTabModelEditorView` function that is reused from two places.
N/A:
=> Don't use 'as any' when checking open view

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/databases/local-databases-ui.ts
Adds a language menu to the databases view:
https://github.com/github/vscode-codeql/assets/42641846/b08a565b-c231-4af9-8571-c5d40e5d9a00
- A lot of the changes are command-wrangling. The main changes are in [`local-databases-ui.ts`](https://github.com/github/vscode-codeql/pull/2856/files#diff-24cce3c26831674245c5877c9683c8c8250c8595c4fa0d1eeece5c9b50bc5c8c).
- This still needs quite a lot of polishing (see internal issue as well) and testing, but I'm keen for any initial feedback on the approach, and then I can polish stuff in follow-up PRs! 💅🏼
⚠️ I've hidden the new language menu behind the `canary` flag, since it's still WIP. No user-facing changes yet.
=> Add ability to filter DB view by language

extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-panel.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/test/__mocks__/model-editor/modelingStoreMock.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/methods-usage/methods-usage-panel.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/model-editor-view.test.ts
Introduces a new `ModelingStore` that will be responsible for managing state related to method modeling. It stores state per database we're modeling. 
In this PR we take the first few steps to get there:
- Introducing the new `ModelingStore` and wiring it up to the module/views.
- Adding the knowledge around active database being modeled to the store.
- Moving the `methods` and `hideModeledMethods` bits of state to the new store.
- Using the three pieces of data (`methods`, `hideModeledMethods` and active db state) and wiring up events/event emitters in order to remove the various callbacks used in the methods usage panel.
There are no guards to enforce that the state doesn't get mutated outside of the store yet. It's something I think we should do, but I didn't want to add more to this …
=> Introduce modeling store and move some state there 

extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-panel.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts
This will allow us to make sure we dispose of subscriptions to events (that we'll register to in the near future).
N/A:
=> Make MethodModelingViewProvider a disposable object

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/test/__mocks__/model-editor/modelingStoreMock.ts
Move some more state into the new modeling store. In this PR we move the modeled methods and modified methods state.
By moving this state out of the React view, the view gets simplified and uses React state only to store what it has been told by the extension host - it doesn't make any changes to the state directly by itself.
With this move we could also add some test coverage around the more complicated state update functions (e.g. `addModeledMethods`). This will be done in a future PR.
N/A:
=> Move modeled and modified method state to store

extensions/ql-vscode/src/view/variant-analysis/RawResultCell.tsx, extensions/ql-vscode/src/view/variant-analysis/RawResultRow.tsx, extensions/ql-vscode/src/view/variant-analysis/RawResultsTable.tsx
This splits out the `RawResultCell` and `RawResultRow` to separate files to make the `RawResultsTable` file easier to read. There are no behaviour changes.
=> Split out components in variant analysis raw results table

extensions/ql-vscode/src/model-editor/shared/modeling-status.ts, extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelingStatusIndicator.tsx
Moved modeling status code into its own module, in a shared location, so that it can be reused in the method modeling panel
N/A:
=> Move modeling status code to its own module

extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/model-editor-view.test.ts
This removes the need for callbacks and sets us up for easily updating the method modeling panel when the selection changes.
I'm not sure about the names that I've used (referring to method and ignoring the usage part) so open to renaming. E.g. we could use `methodUsage` (it just gets a bit long e.g. `onSelectedMethodUsageChanged`).
N/A:
=> Add selected method and usage state to modeling store

extensions/ql-vscode/src/view/common/RawNumberValue.tsx, extensions/ql-vscode/src/view/results/RawTableValue.tsx, extensions/ql-vscode/src/view/variant-analysis/RawResultCell.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/AnalyzedRepoItemContent.spec.tsx
This changes the formatting for both the local raw results table and the variant analysis raw results table to right align and format numbers.
=> Right align and format raw result numbers

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-panel.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx
Hooks the method modeling panel to the modeling store so that the method modeling panel deals with updates events from the store, but that it also sends updates when the dropdown values change.
N/A:
=> Hook method modeling view to modeling store

extensions/ql-vscode/src/databases/code-search-api.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts
Instead of removing the information completely we will show primary and secondary rate limit information in the extension output.
=> Code Search: don't show rate limit warnings to users

extensions/ql-vscode/src/local-queries/query-resolver.ts, extensions/ql-vscode/src/model-editor/auto-model-codeml-queries.ts, extensions/ql-vscode/src/model-editor/external-api-usage-queries.ts, extensions/ql-vscode/src/model-editor/mode-tag.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-queries.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/external-api-usage-query.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/model-editor-queries.test.ts
This will start using the model editor endpoints queries from the CodeQL packs (`codeql/java-queries` and `codeql/csharp-queries`) if we can find the queries in those packs.
There are two cases (example language is Java):
- In case the queries are present in the `codeql/java-queries`, we don't need to write our own queries to disk. We still need to create a synthetic query pack so we can pass the `queryDir` to the query resolver without caring about whether the queries are present in the pack or not.
- In case the queries are not present in the `codeql/java-queries`, we need to write our own queries to disk. We will create a synthetic query pack and install its dependencies so it is fully independent and we can simply pass it through when resolving the queries.
These steps together ensure …
=> Resolve model editor queries from CodeQL packs if present

extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/databases/db-panel.test.ts
During investigations into a new code-search integration test some minor updates were found worth keeping.
=> Minor test updates for `db-panel.test`

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/databases/local-databases-ui.ts
Adds `(selected)` after the selected language in the databases view:
https://github.com/github/vscode-codeql/assets/42641846/ef3545fa-195b-42ae-a5df-067249a78de4
There's no public VS Code API for properly selecting a menu item (https://github.com/microsoft/vscode/issues/109306), so adding a separate `...Selected` command was the closest workaround I could find 😢  See internal issue, where we discussed a bit more.
Still behind "canary", so no user-facing changes for now.
=> Indicate which language is selected in the databases view

extensions/ql-vscode/src/extension.ts
This changes the `MIN_VERSION` that will be used for showing warnings to `1.82.0`. 1.82 is the August release (currently the latest) and upgrades to Node.js 18. We would like to be able to upgrade to dependencies that require Node.js 18, so let's set the minimum supported version to this so we can drop support for older versions after the next release.
We can't really upgrade to a newer VS Code version for integration tests until we fully support Node.js 18, but that means dropping support for running integration tests on Node.js 16. Therefore, we need to merge this before doing our upgrade to a newer VS Code and Node.js version.
=> Bump minimum VS Code version to 1.82

extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-data-provider.ts, extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-panel.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/methods-usage/methods-usage-data-provider.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/methods-usage/methods-usage-panel.test.ts
Show modeling status in the method usages panel. See exact spec in the internal linked issue. 
As part of this I updated modeling store functions to make sure new objects are created when changing the top level properties of the state object. This allows us to continue using object equality to check if updates to the usages panel should happen.
N/A:
=> Add modeling indicator to method usages panel

extensions/ql-vscode/package.json
Since we're reconsidering the design, let's hide the language filter even more, before it makes it into a release.
For development purposes, you can add `"codeQL.showLanguageFilter": true` to your settings to un-hide the language filter menu (FYI @starcke).
=> Hide the language filter behind an extra flag

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/query-language.ts, extensions/ql-vscode/src/databases/local-databases-ui.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/language-context-store.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/local-databases-ui.test.ts
This adds an explicit store to contain the Language filter state outside of the databases panel. It is based on `modeling-store.ts`.
There are two points that are somewhat interesting:
- We encapsulated the LanguageState inside the store, so that the users do not need to know how "All" is implemented. This might not be needed or sufficient in the future, but for now it seemed pretty nice to do.
- The `shouldInclude` method takes a string which is asymmetric with with the `setLanguageContext`. This is because we actually check with an arbitrary string (because that is what the database item has). I wonder if there is a better way to do this.
=> Add language context store.

extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx
Some minor styling updates to the method name section of the modeling panel.
=> Styling updates to method modeling panel

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/query-server/server-process.ts
Previously, if there was an explicit restart of the query server (eg- by changing a configuration setting), then the query server process would be started twice: once by the `close` handler and once by the restart command.
By adding the `removeAllListeners` to the dispose method, we ensure that when the query server shuts down gracefully, there won't be a `close` listener that is going to restart it a second time if there is a different way of restarting it.
=> Avoid double restarts of the query server

extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts
Now that the view provider is disposable, we can make sure we dispose of event subscriptions. 
I suggest using "Hide whitespace" in the diff for easy of review.
N/A:
=> Dispose event subscriptions in method modeling view

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/queries-panel/queries-module.ts, extensions/ql-vscode/src/queries-panel/query-discovery.ts, extensions/ql-vscode/test/__mocks__/appMock.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/queries-panel/query-discovery.test.ts
This adds language filtering to the queries panel. Adding the filtering was trivial, however there were a few other tweaks I had to make.
1. Previously we made `onDidChangeQueries` the same as `onDidChangePathData`. However if we integrated with that it would require a full rescan of the file system to apply a filter which felt quite slow for me. Instead we create a specific emitter for `onDidChangeQueries` which is triggered by either the filesystem changing or the filter changing.
2. Initially my tests failed when trying to dispose `this.languageContext.onLanguageContextChanged`. This was because the MockApp created a MockEventEmitter which returned `{}` as disposable. However `{}` is actually not disposable (because it lacks the method). So I changed it to return something that is …
=> Apply language context to queries panel

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/common/vscode/abstract-webview-view-provider.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-panel.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts
This is to help with re-usability but also to make the code more readable since plumbing code etc. get moved out of the concrete class.
This also solves the issue of disposal of event subscriptions at the right time (see https://github.com/github/vscode-codeql/pull/2891). 
N/A:
=> Extract base functionality for WebviewViewProviders into an abstract class

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-panel.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-view-tracker.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx, extensions/ql-vscode/src/view/method-modeling/ReviewInEditorButton.tsx, extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodsList.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/LibraryRow.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/MethodRow.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodDataGrid.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodsList.spec.tsx, extensions/ql-vscode/src/view/vscode-api.ts, extensions/ql-vscode/test/__mocks__/model-editor/modelEditorViewTrackerMock.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/model-editor-view.test.ts
This adds a new reveal in editor button to the method modeling panel:
Once clicked, it will:
- Expand the group (library/package) in which the method is located
- Scroll to the method
- Highlight the method
https://github.com/github/vscode-codeql/assets/1112623/9d33049d-1c39-421d-aaf7-6389b7418c1d
It's easiest to review this commit-by-commit, I've tried to create somewhat separate pieces.
=> Add reveal in editor button to method modeling panel

.github/workflows/cli-test.yml, .github/workflows/main.yml, .github/workflows/release.yml, docs/node-version.md
This will make it much easier to change the Node version: you'll only need to make changes to 2 files instead of 6 files.
=> Use .nvmrc file for setting up Node version in Actions

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history/history-tree-data-provider.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/test/factories/query-history/local-query-history-item.ts, extensions/ql-vscode/test/factories/query-history/variant-analysis-history-item.ts, extensions/ql-vscode/test/factories/variant-analysis/shared/variant-analysis.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/history-tree-data-provider.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/variant-analysis-history.test.ts
This adds language filtering to the history panel. The implementation is mostly straightforward, we only show `unknown` languages when `All` is selected.
-------
Without filter:
-------
After `java` filter:
=> Add support for filtering history panel.

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/shared/view-state.ts, extensions/ql-vscode/src/stories/model-editor/LibraryRow.stories.tsx, extensions/ql-vscode/src/stories/model-editor/ModelEditor.stories.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/LibraryRow.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodsList.spec.tsx
Adds a feature flag and adds it to the model editor view state.
=> Add feature flag for showing multiple modelings

.github/workflows/main.yml
This increases the memory limit of Node.js when running ESLint in Actions by setting `NODE_OPTIONS=--max-old-space-size=4096`. The [`max-old-space-size` option](https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes) effectively sets the memory limit of V8 (in megabytes). Since Actions has a 7GB memory limit, 4096 MB should be safe to use.
=> Increase memory limit when running ESLint

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts
I noticed we were still using `this.webviewView.webview.postMessage` in a couple of places in the method modeling panel so I fixed that and by doing that a type mismatch was flagged and fixed.
N/A:
=> Use base postMessage instead of webview one

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/common/vscode/abstract-webview-view-provider.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/stories/common/ResponsiveContainer.stories.tsx, extensions/ql-vscode/src/stories/method-modeling/NoMethodSelected.stories.tsx, extensions/ql-vscode/src/stories/method-modeling/NotInModelingMode.stories.tsx, extensions/ql-vscode/src/view/common/ResponsiveContainer.tsx, extensions/ql-vscode/src/view/method-modeling/NoMethodSelected.tsx, extensions/ql-vscode/src/view/method-modeling/NotInModelingMode.tsx
Added components for the empty states of the method modeling panel. These are not yet hooked to anything.
As part of this I've introduced a reusable component that I've called "ResponsiveContainer", please let me know if you can think of a better name!
N/A:
=> Add empty states for modeling panel

extensions/ql-vscode/src/common/query-language.ts
ML-powered queries are [now deprecated](https://github.blog/changelog/2023-09-29-codeql-code-scanning-deprecates-ml-powered-alerts/), so this PR removes the ML-powered queries pack from the list we'll download by default for JavaScript.
=> Packaging: Remove ML-powered queries pack from known list

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx
Updated the flows so that the modeling panel remains open and shows the relevant empty state when appropriate.
N/A:
=> Wire up modeling panel empty states

extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingInputs.tsx, extensions/ql-vscode/src/view/method-modeling/ReviewInEditorButton.tsx
Some stylistic changes to the method modeling panel, mainly to space out elements better.
This is how it looks now
N/A:
=> UI polish for modeling panel

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/shared/view-state.ts, extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx
This adds a view state to the method modeling panel similar to the model editor. This will be used to send the state of the show multiple models feature flag to the webview so this can be used to selectively show/hide components in the method modeling panel.
=> Add view state to method modeling panel

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx
We can avoid putting the entire method in the message because we only need to signature.
=> Convert RevealMethodMessage to only include method signature

extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeled-method-fs.ts, extensions/ql-vscode/src/model-editor/modeled-methods-legacy.ts
This will change the input/output types for modeled methods in the `modeled-method-fs.ts` file to take in multiple models per method. This removes the need for conversion functions between this file and `yaml.ts` files. Instead, the conversion functions are done when calling any functions defined in `modeled-method-fs.ts` files.
=> Convert `modeled-method-fs.ts` to handle multiple models per method

extensions/ql-vscode/CHANGELOG.md
Update the changelog for https://github.com/github/vscode-codeql/pull/2824, because I forgot to do it in the PR.
Links to the docs which will be updated by https://github.com/github/codeql/pull/14408
=> Update CHANGELOG.md for telemetry changes

CODEOWNERS
This adds SecExp as a CODEOWNER for all method modeling panel files to ensure the reviews are requested correctly.
=> Set SecExp as codeowner for modeling panel

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodsList.tsx
Removes the `methods` and `modeledMethods` fields from `SaveModeledMethods` in favour of including `methodSignatures`. The extension host can use the `ModelingStore` to look up the methods and modelings using the method signatures.
Involves adding `getMethods` and `getModeledMethods` to `ModelingStore`.
Tested locally and seems to be saving models and updating the "unsaved" labels correctly.
=> Remove method and modeledMethods from SaveModeledMethods message

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/syntaxes/ql.tmLanguage.yml, syntaxes/ql.tmLanguage.json
Fixes https://github.com/github/codeql-core/issues/3697
This PR updates the TextMate grammar to allow instantiation arguments in import statements. This will improve syntax highlighting. Specifically, It is meant to fix the highlighting of `pragma` in the example below.
Note that I don't know the TextMate grammar world very well, so am not really sure whether what I did here makes any sense.
=> fix syntax highlighting after imports with instantiation arguments

extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts
Small change to make sure we update the modified methods state when the modeled method gets updated. If we don't do that we can end up in a situation where the state/UI is out of date. For example the following bug exists in the current code:
1. Open model editor
2. Click view on some method
3. Change to source (see it being marked as modeled)
4. Click on another method from the method usages panel 
5. Change to flow summary
At this point the second method should be marked as modeled, but it isn't.
N/A:
=> Ensure modified methods updated after changing a method from the modeling panel

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-panel.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts
This removes the following bug:
1. Open model editor against db X
2. Click view on some method A
3. Open model editor against db Y
4. Click view on some method B
5. Close the model editor tab for db Y
=> At this point the method modeling panel is showing method B even though the model editor for db Y has been closed.
This PR fixes this so that we go back to the "Select an API or method to model" state.
N/A:
=> Track db related to modeled method and react when it closes

extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts
This ensures that even if the model editor opens before activating the CodeQL tab, the modeling panel is initialised properly.
See interna linked issue for more details.
N/A:
=> Set modeling mode when initialising method modeling panel

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodsList.tsx
Updates the `generateMethodsFromLlm` message to not include the full `Method` and `ModeledMethod` objects, but instead to only include the method signatures and let the modeling store provide the full canonical data.
=> Only include method signatures in generateMethodsFromLlm message

extensions/ql-vscode/src/view/common/ResponsiveContainer.tsx
The contents of the header and content were too close so this adds a bit of spacing.
N/A:
=> Add some spacing in modeling method empty states

extensions/ql-vscode/src/model-editor/method.ts, extensions/ql-vscode/src/stories/method-modeling/MethodAlreadyModeled.stories.tsx, extensions/ql-vscode/src/view/method-modeling/MethodAlreadyModeled.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodDataGrid.tsx
We currently allow users to model already modeled methods, so this PR introduces a new blank state.
=> Deal with already modeled methods in the modeling panel

extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/shared/modeled-methods-legacy.ts, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx, extensions/ql-vscode/src/view/method-modeling/ModeledMethodsPanel.tsx
This PR moves `modeled-methods-legacy.ts` to the `/shared` directory, so it's easier to use it in the webview code. We then make use of its methods in a few places that are currently doing their own custom conversion. So this PR doesn't add any new conversion points but does make them more standardised.
=> Make use of modeled-methods-legacy.ts in the webview code

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts
Not sure how we didn't notice this until now but it seems the `FromModelEditorMessage` type doesn't include `CommonFromViewMessages`. This means it doesn't include messages for telemetry or errors.
However the view could still send those messages, and they would trigger the `assertNever` and cause an error. Probably every bit of telemetry was triggering this, but we didn't notice.
=> Add CommonFromViewMessages to FromModelEditorMessage

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
It doesn't seem like this dependency gets used and it pulls in postcss 7, which is an unmaintained version. This should get rid of any dependencies on postcss 7.
=> Remove `gulp-sourcemaps` dependency

extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts
This fixes three bugs related to the modeling store and view states:
- In the model editor view, when `setModeledMethods` was called, it would do it on the active database, instead of the database that the view was showing. This should not result in any visible bugs since the active database is always the one that is being shown (in theory), but I can imagine that it could cause issues if showing multiple model editors next to each other.
- In the method modeling panel, the "reveal in editor" button would always show the already active model editor. Therefore, if you had multiple open and were still viewing the method of the first one, it would always show the second one.
- In the method modeling panel, the same bug would cause the incorrect modeled methods to be updated.
=> Fix confusion between modeling store and view states

extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-data-provider.ts
This is causing a failure when loading the usages panel.
N/A:
=> Ensure modeled methods are not undefined in usages panel

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
This will respect the user's `saveBeforeStart` setting when running a variant analysis. This re-uses the existing `saveBeforeStart` function that is used when running local queries. The default behavior if the setting is not set is to save all open named files.
=> Use `saveBeforeStart` setting when running a variant analysis

extensions/ql-vscode/src/stories/method-modeling/MultipleModeledMethodsPanel.stories.tsx, extensions/ql-vscode/src/view/method-modeling/ModeledMethodsPanel.tsx, extensions/ql-vscode/src/view/method-modeling/MultipleModeledMethodsPanel.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MultipleModeledMethodsPanel.spec.tsx
This adds the ability to add/remove modelings on the method modeling panel if the feature flag is enabled. This adds a plus/trash icon which are enabled based on the already modeled methods:
- If there is more than 1 modeled method, the remove button is enabled
- If all modeled methods are modeled (i.e. not unmodeled, `type !== 'none'`), then the add button is enabled
I've also added a new story for testing this behaviour since the boundary is at the current story, which means that you weren't able to validate that the new `onChange` behavior works. Now, you can fully experiment with the new story since it also keeps track of state.
=> Add ability to add/remove modelings to method modeling panel

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases/local-databases/database-item-impl.ts, extensions/ql-vscode/src/databases/local-databases/database-item.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/shared/view-state.ts, extensions/ql-vscode/src/stories/model-editor/LibraryRow.stories.tsx, extensions/ql-vscode/src/stories/model-editor/MethodRow.stories.tsx, extensions/ql-vscode/src/stories/model-editor/ModelEditor.stories.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/LibraryRow.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/MethodRow.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodDataGrid.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodsList.spec.tsx
Rename 'open database' button of the model editor to 'open source' and hide it if the source is not available as a workspace folder.
=> Rename 'open database' button and only show if source available

extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-view-tracker.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/test/__mocks__/model-editor/modelEditorViewTrackerMock.ts
This will only allow opening a single model editor per database. When a new model editor is opened for which a model editor already exists, it will focus the existing one.
=> Only allow a single model editor per database

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/shared/modeling-status.ts, extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodsList.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/MethodRow.spec.tsx
Switches to using `SetMultipleModeledMethodsMessage` in `FromModelEditorMessage`, and therefore allows editing and saving multiple modeled methods in the model editor.
The only tricky bit was constructing the `onChange` handlers for the input components. That bit could use some scrutiny when reviewing.
Tested locally and appears to be working correctly, both when the feature flag is disabled and enabled.
=> Implement editing / saving multiple modeled methods from the model editor

extensions/ql-vscode/src/view/method-modeling/MultipleModeledMethodsPanel.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MultipleModeledMethodsPanel.spec.tsx
This will change the add button in the method modeling panel to only be disabled if there is exactly 1 unmodeled method and there are no unmodeled methods. This should be more intuitive for users since they are able to see in 1 screen that there is an unmodeled method.
=> Only disable add button when there are no models yet

extensions/ql-vscode/src/view/method-modeling/MultipleModeledMethodsPanel.tsx
It seems like there was a semantic merge conflict between https://github.com/github/vscode-codeql/pull/2959 and https://github.com/github/vscode-codeql/pull/2952 which breaks the build. This adds the missing `useMemo` import.
=> Add missing useMemo import

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/run-queries-shared.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-results.test.ts
This PR changes the filename used for sorted result sets from using the result set name directly to using a hash. Using a hash is preferable as the result set names are generated from the named results of the final stage. It is therefore partially under user-control and may contain additional special characters that cannot be used in filenames as the RA name character set is extended.
=> Hash result set name in sorted result set path

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/shared/modeled-methods-legacy.ts, extensions/ql-vscode/src/stories/method-modeling/MultipleModeledMethodsPanel.stories.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx, extensions/ql-vscode/src/view/method-modeling/ModeledMethodsPanel.tsx, extensions/ql-vscode/src/view/method-modeling/MultipleModeledMethodsPanel.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MultipleModeledMethodsPanel.spec.tsx
This makes the modeled methods panel send the `SetMultipleModeledMethodsMessage` message when the modeled methods change. This is the last step in wiring up the modeled methods panel; after this has been merged, it is possible to view, edit and save multiple models in the method modeling panel.
The only remaining usage of `convertToLegacyModeledMethod` is in the `ModeledMethodsPanel` when the feature flag is disabled. In this case, we're using a different code path, but once the feature flag is removed, it should be possible to remove `convertToLegacyModeledMethod`.
=> Use `SetMultipleModeledMethodsMessage` in modeled methods panel

extensions/ql-vscode/src/view/method-modeling/__tests__/MultipleModeledMethodsPanel.spec.tsx
This was caused by a semantic merge conflict resulting in the wrong `onChange` argument being used in the test.
=> Fix incorrect test for `MultipleModeledMethodsPanel`

extensions/ql-vscode/src/common/readonly.ts, extensions/ql-vscode/src/common/vscode/abstract-webview-view-provider.ts, extensions/ql-vscode/src/common/vscode/abstract-webview.ts, extensions/ql-vscode/src/model-editor/auto-model.ts, extensions/ql-vscode/src/model-editor/auto-modeler.ts, extensions/ql-vscode/src/model-editor/bqrs.ts, extensions/ql-vscode/src/model-editor/method.ts, extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-data-provider.ts, extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-panel.ts, extensions/ql-vscode/src/model-editor/modeled-method-fs.ts, extensions/ql-vscode/src/model-editor/modeled-method.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/src/model-editor/shared/modeled-percentage.ts, extensions/ql-vscode/src/model-editor/shared/modeling-status.ts, extensions/ql-vscode/src/model-editor/shared/sorting.ts, extensions/ql-vscode/src/model-editor/yaml.ts, extensions/ql-vscode/src/view/model-editor/__tests__/MethodName.spec.tsx
This improves the immutability of the modeling store state by using TypeScript's readonly types to ensure that state can only be modified from within the modeling store or when it's copied. This mostly consists of adding `readonly` to properties and arrays, but this also adds a `DeepReadonly` type to use in `postMessage` arguments to ensure that readonly objects can be passed in. `postMessage` will never modify the objects, so this is safe.
Alternative approaches are also possible such as copying the state when retrieving it, but this should guard against the most common cases where we could be modifying state unintentionally.
=> Improve immutability of modeling store state

extensions/ql-vscode/src/model-editor/shared/in-progress-methods.ts, extensions/ql-vscode/src/stories/model-editor/LibraryRow.stories.tsx, extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/LibraryRow.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodDataGrid.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodsList.spec.tsx
I'd like to be able to send `InProgressMethod` objects through webview messages so changing from class to an interface since messages need to be JSON serializable.
N/A:
=> Convert InProgressMethods to an interface

extensions/ql-vscode/src/packaging/packaging.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/packaging/packaging.test.ts
When using the "CodeQL: Install pack dependencies" command, we would show packs that are located in the package cache or distribution. Since there are no dependencies to install for these packs, these options are not useful.
This will filter out any packs that are not in the workspace folders when showing the quick pick. This should exclude most packs if you are in a workspace without the `codeql` submodule and should be a lot more intuitive in those cases. If you are in a workspace with the `codeql` submodule, it will still show all the packs.
Before:
After:
=> Do not show non-workspace packs when installing pack dependencies

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/auto-modeler.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/src/model-editor/shared/in-progress-methods.ts, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/test/__mocks__/model-editor/modelingStoreMock.ts
The state is currently in the React view but we need it in the modeling store so that it can be used by the method modeling panel too.
N/A:
=> Move in-progress methods state to modeling store

extensions/ql-vscode/CHANGELOG.md
This should probably be mentioned in the CHANGELOG since it's a user-visible change to a command.
=> Add CHANGELOG entry for #2960

extensions/ql-vscode/src/model-editor/shared/multiple-modeled-methods.ts, extensions/ql-vscode/src/view/method-modeling/MultipleModeledMethodsPanel.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/MethodRow.spec.tsx
Hooks up the `disabled` attribute for the add/remove model buttons in the model editor.
Uses the same logic as the method modeling panel, and pulls out the implementation to a shared location. Although it turns out the model editor doesn't need the logic for disabling the remove button, because it's never shown in situations when it would be disabled.
Also adds some tests that the buttons are shown / enabled at the right times.
=> Enable/disable the add/remove model buttons at the right times

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-data-provider.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts
In https://github.com/github/vscode-codeql/pull/2926 I was trying to simplify the code as much as possible, but I accidentally changed the `codeQLModelEditor.jumpToMethod` command which does need to be able to jump to usages other than the first usage.
This PR reverts the changes to that command and makes it work again. This does require adding a new `getMethod` method to the modeling store.
I did consider another way of implementing this which was to add a `usageIndex: number` field to the command. That also worked, but I decided it was safer to just revert the changes from the earlier PR and stick more closely to the original state of the code.
=> Revert changes to codeQLModelEditor.jumpToMethod to allow jumping to usages other than the first usage

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/src/model-editor/shared/in-progress-methods.ts, extensions/ql-vscode/src/stories/method-modeling/MethodModelingInputs.stories.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingInputs.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx, extensions/ql-vscode/src/view/method-modeling/ModeledMethodsPanel.tsx, extensions/ql-vscode/src/view/method-modeling/MultipleModeledMethodsPanel.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MethodModeling.spec.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MethodModelingInputs.spec.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/ModeledMethodsPanel.spec.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MultipleModeledMethodsPanel.spec.tsx
Update the method modeling panel to listen to state changes around in-progress methods, and to show the correct UI when the method has modeling is in progress.
N/A:
=> Show in-progress state in method modeling panel

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/databases/local-databases-ui.ts
This removes the old way of filtering the language context now that we have the language filter panel.
For reference the old way was introduced here:
- https://github.com/github/vscode-codeql/pull/2856
- https://github.com/github/vscode-codeql/pull/2871
=> Remove old language context filter.

extensions/ql-vscode/src/model-editor/shared/validation.ts, extensions/ql-vscode/src/view/method-modeling/__tests__/MultipleModeledMethodsPanel.spec.tsx, extensions/ql-vscode/test/unit-tests/model-editor/shared/validation.test.ts
This fixes a bug where the validation of modeled methods would not consider the kind of the modeled method, and would therefore give an error when there was e.g. a neutral sink and a non-neutral summary.
=> Fix neutral model validation to consider kind

extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-data-provider.ts, extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-panel.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/methods-usage/methods-usage-data-provider.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/methods-usage/methods-usage-panel.test.ts
This creates new tree item types for methods and usages such that these can contain references to their parent and children. This allows us to easily find the parent of a usage and to find the children of a method. This removes an expensive `find` call in `getParent`.
=> Introduce separate tree item types in the methods usage panel

extensions/ql-vscode/src/view/method-modeling/__tests__/MultipleModeledMethodsPanel.spec.tsx
This fixes a failing test caused by a semantic merge conflict between #2965 and #2979.
=> Fix failing test

extensions/ql-vscode/src/view/model-editor/ModelKindDropdown.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModelKindDropdown.spec.tsx
When opening a library group in the model editor, unmodeled methods would always be marked as unsaved, even if there were no changes. This was because the `ModelKindDropdown` component did not properly take into account that the `kind` for an unmodeled method should be an empty string. It would always try setting it to `undefined`, which would cause the method to be marked as unsaved. This fixes it by checking if there are valid kinds before setting the kind to the first one.
=> Fix unmodeled methods always being marked as unsaved

extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/MethodRow.spec.tsx
Hooks up the actual `onClick` handler for the add/remove model buttons.
Also adds tests. I couldn't think of any more edge cases to test, but if there are some please let me know and I'll add tests for those.
(While testing, I did spot one bug where the method modeling panel didn't update perfectly. I'll open a separate PR for this.)
=> Implement onClick for the add/remove model buttons in the model editor

extensions/ql-vscode/scripts/source-map.ts
This makes it possible to decode source maps containing references to code that is not part of the extension. If it finds any such references, it will simply not decode the source map and use the original stack trace instead.
Example stack trace:
```
Unhandled error: Error: Illegal argument: character must be non-negative
at w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:1101)
at new s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:121:4419)
at new o (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:121:5899)
at asRange (/Users/user/.vscode/extensions/github.vscode-codeql-1.9.2/out/extension.js:5543 …
```
=> Fix decoding source map with VS Code internal files

extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-data-provider.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/methods-usage/methods-usage-data-provider.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/methods-usage/methods-usage-panel.test.ts
This changes the usage data provider tree items to keep a reference to the method and usage instead of only including their properties in the tree item. This makes it easier to find the original method and usage when revealing an item in the tree. It also removes the `getParent` call in `getTreeItem`.
The main reason for this fix is to ensure `codeQLModelEditor.jumpToMethod` gets the correct `usage` argument. It received the tree item before, but now we can actually pass the usage that was clicked on.
=> Keep reference to original items in usage data provider

extensions/ql-vscode/src/stories/model-editor/InProgressDropdown.stories.tsx, extensions/ql-vscode/src/view/common/Dropdown.tsx, extensions/ql-vscode/src/view/model-editor/InProgressDropdown.tsx
Small style change for in-progress drop-downs to show italic font style.
Also added a Storybook story for in-progress drop-downs.
N/A:
=> Style update to in-progress drop-down

extensions/ql-vscode/src/variant-analysis/custom-errors.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/unit-tests/variant-analysis/custom-errors.test.ts
When the GitHub API returns an error for a missing default branch, we will now show a custom error message. This custom error message includes a link to the page to create the branch. The error is detected using the `errors` field on the response that is now being returned.
Example response:
```json
{
"message": "Variant analysis failed because controller repository dsp-testing/koesie10-empty-repo does not have a branch 'main'. Please create a 'main' branch in the repository and re-run the variant analysis.",
"errors": [
{
"repository": "dsp-testing/koesie10-empty-repo",
"default_branch": "main",
"resource": "Repository",
"field": "default_branch",
"code": "missing"
}
]
}
```
Example error:
=> Add custom error handler for missing default branch

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/query-results.ts
`logFileLocation` was not set after a query finishes running. I don't know when this bug was introduced. I think it goes as far back as the refactor to remove the old query server.
=> Ensure the `logFileLocation` is set

extensions/ql-vscode/src/view/model-editor/MethodRow.tsx
This follows on from https://github.com/github/vscode-codeql/pull/2990.
This addresses the point of using `MultiModelColumn` to fit multiple inputs for a certain field but different models into a single grid cell. Instead, we use one grid cell per input, and use `gridRow="span N"` to make the method name span multiple rows.
Here's what it looks like:
I've used a narrow window width so things flow onto multiple lines. The grid lines are visible because I've highlighted that element in the developer tools. Sadly the grid lines don't show where cells span multiple rows/columns, but you can see by the contents that it's working.
=> Use one grid cell per model input, and have the method name span multiple rows

extensions/ql-vscode/src/stories/model-editor/MethodRow.stories.tsx, extensions/ql-vscode/src/view/method-modeling/ModeledMethodAlert.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/MethodRow.spec.tsx
Implements displaying validation in the model editor. Each validation result is added as a `span 5` grid cell, so it sits underneath the modelings.
I wasn't sure whether the validation errors should span the full width or sit only underneath the modelings. I went with just under the modelings, but changing this would be very easy to do now or in the future.
For now I've disabled the "click on error to highlight model" functionality. I think it's less useful here than it is for the method modeling panel because all the modelings are visible at once and it's not that the invalid bit is on a different page. If we want to we could add highlighting of individual modelings, but it would add a little complexity.
Screenshot:
=> Show validation results in the model editor

extensions/ql-vscode/.eslintrc.js
This will change ESLint to give an error when you do something like this:
```tsx
{x.map((y) => <>{y.name}</>)}
```
In this case, there's no `key` being passed to the top-level element in a map. We should always explicitly pass in a key to make the best use of React. This can be fixed by doing this:
```tsx
{x.map((y) => <Fragment key={y.id}>{y.name}</Fragment>)}
```
We ran into this in #2995: https://github.com/github/vscode-codeql/pull/2995/files#r1363990725
=> Enable `react/jsx-key` for fragment shorthands

extensions/ql-vscode/src/model-editor/extension-pack-picker.ts, extensions/ql-vscode/src/model-editor/extensions-workspace-folder.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/extensions-workspace-folder.test.ts
It is possible to open the model editor without opening a folder, but this gave an unhelpful error message. This adds a more helpful error message.
=> Show error message for no workspace folders with model editor

extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-panel.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-panel.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeling-events.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/test/__mocks__/model-editor/modelingEventsMock.ts, extensions/ql-vscode/test/__mocks__/model-editor/modelingStoreMock.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/methods-usage/methods-usage-panel.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/model-editor-view.test.ts
As part of the method modeling panel work, we introduced a new `ModelingStore` that is used to hold state around modeling and publishing events that the various panels subscribe to. The events are currently part of the `ModelingStore`.
In this PR we introduce a new `ModelingEvents` class and move all the events there. In the future, we can have UI interactions also represented by events.
N/A:
=> Move modeling events to new ModelingEvents class

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/local-queries/local-queries.ts, extensions/ql-vscode/src/local-queries/local-query-run.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/src/query-history/store/query-history-local-query-domain-mapper.ts, extensions/ql-vscode/src/query-history/store/query-history-local-query-dto-mapper.ts, extensions/ql-vscode/src/query-history/store/query-history-local-query-dto.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/run-queries-shared.ts, extensions/ql-vscode/test/factories/query-history/local-query-history-item.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/store/query-history-store.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-results.test.ts
This makes a change to the query history format to save the output directory of the query. This will allow us to open the results directory and show the evaluator log for queries which have been cancelled.
I've also tested that it handles opening an older query history item format. In that case, it will try to recreate the output dir from a completed query, which should always work since we don't store non-completed queries in the query history JSON.
Please review this commit-by-commit.
=> Fix results directory and evaluator log for cancelled queries

extensions/ql-vscode/src/common/errors.ts, extensions/ql-vscode/src/common/logging/notifications.ts, extensions/ql-vscode/src/common/vscode/commands.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-server/legacy/run-queries.ts, extensions/ql-vscode/test/unit-tests/common/errors.test.ts
When calling for example `showAndLogExceptionWithTelemetry`, the stack trace would be sent to Application Insights, but there was no way to see the stack trace from within VS Code. This will add the stack trace to the log by returning it from `fullMessageWithStack` and using it in the appropriate places.
=> Show stack for redactable error in log

extensions/ql-vscode/src/stories/model-editor/MethodRow.stories.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx
This adds back the clickable link in the validation error alert. When clicking on e.g. "Modify or remove the duplicated classification.", the problematic row will be highlighted. This uses a very similar method to the focusing using `revealedMethodRow`.
I think the name `DataGridRow` for this component is still accurate, so I don't think renaming it will make it clearer how this is used.
=> Add higlight on modeled method row when clicking in validation error

extensions/ql-vscode/src/view/method-modeling/MultipleModeledMethodsPanel.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MultipleModeledMethodsPanel.spec.tsx
In the method modeling panel, you may be viewing model 3/3 but then one of the models is deleted. In this case we should now be viewing model 2/2 instead of model 3/2. The "remove model" button in the method modeling panel already handles this, but the list of modeled methods can also be changed by outside sources.
To test this you may need to merge in https://github.com/github/vscode-codeql/pull/2982 so the number of modeled methods can be affected by an external source.
=> Handle when the number of modeled methods decreases

extensions/ql-vscode/src/model-editor/modeling-store.ts
There was a typo on which event to use (introduced in https://github.com/github/vscode-codeql/pull/3005)
N/A:
=> Activate method modeling panel when model editor is opened

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/language-context-store.ts, extensions/ql-vscode/src/local-queries/local-queries.ts, extensions/ql-vscode/src/local-queries/skeleton-query-wizard.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/local-queries/skeleton-query-wizard.test.ts
This will change the "Create new query" command to use the selected language when creating a new query. If no language is selected, it will still prompt the user to pick a language.
=> Use selected language when creating query

extensions/ql-vscode/src/view/model-editor/MethodRow.tsx
Addresses two bugs around the `UnmodelableMethodRow` component. I believe we missed these until now because this component is only shown when the "Hide modeled methods" option is deselected.
One bug is it wasn't computing the `gridColumn: span` value correctly, so when multiple models were shown it would break the entire table layout by trying to put two rows worth of elements on the same grid row. Thankfully this visual bug only manifested when the `codeQL.model.showMultipleModels` feature flag was enabled, and there's no visual change when it isn't enabled.
Another bug is that the `MethodClassifications` component was being added at a different point than from the normal method rows. We were adding it near the end of the cell instead of near the start. This PR changes it to match the …
=> Fix styling of "already modeled" rows when showing multiple methods

extensions/ql-vscode/src/local-queries/skeleton-query-wizard.ts
In the "create query" process, we should open the query as soon as it's created. Currently, it gets opened at the very end of the process, i.e. after the "download database" step. If users skip that download step (or if it fails), then the newly-created query doesn't get opened and is hard to find 🔍 
N/A: the "create query" command is still feature-flagged 🎌
=> Create query: open new query in editor before downloading DB

extensions/ql-vscode/src/model-editor/method.ts, extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-data-provider.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/methods-usage/methods-usage-data-provider.test.ts
Makes sure that the model editor and the usages panel are using the same logic when deciding whether to show or hide a method.
Before this PR, you wouldn't be able to view usages of any methods that were already modeled and the modeling had been saved. We previously thought this bug only applied when you had modelings coming from an external pack, but you can reproduce it within one pack too.
Steps to reproduce:
- Add a modeling to a method
- Save the extension pack
- Click "View" on the modeled method and observe that nothing happens
With this PR, the usages panel and the model editor are fully in sync and show the same methods and clicking "View" always highlights the method in the usages panel.
=> Use the same logic for hiding methods in model editor and usages panel

extensions/ql-vscode/src/queries-panel/queries-panel.ts, extensions/ql-vscode/src/queries-panel/query-tree-data-provider.ts, extensions/ql-vscode/src/queries-panel/query-tree-view-item.ts
This will focus the currently open query in the queries panel. If a file which is not a query file is opened, it does not change the selection.
=> Reveal opened files in queries panel

docs/test-plan.md
This PR adds checks for manually testing the new method modeling flow to our release test plan.
=> Add method modeling flow to test plan

extensions/ql-vscode/src/databases/local-databases-ui.ts, extensions/ql-vscode/src/databases/local-databases/database-manager.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-queries/local-databases.test.ts
When the language context changes, we should make sure that the current database gets deselected. See internal linked issue for details 🔍 
- This feels a bit hacky, but seems to work. A few comments/questions about the implementation inline.
- I also haven't been able to write a test for this (since I couldn't figure out to access the relevant properties/events in the tests), so any suggestions on that front also welcome! 🙏🏽 
N/A—still feature-flagged for internal use ⛳
=> Deselect current db when the language context changes

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/common/sarif-utils.ts, extensions/ql-vscode/src/stories/results/AlertTable.stories.tsx, extensions/ql-vscode/test/unit-tests/common/sarif-utils.test.ts
This fixes an empty message when the SARIF artifact location is `file://`. I've also added it to a story to see it locally without running a query.
Before:
After:
Query that shows this problem: `cpp/ql/src/Security/CWE/CWE-079/CgiXss.ql` with `kirxkirx/vast`.
Closes https://github.com/github/vscode-codeql/issues/1357
=> Fix empty message with empty SARIF path

extensions/ql-vscode/src/config.ts
Enable the multiple models feature for the model editor and panels.
N/A:
=> Enable multiple models feature

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/local-queries/local-queries.ts, extensions/ql-vscode/src/local-queries/skeleton-query-wizard.ts, extensions/ql-vscode/src/queries-panel/queries-module.ts, extensions/ql-vscode/src/queries-panel/queries-panel.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/local-queries/skeleton-query-wizard.test.ts
This will change the behavior of the "Create new query" command to create the new query in the same folder as the first selected item in the queries panel. If no items are selected, the behavior is the same as before.
I've used events to communicate the selection from the queries panel to the local queries module. This is some more code and some extra complexity, but it ensures that we don't have a dependency from the local queries module to the queries panel module. This makes testing easier.
=> Create new queries in selected folder of queries panel

extensions/ql-vscode/src/model-editor/flow-model-queries.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts
This will hide the flow generation button for non-supported languages. Currently, all languages supported by the model editor also have support for flow generation.
=> Only show flow generation button when supported

extensions/ql-vscode/src/codeql-cli/query-language.ts, extensions/ql-vscode/src/databases/database-fetcher.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/local-queries/skeleton-query-wizard.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-submission-integration.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/database-fetcher.test.ts
This will show the language display name when asking for a language (when creating a query or when running a query without detecting the language automatically). It will also sort the languages alphabetically.
=> Use language display name when asking for language

docs/testing.md
Just spotted some minor issues in the testing instructions!
N/A
=> Minor fixes to testing.md

extensions/ql-vscode/src/model-editor/auto-modeler.ts, extensions/ql-vscode/src/model-editor/extensions-workspace-folder.ts, extensions/ql-vscode/src/model-editor/flow-model-queries.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-queries-setup.ts, extensions/ql-vscode/src/model-editor/model-editor-queries.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/external-api-usage-query.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/model-editor-queries.test.ts
We shouldn't be directly using the `extLogger` if we have access to the app logger (either directly or by passing it in as a parameter). This removes all imports of `extLogger` from the model editor directory.
=> Remove `extLogger` imports from model editor

extensions/ql-vscode/src/config.ts
Lowering the batch size to allow higher number of requests required for new functionality.
Basically due to sources we now need double the number of LLM requests, and because we havent increased parallelism we need to half the number of candidates.
N/A:
=> Change auto-model default batch size

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/model-editor/auto-model-api.ts, extensions/ql-vscode/src/model-editor/auto-modeler.ts
=> Add ability to use a dev endpoint for auto-model

extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/databases/local-databases/database-manager.ts, extensions/ql-vscode/src/local-queries/qlpack-generator.ts, extensions/ql-vscode/src/local-queries/skeleton-query-wizard.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/local-queries/skeleton-query-wizard.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/qlpack-generator.test.ts
This will change the skeleton query wizard to detect existing query packs when creating a skeleton query. This allows the user to create a query in an existing query pack that is not named
`codeql-custom-queries-{language}`.
See the linked internal issues for the scenarios this covers.
=> Detect existing query packs when creating skeleton query

extensions/ql-vscode/src/view/common/DataGrid.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx
This fixes a bug where the method row would not scroll into view when revealing a method. The problem was that the `DataGridRow` component on which the `ref` was set is a `display: contents` element, which does not have a visual representation in the DOM. Therefore, it wasn't possible to scroll the method row into view. This fixes it by moving the ref to the `DataGridCell` component of the first column, which is a normal element.
=> Fix scroll into view not working when revealing method

extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/modeling-events.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts
Now that we check [viewState?.language](https://github.com/github/vscode-codeql/blob/6685883ebfdf67782845ccc5da453c9d002a0055/extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx#L83) before showing the "Not in modeling mode" screen,  we need to make sure that `language` is set when opening a new DB. 
N/A:
=> Update method modeling panel language when new db opened

extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/common/bqrs-cli-types.ts, extensions/ql-vscode/src/local-queries/query-resolver.ts, extensions/ql-vscode/src/model-editor/generate-model-queries.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/shared/view-state.ts, extensions/ql-vscode/src/stories/model-editor/LibraryRow.stories.tsx, extensions/ql-vscode/src/stories/model-editor/MethodRow.stories.tsx, extensions/ql-vscode/src/stories/model-editor/ModelEditor.stories.tsx, extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/LibraryRow.spec.tsx, extensions/ql-vscode/test/factories/model-editor/view-state.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/generate-model-queries.test.ts
This adds the ability to generate Ruby models from a database. It uses [the `GenerateModel.ql` query](https://github.com/github/codeql/blob/435b7df764cc9e25ff9b75c7d2523ad1303a312f/ruby/ql/src/queries/modeling/GenerateModel.ql) to do this. The query will essentially return data in the data extensions format, so this will just parse it and return it as `ModeledMethod` objects.
This follows the general flow of [the `generate_model.py` script](https://github.com/github/codeql/blob/435b7df764cc9e25ff9b75c7d2523ad1303a312f/ruby/scripts/generate_model.py).
I didn't really want to add a new setting for this, so this is guarded by the `codeQL.model.flowGeneration` setting.
https://github.com/github/vscode-codeql/assets/1112623/6cd3b100-955f-4453-843c-564fd66aa57f
=> Add generation of Ruby models

extensions/ql-vscode/src/local-queries/qlpack-generator.ts, extensions/ql-vscode/src/local-queries/skeleton-query-wizard.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/qlpack-generator.test.ts
This prevents the creation of duplicate query pack names when creating a query in the following ways:
- When you have selected a folder, the query pack name will include the name of the folder. This should prevent duplicate query pack names when creating queries in different folders. - When the folder name includes `codeql` or `queries`, we will not add `codeql-extra-queries-` since that would be redundant.
- After generating the query pack name, we will resolve all qlpacks and check if one with this name already exists. If it does, we will start adding an index to the name until we find a unique name.
=> Prevent duplicate query packs when creating a query

extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/view/method-modeling/MultipleModeledMethodsPanel.tsx
Adds some telemetry events for interactions with the modeling panel.
The `method-modeling-set-multiple-modeled-methods` is a bit generic, but we can improve that in the future if we want to.
N/A:
=> Add telemetry for method modeling panel

extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelKindDropdown.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModelKindDropdown.spec.tsx
I noticed that the `method` input was not used in the `ModelKindDropdown` so I got rid of it.
N/A:
=> Remove unnecessary ModelKindDropdown input

extensions/ql-vscode/src/model-editor/auto-modeler.ts
See linked internal issue for details.
N/A:
=> Remove logic that sets neutral models during automodeling

extensions/ql-vscode/src/view/common/Alert.tsx, extensions/ql-vscode/src/view/common/Dropdown.tsx, extensions/ql-vscode/src/view/common/FileCodeSnippet/CodeSnippetMessage.tsx, extensions/ql-vscode/src/view/common/HorizontalSpace.tsx, extensions/ql-vscode/src/view/common/TextButton.tsx, extensions/ql-vscode/src/view/common/VerticalSpace.tsx, extensions/ql-vscode/src/view/data-flow-paths/DataFlowPaths.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisRepositoriesStats.tsx
This switches all styled components I could find with custom props to using transient props. It's easiest to review this commit-by-commit; each commit changes 1 component.
=> Use transient props for all styled components

extensions/ql-vscode/src/model-editor/languages/models-as-data.ts, extensions/ql-vscode/src/model-editor/languages/ruby/index.ts, extensions/ql-vscode/src/model-editor/languages/static/index.ts, extensions/ql-vscode/src/model-editor/method.ts, extensions/ql-vscode/src/view/method-modeling/MethodModelingInputs.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelInputDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelOutputDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelTypeDropdown.tsx
This moves the creation of possible method argument options from the view to the languages. This allows differentiating between the languages, for example by using `Argument[self]` for Ruby instead of `Argument[this]`. Right now, this is the only difference, but in the future there will be more differences, like `Argument[block]` for Ruby and keyword arguments for Ruby.
=> Extract creation of method argument options to languages

extensions/ql-vscode/src/model-editor/languages/ruby/index.ts
This adds support for `Argument[key:]` for Ruby. These are used for keyword arguments (in e.g. `def method(key:)`.
[The query will return](https://github.com/hmac/codeql/commit/5cfe71f91b51de1ca61b0c46091f99e0fdc6bc34) keyword arguments as `key:`.
Based on https://github.com/github/vscode-codeql/pull/3052
=> Add support for Ruby keyword arguments

extensions/ql-vscode/src/log-insights/join-order.ts
To improve readability of RA names, we will soon start using an extended character set for RA names. Quoting using backticks will be used to support pretty-printing and parsing of identifiers with extended characters. This PR extends the join-order evaluator log processor's RA parsing with support for quoted identifiers and brings it in line with the DCA join-order badness RA parser (see referenced PR below).
This PR should have no user visible effect until we start using quoted RA names with extended characters in evaluator logs. I've manually verified that we can still process existing evaluator logs and an evaluator log generated with a pre-release CLI that generates quoted identifiers.
=> Extend join order badness RA parser

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases/local-databases-ui.ts
When databases in the DB panel have the same language, let's sort them by name within each language.
=> Sort databases by name if their languages are the same

extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-queries/local-databases.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/local-databases-ui.test.ts
A few bits of clean-up, noticed in https://github.com/github/vscode-codeql/pull/3047.
N/A
=> Minor tidy-up for `local-databases` tests

docs/releasing.md
Updates the instructions for doing an extension release.
The original prompt for this was to add instructions for releasing from a branch other than `main`. This hit some snags because of steps like "lock the main branch", but I think we can change the release process to just avoid all of that.
Major changes are:
- Can now release from a branch other than `main`, so we can do quick bug-fix releases based on the previous release and avoid the risk of releasing other unrelated changes.
- Release from the release branch instead of merging the release branch into `main` and then releasing from `main`.
- No locking or unlocking of branches. There are no issues with PRs being merged during the release process, because everything happens on a separate branch.
- The step for checking node modules …
=> Add instructions for releasing from a branch other than main

extensions/ql-vscode/src/model-editor/modeled-method.ts, extensions/ql-vscode/src/stories/method-modeling/MethodModeling.stories.tsx, extensions/ql-vscode/src/stories/method-modeling/MethodModelingInputs.stories.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingInputs.tsx, extensions/ql-vscode/src/view/method-modeling/ModeledMethodsPanel.tsx, extensions/ql-vscode/src/view/method-modeling/MultipleModeledMethodsPanel.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MethodModelingInputs.spec.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/ModeledMethodsPanel.spec.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MultipleModeledMethodsPanel.spec.tsx, extensions/ql-vscode/src/view/model-editor/InputDropdown.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelInputDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelKindDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelOutputDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelTypeDropdown.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModelKindDropdown.spec.tsx
There are two commits in this PR:
- https://github.com/github/vscode-codeql/commit/0d3e626328768fc40bcad445ee03d399ecb37920 is doing a bunch of prop drilling so that the various input drop-downs have the modeling status available to them.
- https://github.com/github/vscode-codeql/commit/0078093e17a21c073c811d189256725d88e9c111 adds some logic that allows us to differentiate between models that were suggested by automodel but not necessarily accepted/committed, and ones that have.
This is not perfect as only changes to the Type change provenance at the moment. I'm chasing up to find if that's correct.
N/A:
=> Differentiate between suggestions and accepted models

extensions/ql-vscode/src/language-support/contextual/location-finder.ts, extensions/ql-vscode/src/language-support/contextual/query-resolver.ts, extensions/ql-vscode/src/language-support/contextual/template-provider.ts, extensions/ql-vscode/src/local-queries/query-resolver.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/run-cli.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/language-support/contextual/query-resolver.test.ts
This fixes the contextual queries when you are not in a workspace with the submodule and do not have any downloaded packs in the package cache. In that case, the contextual queries would fail because they weren't able to determine which pack belonged to the database.
This fixes it by downloading the `codeql/${language}-all` pack in case no dbscheme is found for the database. After the download is complete, it will return the expected value for the qlpacks. This should work in almost all cases (at least for standard languages).
Tested by removing the `~/.codeql/packages` directory and testing in a workspace without CodeQL submodule.
=> Make contextual queries work for fresh installs

extensions/ql-vscode/src/view/common/DeterminateProgressRing.tsx, extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodDataGrid.spec.tsx, extensions/ql-vscode/src/view/results/Graph.tsx, extensions/ql-vscode/src/view/results/locations/ClickableLocation.tsx, extensions/ql-vscode/src/view/results/locations/Location.tsx, extensions/ql-vscode/src/view/tsconfig.json
This PR enables the `noUnusedParameters` option in `src/view/tsconfig.json` and fixes all of the resulting errors.
With this option enabled it finds unused parameters to function components, e.g. it would detect
```typescript
const MyComponent = ({ myUnusedProp }: Props) => {
return (
<span>Hello World!</span>
);
}
```
However it doesn't appear to detect when there is a field defined on the `Props` type that is never referenced anywhere. So if we removed `myUnusedProp` from the function parameters but left the `Props` type definition as
```typescript
interface Props {
myUnusedProp: string;
}
```
then it would not cause a linting error.
For this PR I've also removed the field from the props types, but long term we should look into if we can catch these automatically as well. There may well …
=> Enable noUnusedParameters for the view code

extensions/ql-vscode/src/model-editor/modeled-method.ts, extensions/ql-vscode/src/view/model-editor/ModelInputDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelKindDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelOutputDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelTypeDropdown.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/MethodRow.spec.tsx
Change the provenance from `ai-generated`/`df-generated` to `ai-manual`/`df-manual` whenever any input changes. Also make sure the provenance remains correct after several updates. 
See internal linked issue for discussion/details on the decision.
N/A:
=> Update provenance when inputs change

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/databases/database-fetcher.ts, extensions/ql-vscode/src/databases/local-databases/database-manager.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-queries/local-databases.test.ts
No longer add the database source folder to the workspace by default (since this caused bugs in single-folder workspaces). If users want to keep the old behaviour of auto-adding DB source folders, they can set the `addDatabaseSourceToWorkspace` setting to `true`.
See internal linked issue for more details.
- https://github.com/github/codeql/pull/14668
=> Don't add database source archive folders by default

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/config.ts
Follow up to #3047 to properly rename this setting and deprecate the old name!
=> Rename "allowHttp" setting

extensions/ql-vscode/src/databases/local-databases/database-manager.ts, extensions/ql-vscode/src/local-queries/qlpack-generator.ts
Fixes a few small bugs:
- The currently selected DB getting deselected when you choose `All languages`: 
https://github.com/github/code-scanning/assets/42641846/370b8c98-f7e9-4c03-9751-dd27b20fca9b
- When the custom queries folder exists (in my case it was empty), error `Could not create skeleton QL pack: EEXIST: file already exists, mkdir '...\codeql-custom-queries-cpp'`. 
See internal linked issue for more details!
N/A (still feature flagged)
=> Fix minor bugs with queries panel + language selector

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/src/databases/database-fetcher.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/database-fetcher.test.ts, extensions/ql-vscode/test/vscode-tests/utils/mocking.helpers.ts
This switches the request to the GitHub API for listing CodeQL databases from a custom request to the Octokit REST API. This allows us to be more type-safe without introducing our own types.
The update to `@octokit/openapi-types` was necessary to have access to the `commit_oid` field.
=> Use Octokit REST for listing CodeQL databases

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/queries-panel/queries-module.ts
Makes queries panel + language filter generally available. See internal issue for more details about the release.
=> Remove feature flags for queries panel + language selector

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/databases/database-fetcher.ts, extensions/ql-vscode/src/databases/github-database-module.ts, extensions/ql-vscode/src/databases/github-database-prompt.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/github-database-prompt.test.ts, extensions/ql-vscode/test/vscode-tests/utils/mocking.helpers.ts
This adds a prompt for the user to download a CodeQL database when opening a GitHub repository. This is currently behind the `codeQL.githubDatabase.enable` feature flag, but this setting is exposed in the VS Code settings UI. This is necessary because `updateValue` on a setting doesn't do anything unless it's listed in the `package.json`.
=> Prompt user for database download on startup

extensions/ql-vscode/src/databases/github-database-prompt.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/github-database-prompt.test.ts
This adds the option to download multiple databases from GitHub in the initial GitHub database download prompt. The databases will be downloaded concurrently.
Unfortunately it doesn't seem possible to change the "OK" text in the quick pick to "Download", so I've left it as "OK" for now.
=> Allow downloading multiple databases from GitHub

extensions/ql-vscode/package.json
This removes the `workspaceContains:.git` activation event since it seems to be conflicting with running CLI tests. When this is present, the extension is activated before the Jest setup script is ran and the incorrect version is retrieved from the CLI.
=> Remove workspaceContains:.git activation event

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/databases/github-database-download.ts, extensions/ql-vscode/src/databases/github-database-module.ts, extensions/ql-vscode/src/databases/github-database-updates.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/github-database-updates.test.ts
This adds a prompt for updating GitHub databases for the current repository. If the user clicks "Update", it will prompt for which languages to update the database for. Once selected, it will download and store the new databases, and then automatically delete the old ones. It will keep the selected database to the same language and repository.
=> Add prompt for updating GitHub databases

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/local-queries/local-queries.ts, extensions/ql-vscode/src/local-queries/quick-query.ts, extensions/ql-vscode/test/unit-tests/command-lint.test.ts
The "Quick query" command creates a new workspace folder, which doesn't work well for users in single-folder workspaces. This PR adds a prompt for those people to encourage them to use the new "Create query" command instead:
See internal linked issue for more details.
- N/A: No docs change needed
=> Discourage use of "Quick query" in single-folder workspaces

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases/local-databases/locations.ts
This preserves the focus on the results viewer when showing a location to ensure that the user can navigate to the next result without having to click or change the focus to the results viewer first. This allows the user to quickly navigate through the results.
=> Preserve focus on results viewer when showing location

extensions/ql-vscode/src/databases/github-databases/api.ts, extensions/ql-vscode/src/databases/github-databases/download.ts, extensions/ql-vscode/src/databases/github-databases/github-database-module.ts, extensions/ql-vscode/src/databases/github-databases/github-databases-module.ts, extensions/ql-vscode/src/databases/github-databases/index.ts, extensions/ql-vscode/src/databases/github-databases/updates.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/github-databases/api.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/github-databases/download.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/github-databases/updates.test.ts
This refactors all GitHub databases files to be in a separate directory and fixes the naming of the module.
=> Move GitHub databases files to separate directory

extensions/ql-vscode/package.json, extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/databases/database-fetcher.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/jest.setup.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/model-editor/modeled-method-fs.test.ts
It seems like changes to the CLI path setting are not picked up by the extension when it is already activated. This is probably because the `workspace.onDidChangeConfiguration` event is not fired when the update is made programmatically.
This fixes it by manually firing the event so that all listeners (CLI server, query server, IDE server) can pick up the change.
Some other small changes to the tests were necessary to make everything work (mostly with retries), but this should now work properly.
=> Fix tests with `workspaceContains:.git` activation event

extensions/ql-vscode/.eslintrc.js, extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/common/sarif-utils.ts, extensions/ql-vscode/src/common/vscode/archive-filesystem-provider.ts, extensions/ql-vscode/src/databases/db-item-selection.ts, extensions/ql-vscode/src/databases/local-databases/database-item-impl.ts, extensions/ql-vscode/src/local-queries/results-view.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/src/view/results/locations/NonClickableLocation.tsx, extensions/ql-vscode/src/view/results/result-keys.ts, extensions/ql-vscode/test/unit-tests/command-lint.test.ts, extensions/ql-vscode/test/unit-tests/variant-analysis/custom-errors.test.ts, extensions/ql-vscode/test/vscode-tests/ensureCli.ts
This enables [the ESLint `curly` rule](https://eslint.org/docs/latest/rules/curly) with its options set to `all`. This enforces curly braces around all blocks, even single-line ones.
I've used `npm run lint -- --fix` to fix all occurrences.
=> Enable ESLint `curly` rule

extensions/ql-vscode/src/codeql-cli/cli.ts
This hides that the `resolve tests` command is run from the user, as it is run as part of a background process and spams the log.
=> Silence `resolve tests` command

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/snippets.json
The snippets were expanding to the old class-based dataflow API which we don't want users to use anymore.
This PR updates those snippets to expand to the new module-based API:
=> Change dataflow and taint-tracking snippets to match the module-based API

extensions/ql-vscode/src/common/bqrs-cli-types.ts, extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/compare/compare-view.ts, extensions/ql-vscode/src/compare/result-set-names.ts, extensions/ql-vscode/src/compare/resultsDiff.ts, extensions/ql-vscode/src/stories/compare/CompareTable.stories.tsx, extensions/ql-vscode/src/view/results/RawTableHeader.tsx
This makes a start on refactoring the compare view to be more maintainable and extensible. The main changes are:
- Extracting a `findResultSetNames` function from `findCommonResultSetNames`
- Renaming `findCommonResultSetNames` to `findResultSetsToCompare`
- Caching BQRS schemas instead of reading them when changing result sets
=> Refactor compare view

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/compare/compare-view.ts, extensions/ql-vscode/src/compare/resultsDiff.ts, extensions/ql-vscode/src/stories/compare/CompareTable.stories.tsx, extensions/ql-vscode/src/view/compare/Compare.tsx, extensions/ql-vscode/src/view/compare/CompareTable.tsx
The columns are part of the result, so they should be moved there. This is in preparation of showing SARIF results in the same view, which don't have columns.
=> Move columns in compare view to result

extensions/ql-vscode/src/view/compare/CompareTable.tsx, extensions/ql-vscode/src/view/compare/RawCompareResultTable.tsx
This extracts part of the `CompareTable` component to a new `RawCompareResultTable` to reduce duplication between the `from` and `to` columns.
=> Extract `RawCompareResultTable` component

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/view/compare/Compare.tsx
The loading message for the compare view was never shown because the `comparison` was never `undefined`/`null`. This changes the comparison to be `null` on load to make sure that we explicitly handle this case rather than relying on an empty comparison message. This helps when there is a large number of results and loading them takes a while.
=> Fix loading message for compare view

extensions/ql-vscode/src/view/compare/Compare.tsx, extensions/ql-vscode/src/view/compare/CompareTable.tsx, extensions/ql-vscode/src/view/results/resultsView.css
This switches all compare view components to use `styled-components` rather than separate CSS to make it easier to modify and ensure more locality.
=> Switch to styled-components for compare components

extensions/ql-vscode/src/view/common/VerticalRule.tsx, extensions/ql-vscode/src/view/results/AlertTablePathNodeRow.tsx, extensions/ql-vscode/src/view/results/AlertTablePathRow.tsx, extensions/ql-vscode/src/view/results/EmptyQueryResultsMessage.tsx, extensions/ql-vscode/src/view/results/octicons.tsx, extensions/ql-vscode/src/view/results/resultsView.css
This switches some classes in the results view to styled components. It also removes some classes that I wasn't able to find a usage for.
=> Switch to styled-components for some components in the results view

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/compare/compare-view.ts, extensions/ql-vscode/src/compare/result-set-names.ts, extensions/ql-vscode/src/stories/compare/CompareTable.stories.tsx, extensions/ql-vscode/src/view/compare/Compare.tsx, extensions/ql-vscode/src/view/compare/CompareTable.tsx
This splits up the compare view messages into 1 message for the query info and 1 message for the result set. To make this possible, the compare view now also caches the common result set names.
=> Split compare view messages

.github/dependabot.yml
Patch and minor upgrades of dependencies can also be useful and contain performance improvements etc. We now need to manually run these using `npm upgrade`, which either results in a risky upgrade by upgrading all dependencies, or a lot of time spent on upgrading single dependencies. This will create more Dependabot PRs, but these should be relatively safe and easy to merge.
=> Do not ignore patch/minor updates in Dependabot configuration

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
`classnames` provides its own type definitions, so we do not need to have this installed.
=> Remove `@types/classnames` package

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/language-support/contextual/template-provider.ts
This will avoid showing a query-server popup on hovers. When someone does CTRL+hover on source code in a database archive, the definitions provider is triggered. The first time this is run, there will be a query that is invoked in order to find definitions. This can be a long process.
Previously, this query brought up a popup window that could be cancelled. However, this is confusing users since the query is automatically cancelled when the mouse hovers away from the element.
The downside of this PR is that even when find definitions is explicitly invoked, (using F12), there will still be no hover.
I think this is an improvement, but I am happy to discuss if others disagree.
- [n/a] _[Maintainers only]_ If this pull …
=> Avoid creating a multitoken when finding definitions

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/jest-runner-vscode.config.js, extensions/ql-vscode/test/vscode-tests/cli-integration/jest-runner-vscode.config.js, extensions/ql-vscode/test/vscode-tests/cli-integration/jest.setup.ts, extensions/ql-vscode/test/vscode-tests/jest.activated-extension.setup.ts
This is to avoid downloading the CodeQL CLI in each test suite
N/A:
=> Allow the CodeQL CLI path to be set from an environment variable

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/compare/compare-view.ts, extensions/ql-vscode/src/compare/interpreted-results.ts, extensions/ql-vscode/src/compare/result-set-names.ts, extensions/ql-vscode/src/compare/sarif-diff.ts
This adds diffing of SARIF results to the compare view. It naively compares the `JSON.stringify` of the SARIF results and doesn't do anything smart about differing paths etc.
=> Add SARIF result comparison to compare view

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/model-editor/consistency-check.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/modeling-events.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/test/unit-tests/model-editor/consistency-check.test.ts
This adds an internal consistency check for the model editor. This catches cases where the model editor thinks something is supported, but the model editor queries return that it it not supported.
This would for example have caught https://github.com/github/codeql/pull/15089 without needing to manually check the query.
=> Add a consistency check for the model editor

extensions/ql-vscode/src/databases/database-fetcher.ts, extensions/ql-vscode/src/databases/local-databases-ui.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/databases/database-fetcher.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/new-query.test.ts, extensions/ql-vscode/test/vscode-tests/global.helper.ts
The CodeQL CLI always supports the `database unbundle` command since https://github.com/github/vscode-codeql/commit/140d369098b286a006322432777b88649832c954 so we can remove the fallback behavior.
There were some places which were not passing in the CodeQL CLI server, but these always have access to the CLI server, so this just passes them in.
The only change in behavior (in terms of the fallback behavior) is in the `new-query.test.ts` test.
=> Remove fallback behavior for database unbundle

extensions/ql-vscode/src/model-editor/yaml.ts, extensions/ql-vscode/test/unit-tests/model-editor/yaml.test.ts
This fixes some incorrect model files on case-insensitive file systems when the package names are the same but the capitalization is different.
For example, when there are two packages `Volo.Abp.TestApp.MongoDb` and `Volo.Abp.TestApp.MongoDB`, there would be 1 model file for each package. However, on case-insensitive file systems, the second file would overwrite the first file. This results in missing models. This fixes it by canonicalizing the filenames to lowercase and writing all files with the same package name to the same file.
=> Fix incorrect model files on case-insensitive file systems

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/unzip.ts, extensions/ql-vscode/src/common/vscode/archive-filesystem-provider.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/common/vscode/archive-filesystem-provider.test.ts
This switches the archive filesystem provider to `yauzl` instead of `unzipper` in preparation for removing `unzipper`. There should be no changes in behavior (except when Node > 18.15.0, in which case `unzipper` might actually read corrupted ZIP files).
=> Switch to `yauzl` in the archive filesystem provider

extensions/ql-vscode/src/codeql-cli/distribution.ts, extensions/ql-vscode/src/common/distribution.ts, extensions/ql-vscode/src/common/unzip.ts, extensions/ql-vscode/test/vscode-tests/ensureCli.ts
This switches the CodeQL CLI download to `yauzl` instead of `unzipper`. There should be no changes in behavior. I tested this manually on Insiders by removing the distribution directory and this successfully downloaded and extracted the CLI.
=> Switch to `yauzl` for CodeQL CLI

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/scripts/source-map.ts
This moves the last call to `unzipper` to use `yauzl` instead. Since we're not using `unzipper` anymore, this also removes `unzipper` as a dependency.
=> Switch to `yauzl` for source map script

extensions/ql-vscode/src/query-testing/qltest-discovery.ts
During the qltest discovery, we were recreating the watchers for qltests on every file change. This was causing the watchers to be recreated on each change, while there were no functional changes to the watchers themselves.
This commit moves the creation of the watchers to the constructor of the QLTestDiscovery class, and removes the creation of the watchers from the discover() method. The behavior should be the same.
=> Do not reregister watchers on every file change for qltests

extensions/ql-vscode/package.json
This setting has been removed, so it should not be referenced in `package.json` anymore.
=> Remove missed feature flag reference from package.json

extensions/ql-vscode/scripts/generate-schemas.ts, extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/common/discovery.ts, extensions/ql-vscode/src/common/qlpack-language.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/local-queries/skeleton-query-wizard.ts, extensions/ql-vscode/src/model-editor/extension-pack-metadata.schema.json, extensions/ql-vscode/src/model-editor/extension-pack-metadata.ts, extensions/ql-vscode/src/packaging/qlpack-file-loader.ts, extensions/ql-vscode/src/packaging/qlpack-file.schema.json, extensions/ql-vscode/src/packaging/qlpack-file.ts, extensions/ql-vscode/src/queries-panel/queries-module.ts, extensions/ql-vscode/src/queries-panel/query-pack-discovery.ts, extensions/ql-vscode/test/unit-tests/common/qlpack-language.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/queries-panel/query-pack-discovery.test.ts
This removes the use of the CLI `codeql resolve library-path` command to detect the language of a query pack. Instead, it uses the `qlpack.yml` file to determine the language. This is slightly less correct since it only works for `codeql/${language}-all` dependencies, but it is much faster and more reliable. It also doesn't result in the CLI server restarting for invalid query packs (such as in the `github/codeql` repository or in any workspaces containing it). Query pack discovery on `github/codeql` now takes less than 3 seconds rather than more than 11 seconds, and it also doesn't slow down other extension operations using the CLI server anymore.
=> Do not use the CLI server to determine query pack language

extensions/ql-vscode/src/codeql-cli/distribution.ts, extensions/ql-vscode/src/config.ts
As far as I can tell, these fields do not work. They aren't linked up to read values from the config, and setting `"codeQL.cli.repositoryName": "foo"` in your config does nothing.
This reason for this is because the only way these values are accessed is through the `DistributionConfigListener` class, which implements the `DistributionConfig` interface. That class does not define these fields and therefore they get their default value of `undefined`. The reason we didn't notice this earlier is because the field is allowed to be `undefined`. If you change the type to `string | null` then it produces an error.
Looking back in the history, I believe the intention was to fully remove these in https://github.com/github/vscode-codeql/pull/174 (see the comments on the linked internal issues) but …
=> Remove ownerName and repositoryName from DistributionConfig

extensions/ql-vscode/src/common/logging/vscode/output-channel-logger.ts, extensions/ql-vscode/src/stories/common/Alert.stories.tsx, extensions/ql-vscode/src/view/variant-analysis/FailureReasonAlert.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisStatusStats.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisStats.spec.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisStatusStats.spec.tsx
This PR removes ambiguity of our 'View logs' messages.
=> Remove ambiguity from 'View logs' messages

.github/dependabot.yml, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/scripts/update-node-version.ts
According to the DefinitelyTyped documentation, the patch version of the type declaration package is unrelated to the library patch version. Therefore, we should use an [X-range](https://github.com/npm/node-semver?tab=readme-ov-file#x-ranges-12x-1x-12-) for `@types/node` to allow newer patch versions to be installed automatically.
=> Use semver range for `@types/node`

docs/vscode-version.md, extensions/ql-vscode/package.json, extensions/ql-vscode/scripts/generate-chromium-version.ts
This also adds the script as a script in the `package.json` with the naming such that `npm generate` will re-generate the Chromium version file. This will ensure that the CI checks fail when the Chromium version doesn't match the minimum supported VS Code version.
I've also updated the documentation for updating the VS Code version to simply run `npm run generate` which will run this script as well.
=> Rename update Chromium version script to generate Chromium version

docs/node-version.md, docs/vscode-version.md
There were still references to a pinned version of VS Code used in the integration tests, but this was resolved in https://github.com/github/vscode-codeql/pull/2877.
=> Update outdated VS Code version docs

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/model-editor/extension-pack-picker.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-queries.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/extension-pack-picker.test.ts
Opening the model editor takes a while. This PR gives the user the option to cancel the progress and not open the editor.
When cancelling the open process the user effectively cancels a query run. This results in an error message and a telemetry event.
From my investigation I deduct that this behaviour stems from the query server in https://github.com/github/vscode-codeql/blob/nora/make-model-editor-open-cancellable/extensions/ql-vscode/src/query-server/run-queries.ts#L69
I would be happy for feedback on how to resolve this issue.
=> CodeQL model editor: user should be able to stop modeling before the main editor view is open

extensions/ql-vscode/src/model-editor/model-editor-queries.ts
This fixes a missing `await` in `prepareModelEditorQueries` that caused the function to potentially return before the query files were written.
This was discovered by looking at the error in https://github.com/github/vscode-codeql/pull/3197.
=> Fix missing `await` in `prepareModelEditorQueries`

.github/workflows/update-node-version.yml
This adds a GitHub Actions workflow that runs on a schedule to update the Node version based on the latest released VS Code version. The PR will only be created when there is a change.
=> Add GitHub Actions workflow for updating Node version

extensions/ql-vscode/.eslintrc.js
This removes some ESLint rules that do not give any linting errors when removing the rule overrides from the config file. This could be because there are no instances of the rule being violated, or because the rule is already disabled by some other configuration.
=> Remove disabled ESLint rules without linting errors

extensions/ql-vscode/.eslintrc.js, extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/common/helpers-pure.ts, extensions/ql-vscode/src/common/sarif-utils.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/language-support/language-support.ts, extensions/ql-vscode/src/variant-analysis/export-results.ts, extensions/ql-vscode/test/matchers/toEqualPath.ts
This removes some more ESLint rule overrides for rules for which there were very few violations. This simplifies our ESLint configuration. It's easiest to review this commit-by-commit.
=> Remove more ESLint rule overrides

README.md
I'm not sure much we care about this CI status badge! But either way, we probably want it to point to our `main` branch ✔️ 
N/A
=> Update CI status badge in README

extensions/ql-vscode/src/model-editor/languages/ruby/access-paths.ts, extensions/ql-vscode/src/model-editor/languages/ruby/index.ts
This moves all functions for parsing and formatting Ruby access paths to a separate file so they can be re-used in the future. It also makes the `ruby/index.ts` file easier to read.
=> Move Ruby access paths functions to separate file

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases/local-databases-ui.ts, extensions/ql-vscode/src/local-queries/local-queries.ts
Previously, if you ran a query without having a DB selected, the extension would pop up a file explorer window prompting you to select a database archive from your file system. This isn't the most common way to select a database so it was a fairly confusing pop-up. See internal issue for more info 🔍 
New flow (inspired by designs from the internal issue, though I updated the wording slightly):
- Choose between an existing or new DB:
- If you choose "existing", we list the DBs from your DB panel
- If you choose "new", we offer the different options for importing a DB:
In all cases, we select that DB and run the query against it 🎉 (Note: this also works in the same way for "[CodeQL: Debug Query](https://github.com/github/vscode-codeql/pull/2291)") 
- Suggestions on wording and code …
=> Improve user experience when no database is selected

extensions/ql-vscode/src/model-editor/shared/access-paths.ts, extensions/ql-vscode/test/unit-tests/model-editor/shared/access-paths.test.ts
This adds functions for parsing and validating access paths (such as `Argument[foo].Element.Field[foo.Bar.x]`) to prepare for future functionality where we're going to be parsing and validating access paths. These functions are not yet used in this PR.
See the description of the `access-paths.ts` for the reasons for manually parsing the access path rather than simply splitting by `.` or using a regex.
Example result of `parseAccessPathTokens` (from the test):
**Input**: `Argument[foo].Element.Field[foo.Bar.x]`
**Output**:
```json
[
{
"range": {
"start": 0,
"end": 13
},
"text": "Argument[foo]"
},
{
"range": {
"start": 14,
"end": 21
},
"text": "Element"
},
{
"range": {
"start": 22,
"end": 38
},
"text": "Field[foo.Bar.x]"
}
]
```
=> Add functions for parsing and validating access paths

extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-mapper.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-monitor.ts, extensions/ql-vscode/test/unit-tests/variant-analysis/variant-analysis-mapper.test.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-monitor.test.ts
Renaming mapping functions around variant analysis objects to `mapXXX` (from `processXXX`).
Whenever I read `processXXX` it makes me think it's actually processing the variant analysis submission etc. when in fact it just maps from one object to another.
N/A:
=> Rename variant analysis mapping functions

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/view/common/DataGrid.tsx, extensions/ql-vscode/src/view/common/Dropdown.tsx, extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodsList.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/LibraryRow.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/MethodRow.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModelEditor.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodDataGrid.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodsList.spec.tsx
Adds the ability to click specific rows in the model editor, and just save those instead of the entire library/model. See internal linked issue for more details. (Paired with @robertbrignull 🍐)
Probably easiest to review commit-by-commit, since there's quite a bit of boilerplate.
https://github.com/github/vscode-codeql/assets/42641846/77c90ed6-6d2c-4bf6-bf2a-2db0a2143e42
I'm opening the PR now to get some general feedback on the approach, since we can change the styling more easily. I already have a few concerns/questions:
- The "focused" property (from clicking "Review in editor") also temporarily highlights a row (until you click away). I've changed the "focused" background colour to an orange-y thing, but it might still be confusing: …
=>  CodeQL model editor: support saving single/selected models

extensions/ql-vscode/src/view/common/SuggestBox/__tests__/highlight.test.ts, extensions/ql-vscode/src/view/common/SuggestBox/__tests__/options.test.ts, extensions/ql-vscode/src/view/common/SuggestBox/highlight.ts, extensions/ql-vscode/src/view/common/SuggestBox/options.ts
This adds some helper functions that will be used for a suggestion box in the future. There is one helper function for highlighting part of a text case-insensitively. Another helper function will try to find followup options based on a list of tokens.
The tests for these functions use access paths as input, but these functions are not intended to be specific to access paths. They can be used for any list of options/string.
=> Add helper functions for suggestion box

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
This PR adds stubs of commands for `codeQL.runVariantAnalysisContextExplorer` and `codeQL.runVariantAnalysisPublishedPack`. Both of these are currently behind the canary flag and a new `codeQL.variantAnalysis.multiQuery`. We're not trying to fully implement these commands in this PR, but just add the boilerplate that we can extend later.
=> Add stubs of commands for multi-query support

extensions/ql-vscode/src/view/common/useDebounceCallback.ts, extensions/ql-vscode/src/view/model-editor/ModelInputDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelOutputDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelTypeTextbox.tsx
For type models, it doesn't make sense to have an input and output column dropdown. We instead use the "input" column to store the `path` and the "output" column the `relatedTypeName`: 
These are now free text fields instead of dropdowns. Note: I haven't played around much with styling and different sized screens yet, but it looks like things resize in a sensible way 🤔 
See internal linked issue for more details! (Paired with @koesie10 🍐)
N/A: this is still feature-flagged for internal use.
=> CodeQL model editor: Add support for free text input in type models

extensions/ql-vscode/src/view/model-editor/ModelTypeDropdown.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModelTypeDropdown.spec.tsx
Currently type models in Ruby are read-only, and you can't manually select/define one. This PR adds it as a selectable type. (Based on https://github.com/github/vscode-codeql/pull/3217, which turns the input/output dropdowns into free text fields. See internal linked issue for more details)
Any suggestions on if/how to test this? 🤔 Maybe a view test in [MethodRow.spec.tsx](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/src/view/model-editor/__tests__/MethodRow.spec.tsx) or something?
N/A
=> CodeQL model editor: Make `Type` a selectable model kind for Ruby

extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
This is a small change to set us up for future support for multiple queries.
I've stuck with the original name for now to avoid confusion/conflicts, but in the future we should consider renaming the variables to something more useful e.g. `queryFileUris`.
N/A:
=> Allow multiple file URIs to be passed into prepareRemoteQueryRun

extensions/ql-vscode/test/common/logging/output-channel-logger.test.ts, extensions/ql-vscode/test/unit-tests/common/disposable-object.test.ts, extensions/ql-vscode/test/unit-tests/databases/config/db-config-store.test.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-manager.test.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-monitor.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-queries/local-databases.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/queries-panel/query-tree-data-provider.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/codeql-cli/distribution.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/common/vscode/external-files.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/common/vscode/progress.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/database-fetcher.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/language-support/ast-viewer/ast-builder.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/language-support/ast-viewer/ast-viewer.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/local-queries/query-resolver.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/variant-analysis-history.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-results.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-testing/test-adapter.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-testing/test-runner.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/telemetry.test.ts
Replaces 3 methods we identified are deprecated with the successor.
=> Remove deprecated jest syntac

extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/codeql-cli/query-language.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
Implements the `codeQL.runVariantAnalysisPublishedPack` command. This can likely still be considered a prototype implementation, but it seems to work quite well. Of course right now it fails saying you can't run multiple queries, but that will be fixed in the future.
=> Add prototype implementation for codeQL.runVariantAnalysisPublishedPack

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/common/vscode/telemetry.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/telemetry.test.ts
We'd like to know if users are re-enabling the old behaviour of [auto-adding database sources](https://github.com/github/vscode-codeql/pull/3047) to the workspace. In future, this same approach could be extended to other settings. 
See internal linked issue for more info and an example Kusto query! 🔗 
- https://github.com/github/codeql/pull/15333
=> Send telemetry for `addDatabaseSourceToWorkspace` setting

extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/src/variant-analysis/shared/variant-analysis.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-mapper.ts
Add some data and logic to ensure that multi-query MRVAs are skipped from the query history for now. 
I've added a `queries` field to the `VariantAnalysis` entity with a single `language` field to help drive this, but in the future that will look very different. By changing the domain entity and not touching the query history, we're making it really easy for us to change how it looks, while the multi-query feature gets more fleshed out.
N/A:
=> Skip multi-query MRVAs from query history

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/stories/common/SuggestBox.stories.tsx, extensions/ql-vscode/src/view/common/SuggestBox/SuggestBox.tsx, extensions/ql-vscode/src/view/common/SuggestBox/SuggestBoxItem.tsx, extensions/ql-vscode/src/view/common/SuggestBox/__tests__/SuggestBox.test.tsx, extensions/ql-vscode/src/view/common/SuggestBox/index.ts, extensions/ql-vscode/src/view/common/SuggestBox/options.ts
This creates a `SuggestBox` component that can be used for a VS Code-like autocomplete on a list of options.
https://github.com/github/vscode-codeql/assets/1112623/70cc0586-d734-4110-906a-6a36bc97f4df
This does not yet wire it up to anything, nor does it use the functions introduced in #3218. This component is not specific to access paths and could be used for any list of options with follow-up options.
The component uses [`@floating-ui/react`](https://floating-ui.com/docs/react) to correctly position the suggestions and to implement accessibility correctly. Documentation about this can be found on [the Floating UI docs](https://floating-ui.com/docs/react). The example most like this implementation is the [Autocomplete (combobox)](https://codesandbox.io/s/fragrant-water-bsuirj?file=/src/Ap …
=> Create `SuggestBox` component

extensions/ql-vscode/src/view/common/SuggestBox/HighlightedText.tsx, extensions/ql-vscode/src/view/common/SuggestBox/LabelText.tsx, extensions/ql-vscode/src/view/common/SuggestBox/SuggestBox.tsx, extensions/ql-vscode/src/view/common/SuggestBox/highlight.ts
This adds highlighting of the currently typed text into the shown items of the suggest box. See the blue highlighted part here:
=> Add highlighting to items in suggest box

extensions/ql-vscode/src/codeql-cli/cli-command.ts, extensions/ql-vscode/src/codeql-cli/cli-version.ts, extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/codeql-cli/distribution.ts, extensions/ql-vscode/src/common/short-paths.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/test/matchers/toExistInCodeQLPack.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/data-remote-qlpack/qlpack.yml, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts, extensions/ql-vscode/test/vscode-tests/cli.ts, extensions/ql-vscode/test/vscode-tests/utils/bundled-pack-helpers.ts
This PR updates the VS Code extension to use `codeql pack bundle --mrva` to create the compiled pack to submit to MRVA. If the current CLI does not support `codeql pack bundle --mrva`, we fall back to the old manual pack creation path, where we manually copy the appropriate files and adjust the dependencies.
A commit-by-commit review is suggested. The first couple commits have the major changes. The remainder are either trivial fixes or minor test logging improvements. These test logging improvements were useful for debugging CI failures, so I left them in for future use.
Key changes:
- The extension can now consume the JSON output of `codeql version` to see what features the current CLI version supports. We use this to detect `--mrva` support for `codeql pack bundle`. This is the …
=> Use CLI to bundle packs for MRVA

extensions/ql-vscode/src/databases/local-databases-ui.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/local-databases-ui.test.ts
Follow-up to https://github.com/github/vscode-codeql/pull/3214 to add a basic test of the new "Select database" prompt. 
I plan to open a new issue for more comprehensive tests and to improve the feature generally, so this is just a starting point and to get advice on whether this is a sensible way to test... 
(Example follow-up work: we could probably filter any existing DBs by language, check that we actually _have_ existing DBs, test those different cases...) 
N/A - test change only
=> Add test for "promptForDatabase"

extensions/ql-vscode/src/variant-analysis/ql-pack-details.ts, extensions/ql-vscode/src/variant-analysis/run-remote-query.ts
The `generateQueryPack` function in `run-remote-query.ts` currently has logic to calculate a few things like the QL pack root, paths to the query files, the language, etc. In order to add multi-query support, a few of these calculations need to be moved further up the stack and then passed in to `generateQueryPack` as arguments. 
In this PR, we're introducing a new type (`QlPackDetails`) in the `/variant-analysis` domain to hold such information so that a single object can be passed in to `generateQueryPack` and using that to include the `queryFile`. In follow up PRs, we'll also need to move the language, and other related information. We'll also transition from a singular `queryFile` to multiple ones.
I'm not 100% convinced on the `QlPackDetails` name, so open to suggestions! We can also …
=> Use object for pack generation details

extensions/ql-vscode/src/view/model-editor/ModelTypeTextbox.tsx
When you click the `Type` input boxes in the model editor (for Ruby), this shouldn't select/deselect the row: 
(Inspired by https://github.com/github/vscode-codeql/pull/3156/commits/c8d31278a383edc63cedec4115243197668370c6, which disables (de)selection when you click a dropdown) 
N/A: Feature-flagged for internal use for now.
=> CodeQL model editor: Don't highlight row when clicking inside text box

extensions/ql-vscode/src/common/ql.ts, extensions/ql-vscode/src/databases/qlpack.ts, extensions/ql-vscode/src/local-queries/quick-query.ts, extensions/ql-vscode/src/local-queries/skeleton-query-wizard.ts, extensions/ql-vscode/src/model-editor/extension-pack-picker.ts, extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/test/unit-tests/common/ql.test.ts
I think this makes it clearer what this function does.
N/A:
=> Rename `getQlPackPath` to `getQlPackFilePath`

extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
Newer CLI versions preserve the metadata for extensible predicates in the compiled pack, so they no longer preserve queries that contain extensible predicates when creating a MRVA pack.
Fixes https://github.com/github/semmle-code/issues/48686
=> Fix MRVA integration test failure

extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
Pushes creating `QlPackDetails` even further up the stack - where details will be decided, which is nearer the commands.
N/A:
=> Push QL pack details creation to commands

extensions/ql-vscode/src/common/ql.ts, extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
ql.ts seems a better location for this function so I've moved it.
N/A:
=> Move findPackRoot to ql.ts

extensions/ql-vscode/src/variant-analysis/ql-pack-details.ts, extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
Similar to https://github.com/github/vscode-codeql/pull/3267, this PR moves the QL pack file path out of `generateQueryPack`.
N/A:
=> Move QL pack file path to the QlPackDetails

extensions/ql-vscode/src/variant-analysis/ql-pack-details.ts, extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-submission-integration.test.ts
Similar to https://github.com/github/vscode-codeql/pull/3267, this PR moves the query language out of `generateQueryPack`.
N/A:
=> Move query language to the QlPackDetails

extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
Aims to fix the CLI tests on windows. We believe they were broken in https://github.com/github/vscode-codeql/pull/3262 by the change to `getFile`. This PR adds back in the use of `Uri.file(...).fsPath` to convert the paths supplied by the test code (which always use forward slashes) to a platform-dependent file path.
Successful CLI test run: https://github.com/github/vscode-codeql/actions/runs/7639479147
There may well be other ways of achieving this, though I can't immediately find one that's clearly better. Stackoverflow is suggesting `somepath.split(path.sep).join(locale.sep)` though I'm not sure I like that more than using `Uri`. Since it's just for the CLI tests I don't think we need to be too worried about being perfect, so if this works it should be fine.
=> Use Uri to convert paths to platform specific fs paths

.github/workflows/cli-test.yml
`run-remote-query.ts` has logic that deals with different versions of the CLI so we should run the whole matrix of CLI tests when the file changes.
N/A:
=> Add run-remote-query.ts to CLI tests workflow triggers

extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/variant-analysis/ql-pack-details.ts, extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
Updates query pack creation and relevant MRVA commands to allow having multiple queries.
I'm still doing a bit of manual testing but worth starting to review the code changes.
N/A:
=> Add support for running multiple queries in MRVA

extensions/ql-vscode/src/codeql-cli/cli.ts
I incorrectly set the minimum version to 2.17.0, while it should be 2.16.1.
N/A:
=> Fix version used in multi-query pack create constraint

extensions/ql-vscode/src/variant-analysis/run-remote-query.ts
I think this name makes the code a bit more readable and avoids the target pack being confused with the initial information we have around the queries and the pack they might be in.
N/A:
=> Rename queryPackDir -> targetPackPath

extensions/ql-vscode/src/variant-analysis/shared/variant-analysis.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-view.ts, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisHeader.tsx
Adds a very minimal solution to showing query information for a multi-query MRVA in the results view. This is something we'll expand on in the future.
N/A:
=> Add basic multi-query support to MRVA results view header

extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/store/query-history-store.test.ts
I hit some errors in https://github.com/github/vscode-codeql/actions/runs/7695850568/job/20969605471?pr=3287 and this made me realise that `query-history-store.test.ts` is being a bit naughty when writing test data. We're writing the query history file but the data being written is the internal query history types instead of the query history DTO types.
This PR introduces a `writeRawQueryHistory` method which accepts the correct `QueryHistoryDto` type and writes it to disk. Hopefully this will help avoid people making the same mistake in the future by discouraging direct use of `writeFileSync` and writing incorrect JSON.
When I merge this branch into the `robertbrignull/move_language_pack` branch then the `no-workspace` tests pass locally (where they don't before) so that convinces me …
=> Don't accidentally mix DTO and non-DTO types in query-history-store.test.ts

extensions/ql-vscode/test/vscode-tests/no-workspace/data/variant-analysis/workspace-query-history.json, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/variant-analysis-history.test.ts
In `variant-analysis-history.test.ts` we are reading the raw query history DTO types from a file and then trying to compare them to the internal types from the query history manager. On `main` this happens to work because the types are the same, but the whole point of having these two types is that they don't have to be the same.
The "workspace-query-history.json" file is where the query history manager also loads its data from. However in the tests we never actually want it as this raw data and instead just want to make sure it's done the loading correctly.
Similar to https://github.com/github/vscode-codeql/pull/3290, I found this because of a test failure on https://github.com/github/vscode-codeql/actions/runs/7699342606/job/20983096500?pr=3287 where the internal types are changing but …
=> Don't compare internal and dto types in variant-analysis-history.test.ts

extensions/ql-vscode/src/query-history/history-item-label-provider.ts, extensions/ql-vscode/src/query-history/query-history-info.ts, extensions/ql-vscode/src/query-history/store/query-history-variant-analysis-domain-mapper.ts, extensions/ql-vscode/src/query-history/store/query-history-variant-analysis-dto-mapper.ts, extensions/ql-vscode/src/variant-analysis/export-results.ts, extensions/ql-vscode/src/variant-analysis/gh-api/gh-api-client.ts, extensions/ql-vscode/src/variant-analysis/markdown-generation.ts, extensions/ql-vscode/src/variant-analysis/shared/variant-analysis.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-mapper.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-monitor.ts, extensions/ql-vscode/test/factories/variant-analysis/shared/variant-analysis-submission.ts, extensions/ql-vscode/test/factories/variant-analysis/shared/variant-analysis.ts, extensions/ql-vscode/test/unit-tests/variant-analysis/markdown-generation.test.ts, extensions/ql-vscode/test/unit-tests/variant-analysis/variant-analysis-mapper.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
A slimmed down version of https://github.com/github/vscode-codeql/pull/3285 that doesn't modify the `query` object. The idea being to split up that change and make it easier if we do want to do it or something similar to it in the future.
My reasoning on `pack` and `language` is that they're really properties of the variant analysis rather than properties of the query. This becomes more true when you consider multiple queries, but I think it's still true now.
I'm deliberately not modifying the query history format in this PR. We could do, but since it's a lossless transformation in both directions we can just leave it. Or we could save the query history update for when we add in multiple query support and batch those changes together.
=> Move language and pack to top level of variant analysis object

extensions/ql-vscode/src/model-editor/suggestions-bqrs.ts, extensions/ql-vscode/src/model-editor/suggestions.ts, extensions/ql-vscode/test/unit-tests/model-editor/suggestions-bqrs.test.ts
This PR adds some helper functions + types for parsing suggestions into a suitable format that we can display as dropdown suggestions in the model editor. (The suggestions will come from running a CodeQL query when the model editor starts up. That logic will be added in a later PR 🔜 )
See internal linked issue for more context 🗺️ 
N/A
=> CodeQL model editor: Add functions for parsing complex access path suggestion options

extensions/ql-vscode/src/model-editor/languages/models-as-data.ts
Store the access path suggestions in the MaD model, so that we can pass those suggestions on to the webview. (I'll hook up the webview side in a later PR.)
See internal issue for more info + the bigger picture 🖼️ 
N/A - no user-facing changes
=> Add `accessPathSuggestions` to "models as data" model

extensions/ql-vscode/src/model-editor/suggestion-queries.ts, extensions/ql-vscode/src/model-editor/suggestions.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/suggestion-queries.test.ts
This PR adds functions for running "suggestion queries" (i.e. CodeQL queries that populate the autocomplete suggestions in the model editor). These queries currently live on a [branch](https://github.com/github/codeql/compare/koesie10/access-path-suggestions) from @koesie10's hackathon branch, so it's possible that the exact names and tags will change in future.
See internal issue for more details and context! ✨ 
N/A - only used in tests for now
=> Functions for running "access path suggestions" queries

extensions/ql-vscode/src/common/files.ts, extensions/ql-vscode/src/common/ql.ts, extensions/ql-vscode/src/variant-analysis/ql.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/data/variant-analysis-query-packs/workspace1/dir1/query1.ql, extensions/ql-vscode/test/data/variant-analysis-query-packs/workspace1/pack1/qlpack.yml, extensions/ql-vscode/test/data/variant-analysis-query-packs/workspace1/pack1/query1.ql, extensions/ql-vscode/test/data/variant-analysis-query-packs/workspace1/pack1/query2.ql, extensions/ql-vscode/test/data/variant-analysis-query-packs/workspace1/pack2/qlpack.yml, extensions/ql-vscode/test/data/variant-analysis-query-packs/workspace1/pack2/query1.ql, extensions/ql-vscode/test/data/variant-analysis-query-packs/workspace1/query1.ql, extensions/ql-vscode/test/data/variant-analysis-query-packs/workspace2/query1.ql, extensions/ql-vscode/test/unit-tests/common/files.test.ts, extensions/ql-vscode/test/unit-tests/variant-analysis/ql.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/packaging/packaging.test.ts
Add some logic to handle calculating QL pack roots for MRVA better.
N/A:
=> Improve handling of unknown QL pack roots for multi-query MRVAs

extensions/ql-vscode/src/model-editor/languages/ruby/access-paths.ts
This fixes parsing of access paths for Ruby methods that contain square brackets, such as `Liquid::Context#[]`. The previous implementation would incorrectly stop capturing at the `]` character, resulting in a method name of `[` for an access path of `Method[[]].ReturnValue`. This fixes it by switching to the shared access path parsing code, which correctly handles square brackets.
=> Fix Ruby method parsing for methods containing brackets

extensions/ql-vscode/src/view/common/SuggestBox/__tests__/SuggestBox.test.tsx
This might fix the flaky test by adding some (conditional) waits for elements to appear and disappear.
=> Wait for options to be shown and to be removed when pressing Tab

extensions/ql-vscode/src/model-editor/consistency-check.ts, extensions/ql-vscode/test/unit-tests/model-editor/consistency-check.test.ts
It's useful to know which models are present for a certain method to compare the CodeQL queries against. This changes the messages to be like:
```
Model editor query consistency check: Missing method Liquid::Render!#new for method that is modeled as summary
```
=> Add more information for consistency check errors

extensions/ql-vscode/src/model-editor/languages/ruby/index.ts, extensions/ql-vscode/src/model-editor/languages/ruby/suggestions.ts, extensions/ql-vscode/src/model-editor/suggestions.ts, extensions/ql-vscode/test/unit-tests/model-editor/languages/ruby/suggestions.test.ts
Following on from https://github.com/github/vscode-codeql/pull/3295, this PR adds `accessPathSuggestions` to the Ruby MaD language model, so that we can display autocomplete suggestions for Ruby in the model editor. (I'll hook up the model editor webview in a later PR 🪝 )
See internal linked issue for more context! 🔗 
N/A—still feature-flagged for internal use
=> Add access path suggestions to MaD model for Ruby

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/suggestions.ts, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx
If you have the relevant feature flag enabled, the model editor will now generate and load access path suggestions on start-up. 
I haven't yet added logic to the webview to actually _use_ those suggestions, but they will eventually be used to display autocomplete suggestions! 
See internal linked issue for more info 🔍 
N/A
=> Send access path suggestions to the model editor view

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/common/files.ts, extensions/ql-vscode/src/variant-analysis/ql.ts, extensions/ql-vscode/test/unit-tests/common/files.test.ts, extensions/ql-vscode/test/unit-tests/variant-analysis/ql.test.ts
We currently allow users to run a MRVA with a query that is not in their workspace. However, this can become problematic, specially when adding multi-query support. 
In this change we introduce a restriction where users cannot run a MRVA if the query is not in their workspace.
TODO:
=> Stop allowing running MRVA with query outside of workspace

extensions/ql-vscode/src/model-editor/shared/access-paths.ts, extensions/ql-vscode/src/view/common/SuggestBox/SuggestBox.tsx, extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/ModelInputSuggestBox.tsx, extensions/ql-vscode/src/view/model-editor/ModelOutputSuggestBox.tsx, extensions/ql-vscode/src/view/model-editor/ModelSuggestionIcon.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodsList.tsx
Reads the access path suggestions (from #3304 and previous PRs) in the webview and shows them in a "suggest box":
This is only enabled for Ruby, so the public model editor (i.e. for Java & C#) is unaffected. See internal linked issue for more details 🔗
❓  Should this have a view test? The `SuggestBox` component is already tested, so I wasn't sure if it made sense to test e.g. the `ModelInputSuggestBox` separately too.
N/A—still feature-flagged for internal use 🦞
=> CodeQL model editor: Show access path suggestions in the webview

extensions/ql-vscode/src/view/common/SuggestBox/SuggestBox.tsx
When a user clicks inside a suggest box in the model editor, we don't want that to count as (de)selecting a model editor row. I've tried to do something similar to the `stopPropagation` from [here](https://github.com/github/vscode-codeql/pull/3156/commits/c8d31278a383edc63cedec4115243197668370c6), but I got various accessibility warnings so I'm not convinced this is correct... 😬
Specifically, I just wanted to add `<div onClick={stopClickPropagation}>` but that triggered these warnings: 🤔 
> Visible, non-interactive elements with click handlers must have at least one keyboard listener.eslint [jsx-a11y/click-events-have-key-events](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/click-events-have-key-events.md)
> Avoid non-native interactive elements. If using …
=> Don't select a model editor row when you click the suggest box

extensions/ql-vscode/src/model-editor/languages/models-as-data.ts, extensions/ql-vscode/src/model-editor/languages/ruby/index.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/suggestion-queries.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/suggestion-queries.test.ts
This makes the query constraints for the access paths query configurable since these can differ between the languages. It also updates the query constraint for the Ruby query from the `access-path-suggestions` tag to `access-paths`, since that is [how the query was merged into CodeQL `main`](https://github.com/github/codeql/pull/15503/files#diff-891818fe6372315cfd5d569d6ec1dc4cdbd9614fab0306a14f8d98afeb72e2fdR6).
=> Make query constraints for access paths query configurable

extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelInputSuggestBox.tsx, extensions/ql-vscode/src/view/model-editor/ModelOutputSuggestBox.tsx, extensions/ql-vscode/src/view/model-editor/ModelTypePathSuggestBox.tsx
(Paired with @koesie10 🍐)
As suggested in https://github.com/github/vscode-codeql/pull/3305#pullrequestreview-1856442575, we can also use the `SuggestBox` for "Type" methods (specifically for path suggestions). This technically uses the `outputAccessPathSuggestions` because `ReturnValue` is a valid value. 
Second commit is another small fix from that same PR review comment!
N/A—feature-flagged for internal use only 🔐
=> CodeQL model editor: Use suggest box for type path suggestions

extensions/ql-vscode/src/compare/sarif-diff.ts, extensions/ql-vscode/test/unit-tests/compare/sarif-diff.test.ts
The SARIF comparison code was comparing the index of the artifact location, which is not useful for comparison and may differ between runs of very similar queries. This adds a function to convert a SARIF result to a canonical form, which removes the index from the artifact location.
=> Fix bug in SARIF comparison

extensions/ql-vscode/src/model-editor/model-editor-view.ts
Always show the "Generate" button in the Ruby model editor, even if the `flowGeneration` flag isn't set. This is because the "generation" functionality for Ruby is more important than in the static languages' case (for generating `Type` models).
See internal linked issue for more details! 🔍
N/A—this doesn't affect the Java/C# editor, and the Ruby one is still feature-flagged.
=> CodeQL model editor: Always show the "Generate" button for Ruby DBs

extensions/ql-vscode/src/model-editor/languages/ruby/suggestions.ts, extensions/ql-vscode/test/unit-tests/model-editor/languages/ruby/suggestions.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/suggestion-queries.test.ts
This parses the new access paths query BQRS output introduced in https://github.com/github/codeql/pull/15503. Somewhat dependent on https://github.com/github/vscode-codeql/pull/3318 for resolving the correct query.
The only difference in the output format is the fourth column (`details`), which was a string before, but has now been renamed to `node` and is an `Entity`. The same information is available in `node.label`, so that's the only change this makes (in addition to validating this new format).
To test this, you can use the `github/codeql` repository on `main` or update a submodule in another workspace to `main`.
=> Parse new access paths query BQRS output

extensions/ql-vscode/src/view/common/SuggestBox/SuggestBox.tsx
This fixes not being able to open the command palette using Cmd/Ctrl+Shift+P when in a suggest box. Documentation about the `returnFocus` prop can be found here: [`returnFocus`](https://floating-ui.com/docs/floatingfocusmanager#returnfocus).
The problem seems to be that if you press Cmd/Ctrl+Shift+P, focus moves to the `body` element. Floating UI then tries to focus the suggest box again, which removes the focus from the command palette. By adding this prop and setting it to `false` (the default is `true`), Floating UI doesn't try to regain focus. This results in a somewhat worse experience when returning from the command palette, but is still preferable to not being able to open the command palette at all.
=> Fix not being able to open command palette in suggest box

extensions/ql-vscode/src/codeql-cli/cli.ts
Fixes https://github.com/github/vscode-codeql/issues/3219.
The `packAdd` command is only used in the "Create query" flow, where it was causing some confusing/useless log messages. This is because we were incorrectly expecting JSON output.
I've tested this by running "Create query" and checking that it still works, but _doesn't_ display the following error message 
> Could not create skeleton QL pack: Parsing output of Adding and installing java pack dependency. failed: Unexpected token 'P', "Package in"... is not valid JSON
- I don't think this a changelog update it necessary? It just removes an errant log message 🤔
=> Don't try to parse output of `codeql pack add` as JSON

extensions/ql-vscode/src/view/results/AlertTable.tsx, extensions/ql-vscode/src/view/results/AlertTablePathNodeRow.tsx, extensions/ql-vscode/src/view/results/AlertTablePathRow.tsx, extensions/ql-vscode/src/view/results/AlertTableResultRow.tsx, extensions/ql-vscode/src/view/results/RawTable.tsx, extensions/ql-vscode/src/view/results/RawTableRow.tsx, extensions/ql-vscode/src/view/results/useScrollIntoView.tsx
Everywhere we create or consume a React ref, give it a proper type instead of using `Ref<any>`.
To make this work I switched to passing `null` as the initial value instead of leaving it blank. I believe this doesn't change the behaviour of the components in any way.
Leaving the initial value empty was leading to a computed type of `Thing | undefined` and that was causing problems when trying to pass it to `ref={ref}` on an element. The ref type already expects `null` to be a possible value, so using that instead of `undefined` makes everything happy.
=> Provide types for all react refs

extensions/ql-vscode/src/view/common/CodePaths/__tests__/CodePaths.spec.tsx, extensions/ql-vscode/src/view/jest.setup.ts, extensions/ql-vscode/src/view/variant-analysis/__tests__/RepoRow.spec.tsx, extensions/ql-vscode/src/view/vscode-window.ts
There are a few places where we are reading/writing extra fields to the `window` object. I believe these fields which are provided by VS Code, but sometimes in the tests we are mocking them ourselves.
Instead of using `window as any` we can define the type that we expect it to take using `declare`. This is telling the typescript compiler that a variable exists with this given name and type and it will just believe us.
Since this is just telling the compiler what type things are, it shouldn't change anything at runtime. Therefore hopefully if this compiles then it's safe 🤞🏼 
We already do this in `extensions/ql-vscode/.storybook/preview.ts`, though I couldn't see a way for us to share this code and avoid duplication. Although `preview.ts` can import code from `src` (as evidenced by …
=> Introduce VsCodeWindow to provide types for the fields we're reading/writing

extensions/ql-vscode/src/common/helpers-pure.ts, extensions/ql-vscode/src/common/vscode/selection-commands.ts, extensions/ql-vscode/src/debugger/debug-configuration.ts, extensions/ql-vscode/src/debugger/debug-protocol.ts
This aims to remove the use of `any` from `debug-configuration.ts` and `debug-protocol.ts`. The first commit does this by replacing instances of `any` with `unknown`, and this appears to work fine.
The second commit tries to improve type clarity by reusing the `NotArray` type. I'm not 100% sure but I think this is what `makeArray` is trying to achieve with `T extends Exclude<any, any[]>`. Using a named type there and reusing code instead of having two hacks for the same thing will hopefully make it easier to understand in the future.
As part of this I had to augment `NotArray` to handle other primitive types instead of just `object`, but I don't think this will have any negative effect on `selection-commands.ts`.
=> Remove use of any and make typing clearer in debugger code

extensions/ql-vscode/src/databases/README.md
Just spotted in passing that the README in the [`databases`](https://github.com/github/vscode-codeql/tree/main/extensions/ql-vscode/src/databases) folder was out of date (we've probably done some restructuring since then).
N/A—no code changes
=> Update databases README

extensions/ql-vscode/src/common/errors.ts, extensions/ql-vscode/src/common/files.ts, extensions/ql-vscode/src/local-queries/local-queries.ts
When checking if an object is a certain type, we should use `unknown` instead of `any`. The only difference this makes to the implementation is we need to add some extra `obj !== null` and `typeof obj === "object"` checks, but this makes it safer anyway since before if some of these were passed a `null` value they would throw an error when trying to access fields on it.
=> Use unknown instead of any in type functions

extensions/ql-vscode/src/common/vscode/multi-file-system-watcher.ts
This PR:
- Changes the type of `listener` from `(Uri) => any` to `(Uri) => void`, because I believe these listeners are not expected to return anything and any return value is ignored anyway.
- Removes the `thisArgs` parameter and instead uses `bind` before passing in the listener function.
=> Use bind instead of thisArg parameter in MultiFileSystemWatcher

extensions/ql-vscode/scripts/add-fields-to-scenarios.ts, extensions/ql-vscode/scripts/source-map.ts, extensions/ql-vscode/src/common/text-utils.ts, extensions/ql-vscode/src/common/vscode/multi-cancellation-token.ts, extensions/ql-vscode/src/databases/code-search-api.ts, extensions/ql-vscode/src/databases/database-fetcher.ts, extensions/ql-vscode/src/local-queries/quick-query.ts
This is all the cases I could find where we are using `any` but there exists some other type we can use instead that doesn't involve changing anything else. If everything still compiles then this should be safe to do so.
=> Use correct types where possible instead of any

extensions/ql-vscode/src/common/vscode/telemetry.ts
In this PR:
- Use string index notation to access the private field instead of casting to `any`. As far as I can tell this is the "intended way" to access private fields.
- Uses the `EnvelopeTelemetry` type since it exists, instead of `any`.
=> Avoid use of any in TelemetryListener

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/supported-languages.ts
The model editor for Ruby will now be available behind the canary setting instead of being feature flagged separately.
=> Remove `enableRuby` feature flag

extensions/ql-vscode/src/language-support/contextual/cached-operation.ts, extensions/ql-vscode/src/language-support/contextual/template-provider.ts
This PR removes the uses of `any` in `CachedOperation`. Unfortunately just replacing the use of `any` with `unknown` is not enough, but we can make it work if we add a type parameter for the function arguments.
I've made it work by having two type arguments. One for the arguments and another for the return type. Hopefully this isn't too cumbersome. I did manage to remove one set of explicit type args from `template-provider.ts` so now we only specify them once when declaring the variable and have them inferred when actually constructing the `CachedOperation` object.
I wanted to do it with one argument so you could do `CachedOperation<typeof this.getDefinitions>`, but sadly I couldn't get this to work. The issue I hit was that the async function didn't like a return type of `ReturnType<T>` …
=> Give more types to CachedOperation to avoid use of any

extensions/ql-vscode/src/model-editor/bqrs.ts, extensions/ql-vscode/src/model-editor/languages/models-as-data.ts, extensions/ql-vscode/src/model-editor/languages/ruby/access-paths.ts, extensions/ql-vscode/src/model-editor/languages/ruby/index.ts, extensions/ql-vscode/src/model-editor/languages/ruby/suggestions.ts, extensions/ql-vscode/src/model-editor/method.ts, extensions/ql-vscode/src/view/model-editor/ModelTypeDropdown.tsx, extensions/ql-vscode/test/unit-tests/model-editor/languages/ruby/generate.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/generate.test.ts
This adds the possibility for languages to define which predicates are supported for each endpoint type. It also defines a method for languages to define the endpoint type of an endpoint, overriding the default heuristics.
For Ruby, we are making the following changes to support of models:
- Source models are not supported for constructors and class definitions
- Sink models are not supported for class instances and class definitions
- Summary models are not supported for class instances and class definitions
This is based on the examples shown [here](https://redirect.github.com/github/codeql/pull/15541#issuecomment-1933632591).
=>  Add supported endpoint types to predicates

extensions/ql-vscode/src/common/jsonl-reader.ts, extensions/ql-vscode/src/common/memento.ts, extensions/ql-vscode/src/common/vscode/commands.ts, extensions/ql-vscode/src/log-insights/log-scanner.ts, extensions/ql-vscode/src/log-insights/log-summary-parser.ts
These are a few functions that currently use `any` but could instead have a type parameter.
I think each of these cases increases our type safety a little bit. I can't see any downsides, unless I've missed an edge case.
=> Add new type parameters to functions where possible

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/supported-languages.ts
This makes Python available in the model editor if you have `"codeQL.model.enablePython": true` in your (user or workspace) settings ⚙ (heavily inspired by the previous Ruby implementation from https://github.com/github/vscode-codeql/pull/3017/commits/b023431626c1cfe99d85ce194868f9a7de0d1f2a)
Note that Python won't actually work in the model editor yet, since we haven't implemented it. But we can do the necessary development work behind this flag without affecting existing users 🏴 
N/A
=> Add feature flag for Python model editor

extensions/ql-vscode/gulpfile.ts/view.ts
When you change a file not in the view directory, but which is imported by the view directory (for example `src/model-editor/languages/languages.ts`, the view would not be recompiled while these do have an impact on the compiled output. This is very surprising behavior and not what we would expect: I expect a change to any file to immediately be visible in the view as well, without having to re-run `npm run build` or `npm run watch`. This fixes it by watching for all changes in the `src` directory.
=> Recompile view when shared files change

docs/test-plan.md
Just some small things I noticed while going through the test plan.
N/A:
=> Make some clarifications in the test plan

extensions/ql-vscode/src/view/results/ResultsApp.tsx
I think these cases for `resultsInfo === null` are impossible. The only two places where `updateStateWithNewResultsInfo` is called both pass a non-null object for `resultsInfo`.
I tried adding logging/exceptions/breakpoints into these cases and trying to hit them and I couldn't. I've also tried testing this branch and everything seems to still work perfectly fine.
=> Remove cases from ResultsApp that seem to be impossible

extensions/ql-vscode/.eslintrc.js, extensions/ql-vscode/gulpfile.ts/textmate-grammar.ts, extensions/ql-vscode/gulpfile.ts/textmate.ts
This adds types to the TextMate gulp step to remove `any` from the `gulpfile.ts` directory. This is based on [a TextMate schema](https://github.com/martinring/tmlanguage/blob/478ad124a21933cd4b0b65f1ee7ee18ee1f87473/tmlanguage.json) and [the files that are being transformed](https://github.com/github/vscode-codeql/tree/9f4b82710a18753c606e9d42b12809990b102a07/extensions/ql-vscode/syntaxes). I have confirmed that the `sha256sum` of the compiled TextMate JSON files are identical in `main` and this branch, so there are no behavioral changes.
=> Add types to TextMate gulp step

extensions/ql-vscode/src/model-editor/auto-modeler.ts
I don't think we need to record the error/stack trace at all so I've removed it completely. We have metrics in the backend service around it.
N/A:
=> Tidy up auto-modeling rate limit error message

extensions/ql-vscode/test/vscode-tests/no-workspace/telemetry.test.ts
In https://github.com/github/vscode-codeql/pull/2824, we added support for the `telemetry.telemetryLevel` setting.
However, our [tests](https://github.com/github/vscode-codeql/blob/0f4a7788a70e1a9ff552cfbb1589982ce62bc29b/extensions/ql-vscode/test/vscode-tests/no-workspace/telemetry.test.ts#L76) still tested the deprecated `telemetry.enableTelemetry` setting, so I've now replaced those checks with `telemetry.telemetryLevel`. I _could_ have kept tests for the deprecated setting as well, but it didn't seem worthwhile. 
I've just done a basic replacement of `telemetry.enableTelemetry`: `true`/`false` with `telemetry.telemetryLevel`: `"all"`/`"off"`. The telemetry levels can be a bit more fine-grained than that, but I didn't want to add more complexity to the tests in this PR 😄 
(More …
=> Replace deprecated telemetry setting in the tests

extensions/ql-vscode/test/unit-tests/common/short-paths.test.ts
Follow-up to https://github.com/github/vscode-codeql/pull/3233/files#r1455336296, where we suggested adding some unit tests. 
The functionality is only relevant on Windows, so I've skipped most of the tests on ubuntu 🪟 I've added a couple of tests so far, based on examples from the [8.3 filename Wikipedia page](https://en.wikipedia.org/wiki/8.3_filename#VFAT_and_computer-generated_8.3_filenames), but I'm open to more suggestions! E.g. I couldn't work out how to test the [stuff around `inode`s and symlinks](https://github.com/github/vscode-codeql/blob/d7e9606bfab6108156276245d14ced7b3dbd868e/extensions/ql-vscode/src/common/short-paths.ts#L54-L84) 😵
N/A—only affects tests and test data
=> Add unit tests for "short-paths" functions

extensions/ql-vscode/package-lock.json
This upgrades [the `ip` package](https://github.com/indutny/node-ip) to 2.0.1, which fixes a security vulnerability (which is not exploitable in `vscode-codeql` since the `isPublic` function isn't used in our transitive dependencies).
=> Upgrade ip package

extensions/ql-vscode/src/codeql-cli/cli.ts
This streams the CLI server command stderr instead of buffering it and only printing it when the CLI command has completed. This helps users to know that something is actually happening for long-running commands. The full stderr will still be completed in an error when the command fails.
I think an easy way to test this is running a variant analysis. While the query is compiling, output should be streamed to the extension log output.
Closes https://github.com/github/vscode-codeql/issues/1459
=> Stream CLI server command stderr instead of buffering

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/auto-modeler.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeling-events.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/test/__mocks__/model-editor/modelingEventsMock.ts
This PR adds a new `sentToLLMMethods: Set<string>` field to `ModelingStore` along with all the associated events and plumbing.
Note: very open to suggestions for the naming of fields/methods. Naming is hard 😢 
The intention here is to very simply track which methods have been sent to the LLM in the current modeling session (i.e. it'll be reset if the model editor is closed and reopened). This state can be used along with the set of modeled methods to identify the set of positive and negative predictions from the LLM.
Methods are added to `sentToLLMMethods` whenever we successfully receive a response from the LLM. We add all methods from that batch, regardless of the modelings included in the LLM response. Currently there's no way to remove methods from `sentToLLMMethods` because we want …
=> Add sentToLLM to ModelingStore

extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodsList.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/LibraryRow.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/MethodRow.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodDataGrid.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodsList.spec.tsx
This adds the `processedByAutoModelMethods` state to the React view, and also passes the state down to `MethodRow` to ensure that the state is used.
=> Add `processedByAutoModelMethods` state to React view

extensions/ql-vscode/src/model-editor/auto-model.ts, extensions/ql-vscode/src/model-editor/auto-modeler.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/test/unit-tests/model-editor/auto-model.test.ts
Once a method has been processed by AutoModel once, don't try to process it again. Pretty simple now we have `processedByAutoModelMethods` available.
The only problem I've noticed with this is that it can make the UI confusing when there's nothing to model. You'll press to "model with AI" button and it'll appear to do nothing. I'm going to open a separate PR to follow this one to try to address that.
=> Don't send methods to AutoModel more than once

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/shared/view-state.ts, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/test/factories/model-editor/view-state.ts
Add "Evaluate" and "Stop evaluation" buttons on the Model Editor. They're only visible if the feature flag is enabled (`codeQL.model.evaluation`). The buttons don't do anything yet.
The "Evaluate" button is disabled if there are no custom models or if there are unsaved changes. More details on the internal issue.
N/A:
=> Add dummy model evaluation buttons to model editor

extensions/ql-vscode/src/model-editor/modeled-method.ts, extensions/ql-vscode/src/stories/method-modeling/MethodModelingInputs.stories.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingInputs.tsx, extensions/ql-vscode/src/view/method-modeling/MultipleModeledMethodsPanel.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MethodModelingInputs.spec.tsx, extensions/ql-vscode/src/view/model-editor/InputDropdown.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelInputDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelKindDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelOutputDropdown.tsx, extensions/ql-vscode/src/view/model-editor/ModelTypeDropdown.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModelKindDropdown.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModelTypeDropdown.spec.tsx
This makes negative predictions show up in italics in the model editor. It does not yet implement this for the method modeling panel, this will be a follow-up PR.
The first commit switches from `$accepted` to `$pending` since that makes more sense (a negative prediction can never be "accepted"). The second commit incorporates the processed by auto model state into the `isModelPending` method.
After saving:
=> Show auto-model negative predictions in italics

extensions/ql-vscode/src/compare/sarif-diff.ts, extensions/ql-vscode/test/unit-tests/compare/sarif-diff.test.ts
There were a few more common location `index` properties that are being used in thread flows. This fixes it by ignoring these for the canonical result. The test is based on [this PR](https://redirect.github.com/github/codeql/pull/15654) on an OpenJDK database.
=> Ignore more location indexes in SARIF comparison

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/modeled-method.ts, extensions/ql-vscode/src/view/method-modeling/MethodModeling.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx, extensions/ql-vscode/src/view/method-modeling/MultipleModeledMethodsPanel.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MethodModeling.spec.tsx, extensions/ql-vscode/src/view/method-modeling/__tests__/MultipleModeledMethodsPanel.spec.tsx
This adds showing auto-model negative predictions in italics to the method modeling panel by adding the processed by LLM state to the panel.
=> Add processed by auto model state to method modeling panel

extensions/ql-vscode/src/model-editor/languages/models-as-data.ts, extensions/ql-vscode/src/model-editor/languages/ruby/index.ts, extensions/ql-vscode/src/model-editor/languages/static/index.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/generate.test.ts
Since CodeQL v2.16.0, the Ruby model generation query [has proper query tags](https://github.com/github/codeql/commit/9b998a39b4b9b06de3c18c07529f339362a02f37), so we shouldn't be using the query path anymore.
=> Update Ruby model generation query constraints

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/model-evaluation-run.ts, extensions/ql-vscode/src/model-editor/model-evaluator.ts, extensions/ql-vscode/src/model-editor/modeling-events.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/src/model-editor/shared/model-evaluation-run-state.ts, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/test/__mocks__/model-editor/modelingEventsMock.ts
This PR introduces the `ModelEvalutionRun` domain entity and wires up model evaluation run information to the modeling store and the model editor view. Some notes:
- The `ModelEvaluationRun` interface is pretty minimal at the moment. I expect it to grow while we build more features (e.g. it might need to contain model packs).
- The model evaluation run information is not yet persisted - it's only in memory (in the `ModelingStore`).
- A new `ModelEvaluator` class has been added to contain logic around model evaluation in order to keep changes in `model-editor-view` minimal. The implementation is pretty minimal for now and will be fleshed out in the near future.
N/A:
=> Add model evaluation run to store and view

extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/model-evaluator.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/model-editor-view.test.ts
Wires up the logic to actually trigger a variant analysis for a model evaluation.
This will currently fail while building a pack because of a known dependency we have on some CodeQL CLI changes (see internal issue).
N/A:
=> Add logic to trigger model evaluation run

extensions/ql-vscode/src/model-editor/model-extension-file.schema.json, extensions/ql-vscode/src/model-editor/model-extension-file.ts, extensions/ql-vscode/src/model-editor/yaml.ts
This refactors the saving of YAML files for model extension files. Instead of directly constructing a string from the modeled methods, we will now create the structure of the YAML as a JS object. Then, we consume that object to create a YAML string. This would also allow us to e.g. dump the YAML directly, but the primary objective is to re-use this new function in a follow-up PR.
The YAML functions itself are pretty well-tested in [`yaml.test.ts`](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/test/unit-tests/model-editor/yaml.test.ts), so I'm pretty confident that this results in the same output in all instances.
=> Extract saving of model extension YAML file

extensions/ql-vscode/src/view/method-modeling/__tests__/MultipleModeledMethodsPanel.spec.tsx
Adding or removing a prop from the `MultipleModeledMethodsPanel` component required adding/removing that prop from almost 40 separate places in this file (29 tests + 9 `rerender` calls = 38). This moves all of this to a simple `render` function that doesn't require any props, so now you only need to change it in 1 place (`baseProps`).
=> Reduce repetition in `MultipleModeledMethodsPanel.spec.tsx`

extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-data-provider.ts, extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-panel.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/src/model-editor/shared/auto-model-candidates.ts, extensions/ql-vscode/src/model-editor/shared/sorting.ts, extensions/ql-vscode/src/view/model-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/methods-usage/methods-usage-data-provider.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/methods-usage/methods-usage-panel.test.ts
This PR aims to make sorting of methods easier and prevent them from changing sort order and flying around when you make manual changes. Sorting of methods is moved to the modeling store so it happens in one place only, and then it is the job of each view to preserve the ordering of methods it is given.
This gives us a lot more control over what actions trigger a change in method sorting. As of this PR the only actions that should cause methods to change order are:
- the initial loading of methods
- saving modeled methods
- new AI predictions
It also helps reduce some of the code bloat caused by https://github.com/github/vscode-codeql/pull/3382 because we no longer need to pass as much information to all the different views.
=> Move all sorting to the modeling store, and then all views preserve the sorting

extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
Tiny change to rename a variable so that it makes a bit more sense. 
N/A:
=> Rename variable in variant analysis manager

extensions/ql-vscode/src/model-editor/model-evaluator.ts, extensions/ql-vscode/src/variant-analysis/export-results.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-content-provider.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-view-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-view.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-manager.test.ts
A quick PR to rename the `getVariantAnalysis()` function of the `VariantAnalysisManager` to `tryGetVariantAnalysis()` to better reflect its behaviour. In a future PR I'm planning to introduce a `getVariantAnalysis()` that throws an error if the analysis doesn't exist.
N/A:
=> Rename getVariantAnalysis to tryGetVariantAnalysis

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/query-history/query-status.ts, extensions/ql-vscode/src/query-history/store/query-history-variant-analysis-domain-mapper.ts, extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisActions.stories.tsx, extensions/ql-vscode/src/variant-analysis/shared/variant-analysis.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-mapper.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-monitor.ts, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisActions.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisStats.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisStatusStats.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisActions.spec.tsx, extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisStats.spec.tsx, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-manager.test.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-monitor.test.ts
Introduces a new 'canceling' status for variant analyses which is used to show whether we're in the middle of stoping the analysis.
=> Add support for 'canceling' status for variant analysis

extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-monitor.test.ts
Quick PR to make some small renames of variables in the variant analysis monitor tests. See individual commits for easier diffing.
N/A:
=> Minor renames in variant analysis monitor tests

extensions/ql-vscode/src/model-editor/generate.ts, extensions/ql-vscode/src/model-editor/languages/models-as-data.ts, extensions/ql-vscode/src/model-editor/languages/ruby/generate.ts, extensions/ql-vscode/src/model-editor/languages/ruby/index.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeled-method-fs.ts, extensions/ql-vscode/src/model-editor/yaml.ts, extensions/ql-vscode/test/unit-tests/model-editor/languages/ruby/generate.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/model-editor/modeled-method-fs.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/generate.test.ts
This will generate a separate file `models/ruby.model.generated.yml` when running the model editor for Ruby and type models are hidden (the default). This file is ignored by the model editor, but stores all type models generated by the query. This is part of hiding type models by default.
=> Generate separate file for generated type models in Ruby by default

extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/query-testing/test-manager.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-testing/test-adapter.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-testing/test-runner-helpers.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-testing/test-runner.test.ts
This fixes tests with warnings that would error out instead of showing the diff. It now results in:
The warning being shown in the actual output is expected and is [part of normal testing of CodeQL](https://github.com/search?q=repo%3Agithub%2Fcodeql+%22WARNING%3A+%22+path%3A*.expected&type=code). I don't think that's something that can be changed.
Closes https://github.com/github/vscode-codeql/issues/3386
=> Show test results for tests with warnings

extensions/ql-vscode/src/query-history/query-history-manager.ts
Multi-query variant analyses aren't currently tracked in the query history so the query history manager would log warnings when it would receive updates for them. This change stops logging warnings for those. 
N/A:
=> Skip logging warning for multi-query variant analyses

extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditorProgressRing.tsx, extensions/ql-vscode/src/view/model-editor/ModelEvaluation.tsx
No user-visible changes. This PR slightly refactors the ModelEditor component into smaller components, so that we can more easily make changes later! 
N/A
=> Extract "ModelEvaluation" component

extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/ModelEvaluation.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModelEvaluation.spec.tsx
Adds an "Evaluation Run" link to the model editor, in the case that there is an in-progress or completed evaluation run. This will eventually open a new "model alerts" webview (to be added in future PRs) 
N/A, this is feature-flagged for internal use
=> Add link to open "Evaluation Run" from the model editor

docs/test-plan.md
Replaces the query used in the test plan from `@kind treemap` to `@kind table`. The intention is to test a generic non-problem query and not specifically `treemap` which is a kind that is rarely used and we don't necessarily have full support for. It's more important to test a `table` query since those are more likely to be run by users.
=> Avoid using a @treemap query in testplan

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/common/vscode/webview-html.ts, extensions/ql-vscode/src/model-editor/model-alerts/model-alerts-view.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/model-evaluator.ts, extensions/ql-vscode/src/view/model-alerts/ModelAlerts.tsx, extensions/ql-vscode/src/view/model-alerts/index.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/webview.tsx, extensions/ql-vscode/test/vscode-tests/activated-extension/model-editor/model-evaluator.test.ts
This PR adds a (currently empty) "Model alerts" webview, which can be opened by clicking "Evaluation run" from the model editor. In future, this will be populated with evaluation results, but for now it looks like this 😂 
https://github.com/github/vscode-codeql/assets/42641846/ffee2626-d700-461e-9922-2fd6f919afc5
See internal linked issue for more context and future work! 
N/A (feature-flagged for internal use)
=> Add a new "model alerts" webview (for showing results from model evaluation)

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-panel.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/methods-usage/methods-usage-panel.ts, extensions/ql-vscode/src/model-editor/model-editor-module.ts, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx, extensions/ql-vscode/test/__mocks__/model-editor/modelingEventsMock.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/methods-usage/methods-usage-panel.test.ts
This PR fixes the method modeling panel getting stuck showing "start modeling" if you open the model editor before you open the QL sidebar panel.
The problem was that when the webview loaded we weren't setting the `language` field correctly in the webview. There needs to be a call to `setViewState()` after determining the language.
I recommend reviewing commit by commit.
The actual fix is made in https://github.com/github/vscode-codeql/commit/d4413424c19121b2bd5b81539d8619f9480cc814 which is the third commit. The two commits before that are refactoring methods so we can reuse code. For this fix I've not worried about being inefficient with sending webview messages. For example since `setDatabaseItem` calls `setViewState` we don't have to call it before in this case, but I felt the …
=> Refactor events to fix the method modeling panel getting stuck showing "start modeling"

extensions/ql-vscode/test/factories/query-history/local-query-history-item.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/store/query-history-store.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-results.test.ts
In a few cases in the tests we need either a `CancellationToken` or `CancellationTokenSource` and we're building a minimal object and then forcibly casting it to the right type. Using `CancellationTokenSource` is not hard so I see no reason we shouldn't use the real class in all of these cases.
=> Use CancellationTokenSource instead of casting dummy objects

extensions/ql-vscode/src/model-editor/modeling-store.ts
I only just noticed that `hasStateForActiveDb` is now completely unused after I removed the only usage of it in https://github.com/github/vscode-codeql/pull/3439
=> Delete hasStateForActiveDb as it is unused

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases/database-fetcher.ts, extensions/ql-vscode/src/databases/local-databases-ui.ts, extensions/ql-vscode/src/local-queries/local-queries.ts, extensions/ql-vscode/src/local-queries/skeleton-query-wizard.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/local-queries/skeleton-query-wizard.test.ts
This fixes a potential bug I spotted where we might unexpectedly prompt a user for credentials to download a CodeQL database.
The code for downloading databases from GitHub is in `promptImportGithubDatabase` and `downloadGitHubDatabase` and both of those took an optional `Credentials` parameter. It is then up to the caller to decide whether to use credentials or not. In this PR we push the decision further down so we only decide in `downloadGitHubDatabase` and therefore use the same logic for all cases.
The current logic around using credentials is:
- In `handleChooseDatabaseGithub` in `local-databases-ui.ts` (called when manually importing a database by command palette or UI), we were using credentials only when the canary flag was set.
- In `createSkeletonQuery` in `local-queries.ts`, …
=> Push decision to use credentials or not down to where the creds are used

extensions/ql-vscode/src/view/model-editor/ModelAlertsIndicator.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModelAlertsIndicator.spec.tsx
Follow-up to https://github.com/github/vscode-codeql/pull/3441 to add a test! There's not much logic to test at the moment, but there will be in future 🔮 
N/A, no user-facing changes
=> Add view test for ModelAlertsIndicator

extensions/ql-vscode/src/common/files.ts, extensions/ql-vscode/src/databases/database-fetcher.ts, extensions/ql-vscode/test/unit-tests/common/files.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/databases/database-fetcher.test.ts
The `findDirWithFile` function is pretty general and I'd argue belongs in `files.ts` more than it does in `database-fetcher.ts`. This refactoring is not a huge win in itself but it helps move towards a few goals:
- make `database-fetcher.ts` smaller and more focussed, and make a future refactoring I want to do easier
- moves the tests of this function out of `vscode-tests/no-workspace` and into `unit-test`
- helps us remove the `test/vscode-tests/no-workspace/databases/database-fetcher.test.ts` file entirely so that the only remaining tests of `database-fetcher.ts` are `test/vscode-tests/cli-integration/databases/database-fetcher.test.ts`
=> Move findDirWithFile to files.ts

extensions/ql-vscode/src/common/vscode/abstract-webview-view-provider.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/test/__mocks__/model-editor/modelingEventsMock.ts, extensions/ql-vscode/test/__mocks__/model-editor/modelingStoreMock.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/method-modeling/method-modeling-view-provider.test.ts
This PR is trying to add tests that would have caught the bug fixed in https://github.com/github/vscode-codeql/pull/3439
To do this we need to initialize a `MethodModelingViewProvider` and send it a "viewLoaded" message. Then we can test that it does the right thing in various `ModelingStore` states. I believe the only thing the test can verify is what messages are sent to the webview.
I've focussed on what it does when the view is first loaded and haven't tried to add tests for all the other behaviours of `MethodModelingViewProvider`. We could add more tests later if we think that would be useful.
=> Add tests of MethodModelingViewProvider.viewLoaded

extensions/ql-vscode/src/databases/database-fetcher.ts, extensions/ql-vscode/src/databases/local-databases/database-item-impl.ts, extensions/ql-vscode/src/databases/local-databases/database-item.ts, extensions/ql-vscode/src/databases/local-databases/database-manager.ts, extensions/ql-vscode/src/databases/local-databases/database-options.ts, extensions/ql-vscode/test/factories/databases/databases.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-queries/local-databases.test.ts
When downloading a database from GitHub, the folder structure looks like this within the `${context.storageUri}/cpp` directory:
When removing this database, we were only deleting the shown `cpp` directory, and not the top-level `cpp` directory because we were deleting the directory that contained the database, rather than the directory that was created during the download.
This fixes it by storing the directory that we create during download on the database item so we can remove that directory when removing the database.
=> Fix incomplete removal of databases

extensions/ql-vscode/src/common/query-metadata.ts, extensions/ql-vscode/src/model-editor/extension-pack-metadata.schema.json, extensions/ql-vscode/src/packaging/qlpack-file.schema.json, extensions/ql-vscode/src/packaging/suite-instruction.ts, extensions/ql-vscode/src/variant-analysis/code-scanning-pack.ts
When resolving the Code Scanning pack, we were manually filtering out non-problem queries by calling `codeql resolve metadata` on every resolved query. This switches it to using a custom suite file (`.qls`) which can do the same but without requiring many calls to `codeql resolve metadata`. There should be no changes in behavior.
=> Use suite file instead of manually filtering queries

extensions/ql-vscode/src/view/common/DataGrid.tsx, extensions/ql-vscode/src/view/model-editor/LibraryRow.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelAlertsIndicator.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodDataGrid.tsx, extensions/ql-vscode/src/view/model-editor/ModeledMethodsList.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/LibraryRow.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/MethodRow.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModelAlertsIndicator.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodDataGrid.spec.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModeledMethodsList.spec.tsx
Adds "alert indicators" in the model editor to show how many results a certain model has generated: 
- We only show these indicators when there's an evaluation run available
- Eventually these indicators will link to a separate model alerts view with more details
- We don't currently have any way of knowing which models are responsible for which alerts (see "alert provenance" work), so we just show a random number for now 🙃 
N/A, this is feature-flagged for internal use/testing 🎏
=> Add "model alerts indicator" component

extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelAlertsIndicator.tsx
Changes a few buttons in the model editor to use the [`VSCodeBadge`](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/badge/README.md) component from the webview UI toolkit. Follow-up from https://github.com/github/vscode-codeql/pull/3441#discussion_r1521510447.
Before: 
After: 
N/A: the usages button has just changed a tiny amount, and the model alerts button is feature-flagged
=> Use VSCodeBadge instead of custom styled component

extensions/ql-vscode/src/model-editor/model-alerts/model-alerts-view.ts, extensions/ql-vscode/src/model-editor/model-evaluation-run.ts, extensions/ql-vscode/src/model-editor/model-evaluator.ts, extensions/ql-vscode/src/model-editor/modeling-events.ts, extensions/ql-vscode/src/model-editor/modeling-store.ts, extensions/ql-vscode/src/view/model-editor/ModelEvaluation.tsx, extensions/ql-vscode/src/view/model-editor/__tests__/ModelEvaluation.spec.tsx
There should only ever be one model alerts view open, so this PR adds some logic to check that we don't already have one! 👀 
The second commit is a related tweak that makes sure we can't open the model alerts view until the variant analysis has kicked off. (This is similar to the MRVA results view, which only opens once the actual workflow run has been triggered, since there's nothing to show otherwise.)
N/A—feature-flagged for internal use/testing 🏴
=> Only allow one open model alerts view

extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/codeql-cli/query-language.ts, extensions/ql-vscode/src/model-editor/model-evaluator.ts, extensions/ql-vscode/src/variant-analysis/code-scanning-pack.ts, extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/jest.config.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/code-scanning-pack.test.ts
This makes the "Run variant analysis against published pack" command cancellable by starting a separate CLI process for downloading packs and bundling the query pack since these are both long-running commands.
Unfortunately, I wasn't able to fix an issue where the tests would timeout on ubuntu-latest because Jest didn't exit. Therefore, I've added the `forceExit` flag to the CLI integration tests.
=> Make the "Run variant analysis against published pack" command cancellable

extensions/ql-vscode/src/common/model-pack-details.ts, extensions/ql-vscode/src/stories/model-alerts/ModelPacks.stories.tsx, extensions/ql-vscode/src/view/model-alerts/ModelPacks.tsx
Adds a new `ModelPacks` React component to show the model packs used during an evaluation run. This is not used anywhere yet - it will be wired up in a follow up PR.
N/A:
=> Add new ModelPacks component

.github/codeql/queries/ProgressBar.qll, .github/codeql/queries/progress-not-cancellable.ql, .github/codeql/queries/token-not-used.ql
This PR adds a CodeQL query to catch cases where we use `withProgress` with `cancellable: true` but then don't actually use the token argument. This will lead to cases where the user clicks the "cancel" button and the progress bar goes away but the background process continues and the user cannot control it.
This was inspired by https://github.com/github/vscode-codeql/pull/3454#discussion_r1523033368 which was only caught because we manually spotted it.
This should hopefully also detect one other existing alert at https://github.com/github/vscode-codeql/blob/3005dacf4ed480aa76e541b7d3697f5a34571faf/extensions/ql-vscode/src/databases/local-databases-ui.ts#L950.
=> Create token-not-used.ql to catch cases where we aren't using the progress bar token correctly

extensions/ql-vscode/src/variant-analysis/run-remote-query.ts, extensions/ql-vscode/src/variant-analysis/shared/variant-analysis.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-mapper.ts, extensions/ql-vscode/test/unit-tests/variant-analysis/variant-analysis-mapper.test.ts
Adds `modelPacks` to variant analysis entities and flows that through from when the packs are discovered to when the entity is created.
The `modelPacks` property is not persisted yet so it's not mapped over when transforming to query history items. This is intentional - we will change that once we're more confident with the shape of the data. See internal linked issue for details.
Note that this is not used yet, it will be wired up in a follow up PR.
N/A:
=> Add model packs to variant analyses

.github/dependabot.yml
Some npm dependencies should be updated together, so this creates some groups for these dependencies. This will also reduce the number of merge conflicts between Dependabot updates.
=> Group some npm dependency updates

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-alerts/model-alerts-view.ts, extensions/ql-vscode/src/model-editor/model-evaluator.ts, extensions/ql-vscode/src/view/model-alerts/ModelAlerts.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlertsHeader.tsx, extensions/ql-vscode/src/view/vscode-api.ts
Wires up showing model packs in the Model Alerts view.
To show the model packs we pass in the variant analysis to the view. We currently only send the variant analysis during creation of the view and do not update it at all as live results come in. That will be handled separately. 
N/A:
=> Show model packs in Model Alerts view

extensions/ql-vscode/src/common/vscode/abstract-webview.ts, extensions/ql-vscode/src/common/vscode/commands.ts, extensions/ql-vscode/src/common/vscode/error-handling.ts, extensions/ql-vscode/src/extension.ts
Currently a `UserCancellationException` is thrown with `silent: true` and there is no `catch` statement around the operation that triggered the exception, the `UserCancellationException` is unhandled and the global error handler is hit.
This PR adds a check for silent `UserCancellationException` in the global error handler. 
Add error handling around webview message processing and use the same logic as we do for commands. We use the same logic by extracting it into a reusable function.
N/A:
=> Added error handling on webview message processing

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-alerts/model-alerts-view.ts, extensions/ql-vscode/src/model-editor/model-evaluator.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/view/model-alerts/ModelAlerts.tsx
Updates model evaluation to listen to updates to pieces of state that relate to variant analyses (variant analysis, repo states, repo results) and propagate those updates to the Model Alerts view.
To achieve this, I've updated the `VariantAnalysisManager` to publish events for changes to the repo states and repo results (it was already publishing events for variant analyses updates).
The view doesn't use the repo states and repo results properly yet - it just prints stuff out as JSON. 
N/A:
=> Wire up variant analysis updates to Model Alerts view

extensions/ql-vscode/src/view/model-editor/ModelEvaluation.tsx
The evaluation run link was not aligned very well so this makes a small update to fix that
Before
After
N/A
=> Center align model evaluation run link

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-alerts/model-alerts-view.ts, extensions/ql-vscode/src/model-editor/model-evaluator.ts, extensions/ql-vscode/src/stories/model-alerts/ModelAlerts.stories.tsx, extensions/ql-vscode/src/stories/model-alerts/ModelAlertsHeader.stories.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlerts.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlertsActions.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlertsHeader.tsx, extensions/ql-vscode/src/view/model-alerts/ModelPacks.tsx, extensions/ql-vscode/test/factories/variant-analysis/shared/variant-analysis.ts
Added button and logic to stop an evaluation run from the Model Alerts view. To achieve this I've:
- Introduced a new `ModelAlertsActions` component and added a button there
- Updated the `ModelAlertsHeader` to have a `ModelAlertsActions` and render things appropriately
- Added a new `stopEvaluationRun` message that the the ModelAlerts view can send
- Wired up the `stopEvaluationRun` message handling to trigger an event to stop the run and updated the `ModelEvaluator` to listen and act on that event
Note that I've gone with Stop -> Stopping to match what we do in the Variant Analysis results view but that maybe look a bit odd because in the ModelEditor the run already presents as stopped. To me it makes sense but I'm happy to discuss/change, and that can be now or later on.
N/A:
=> Add 'stop evaluation' action to Model Alerts view

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/local-queries/local-queries.ts
Update error handling of running a local query to check if cancellation was requested by the user, and avoid showing a notification when that happens.
=> Don't show notification after local query cancellation

extensions/ql-vscode/src/databases/database-fetcher.ts, extensions/ql-vscode/src/databases/local-databases-ui.ts, extensions/ql-vscode/src/databases/local-databases/database-manager.ts
When importing from a directory, check for testproj
Use the testproj style import when using the folder icon to import a
database. This means that if the database directory ends with `testproj`
copy the database into workspace storage and make it available for
re-importing when the origin database changes.
Safely check for out of date databases
When checking to re-import test databases, if the target database is
missing or otherwise unavailable, avoid the check and just continue.
This avoids a bug where a user would delete a test database and there
would be an error when trying to run a query.
Ensure database sources are zipped on re-import
(Commit-by-commit review is recommended).
=> Three minor improvements to `testproj` import

extensions/ql-vscode/src/stories/model-alerts/ModelAlerts.stories.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlerts.tsx
The `ModelAlerts` view won't return any HTML if the `variantAnalysis` isn't set, so I've updated the component to be able to receive that, along with repo states and repo results, through props. We follow this pattern elsewhere.
N/A:
=> Fix ModelAlerts view stories

extensions/ql-vscode/src/view/model-editor/MethodName.tsx
I need to be able to send specific props rather than a `Method` object to the `MethodName` component so I've changed it. 
N/A:
=> Update MethodName component to receive specific props

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-alerts/model-alerts-view.ts, extensions/ql-vscode/src/stories/model-alerts/ModelAlerts.stories.tsx, extensions/ql-vscode/src/stories/model-alerts/ModelAlertsHeader.stories.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlerts.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlertsHeader.tsx
Add a stats row to the model alerts view
N/A
=> Add model alerts stats to the view

.github/codeql/queries/ProgressBar.qll, .github/codeql/queries/progress-not-cancellable.ql, .github/codeql/queries/token-not-used.ql
We can simplify this query because it was written before https://github.com/github/vscode-codeql/pull/3466
Hopefully this will still work and cause zero change in alerts.
=> Simplify query now we've deleted withInheritedProgress

extensions/ql-vscode/src/stories/variant-analysis/AnalysisAlertResult.stories.tsx, extensions/ql-vscode/test/factories/variant-analysis/shared/analysis-alert.ts
This is so it can be re-used in other stories/tests.
N/A:
=> Move AnalysisAlert mock creation to a factory module

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-alerts/model-alerts-view.ts, extensions/ql-vscode/src/model-editor/model-evaluator.ts, extensions/ql-vscode/src/view/model-alerts/ModelAlerts.tsx
It looks like we won't need this state after all, so we should remove it.
N/A:
=> Remove repoStates state tracking from model evaluation

extensions/ql-vscode/src/model-editor/model-alerts/model-alerts.ts, extensions/ql-vscode/src/stories/model-alerts/ModelAlertsResults.stories.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlertsResults.tsx, extensions/ql-vscode/src/view/model-alerts/ModelDetails.tsx
The components aren't used yet - they will be wired up in a separate PR.
N/A:
=> Add React components for showing model alert results

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
Version 7 of `@typescript-eslint` is not compatible with Node 18.17 and requires Node 18.18+ or Node 20. The latest minor/patch version of v7 started enforcing this requirement, but this was already part of the breaking changes for v7.
=> Downgrade `@typescript-eslint/eslint-plugin` to v6

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-alerts/alert-processor.ts, extensions/ql-vscode/src/model-editor/model-alerts/model-alerts-view.ts, extensions/ql-vscode/src/model-editor/model-evaluator.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-results-manager.ts, extensions/ql-vscode/src/view/model-alerts/ModelAlerts.tsx
Wires up the model evaluator to trigger loading of variant analysis repository results, process them and update the model alerts view.
In the absence of alert provenance information, we fake process the analysis results for now, and return mock results.
N/A:
=> Wire up processing model evaluation run results and showing alerts

extensions/ql-vscode/src/model-editor/languages/python/access-paths.ts
This fixes the detection of Python instance methods for methods without parameters (other than `self`).
=> Fix detection of Python instance methods

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-alerts/model-alerts-view.ts, extensions/ql-vscode/src/view/model-alerts/ModelAlerts.tsx
In https://github.com/github/vscode-codeql/pull/3503 I introduced a new message when I could have just re-used the existing message 🤦 this fixes that. 
The setRepoResults message can be re-used because its handling replaces any existing repo results. 
I still find the names of messages a bit confusing so that can be tidied up in a separate PR.
N/A:
=> Re-use setRepoResults instead of having a setReposResult message

extensions/ql-vscode/src/model-editor/model-alerts/alert-processor.ts, extensions/ql-vscode/src/model-editor/model-alerts/model-alerts.ts, extensions/ql-vscode/src/stories/model-alerts/ModelAlerts.stories.tsx, extensions/ql-vscode/src/stories/model-alerts/ModelAlertsResults.stories.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlerts.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlertsResults.tsx
In order to implement some of the filtering we want in the `ModelAlerts` view, we need to keep track of which repo an alert has come from. This PR updates the `ModelAlerts` entity to hold repository information and the `alerts-processor` to propagate it.
I'm not convinced about the shape of the `ModelAlerts` entity yet - I think things will be clearer once we have alert provenance information.
N/A:
=> Update model alert processing to track repo results

extensions/ql-vscode/src/model-editor/model-alerts/alert-processor.ts, extensions/ql-vscode/src/model-editor/shared/model-alerts-filter-sort.ts, extensions/ql-vscode/src/stories/model-alerts/ModelAlerts.stories.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlerts.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlertsSearchSortRow.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlertsSort.tsx, extensions/ql-vscode/test/unit-tests/model-editor/shared/model-alerts-filter-sort.test.ts
Add filtering on model signature or repository, and sorting based on number of results and alphabetically. 
The implementation generally follows similar patterns to what we have in the variant analysis results view.
Apologies for the churn in the `alert-processor.ts` and `ModelAlerts.stories.tsx` - this is mainly so we can have enough test data to try things out in Storybook since we don't have proper alert provenance information yet.
N/A:
=> Added filtering and sorting in the model alerts view

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/model-editor/languages/csharp/index.ts, extensions/ql-vscode/src/model-editor/languages/java/index.ts, extensions/ql-vscode/src/model-editor/languages/languages.ts, extensions/ql-vscode/src/model-editor/languages/shared.ts, extensions/ql-vscode/src/model-editor/languages/static/index.ts
This updates the supported sink and source kinds that are shown in the model editor to [the latest CodeQL valid source/sink kinds](https://github.com/github/codeql/blob/0c5ea975a4c4dc5c439b908c006e440cb9bdf926/shared/mad/codeql/mad/ModelValidation.qll). It splits out Java and C# since these will now have different source/sink kinds.
=> Update supported sink and source kinds in the model editor

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/method-modeling/method-modeling-view-provider.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeling-events.ts
The model alerts view will have a button that lets you open the method in the model editor (to be added in a follow-up PR):
I want to re-use the existing "reveal in model editor" event (used by the method modeling side bar), but that uses the `Method` type (instead of `ModeledMethod`, like in the model alerts view).
Both of those extend the `MethodSignature` type, so I think it makes sense to use that as a suitable "wider" type to accommodate both. I've tested that the button in the method modeling side bar still works as normal 🧪 🎉 
N/A, no user visible impact
=> Use wider type for "reveal in model editor"

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-alerts/model-alerts-view.ts, extensions/ql-vscode/src/view/model-alerts/ModelAlertsResults.tsx
Adds a "View" link in the model alerts view. This will focus on the modeled method in the model editor (same as the "Review in editor" button in the method modeling side bar): 
https://github.com/github/vscode-codeql/assets/42641846/35ac7ebe-fdc2-4829-be4d-fece84183a42
(⚠️ Note: The model alerts view just uses mock data, so there isn't a corresponding method in the model editor to focus on yet! I don't know how to mock this more usefully, so we might need to wait for alert provenance?) 
N/A, feature-flagged for internal use/testing
=> Add "view" button in model alerts view

extensions/ql-vscode/src/view/model-alerts/ModelAlertsResults.tsx
Minor follow-up to #3514. Clicking the "View" link shouldn't also expand/collapse the row 🙃 
N/A: still feature-flagged
=> Fix click propagation for "View" link in model alerts view

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/model-evaluator.ts, extensions/ql-vscode/src/model-editor/modeling-events.ts, extensions/ql-vscode/src/view/model-editor/ModelAlertsIndicator.tsx
In the model editor, you can click the "model alerts indicator" which will (eventually) open the corresponding alerts in the model alerts view.
For now, this PR just adds some types etc to fire a "reveal in model alerts view" event when you click this button. In the next PR I'll add the logic for the model alerts view to listen for those events and do the relevant thing.
N/A, feature-flagged for internal use/testing
=> Fire an event when clicking the "model alerts indicator" button

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/model-editor/model-alerts/model-alerts-view.ts, extensions/ql-vscode/src/view/model-alerts/ModelAlerts.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlertsResults.tsx, extensions/ql-vscode/src/view/model-editor/ModelAlertsIndicator.tsx
Follow-up to https://github.com/github/vscode-codeql/pull/3516. When you click a "model alerts indicator" (in the model editor), it will open the corresponding model in the model alerts view: 
https://github.com/github/vscode-codeql/assets/42641846/e3532897-63b3-4d13-9980-936b0619a56b
⚠️ Note: The model alerts view uses mock data at the moment, so we just open the view and don't auto-scroll to a specific model yet. This behaviour is something to test properly once we have alert provenance!
N/A, feature-flagged for internal use/testing
=> Link from alerts indicator to model alerts view

extensions/ql-vscode/test/unit-tests/model-editor/modeled-method.test.ts
Follow up to https://github.com/github/vscode-codeql/pull/3518 to add some tests! 🧪 
I'm not really sure what else to test 🤔 Suggestions welcome ❤️ 
N/A, no user impact
=> Add unit test for `createModeledMethodKey`

extensions/ql-vscode/src/common/disposable-object.ts, extensions/ql-vscode/src/common/logging/tee-logger.ts, extensions/ql-vscode/src/language-support/contextual/query-resolver.ts, extensions/ql-vscode/src/local-queries/local-query-run.ts, extensions/ql-vscode/src/local-queries/run-query.ts, extensions/ql-vscode/test/common/logging/output-channel-logger.test.ts
This switches the `TeeLogger` from using the `appendFile` function to manually opening and closing a file handle and calling `appendFile` on the file handle. This results in a more efficient implementation as the file handle is only opened once and closed once, instead of being opened and closed for every log message. This should result in less "too many open files" errors.
=> Use file handle in TeeLogger

extensions/ql-vscode/src/common/config-template.ts, extensions/ql-vscode/test/unit-tests/common/config-template.test.ts
This adds a helper for substituting config variables, such as the following:
- `.github/codeql/extensions/${name}-${language}` becomes `.github/codeql/extensions/vscode-codeql-java`
- `${owner}/${name}-${language}` becomes `github/vscode-codeql-java`
- `${workspaceFolder}${pathSeparator}.github/workflows/codeql-analysis.yml` becomes `/home/your-username/your-project/.github/workflows/codeql-analysis.yml`
This is based on [the implementation in VS Code](https://github.com/microsoft/vscode/blob/edfd5b8ba54d50f3f5c2ebee877af088803def88/src/vs/base/common/labels.ts#L316C1-L400) that is used for [the `window.title` setting](https://code.visualstudio.com/docs/editor/variables-reference#_is-variable-substitution-supported-in-user-and-workspace-settings). Some of the unit tests are also based on …
=> Add helper for substituting config variables

extensions/ql-vscode/src/model-editor/languages/python/index.ts
This improves support for Python arguments by doing two things:
- When there is a function definition like:
```python
def foo(x, y)
return x + y
```
It is possible to call the function as normal `foo(1, 2)`, which works with `Argument[0]` and `Argument[1]`. However, it's also possible to call this like `foo(1, y = 2)` or `foo(x = 1, y = 2)`, which doesn't work for those same values (since the function definition isn't always available). Therefore, this changes the generation of these arguments to `Argument[0,x:]` and `Argument[1,y:]`.
- When there is a function definition like:
```python
def foo(x, /, y)
return x + y
```
It is not possible to call this like `foo(x = 5, y = 2)`, only as `foo(5, 2)` or `foo(5, y = 2)`. So, unlike above, we should ensure that these arguments are not modeled …
=> Improve support for Python arguments

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/model-editor/extension-pack-picker.ts, extensions/ql-vscode/src/model-editor/extensions-workspace-folder.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/extension-pack-picker.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/extensions-workspace-folder.test.ts
This adds the `codeQL.model.packLocation` setting, which allows users to specify the location of the CodeQL extension pack. This setting replaces the `codeQL.model.extensionsDirectory` setting, which has been removed.
The pack location supports variable substitutions and supports both absolute and relative paths. The default value is
`.github/codeql/extensions/${name}-${language}` which matches the previous defaults.
My plan is to add the CHANGELOG entry when all three settings have been added, rather than for each one individually.
=> Add `codeQL.model.packLocation` setting

extensions/ql-vscode/src/model-editor/languages/python/index.ts, extensions/ql-vscode/test/unit-tests/model-editor/languages/python/index.test.ts
This adds unit tests for Python argument options and fixes some bugs that I found while writing the unit tests. Suggested in https://github.com/github/vscode-codeql/pull/3540#pullrequestreview-1986021975
=> Add unit tests for Python argument options

extensions/ql-vscode/package.json, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/model-editor/extension-pack-name.ts, extensions/ql-vscode/src/model-editor/extension-pack-picker.ts, extensions/ql-vscode/test/unit-tests/model-editor/extension-pack-name.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/extension-pack-picker.test.ts
This adds the `codeQL.model.packName` setting, which allows users to specify the name of the CodeQL model pack. Like the `codeQL.model.packLocation` setting added in https://github.com/github/vscode-codeql/pull/3539, this supports variable substitutions. After the variable substitution has been performed, we'll try to "sanitize" the name to make it valid. The default value is `${owner}/${name}-${language}` which matches the previous behavior.
My plan is to add the CHANGELOG entry when all three settings have been added, rather than for each one individually.
=> Add `codeQL.model.packName` setting

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts
This feature is now enabled by default for supported languages (which currently only includes Ruby). It also makes the experience for unsupported languages better by not calling `withProgress` for unsupported languages (which would almost immediately exit out of `withProgress`).
No changelog entry is necessary because Ruby is currently only enabled in canary mode.
=> Remove `codeQL.model.enableAccessPathSuggestions` config

extensions/ql-vscode/src/model-editor/languages/models-as-data.ts, extensions/ql-vscode/src/model-editor/languages/ruby/index.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts
This adds a new "mode" to the auto-model generation that doesn't save the modeled methods in a separate file, but instead shows them to the user in the model editor UI, like the manual model generation. It allows overriding of how the models are parsed which is used to ensure only type models are parsed for Ruby.
The new mode isn't currently being used anywhere yet, but this will happen in a follow-up PR.
=> Add auto-model generation mode without separate file

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/model-editor/languages/models-as-data.ts, extensions/ql-vscode/src/model-editor/languages/ruby/generate.ts, extensions/ql-vscode/src/model-editor/languages/ruby/index.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/model-editor/modeled-method-fs.ts, extensions/ql-vscode/src/view/model-editor/__tests__/ModelTypeDropdown.spec.tsx, extensions/ql-vscode/test/unit-tests/model-editor/languages/ruby/generate.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/model-editor/modeled-method-fs.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/generate.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/model-editor/method-modeling/method-modeling-view-provider.test.ts
This removes the `codeQL.model.showTypeModels` setting. We will now always show type models in the model editor. This also means that the "auto-generation mode" needs to change to `models` to ensure that the type models are actually shown to the user. This is done for Ruby, which is currently the only language to show type models.
This does not need a changelog entry because the Ruby model editor is only available in canary mode.
=> Remove `codeQL.model.showTypeModels` config

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
The `@octokit/plugin-throttling` dependency was incorrectly placed in the `devDependencies` section.
N/A:
=> Move octokit throttling plugin dependency out of dev dependencies

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/variant-analysis/ghec-dr.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/config.test.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/variant-analysis/ghec-dr.test.ts
This adds code that reads the `github-enterprise.uri` setting and uses that to decide if we're on github.com, a GHES instance, or GHEC-DR (which as far as I know is the public name so I'll try to refer to it that way in this repo).
The logic for parsing the URI is taken from https://github.com/microsoft/vscode-pull-request-github/blob/a116c509bf98f066f302f25f1716d884df3322db/src/github/utils.ts#L1275 so we keep vaguely consistent with that extension. I'm not totally sure about the logic of ignoring an invalid URI but that's how they've coded it (or actually their code might throw an error).
Then we also add another setting to act as a feature flag to allow using MRVA on GHEC-DR. Right now this is the only thing that these settings control, and they're only checked when trying to trigger a …
=> Detect when the github-enterprise.uri setting is set

extensions/ql-vscode/src/config.ts
Disable the LLM model generation feature when an enterprise URI is set. LLM generation is an in-progress feature that's also behind its own feature flag. It doesn't currently support enterprise environments, so we'll reenable this feature in the future once it is supported in more environments.
=> Disable LLM model generation when not using github.com

extensions/ql-vscode/test/vscode-tests/cli-integration/model-editor/modeled-method-fs.test.ts
- Part of https://github.com/github/vscode-codeql/issues/3578
This fixes the modeled method FS tests for older CodeQL versions by using the CodeQL libraries from the workspace rather than downloading them.
[CLI run](https://github.com/github/vscode-codeql/actions/runs/8892859543)
=> Fix modeled method FS test

extensions/ql-vscode/src/model-editor/supported-languages.ts
This removes the requirement to have `codeQL.canary` set for the Ruby model editor.
=> Add Ruby as a fully-supported model editor language

.github/dependabot.yml, extensions/ql-vscode/test/e2e/docker-compose.yml, extensions/ql-vscode/test/e2e/docker/Dockerfile
This upgrades the `code-server` image to [v4.23.1](https://github.com/coder/code-server/releases/tag/v4.23.1) which runs VS Code 1.88.1. It also enables Dependabot for this Dockerfile such that we'll automatically get updates in the future.
I've also upgraded Alpine in the `docker-compose.yml` file since there's a new version, but this should not result in any changes.
=> Upgrade E2E test dependencies

.github/workflows/release.yml
The `vsce` package is deprecated and has been replaced by `@vscode/vsce`. We already made this change for local development, but not yet for publishing the extension. This makes the change for publishing the extension.
See https://github.com/github/vscode-codeql/actions/runs/8908897407/job/24465341018#step:3:8 for the warning during releases.
=> Use @vscode/vsce when publishing the extension

extensions/ql-vscode/src/extension.ts
This fixes an issue with the supported CLI version warning. When you were on the oldest supported CLI version, we would show a confusing warning. This fixes the comparison to consider the oldest supported CLI version as supported.
Closes https://github.com/github/vscode-codeql/issues/3601
=> Fix incorrect supported CLI version warning

extensions/ql-vscode/README.md
Now that the full documentation has been migrated to docs.github.com, I've updated links in the VS Marketplace README. I'm not sure any items in the checklist are applicable so I've left them unchecked for now.
=> Update links in VS Marketplace README

extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/variant-analysis/ghec-dr.ts, extensions/ql-vscode/test/vscode-tests/minimal-workspace/variant-analysis/ghec-dr.test.ts
The feature is now fully enabled on the API side for all GHEC-DR instances. We should remove the feature flag on the extension side too. To use it now all you'll need to do is set `github-enterprise.uri`.
=> Remove the enableGhecDr flag

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/common/vscode/progress.ts, extensions/ql-vscode/src/debugger/debugger-ui.ts, extensions/ql-vscode/src/local-queries/local-queries.ts, extensions/ql-vscode/src/local-queries/local-query-run.ts, extensions/ql-vscode/src/run-queries-shared.ts
Generating and parsing log summaries can be quite slow, so we should update the progress window with messages about what's being worked on.
I don't really know TypeScript, so there may be a nicer way of achieving what I've done here. 🤷
=> Report progress for post-evaluation actions

docs/test-plan.md
This fixes the model pack query to account for the new MaD ID in the `sinkModel` and removes the LLM section.
=> Update test plan

.github/pull_request_template.md, CONTRIBUTING.md
Remove unused checks on the PR template
=> Update vscode-codeql PR template

.github/workflows/main.yml, extensions/ql-vscode/test/unit-tests/common/short-paths.test.ts
This PR reverts https://github.com/github/vscode-codeql/pull/3637 and also includes configuration that was removed from the windows actions runner images in https://github.com/actions/runner-images/commit/5ecfd27e8fd0a1b4e8c88072772f9bbab9c82b83
This PR supersedes https://github.com/github/vscode-codeql/pull/3638.
Sadly we have to keep the support for 8.3 filenames in the extension as users may still encounter them, as we believe the feature is still enabled by default on Windows 11 for the `C:` drive, although the actions team determined it was not enabled for the Azure Marketplace Windows 2019 image.
@dbartol
=> Re-enable windows 8.3 paths in tests

extensions/ql-vscode/src/model-editor/bqrs.ts, extensions/ql-vscode/src/model-editor/languages/models-as-data.ts, extensions/ql-vscode/src/model-editor/languages/python/access-paths.ts, extensions/ql-vscode/src/model-editor/languages/python/index.ts, extensions/ql-vscode/src/model-editor/method.ts, extensions/ql-vscode/src/model-editor/queries/query.ts, extensions/ql-vscode/test/unit-tests/model-editor/languages/python/access-paths.test.ts
This makes changes to the Python model editor parsing code to incorporate the query changes from https://github.com/github/codeql/pull/15655. These changes consist of:
- Adding support for reading rich type columns (as implemented by https://github.com/github/codeql/pull/16490): This makes it possible to replace the columns `["requests", "Member[adapters].Member[HTTPAdapter].Instance.Member[add_headers]"]` by `["requests.HTTPAdapter", "Member[add_headers]"]`.
- Write rich type columns instead of complex paths. We still retain support for reading non-rich type columns.
- Use the `kind` column that has been added in https://github.com/github/codeql/pull/15655 (the last column returned in the query). This makes it possible to properly handle class methods, which we would otherwise need to …
=> Use rich type columns and endpoint kinds for Python model editor

extensions/ql-vscode/src/model-editor/languages/python/index.ts
This enables type models for Python in the model editor. There is no query for generating type models or for complex access path suggestions, so a simple text box will be shown to enter the path and related type.
- Based on https://github.com/github/vscode-codeql/pull/3653
=> Enable type models for Python in the model editor

extensions/ql-vscode/src/codeql-cli/cli-version.ts, extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/run-queries-shared.ts
This should be much faster than generating it in the extension.
No change-note since this should be a seamless change.
=> Allow compatible CLIs to generate summary symbols file

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/view/common/CodePaths/CodePaths.tsx, extensions/ql-vscode/src/view/common/CodePaths/__tests__/CodePaths.spec.tsx
Hey 👋 
This PR implements my feature request from #3659.
I'm totally open for changes of course (e.g. visualize it differently etc. - e.g. use a callout displaying only the number with a tooltip for more information)
Note:
* Due to the type definitions I assumed that the codeflows are available in the instances where this UI are displayed. (if not more checks would be warranted)
* I've added a `data-testid` to assert the textcontent of the label on one line.
=> Display length of shortest path in MRVA UI

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/src/model-editor/supported-languages.ts
This removes the feature flag `codeQL.model.enablePython` config setting and enables the Python model editor for everyone.
=> Remove feature flag for Python model editor

extensions/ql-vscode/src/view/results/locations/TaxaLocations.tsx
As [requested](https://github.com/github/vscode-codeql/pull/3669#issuecomment-2238661903) on the initial provenance PR, this PR adds non-MaD provenance info to the results UI. CLI 2.18.2 or later is required to see the non-MaD info.
Screenshot:
@aschackmull is this close to what you were expecting?
=> Display non-MaD provenance in results view

.github/workflows/e2e-tests.yml
Discovered in https://github.com/github/vscode-codeql/actions/runs/10268779662/job/28412615133?pr=3682
Root cause was a breaking change announced [here](https://github.blog/changelog/2024-04-10-github-hosted-runner-images-deprecation-notice-docker-compose-v1/).
=> Fix docker command

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
Public-facing changes:
- Add Python support to the CodeQL Model Editor. [#3676](https://github.com/github/vscode-codeql/pull/3676)
- Update variant analysis view to display the length of the shortest path for path queries. [#3671](https://github.com/github/vscode-codeql/pull/3671)
=> Release v1.14.0

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/view/results/AlertTablePathRow.tsx, extensions/ql-vscode/src/view/results/AlertTableResultRow.tsx, extensions/ql-vscode/src/view/results/__tests__/AlertTablePathRow.spec.tsx, extensions/ql-vscode/src/view/results/__tests__/AlertTableResultRow.spec.tsx, extensions/ql-vscode/test/factories/results/mockresults.ts
Hey 👋
This PR implements the my feature request from https://github.com/github/vscode-codeql/issues/3659 for local path queries.
I'm totally open for changes of course (e.g. visualize it differently etc.)
The changes currently look like this:
(a badge showing the shortest path (`4` or `12` here in this screenshot) was added and the length of the paths is shown on the respective entries in parentheses (e.g. `(12 steps)`). Additionally, a tooltip `Shortest path` is shown when hovering over the badge)
**Note**:
* most of the added lines are for tests which I newly created. (the actual changes are quite small)
* I've copied the contents for `mockresults.ts` from this [story](https://github.com/github/vscode-codeql/blob/96c33a14b8662b28ec19f648381905177cdc9cea/extensions/ql-vscode/src/stories/r …
=> Display length of shortest path in local results UI

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/view/jest.config.ts, extensions/ql-vscode/test/jest-config.ts, extensions/ql-vscode/test/unit-tests/jest.config.ts, extensions/ql-vscode/test/unit-tests/variant-analysis/custom-errors.test.ts, extensions/ql-vscode/test/vscode-tests/jest.config.base.ts
This upgrades all Octokit packages to their latest version for which the main change is the switch to ESM. Therefore, we need to transform some more packages in the Jest configuration, but there is only 1 change in the code we need to make.
=> Upgrade Octokit packages

extensions/ql-vscode/src/extension.ts
We are only running unit tests on Node 20 and we can't upgrade certain dependencies (like https://github.com/github/vscode-codeql/pull/3705) because we still support versions of VS Code that use Node 18. This will bump the minimum VS Code version for warnings to 1.90.0 which is the first version of VS Code that [uses Node 20](https://github.com/microsoft/vscode/commit/5216c044283ba1f3c66caa092fd75ba0b3e3e5ca).
After releasing the extension once, we can upgrade the minimum version in `package.json`.
=> Bump minimum VS Code version for warnings

extensions/ql-vscode/package-lock.json
This will resolve https://github.com/github/vscode-codeql/security/dependabot/68 (`express` had a dependency on `path-to-regexp@0.1.7`, this upgrades that to `path-to-regexp@0.1.10`).
=> Run 'npm upgrade express'

.husky/pre-commit, .husky/pre-push
This removes two lines from the Husky hooks that are deprecated:
```
husky - DEPRECATED
Please remove the following two lines from .husky/pre-push:
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
They WILL FAIL in v10.0.0
```
=> Remove deprecated Husky commands

extensions/ql-vscode/package-lock.json
This should close https://github.com/github/vscode-codeql/security/dependabot/69.
=> Upgrade path-to-regexp to 6.3.0

.github/workflows/main.yml, extensions/ql-vscode/test/vscode-tests/activated-extension/jest.setup.ts
Dependabot does not have `security-events: write` permission.
See https://github.com/github/codeql-action/pull/2485 for the original instance of this problem.
=> Avoid uploading eslint sarif for dependabot PR

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
- Update results view to display the length of the shortest path for path queries. [#3687](https://github.com/github/vscode-codeql/pull/3687)
- Remove support for CodeQL CLI versions older than 2.16.6. [#3728](https://github.com/github/vscode-codeql/pull/3728)
=> Release v1.15.0

extensions/ql-vscode/package.json
We were getting a deprecation warning for using the `husky install` command:
It seems like we should just be using the `husky` command according to [the documentation](https://typicode.github.io/husky/how-to.html#manual-setup). This makes that change.
=> Fix Husky install deprecation warning

extensions/ql-vscode/patches/jest-runner-vscode+3.0.1.patch
This removes a patch that has become unnecessary as of [microsoft/vscode#227427](https://redirect.github.com/microsoft/vscode/pull/227427). This does break compatibility with older VS Code versions for tests, but we always run the tests with the newest version of VS Code.
Successful run: https://github.com/github/vscode-codeql/actions/runs/11176227294
=> Remove now unnecessary patch to fix failing CLI tests

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
- Increase the required version of VS Code to 1.90.0. [#3737](https://github.com/github/vscode-codeql/pull/3737)
- Fix a bug where some variant analysis results failed to download. [#3750](https://github.com/github/vscode-codeql/pull/3750)
----
(Minor version bump, since we've changed the minimum VS Code version)
=> Release v1.16.0

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/common/bqrs-cli-types.ts, extensions/ql-vscode/src/common/bqrs-raw-results-mapper.ts, extensions/ql-vscode/src/common/raw-result-types.ts, extensions/ql-vscode/test/data/debugger/QuickEvalLib.qll, extensions/ql-vscode/test/vscode-tests/cli-integration/debugger/debugger.test.ts
Enable `QlBuiltins::BigInt` results in Quick Evals. This involves updating the VS Code extension to understand the BigInt type as it is encoded in BQRS.
Commits:
- [Enable BigInt results in Quick Evals](https://github.com/github/vscode-codeql/pull/3647/commits/ac60ba3a4934e1223e5f16a40128db4b5e66f4b3): implementation
- [Test BigInt-valued quick-eval](https://github.com/github/vscode-codeql/pull/3647/commits/8af1f087aca2935a542f0536f39a09fd2f4b2b42): integration test
- [Add CHANGELOG entry](https://github.com/github/vscode-codeql/pull/3647/commits/c4eaf54dd7e036a6395cbfa8e1084f4b4792c2b5): changelog entry
=> Enable BigInt results in Quick Evals

extensions/ql-vscode/src/codeql-cli/cli.ts
Remove some unused code relating to ML models since the ML models CLI feature is deprecated.
=> Cleanup: Remove references to ML models

extensions/ql-vscode/test/data/debugger/QuickEvalBigIntQuery.ql, extensions/ql-vscode/test/data/debugger/QuickEvalLib.qll, extensions/ql-vscode/test/unit-tests/common/files.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/debugger/debugger.test.ts
Closes https://github.com/github/vscode-codeql/issues/3759
Fixes a problem in https://github.com/github/vscode-codeql/pull/3647 where the tests did not pass under older CLI versions.
This separates the BigInt code into its own file and quick-evals it only on CLI versions that support `QlBuiltins::BigInt`.
=> Add a version-check to BigInt quick-eval test

extensions/ql-vscode/package.json
This excludes even more `.vscode-test` directories which are nested inside `test` directories, such as `./test/vscode-tests/no-workspace/.vscode-test/vscode-darwin-arm64-1.94.2/Visual Studio Code.app/Contents/Resources/app/node_modules/@microsoft/1ds-post-js/tsconfig.json`.
See https://github.com/github/vscode-codeql/pull/3761
=> Exclude more .vscode-test directories in check-types

extensions/ql-vscode/scripts/source-map.ts
This fixes some minor bugs in the source map script:
- It now shows which `gh` command failed instead of just showing a generic error which didn't include which command failed
- It now takes into account both the `label` and the `name` of the release assets, which can apparently be different:
```json
{
"apiUrl": "https://api.github.com/repos/github/vscode-codeql/releases/assets/198176998",
"contentType": "application/zip",
"createdAt": "2024-10-10T12:38:02Z",
"downloadCount": 4,
"id": "RA_kwDODJYu-M4Lz_Dm",
"label": "vscode-codeql-sourcemaps-v1.16.0.zip",
"name": "vscode-codeql-sourcemaps.zip",
"size": 3509607,
"state": "uploaded",
"updatedAt": "2024-10-10T12:38:02Z",
"url": "https://github.com/github/vscode-codeql/releases/download/v1.16.0/vscode-codeql-sourcemaps.zip"
}
```
- It …
=> Improve source map script

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
See [`@types/nanoid`](https://www.npmjs.com/package/@types/nanoid): "nanoid provides its own type definitions, so you do not need this installed."
=> Remove unnecessary @types/nanoid dependency

extensions/ql-vscode/src/compare/sarif-diff.ts, extensions/ql-vscode/test/unit-tests/compare/differentPathsDifferentSourceSink.json, extensions/ql-vscode/test/unit-tests/compare/differentPathsSameSourceSink.json, extensions/ql-vscode/test/unit-tests/compare/sarif-diff.test.ts
This changes the SARIF comparison to only include the source and the sink of a path as an input into the comparison. This will result in a more useful comparison by filtering out results that are the same except for their path.
The results of a comparison on this branch:
The same comparison on `main`:
=> Only compare source and sink in SARIF comparison

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/compare/compare-view.ts, extensions/ql-vscode/src/view/compare/Compare.tsx
This implements streaming for the compare view to avoid a crash when the total JSON.stringified size of the comparison is larger than 1GB (i.e. the Node.js string limit). It does this as follows:
- All results are chunked into 1,000 results per message. This means we'll send at most 1,000 `to` **and** at most 1,000 `from` results in 1 message (i.e. 2,000 actual results).
- We'll send a "setup" message to tell the webview that we're starting a streaming result. This also contains a chunk.
- We'll then send as many "add results" messages as necessary to send all results.
- We'll send a "complete" message to tell the webview that we're done.
The 1,000 results per message is just a safe estimate where we should never run into the string limit. However, I can't really test this.
=> Implement streaming for compare view

.github/workflows/update-node-version.yml, extensions/ql-vscode/scripts/update-node-version.ts
The [Update Node version workflow](https://github.com/github/vscode-codeql/actions/workflows/update-node-version.yml) is currently failing because a 20.18 version of `@types/node` does not exist even though VS Code is now using Node 20.18.0. This doesn't really matter for us since we can still use the 20.17 version of `@types/node`, but the script isn't checking for that.
This adds a check to the script that the version of `@types/node` we are requesting actually exists. If it doesn't, it will decrement the minor version (e.g. 20.18.0 becomes 20.17.0) and try that version instead. It will use the first existing version for the `@types/node` package (e.g. `20.17.*` in this case).
=> Fix update-node-version script for non-existent @types/node version

extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/common/mock-gh-api/vscode/vscode-mock-gh-api-server.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-submission-integration.test.ts
This fixes the variant analysis submission integration tests by using the mock GitHub API server included in the extension to avoid issues with overriding the `fetch` function from outside of the extension code.
=> Fix and re-enable variant analysis submission integration tests

extensions/ql-vscode/package.json, extensions/ql-vscode/src/query-history/history-item-label-provider.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/history-item-label-provider.test.ts
This changes the `codeQL.queryHistory.format` to use a format that [is also used by VS Code](https://code.visualstudio.com/docs/editor/variables-reference), rather than using our own format. We will support the "legacy" format to ensure users that have configured this setting do not need to make any changes.
=> Use standard configuration variable format for history item labels

extensions/ql-vscode/src/view/compare-performance/ComparePerformance.tsx
Includes rows with the number of evaluations and iterations above the pipelines.
=> compare-perf: Show evaluation and iteration counts in table

extensions/ql-vscode/package.json, extensions/ql-vscode/src/compare-performance/compare-performance-view.ts, extensions/ql-vscode/src/extension.ts
Try running the command `Download External Logs for Performance Comparison`...
This will build the following directory structure:
```
$ find 'User/globalStorage/github.vscode-codeql/compare-performance' -type f 
User/globalStorage/github.vscode-codeql/compare-performance/logs-of/artifacts/codeql-dca-runners/codeql-dca-worker_javascript/2181621080/codeql-evaluator-log.json
User/globalStorage/github.vscode-codeql/compare-performance/logs-of/artifacts/codeql-dca-runners/codeql-dca-worker_javascript/2181601861/codeql-evaluator-log.json
User/globalStorage/github.vscode-codeql/compare-performance/artifacts/codeql-dca-runners/codeql-dca-worker_javascript/2181621080/codeql-evaluator-log.json.tar.gz
User/globalStorage/github.vscode-codeql/compare-performance/artifacts/codeql-dca-runners/codeql-dca- …
```
=> PoC download externally stored evaluator logs

extensions/ql-vscode/src/view/compare-performance/ComparePerformance.tsx
Adds a dropdown to choose which metric to render in the top-level table. Does not affect individual pipeline steps, which are always associated with tuple counts.
=> Compare-perf: Add option to choose metric

extensions/ql-vscode/src/log-insights/performance-comparison.ts
Empty RA lines have a tuple count of -1. Do not count them when aggregating.
=> Compare-perf: fix negative tuple counts

extensions/ql-vscode/src/common/jsonl-reader.ts, extensions/ql-vscode/src/compare-performance/compare-performance-view.ts, extensions/ql-vscode/src/compare-performance/remote-logs.ts
Completes the command `codeQL.compare-performance.downloadExternalLogs` story.
If `esbena/auto/esbena/more-downloads/230f947/1731498635271` is entered as the experiment in the prompt for the `CodeQL: Download External Logs for Performance Comparison` command, then the remote logs will be downloaded, processed, and used in the comparison view.
Also turns the jsonl parser into a streaming parser with better logging
=> PoC: compare-performance of external logs

extensions/ql-vscode/src/compare-performance/compare-performance-view.ts, extensions/ql-vscode/src/log-insights/log-scanner.ts
~On top of https://github.com/github/vscode-codeql/pull/3817: just see the latest commit.~
Does the log parsing in parallel with `Promise.all`.
Also adds a progress tracker that we can push further down for better tracking later
=> Hackathon: Parallel evaluator summary log parsing

extensions/ql-vscode/src/view/compare-performance/ComparePerformance.tsx
Colorize delta text and default to sorting by absolute delta. After a few round trips we're back to exactly what @tausbn suggested at the beginning.
=> Colorize delta text instead of icons, and default to using absolute delta

extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/compare-performance/compare-performance-view.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/src/view/compare-performance/ComparePerformance.tsx
A very hacky implementation that simply instantiates an empty `PerformanceOverviewScanner` as the "from" column (i.e. with all values empty). To see it in action, select a single query run in the query history and pick "Compare Performance" from the context menu. Then select the "Single run" option when prompted.
Second commit takes care of simplifying the view when not in comparison mode.
=> compare-perf: Add support for selecting a single run as input

extensions/ql-vscode/src/common/dca.ts, extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/compare-performance/compare-performance-view.ts, extensions/ql-vscode/src/compare-performance/remote-logs.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/log-insights/performance-comparison.ts, extensions/ql-vscode/src/view/common/ComparePerformanceDescription.tsx, extensions/ql-vscode/src/view/common/ComparePerformanceLocalRunDescription.tsx, extensions/ql-vscode/src/view/common/ComparePerformanceRemoteLogsDescription.tsx, extensions/ql-vscode/src/view/common/InfoBox.tsx, extensions/ql-vscode/src/view/common/index.ts, extensions/ql-vscode/src/view/compare-performance/ComparePerformance.tsx
~Adds a generic InfoBox similar to the existing WarningBox.~
~Currently threads through a string as the description, but it should be trivial to change that to a ReactNode if needed...~
Adds a table to the top of the view when remote logs are used. 
Shows a simple string for local runs.
On top of https://github.com/github/vscode-codeql/pull/3817
=> Hackathon: description on top of performance table

extensions/ql-vscode/src/compare-performance/compare-performance-view.ts, extensions/ql-vscode/src/compare-performance/remote-logs.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/log-insights/performance-comparison.ts, extensions/ql-vscode/src/view/common/ComparePerformanceLocalRunDescription.tsx, extensions/ql-vscode/src/view/common/ComparePerformanceRemoteLogsDescription.tsx
Allows the `NONE` choice for the second remote log - enabling the mono-view of the remote logs as well 🎉
=> Hackathon: support mono view of remote logs

extensions/ql-vscode/src/view/common/useMessageFromExtension.ts, extensions/ql-vscode/src/view/compare/Compare.tsx, extensions/ql-vscode/src/view/data-flow-paths/DataFlowPathsView.tsx, extensions/ql-vscode/src/view/method-modeling/MethodModelingView.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlerts.tsx, extensions/ql-vscode/src/view/model-editor/ModelEditor.tsx, extensions/ql-vscode/src/view/results/ResultsApp.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx
There's a lot of duplicated code for various webviews receiving a message from the extension. This PR factors out a React hook, `useMessageFromExtension`, with the common logic.
Commit-by-commit review recommended. I've isolated trivial indentation/formatting changes to its own commit so it's easier to review.
=> Add useMessageFromExtension hook

.github/workflows/release.yml
This will change the publishing of the extension to the VS Code Marketplace to use [a user-assigned managed identity](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-manage-user-assigned-managed-identities). We are [using a federated credential](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-identity) to allow logging in to this managed identity from the `publish-vscode-marketplace` environment. The secrets have already been set in the environment and I've tested them when retrieving the user ID.
The `@vscode/vsce` CLI will automatically retrieve the credentials when we pass the `--azure-credential` flag and run it within the context of the `azure/cli` Action.
=> Publish extension using Azure credentials

extensions/ql-vscode/src/common/jsonl-reader.ts, extensions/ql-vscode/test/benchmarks/jsonl-reader.bench.ts
Replaces the streaming JSONL parser with a faster one that doesn't call `readline`. The streaming JSONL parser on our branch was slower than the original sync version (but doesn't run out of memory), and it seems `readline` is a bottleneck:
Running the benchmark on a 21 MB logfile:
- `readJsonlReferenceImpl`: 172.4 ms (original non-streaming version)
- `readJsonlFile`: 283.3 ms (streaming version based on `readline`)
- `readJsonlFile2`: 151.3 ms (🚀  new version without `readline`)
- `justReadline`: 187.5 ms (consumes the file with `readline` and nothing else)
Note: targeting the hackathon branch. I think it's best to polish that up and try to merge it into `main`.
=> Faster streaming 'jsonl' parser

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/databases/local-databases-ui.ts
Add a palette command that allow user to select a folder and import all database subfolders.
This helps a lot when dealing with micro services that has dozens of databases and save user's time from repeatly choosing folders one by one.
=> Allow import all database subfolders by selecting a folder

extensions/ql-vscode/src/log-insights/log-scanner-service.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/src/query-history/store/query-history-local-query-domain-mapper.ts, extensions/ql-vscode/src/query-history/store/query-history-local-query-dto-mapper.ts, extensions/ql-vscode/src/query-results.ts, extensions/ql-vscode/src/run-queries-shared.ts
Previously the fields from `EvaluatorLogPaths` were copied 1:1 into `LocalQueryInfo` but under different names. It seems easier to keep track of the different kinds of logs if they are called the same everywhere.
=> Refactor: Store EvaluatorLogPaths object on LocalQueryInfo

extensions/ql-vscode/src/common/jsonl-reader.ts, extensions/ql-vscode/test/benchmarks/jsonl-reader.bench.ts
Replaces the jsonl parser with a streaming version that is at least as fast as the sync version. Also see [original PR](https://github.com/github/vscode-codeql/pull/3829) against the hackathon branch.
Thanks to @esbena for the initial streaming version used for the hackaton. That version used the `readline` library to split lines, which turned out to be a bottleneck, however, making the streaming parser slower than the original sync version. So I wrote one that doesn't use `readline`.
Running the benchmark on a 21 MB logfile:
- `readJsonlReferenceImpl`: 172.4 ms (original non-streaming version)
- `readJsonlFile`: 283.3 ms (streaming version based on `readline`)
- `readJsonlFile2`: 151.3 ms (new version without `readline`)
- `justReadline`: 187.5 ms (consumes the file with `readline` and …
=> Add streaming 'jsonl' parser

extensions/ql-vscode/src/view/results/Graph.tsx
When clicking a node in the graph viewer, it would reset the scroll position, similar to what happens when clicking a link with `href="#"` ([such as this link](#)). This PR fixes that.
=> Avoid resetting scroll position after clicking a node in the graph viewer

extensions/ql-vscode/package-lock.json
I just ran `npm upgrade cross-spawn` to upgrade to a non-vulnerable version of cross-spawn.
See https://github.com/github/vscode-codeql/security/dependabot/76
=> Bump cross-spawn version

extensions/ql-vscode/src/codeql-cli/cli.ts, extensions/ql-vscode/src/extension.ts
Closes #3220
issue: https://github.com/github/codeql-core/issues/4654
This notifies the language server of newly downloaded packs once a pack is added to the current ql pack, or a pack's dependencies are installed.
This is the user facing behaviour I observed:
- ✅ creating a query pack and example.ql file using the skeleton wizard:
- works as expected
- ✅ creating a query pack and ql file manually, then installing the ql pack's dependencies using the vs code command palette:
- works: this removes the spurious compilation errors, even in open files.
- :warning: the price of supporting that is that we restart the language server each time a pack is added or a pack's dependencies are installed. There might be cheaper solutions, but I don't know them. If the reviewers don't know of a cheaper …
=> Fix Spurious Compilation Errors

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/vscode/dialog.ts, extensions/ql-vscode/src/common/vscode/telemetry.ts, extensions/ql-vscode/src/config.ts, extensions/ql-vscode/test/e2e/docker/User/settings.json, extensions/ql-vscode/test/e2e/run-query.spec.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/common/vscode/dialog.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/index.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/telemetry.test.ts
This removes the `codeQL.telemetry.enableTelemetry` setting and uses [the VS Code settings](https://code.visualstudio.com/docs/getstarted/telemetry) instead. This is done automatically in the `vscode-extension-telemetry` package, so we don't need to check the VS Code settings.
Since this changes the telemetry when you currently have the extension telemetry disabled, but the VS Code telemetry enabled, this also adds a non-dismissable notification when starting the extension (if VS Code telemetry is enabled and `codeQL.telemetry.enableTelemetry` is `false`).
The E2E tests are expected to fail since it installs the released extension rather than the extension from the repo.
- Closes https://github.com/github/vscode-codeql/issues/3672
=> Remove extension telemetry setting and use VS Code setting instead

extensions/ql-vscode/test/e2e/README.md, extensions/ql-vscode/test/e2e/docker-compose.yml, extensions/ql-vscode/test/e2e/docker/Dockerfile
This upgrades the version of `code-server` and `alpine` as used in the E2E tests. The E2E tests are currently expected to fail until we do a release due to the changes in https://github.com/github/vscode-codeql/pull/3853.
=> Upgrade code-server version for E2E tests

.github/dependabot.yml
It seems like Dependabot is not picking up the `Dockerfile` located in `extensions/ql-vscode/test/e2e/docker`, so this changes the directory in the Dependabot configuration to specify that directory directly instead of specifying a parent directory.
=> Change Dependabot Docker directory for e2e tests

extensions/ql-vscode/package-lock.json
This fixes the following issues:
- https://github.com/github/vscode-codeql/security/dependabot/77
- https://github.com/github/vscode-codeql/security/dependabot/78
I'm not sure why Dependabot wasn't able to upgrade nanoid (perhaps because we need to upgrade two different versions: a direct dependency and a transitive dependency?). I ran `npm upgrade nanoid` to upgrade nanoid.
=> Upgrade nanoid

.github/workflows/release.yml
This may fix publishing to the VS Code Marketplace, which is currently broken because `npx` isn't included in the `azure/cli` Docker image. This is based on the publishing steps of a Microsoft VS Code extension: https://github.com/microsoft/vscode-azureapicenter/blob/13175ef0638b56fa1e605bd4750ec77b1ba5b72d/.github/workflows/publish.yml#L57-L71
I don't think we can test this without creating another release.
=> Fix publishing to VS Code Marketplace

extensions/ql-vscode/package-lock.json
I just ran `npm upgrade vite` since Dependabot seems to be unable to upgrade Vite.
Fixes https://github.com/github/vscode-codeql/security/dependabot/80
=> Upgrade vite

extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/common/interface-types.ts, extensions/ql-vscode/src/common/vscode/abstract-webview.ts, extensions/ql-vscode/src/common/vscode/webview-html.ts, extensions/ql-vscode/src/compare-performance/compare-performance-view.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/log-insights/log-scanner.ts, extensions/ql-vscode/src/log-insights/log-summary.ts, extensions/ql-vscode/src/log-insights/performance-comparison.ts, extensions/ql-vscode/src/query-history/query-history-manager.ts, extensions/ql-vscode/src/view/common/WarningBox.tsx, extensions/ql-vscode/src/view/common/index.ts, extensions/ql-vscode/src/view/compare-performance/ComparePerformance.tsx, extensions/ql-vscode/src/view/compare-performance/RAPrettyPrinter.tsx, extensions/ql-vscode/src/view/compare-performance/RenamingInput.tsx, extensions/ql-vscode/src/view/compare-performance/index.tsx, extensions/ql-vscode/src/view/webview.tsx, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/history-tree-data-provider.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts, extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/variant-analysis-history.test.ts
Adds the 'Compare Performance' UI from the hackathon.
- The integration with DCA has been left out for now. I'm hoping @esbena will follow up on this.
- Added support for predicate-renaming, which was WIP and not demoable in time for the Hackathon demo.
- Some UI performance improvements: using `useMemo` and moved some state into subcomponents where a state change cause as much re-rendering.
- Some clean up of the commit history; mainly squashing simple bugfixes into an earlier commit.
Despite my attempts at cleaning the commit history, it might actually be easiest to review as one giant diff.
=> Add 'compare performance' view

extensions/ql-vscode/CHANGELOG.md
Release changes for v1.17.1
Updates the changelog, including fixing a typo from the previous release.
I don't think there's any other changes that need changelog entries. There was https://github.com/github/vscode-codeql/pull/3843 bit this is only available under the canary feature flag.
See https://github.com/github/vscode-codeql/actions/runs/12928683306 where I ran the CLI tests on latest main (same as this branch without the changelog changes).
=> Release v1.17.1

extensions/ql-vscode/src/view/compare-performance/ComparePerformance.tsx
With `--dynamic-join-order-mode=all`, both `first` and `second` are
undefined, leading to a crash. Until RTJO mode gets proper tuple
counting, this change prevents a crash when unfurling the steps of a
predicate.
=> ComparePerformance: fix crash in RTJO mode

.github/workflows/cli-test.yml, .github/workflows/codeql.yml, .github/workflows/e2e-tests.yml, .github/workflows/label-issue.yml, .github/workflows/main.yml, .github/workflows/release.yml
This change does two things. If it is complicated to review I will split up.
First, this ensures that all workflows have minimal permissions blocks. Second, this adds actions analysis.
A little bit of extra security hardening.
=> Add permissions block and actions analysis

.github/workflows/main.yml, .github/workflows/release.yml
Just two things I missed before.
=> More permissions changes

.gitignore, extensions/ql-vscode/test/factories/model-editor/extension-pack.ts
This fixes `npm run build-storybook` by ensuring we're not importing anything from the `path` module in stories.
=> Fix Storybook build

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json
This upgrade `vite-node` to v3 which doesn't have any breaking changes for us ([breaking changes are in `vitest`](https://github.com/vitest-dev/vitest/releases/tag/v3.0.0), not necessarily in `vite-node`).
This removes our dependency on Vite 5 and esbuild 0.21 and upgrades us to Vite 6 and esbuild 0.24.
=> Upgrade to vite-node v3

.github/workflows/build-storybook.yml
This adds a workflow for building Storybook and deploying it to GitHub Pages. This is based on [the official Storybook documentation](https://storybook.js.org/docs/sharing/publish-storybook#github-pages), although I didn't use [the recommended action](https://github.com/bitovi/github-actions-storybook-to-github-pages) because we would like to split this up into two steps: building and deploying. That is the recommendation from [`actions/upload-pages-artifact`](https://github.com/actions/upload-pages-artifact) and also allows us to only deploy to GitHub Pages on a push to `main`, but still build Storybook in PRs.
You can view the deployment at https://github.github.com/vscode-codeql/.
=> Add workflow for building and deploying Storybook

.github/workflows/e2e-tests.yml
Adding the event so that we can run the workflow manually if needed.
=> Add workflow dispatch to e2e tests

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/databases/database-fetcher.ts
This PR changes the behaviour when requesting to download a CodeQL database from GitHub to always require logging in.
I have only applied this change in behaviour to user-initiated command (either from the UI or command palette) and after this there will be no way to avoid logging in, but if there's extreme backlash we could implement an opt-out config option. There's also a flow when the extension starts up but I have avoided changing this to keep the changes smaller.
The existing behaviour of the extension is that it would require you to login and make the requests authenticated only if canary mode was enabled (or you were using GHEC-DR). If canary mode was disabled then it would authenticate if a token was available but otherwise it would make unauthenticated requests.
Here are some …
=> Change database download to always be authenticated

extensions/ql-vscode/src/query-history/history-item-label-provider.ts
When the `legacyLabelRegex` is tested multiple times against the same string (as happens most of the time, unless a user-specified label is added), it would start searching from the end of the previous match instead of from the start of the string:
[“JavaScript RegExp objects are stateful when they have the global or sticky flags set (e.g., /foo/g or /foo/y). They store a lastIndex from the previous match. Using this internally, test() can be used to iterate over multiple matches in a string of text (with capture groups).”](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test)
This fixes it by resetting `lastIndex` before running the `test` method.
=> Fix legacy label regex

extensions/ql-vscode/src/stories/common/Alert.stories.tsx, extensions/ql-vscode/src/view/common/CodePaths/CodePaths.tsx, extensions/ql-vscode/src/view/common/FileCodeSnippet/CodeSnippetMessage.tsx, extensions/ql-vscode/src/view/common/FileCodeSnippet/FileCodeSnippet.tsx, extensions/ql-vscode/src/view/common/Link.tsx, extensions/ql-vscode/src/view/common/LinkIconButton.tsx, extensions/ql-vscode/src/view/model-alerts/ModelAlertsResults.tsx, extensions/ql-vscode/src/view/model-editor/MethodRow.tsx, extensions/ql-vscode/src/view/model-editor/ModelEvaluation.tsx, extensions/ql-vscode/src/view/variant-analysis/FailureReasonAlert.tsx, extensions/ql-vscode/src/view/variant-analysis/RawResultCell.tsx, extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisStatusStats.tsx
This is part of the work to remove the use of `@vscode/webview-ui-toolkit`. The new library `@vscode-elements/elements` does not have a direct replacement for `VsCodeLink`, this implements a new `Link` component for which the styles have been mostly copied from [here](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/link/link.styles.ts). I have attached comparison screenshots of the old and new component.
Regular styles
Hovered styles
Focused styles
=> Remove the use of `VSCodeLink`

extensions/ql-vscode/src/common/query-language.ts, extensions/ql-vscode/src/language-selection-panel/language-selection-data-provider.ts, extensions/ql-vscode/src/query-history/store/query-history-dto.ts, extensions/ql-vscode/src/query-history/store/query-history-language-domain-mapper.ts, extensions/ql-vscode/src/query-history/store/query-history-language-dto-mapper.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/local-queries/skeleton-query-wizard.test.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/run-cli.test.ts
Allows interacting with qlpacks that use actions as a language.
=> Add "actions" as an analysis language

extensions/ql-vscode/package-lock.json, extensions/ql-vscode/package.json, extensions/ql-vscode/src/view/tsconfig.json, extensions/ql-vscode/src/view/types.d.ts
This sets up support for CSS modules such that the following would now work:
`ActionButton.module.css`:
```css
.button {
display: block;
}
```
```tsx
import styles from "./ActionButton.module.css";
export const ActionButton = () => {
return <button className={styles.button} />
}
```
=> Set up CSS module support

extensions/ql-vscode/src/view/compare-performance/ComparePerformance.tsx
Fixes a minor bug in the compare performance view, where the "ms" unit was not displayed on a grouped predicate entry.
Since the optional parameter `unit` is now provided at all call sites, and its absence was the cause of the bug, I also decided to make the parameter mandatory.
The unit was missing next to the first `2` in this screenshot:
(sorry, I didn't have the same query history item available for both screenshots)
=> Compare perf: Fix missing unit in grouped predicate entry

extensions/ql-vscode/gulpfile.ts/textmate.ts, extensions/ql-vscode/gulpfile.ts/typescript.ts, extensions/ql-vscode/gulpfile.ts/view.ts
The `.pipe()` method on Node.js streams have a gotcha in that they do not propagate errors downstream. This PR changes a few uses of `.pipe()` in our build scripts to the more modern `stream.pipeline()`, which propagates errors correctly.
Previously, if compilation failed with an error, the error would not be visible to Gulp because Gulp only sees the stream that writes to a file, not the intermediate 'esbuild' stream that generated the error. This resulted in unhelpful errors of the form:
```
[13:56:21] The following tasks did not complete: default, <series>, <parallel>, compileViewEsbuild
Did you forget to signal async completion?`
```
Now that the errors is propagated correctly, the TypeScript build error is surfaced correctly. In my concrete case this became the build error
``` …
```
=> Avoid unhandled errors in build streams

.github/workflows/release.yml
Closes https://github.com/github/vscode-codeql/security/code-scanning/646
Dependabot is configured to update actions, so when a new version of this action is released Dependabot should open a PR to update the SHA and comment.
=> Pin azure/login Action

extensions/ql-vscode/package-lock.json
This upgrades node-ipc to remove a warning that Node 22 is unsupported. There are [no changes in the package itself](https://github.com/achrinza/node-ipc/compare/v9.2.8...v9.2.9).
=> Upgrade node-ipc to support Node 22

extensions/ql-vscode/scripts/source-map.ts, extensions/ql-vscode/scripts/update-node-version.ts, extensions/ql-vscode/src/codeql-cli/distribution.ts, extensions/ql-vscode/src/common/short-paths.ts, extensions/ql-vscode/src/databases/local-databases-ui.ts, extensions/ql-vscode/src/databases/local-databases/database-manager.ts, extensions/ql-vscode/src/databases/ui/db-panel.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/local-queries/skeleton-query-wizard.ts, extensions/ql-vscode/src/log-insights/summary-language-support.ts, extensions/ql-vscode/src/model-editor/extension-pack-picker.ts, extensions/ql-vscode/src/model-editor/model-editor-view.ts, extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts, extensions/ql-vscode/test/unit-tests/common/errors.test.ts, extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-manager.test.ts
Since typescript 4.4 ([release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#defaulting-to-the-unknown-type-in-catch-variables---useunknownincatchvariables)), values in a `catch` default to the `unknown` type. So we don't need to specify it, and there were a couple of places where we were explicitly using `any` that would be better off as `unknown`.
Discovered while working on https://github.com/github/vscode-codeql/pull/4056
=> Avoid specifying error type since the default is unknown

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/package.json, extensions/ql-vscode/src/common/commands.ts, extensions/ql-vscode/src/databases/local-databases-ui.ts, extensions/ql-vscode/src/extension.ts, extensions/ql-vscode/src/query-server/messages.ts, extensions/ql-vscode/src/query-server/query-runner.ts, extensions/ql-vscode/test/vscode-tests/cli-integration/query-server/query-server-client.test.ts
Add new command "CodeQL: Trim Overlay Base Cache" that returns a database to the state prior to overlay evaluation, leaving only base predicates and types that may later be referenced during overlay evaluation.
* Requires a recent enough query server. So the command is hidden behind a version check.
* Tested locally and with unit tests.
=> New command: expose `--cache-cleanup=overlay` base cache cleaning

extensions/ql-vscode/CHANGELOG.md, extensions/ql-vscode/src/local-queries/local-query-run.ts
#4037 introduced a bug where `quickEvalPosition` — which indicates that the query was spawned via quick-eval — was not being passed through in the completed query info. This meant the extension tried to interpret the results with the metadata from the enclosing file, which would then fail if it was a `.ql` file with a `@kind` that required a particular named query-predicate.
=> Don't attempt to interpret results when running quick-eval
